### ISSUE TITLE
[D3D9] SWTOR: Transparent textures/decals render improperly with high AA settings

### ISSUE THREAD

**Issue by SimonHanel** [doitsujin/dxvk#3355] opened 2023-04-16 09:00 UTC
Star Wars: The Old Republic has transferred from 32-bit to 64-bit with patch 7.2, and it has apparently introduced some "pixelating" effects when moving the camera around, while looking at textures with transparency (like railings, holographic posters or lights), using "High" or "Very High" anti aliasing settings. Changing AA to Medium will turn everything normal again.

High preset - Anti Aliasing set to Very High
![dxvkMasterVeryHighAA](https://user-images.githubusercontent.com/43139362/232253878-15fe5df6-9cf4-4210-95da-16e6f40a937a.png)
High preset - Anti Aliasing set to Medium
![dxvkMasterMediumAA](https://user-images.githubusercontent.com/43139362/232253882-3f0b80ab-c237-40d8-9a2c-e80207211555.png)

Here's a video demonstrating the issue, with movement:

https://user-images.githubusercontent.com/43139362/232287814-628c0104-67be-4e97-9514-08d8b36569ff.mp4

I've tested the game with DXVK 2.1, the latest master (https://github.com/doitsujin/dxvk/commit/0cf563d5dfcaf2f8b8c659439698f10388eddc2b), 2.0 and 1.10.3, and the issue is persistent. (1.10.3 just removes these textures alltogether). When running the game in native D3D9, there are no issues.

Please let me know if you need anything. Thanks.

### Software information
Star Wars: The Old Republic - Steam Version
Using "High" graphics preset.

### System information
- GPU: Nvidia GTX 1070 Ti
- Driver: 531.41
- OS: Windows 10 Pro 22H2 (build 19045.2728)
- DXVK version: 2.1

### Apitrace file(s)
- [swtor.zip](https://drive.google.com/file/d/1RkQLwyF1-NFkCga6t-6UOLL26xvIS6dD/view?usp=share_link)

### Log files
[swtor_d3d9.log (latest master)](https://gist.github.com/SimonHanel/3842ce269dd63dafd5a6ac341f2b9dd7)

**Comment by K0bin** [comment] 2023-04-16 09:22
Duplicate of #3135.

Basically, it's a Nvidia driver bug that's already fixed in the developer beta driver. Shouldn't be long until the fix makes it's way into the stable branch.

**Closed** 2023-04-16 09:22 UTC
Labels: duplicate, nvidia, d3d9

**Comment by SimonHanel** [comment] 2023-04-16 10:14
My apologies, I should've looked into that thread before opening my issue.

I've just downloaded [the latest Nvidia Vulkan beta driver](https://developer.nvidia.com/vulkan-driver), and it works now. Thanks again.

**Comment by K0bin** [comment] 2023-04-16 10:49
No problem.
