### ISSUE TITLE
The Surge, visual glitches, missing objects

### ISSUE THREAD

**Issue by xpander69** [doitsujin/dxvk#285] opened 2018-04-15 12:36 UTC
Game starts fine and runs, but characters and some objects won't render, they sometimes render in certain angles (maybe something to do with the sun direction or some lights, hard to really pinpoint that)

![ss_15042018_14 28 14](https://user-images.githubusercontent.com/1345116/38778415-0cc11526-40c2-11e8-87c4-fd1ef838dea3.png)

with wined3d it runs also but visuals are all messed up then.
https://www.upload.ee/image/8330408/ss_15042018_14.42.45.png

### Software information
- Tested with low and highest settings, result is same. 
- Tested with nvidias new and old compiler, same deal.

### System information
- GPU: GTX 1070
- Driver: 396.18
- Wine version: 3.5
- DXVK version: 24f0528

### Apitrace file(s)
- with wined3d:
https://mega.nz/#!ULoBjKjC!0nb54GeUjA0OEW3qdwOBc9CXDmmccKU9h1bJw4i6KWA

- with DXVK enabled: https://mega.nz/#!lOBjRbKK!iV7UphFHVmN0qoLo8c9adDfu8AUCBIEcgfMw7kUFkRc

### Log files
- d3d11.log:
[TheSurge_d3d11.log](https://github.com/doitsujin/dxvk/files/1912427/TheSurge_d3d11.log)

- dxgi.log: 
[TheSurge_dxgi.log](https://github.com/doitsujin/dxvk/files/1912428/TheSurge_dxgi.log)

**Comment by doitsujin** [comment] 2018-04-21 18:47
Not sure if this is the cause of the rendering issues, but the game wants to map a depth-stencil image to host memory. While this is technically legal in D3D11, doing the same thing in Vulkan just doesn't work.

It might be possible to work around this by using compute shaders to pack and unpack data from depth buffers into a temporary buffer and doing all sorts of shenanigans, but to be perfectly honest, I'm tempted to tag this as **wontfix** unless more games with the same issue pop up.

For now, f71f527b4d4297e2b45bd0ba352bd8a5ac9cccc2 returns a proper error code if the game tries to map a depth-stencil texture to prevent a driver crash on RADV.

**Comment by xpander69** [comment] 2018-04-21 18:51
ohh :( i wonder what engine this game uses and if there are any other games with the same engine.

**Comment by abienz** [comment] 2018-05-30 13:35
@xpander69 Can you post this to the official WIneHQ post too? https://appdb.winehq.org/objectManager.php?sClass=version&iId=35437

**Comment by xpander69** [comment] 2018-06-01 09:28
@abienz i need to create an account then. have been out of loop with gaming lately (summer time).
will try to do that at one point and test with newer wine versions.

**Comment by oangelo** [comment] 2018-06-03 23:52
I am also having the same issue. Using wine staging 3.9 without DXVK everything is rendered, but I get some light flickering on some surfaces. :-(

**Comment by mimattr** [comment] 2018-08-25 01:29
@xpander69 This title uses an in-house engine called [FLEDGE](https://www.deck13.de/fledge-engine) with the most notable games including [Lords of the Fallen](http://lordsofthefallen.com) and upcoming sequel [The Surge 2](http://thesurge-game.com/#section-home-the-surge-2).

@doitsujin Kudos on your incredible efforts so far! Most corner cases can probably be ignored but it's also important to show support for the few who create [_proper_ PC releases](https://www.eurogamer.net/articles/digitalfoundry-2017-the-surge-face-off) if/when possible. Will see if similar issues occur in other products moving forward.

**Comment by doitsujin** [comment] 2018-08-25 09:27
It's not like I don't *want* to support this feature, but it is very tricky to do so, and impossible to do without any performance impact.

**Comment by Jrugia** [comment] 2018-11-07 16:05
With the DRM-Free release of Lords of the Fallen, I was able to test this game under DXVK. It works fine for the most part but as with The Surge, it fills the log with the same depth-stencil error.  The game seems otherwise playable if you can tolerate the occasional flickering with some of the graphics.

I advise running this game with the DXVK_LOG_LEVEL=none  environment variable, just 5mins into the game and it generated a 1.2mb dxvk log.

**Comment by doitsujin** [comment] 2018-11-07 16:40
I noticed the log spam in Lords of the Fallen, but since it appears to render correctly I didn't bother looking into it yet. Will do at some point, though.

**Comment by Jrugia** [comment] 2018-11-07 17:29
> I noticed the log spam in Lords of the Fallen, but since it appears to render correctly I didn't bother looking into it yet. Will do at some point, though.

I uploaded my savegame where this is easily noticeable. The"GOG.com" folder needs to be unpacked in the "C:\users\your_user\Local Settings\Application Data". 

[GOG.com.tar.gz](https://github.com/doitsujin/dxvk/files/2558485/GOG.com.tar.gz)

**Comment by doitsujin** [comment] 2018-11-08 18:00
**Update**: Now it should hopefully work with the branch mentioned above. I also managed to confirm that the engine *does* indeed use the mapped depth-stencil buffer to decide whether to render certain objects, although I don't quite understand how exactly it works.

Please note that the workaround I implemented to make mapping depth-stencil images possible requires synchronization with the GPU and is therefore very slow.

**Comment by mozo78** [comment] 2018-11-08 19:00
Thank you doitsujin! Can you provide me a precompiled build?

**Comment by mozo78** [comment] 2018-11-08 19:57
Thank you!
There is nothing slow on my end. Rhe game is pretty playable on max graphics settings @ 1920@1080 and it keeps stable 60 FPS :)

**Comment by Jrugia** [comment] 2018-11-08 22:18
Just tested it, does indeed fix the issue and the log is no longer flooded. I did notice a performance drop with a GTX 1060, however it's still playable on an average 40+ fps.

Thanks for the excellent work :D

**Comment by doitsujin** [comment] 2018-11-09 08:38
Yes, that is expected.

**Comment by xpander69** [comment] 2018-11-09 18:00
Works great now, thanks. Performance goes from 90+ down to 70-90FPS with a 1080Ti and all maxed 2560x1440, cant complain much, very playable.

**Comment by doitsujin** [comment] 2018-11-09 18:08
Thanks for testing, guess we can finally close this one!

**Closed by doitsujin** 2018-11-09 18:08 UTC
Labels: d3d11, feature set
