### ISSUE TITLE
DXVK never frees allocated RAM

### ISSUE THREAD

**Issue by Haxk20** [doitsujin/dxvk#1235] opened 2019-10-31 20:06 UTC
### Software information
Any game i tested so far.

### System information
- GPU: AMD RX560X
- Driver: RADV + ACO
- Wine version: Proton 4.11-7
- DXVK version: Whats in Proton 4.11-7

The system RAM gets eaten away after a long gaming session (Around 5 hours or so) and it takes 97% of my RAM by  the time the game crashes (I have 16Gb of RAM) and even after the game crashes the RAM stayes allocated.

Yes i know DXVK shoudlnt clear allocated memory while the game is running due to VRAM but i mean what harm would there be to clear the allocated RAM when DXVK is about to exit ?
This makes some weird stuff happen as when it crashes and i launch it again kernel should by design free the memory and the game should launch which isnt the case here and the game just crashes when i try to launch it or when it launches by some miracle it isnt running at 50fps but at 9fps.
This basically means long gaming sessions that are bigger then 5 hours are basically impossible.
If it matters kernel is Linux-next-20191031

**Comment by doitsujin** [comment] 2019-10-31 21:09
> and even after the game crashes the RAM stayes allocated.

This is a kernel bug and cannot be fixed in DXVK.

**Comment by Haxk20** [comment] 2019-10-31 21:44
> > and even after the game crashes the RAM stayes allocated.
> 
> This is a kernel bug and cannot be fixed in DXVK. Also happens with other applications such as RenderDoc.

Ahhh good to know. Do you by any chance know if it was reported already ? I can report it if it wasnt.

**Comment by doitsujin** [comment] 2019-10-31 21:49
I don't know if there's a report already, you might need to check freedesktop bugzilla.

In any case, I haven't reported this either yet because there's no *reliable* way for me to reproduce the problem; it usually happens for me after a Vulkan command submission fails due to the lack of memory and RenderDoc subsequently crashes. If you have something more reliable, feel free to file a report.

**Comment by Tele42** [comment] 2019-11-04 12:50
Possibly related to https://gitlab.freedesktop.org/mesa/mesa/issues/1426 (medium low confidence).

It may be worth test reverting the bisected commit.

**Comment by doitsujin** [comment] 2019-11-04 12:58
Is it just me or is the freedesktop gitlab dead right now?

**Comment by h3fang** [comment] 2019-11-04 13:02
Just you.

**Comment by Kreyren** [comment] 2019-11-04 14:16
> Is it just me or is the freedesktop gitlab dead right now?

FWIW freedesktop.org was down yesterday and it seems that more people has issues with connection on it.

Rerefencing: https://www.reddit.com/r/linuxquestions/comments/dqxuj3/freedesktoporg_down/ 

There is a post from a webmaster with instructions to set `/etc/hosts` on their internal DNS server in case you need it

**Comment by Haxk20** [comment] 2019-11-04 18:21
I have found that https://gitlab.freedesktop.org/mesa/mesa/issues/1920
Is probably what i suffer from too.

**Closed** 2019-12-11 21:20 UTC
Labels: not a bug
