### ISSUE TITLE
White screen running Launchpad.exe for Everquest

### ISSUE THREAD

**Issue by jporterf** [doitsujin/dxvk#1824] opened 2020-11-20 12:22 UTC
Running the launcher produces just a white screen.  The elements on the screen are clickable (cursor changes, and actions occur when you click them) but the window itself is blank white.

### Software information
Everquest Live version, found at www.everquest.com by Daybreak games.  Using the default values from installation.

### System information
- GPU: Nvidia Geforce 1650 Super
- Driver: 455.26.01
- Wine version: wine-5.19-88-gf4a66ad257d (Staging)
- DXVK version: dxvk-mingw-git 1.7.2.r7.g6a10c81d-1
- Kernel version 5.9.0-1-tkg-cfs 

### Apitrace file(s)
https://drive.google.com/file/d/1rHPBYf7iPYubptO2dzbdC7wO7zegeDkC/view?usp=sharing

### Log files
https://drive.google.com/file/d/1sgCcFQskGMml6qSyxX44BuPLt41eEY3u/view?usp=sharing
https://drive.google.com/file/d/1ZXjnyGdTn5coaS_BZFOi8--F7ADvFnM5/view?usp=sharing
https://drive.google.com/file/d/16pMeT7KpVOYxbqa7pi7HfpWktgXI9GWq/view?usp=sharing

**Comment by doitsujin** [comment] 2020-11-20 12:26
None of the Google Drive links are accessible.

You can attach log files directly as text files to github issues, it's usually much less of a hassle.

**Comment by jporterf** [comment] 2020-11-20 13:34
Try again, I opened up access

**Comment by doitsujin** [comment] 2020-11-20 14:02
```
err:   Failed to create surface
```
Not much we can do there. This could be related to child window rendering for Vulkan surfaces, which is probably not supported by your wine build (would be helpful if you could post logs of that as well), and uses shared resources which we cannot support (wined3d doesn't support those either fwiw).

**Comment by rennil42** [comment] 2020-11-21 00:13
I just tested the launcher using winehq-stable (5.0.3) on Ubuntu 20.04 and the launcher works and renders as expected, however I experience the white screen issue on winehq-staging (5.21).

**Comment by EvanCarroll** [comment] 2022-05-28 01:53
I'm also getting the white screen issue.

**Comment by EvanCarroll** [comment] 2022-05-28 02:11
> Just use wined3d for the launcher with per-application DLL overrides.

Do you have any docs on how to set that up? I just see the ability to install or remove dxvk for a wineprefix?

**Comment by EvanCarroll** [comment] 2022-05-28 05:04
It may also be worth nothing that at least for me `file` returns

* for `LaunchPad.exe` PE32 executable (GUI) Intel 80386, for MS Windows
* for `eqgame.exe` PE32+ executable (GUI) x86-64, for MS Windows

**Comment by EvanCarroll** [comment] 2022-05-28 06:54
Workaround for Everquest
====

Click around on the bottom right of the white box until you enter the game. Then run

```shell
/proc/$(pidof eqgame.exe)/cmdline
```

Create a script like this,

```shell
#!/bin/sh
cd "./wineprefix/drive_c/users/Public/Daybreak Game Company/Installed Games/EverQuest/"
wine "eqgame.exe" "patchme" "/ticket:whateverticketnumber"
```

**Comment by Blisto91** [comment] 2024-02-06 22:06
Is this still an issue today? I'm not able to reproduce again at the moment

**Comment by rennil42** [comment] 2024-02-07 12:36
I am not experiencing it either. I did trigger it recently however I think that was a config issue on my end. I believe this can be closed.

**Comment by K0bin** [comment] 2024-07-07 12:36
I'm closing this for now. If someone manages to reproduce it, just respond and I can reopen it.

**Closed by K0bin** 2024-07-07 12:36 UTC
