### ISSUE TITLE
Help - Not Compiling on Ubuntu 22.04

### ISSUE THREAD

**Issue by G2a1c2e5l1A** [doitsujin/dxvk#3075] opened 2022-11-17 16:16 UTC
Hello,
I installed all dependencies and also checked the vulkan drivers status.

After getting  ‘std::cv_status’ error, I applied 
update-alternatives --config x86_64-w64-mingw32-gcc
update-alternatives --config x86_64-w64-mingw32-g++
update-alternatives --config i686-w64-mingw32-gcc
update-alternatives --config i686-w64-mingw32-g++

And it was fixed as described on the troubleshootings section.

However I'm still getting the following errors:

`[165/278] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../src/d3d11 -I../include -I../include/vulkan/include -I../include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj -c ../src/d3d11/d3d11_annotation.cpp
In file included from ../src/d3d11/d3d11_device.h:19,
                 from ../src/d3d11/d3d11_state_object.h:3,
                 from ../src/d3d11/d3d11_context_imm.h:8,
                 from ../src/d3d11/d3d11_annotation.cpp:3:
../src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
`

What would this be about? How could I fix it?

Thanks!

**Comment by K0bin** [comment] 2022-11-17 16:17
Duplicate of #3074

**Closed by K0bin** 2022-11-17 16:17 UTC
