### ISSUE TITLE
Graphic bugs on Metal gear Solid The Phantom Pain using DXVK

### ISSUE THREAD

**Issue by zarebcn** [doitsujin/dxvk#2784] opened 2022-08-04 11:50 UTC
Hi, i have been trying to use DXVK on MGSTPP and i have detected some graphic bugs. 

Im using an RX 570 with AMD drivers 22.3.2, without DXVK the graphics are perfectly fine but i tried to use DXVK because DX11 support on AMD side is a bit shit and i get some frame drops without gpu or cpu being maxed out. 

I tried 4 versions of DXVK, since 1.10 to 1.10.3, and all of them got this bugs. Im using windows 10 fully updated by the way.
On other games DXVK works perfectly fine. 

Going to attach 2 pics of this bugs:

![IMG20220804132923](https://user-images.githubusercontent.com/9139686/182839830-b1dd2bf2-d55f-4fda-bf43-7e53556b16ba.jpg)
![IMG20220804133112](https://user-images.githubusercontent.com/9139686/182839858-69f10e46-1656-413a-9bb5-3b928f8acd15.jpg)

**Comment by doitsujin** [comment] 2022-08-04 11:54
We don't support Windows, and this is likely a driver bug since the game is [known to work](https://www.protondb.com/app/287700) on Linux.

**Comment by zarebcn** [comment] 2022-08-04 12:10
Ok, i understand that you dont support windows but without DXVK graphics are perfectly fine and in all other games theres no issues with DXVK. Yeah, the drivers are 4 months old but the game is several years old, maybe i have to use some config on the dxvk.conf file or a problem with vulkan itself?

log files:
[mgsvtpp_d3d11.log](https://github.com/doitsujin/dxvk/files/9259491/mgsvtpp_d3d11.log)
[mgsvtpp_dxgi.log](https://github.com/doitsujin/dxvk/files/9259494/mgsvtpp_dxgi.log)

**Comment by doitsujin** [comment] 2022-08-04 12:23
Again, the problem is almost certainly the AMD driver, and probably specifically on older GPUs as well (they *constantly* break Vulkan stuff on Polaris, Vega, and even RDNA 1 sometimes). It works fine on RADV, and I don't want to spend several days figuring out what might be going wrong and whether or not it's possible to work around this, since it's just not our target platform. Hence, no support.

**Comment by adolfintel** [comment] 2022-08-06 17:02
@doitsujin I don't mean to be a jerk, but I see A TON of issues on this repo that always follow the same pattern: someone has a problem and they're either using Windows (sometimes even Windows 7), an old GPU, unsupported drivers,... you know the drill.

Wouldn't it be appropriate to have a warning dialog pop up when a DXVK DLL is loaded and it detects that it's not running in Wine? Maybe even straight up refuse to load? After all, DXVK is supposed to be used on Linux.

Just my opinion, feel free to disagree.

**Comment by orowith2os** [comment] 2022-08-07 00:07
It's been stated that DXVK on Windows is not officially supported by DXVK, and even if it were, support is not a right, as can be deducted from the license. Old GPUs may also not be getting Vulkan driver updates, and as such, DXVK may not properly work on them.

**Comment by nipkownix** [comment] 2022-08-07 01:35
>  Maybe even straight up refuse to load? After all, DXVK is supposed to be used on Linux.

Either that, or try to redirect it to the system's DirectX dlls instead, although I'm not sure if that's worth the hassle.

**Comment by aufkrawall** [comment] 2022-08-08 00:38
Why would it be DXVK's responsibility to educate users by force? Really don't like the vibes of that idea.
Imho a warning in the issue template for amdvlk-pro driver (and probably also -open, as that one regresses like crazy too; not to be confused with RADV) and asking users to re-test with RADV would be sufficient. It's not so much Windows vs. Linux when the game actually manages to load, such visual corruption issues are always shared between Windows and amdvlk-pro driver on Linux. It's also not like RDNA1/2 would necessarily show less issues with this driver and DXVK vs. e.g. Polaris.

**Comment by adolfintel** [comment] 2022-08-08 07:44
@aufkrawall I think it's needed because many of these users don't even know that DXVK is not supposed to be used on Windows.

Take a look at this example (from the PCGamingWiki page for GTA IV):
![image](https://user-images.githubusercontent.com/16307689/183362192-978d852a-5c15-477a-a015-82e1e188ec9b.png)

The link points directly to the releases page, do you think the average GTA IV player will take time to go and read the readme file?

Look how many times people recommend using DXVK on Windows on PCGW: https://www.pcgamingwiki.com/w/index.php?search=dxvk&title=Special%3ASearch . The only page that has a warning is Stray because some good soul added it a few days ago.

Same thing on the Steam community, with this guy recommending using DXVK to play Stray on Windows 7
![image](https://user-images.githubusercontent.com/16307689/183363134-edfa8664-0c45-4332-9169-b842c7eda53b.png)

When these users inevitably run into issues, they're going to come here and open issues and then we have to explain them that they're not supposed to do that.

A simple warning message like the one below could be added [here](https://github.com/doitsujin/dxvk/blob/4f0c217633c5b4a2c7257ba552485ce416dceb93/src/dxvk/dxvk_adapter.cpp#L22) or in any other piece of code that's executed early during the initialization and will at least inform some these users.
```
DXVK is not designed to be used on Microsoft Windows.

You can continue but you may run into performance and/or stability issues, please DO NOT report these issues on Github.

To disable this message, add dxvk.disableWarnings=True to the config file.
```

Similar warnings could be added at the same location to warn people with old Kepler GPUs or with really old drivers.

**Comment by Blisto91** [comment] 2022-08-08 09:00
This issue is maybe derailing a bit so I'd suggest opening a new one if you have concerns or or want to discuss change suggestions.

fwiw I'm not personally a fan of outright disallowing dxvk to be used on windows. Even tho i understand the concern for having lots of reports that are mostly related to improper windows and dxvk compatibility do note that windows users can and have reported and brought legitimate dxvk issues to light.

**Comment by adolfintel** [comment] 2022-08-08 10:18
@zarebcn that really wasn't my intention, I'm sorry if I made you feel unwelcome in some way.

My proposal was simply to warn users about known issues on an unsupported platform so that the project doesn't get flooded with issues. There's no fanboy war going on.

Believe it or not, I've been on the other side of this for many years, if you look on my profile you'll see that I even have scripts to build WineD3D for windows that I've been maintaining since 2014 (and from 2016 through 2019 even mesa builds). It's bad, it's unsupported, often has stability issues, but sometimes it gets the job done when you want to play some broken old game on windows, before DXVK and dgVoodoo came along it was a godsend for windows users!  
Of course, people have been abusing the hell out of it and sending me emails complaining that it doesn't work and expecting me to be able to fix it, that's why I suggested that maybe DXVK should have a warning, that's all.

I'll open a separate issue as Blisto suggested.

**Comment by zarebcn** [comment] 2022-08-08 10:50
@adolfintel I think that i understood it in the wrong way, i see your point. Sorry if i overreacted a bit but i just came here for informing of a bug and i felt that i was being annoying with my issue and got no support but complaints.

Va bene, saluti.

**Comment by aufkrawall** [comment] 2022-08-08 13:26
> @aufkrawall I think it's needed because many of these users don't even know that DXVK is not supposed to be used on Windows.

Well, if such hints are mentioned in game wikis etc., it is probably (relatively) safe to assume that the game in question generally works with DXVK on Windows. I don't want to turn a bug ticket into a driver flame war, but reality is that basically every game just works with DXVK on Windows with Nvidia when loading of the DLL is not an issue (which tends to happen, but it's obviously a minority of affected titles). I probably have run dozens of games with DXVK with Nvidia on Windows, and can't recall any case of visual corruption.

**Comment by Blisto91** [comment] 2022-08-08 17:33
Try latest master.
https://github.com/doitsujin/dxvk/actions/runs/2819592531

**Comment by zarebcn** [comment] 2022-08-09 12:08
@Blisto91 Tried with this build and the bug is still there. My drivers are up to date (22.7.1)

**Comment by Blisto91** [comment] 2022-08-09 13:15
I will try to check it out here later on Linux with the community drivers when i get home and see if i can repro a difference between master and 1.10.3

**Comment by Blisto91** [comment] 2022-08-09 13:28
When gpu isn't 100% it's usually because there is a cpu bottleneck or otherwise. Unless there is a fps or vsync cap.
There have been some optimizations on master that should improve CPU bound performance. But if you FPS drops the same time as your GPU utilization goes up that sounds weird.

Can you check if there is a difference in how much Vram is used between the two versions?

**Comment by zarebcn** [comment] 2022-08-09 13:36
@Blisto91 Yh, i use vsync cap at 60fps. Im pretty sure that i deleted .cache file but im going to try again and i'll do some pics

**Comment by K0bin** [comment] 2022-08-09 14:10
That's a totally unrelated problem. Please open a new issue for that.

**Comment by Blisto91** [comment] 2022-08-09 14:30
How does it behave without vsync?

Also try disabling the overlay you are using and see if you see the same just using dxvk's own.
Make a file called `dxvk.conf` next to the games exe (or where the logs generate) and insert `dxvk.hud = full`
Post a screenshot of what that says.

**Comment by zarebcn** [comment] 2022-08-09 15:04
Both 2k and max settings and vsync disabled but the game seems to cap at 60fps for me. Maybe caps at the display Hz.

Master
![IMG20220809164956](https://user-images.githubusercontent.com/9139686/183685178-57a2a5e3-1b8e-4001-9bca-61b9932bf6ab.jpg)

---

1.10.3
![IMG20220809165718](https://user-images.githubusercontent.com/9139686/183685332-e4e7fa23-35de-4cfc-ac8d-b1191b83b99d.jpg)

**Comment by K0bin** [comment] 2022-08-09 15:06
Please start taking screenshots.

**Comment by doitsujin** [comment] 2022-08-09 16:05
I'm not seeing any meaningful performance differences on my system between the two versions.

**Comment by Blisto91** [comment] 2022-08-09 17:42
Haven't reproduced either. Can you send a save game?

**Comment by zarebcn** [comment] 2022-08-09 19:06
@Blisto91 I had Twitch Studio vulkan layer disabled on both tests, im going to send my savegame and config files of my game but i dunno if you will be able to use it because i think that are linked to an user.

[local.zip](https://github.com/doitsujin/dxvk/files/9293911/local.zip)
[remote.zip](https://github.com/doitsujin/dxvk/files/9293912/remote.zip)

**Comment by doitsujin** [comment] 2022-08-09 23:10
Turns out that this was once again specific to the official AMD drivers. RADV and Nvidia are fine.

No idea why, but enabling the Vulkan 1.3 `maintenance4` feature just completely destroys GPU-bound performance.

I disabled this feature now to work around this, DXVK doesn't *really* need it, although the relaxed interface matching rules are nice for buggy D3D games. But AMD should **really** take a look at this, there's no way that enabling this particular feature should cost that much performance (or really, any performance).

**Comment by zarebcn** [comment] 2022-08-10 13:13
@doitsujin If disabling this the performance is the same as in older versions is fantastic and if continues to launch games even without disabling twitch studio vulkan layers in my case it will be awesome.

In reference to the graphic corruption theres something that can be done? Maybe some config in the dxvk.conf file? Because is a pity that performance wise is perfect, far better than dx11 one, but the bug kills the immersion.

**Comment by Blisto91** [comment] 2022-08-10 13:25
Sorry for jamming myself in when the ping wasn't for me 😁 

You can try messing with the conf options, tho i'm pretty sure it wont affect it. But doesn't hurt trying.
This will most likely need a driver fix from amd. If my GPU wasn't unsupported with those drivers i would open one myself at the [AMDVLK repo](https://github.com/GPUOpen-Drivers/AMDVLK). A fix there might carry over to the windows drivers since they share alot of code afaik and is why it also reproduces the issue. Or atleast the funky trees I've been told.

You could try reporting it yourself and see if anything comes out of it. I know they have a bug report tool in adrenalin or what it's called. Tho dunno what they'll think about a bug report with dxvk on windows, but you could say it's the same issue with AMDVLK on linux.

**Comment by aufkrawall** [comment] 2022-08-10 13:29
AMD devs told me not to open tickets for the Windows driver at amdvlk GitHub tracker (e.g. related to unreliable shader cache on Windows that spams duplicates vs. Linux amdvlk-pro...). You could of course reproduce the issue on Linux with the amdvlk-pro driver, but they didn't fix ~anything I reported with regard to it.

**Comment by Blisto91** [comment] 2022-08-10 13:31
Ye they shouldn't open at the AMDVLK tracker. Might have worded it badly.
They could try their luck with the windows bug report tool or hope someone else on linux that can reproduce there with amdvlk opens a issue and a fix carries over. Or try on linux themselves ofc.

**Comment by jinjianrong** [comment] 2022-09-30 12:40
The issue is caused by out of bound buffer access.   amdvlk 2022.Q3.5 release added a workaround for the game.

**Comment by Blisto91** [comment] 2022-09-30 12:44
Sounds good. Did see the games mentioned in the release notes.
Didn't know amdvlk had been made aware. Was gonna make a issue myself if it was still an issue in a few months when i anticipate getting a new GPU that will be supported by the latest driver.

Will this also be relevant for a future windows driver release? Since that is what the original issue poster is on.

**Comment by Blisto91** [comment] 2022-11-21 07:16
@zarebcn Could i get you to try again with latest driver and dxvk? 🙂

**Comment by Blisto91** [comment] 2022-12-07 07:06
Did you submit a bug report to AMD?

**Comment by zarebcn** [comment] 2022-12-23 11:16
> Did you submit a bug report to AMD?

Nope because i think that they will say that i should not use dxvk on windows and use directx instead

**Comment by zarebcn** [comment] 2022-12-23 11:21
Yaaay its finally fixed!!! 😀

![METAL GEAR SOLID V_ THE PHANTOM PAIN 23_12_2022 12_01_36](https://user-images.githubusercontent.com/9139686/209326991-62a9e367-f665-4168-897b-9ddf7e87dae1.png)
![METAL GEAR SOLID V_ THE PHANTOM PAIN 23_12_2022 12_01_51](https://user-images.githubusercontent.com/9139686/209327024-31779018-754b-4033-9079-3b994d2b227a.png)

Im using Amernime modded drivers 22.12.2 with dxgma kernel, AMD has not still released official 22.12.2 for polaris, and finally its fixed. Will see if with the next official release its fixed. Btw im using dxvk 1.10.3 because with 2.0 doesnt work MSI afterburner overlay.

**Comment by Blisto91** [comment] 2022-12-23 12:35
Good to hear 🙂

**Comment by WWSNK** [comment] 2023-01-15 15:16
Great news! I will try that in my end too.

**Comment by Blisto91** [comment] 2023-02-16 09:17
@zarebcn Is it fixed in the newly released official driver? 🙂

**Comment by zarebcn** [comment] 2023-02-16 14:08
Hi @Blisto91, i tested with the official driver and yes its fixed too but i dont know what they have done with the vulkan driver but now theres a noticeable loss of performance when using vulkan so i will stick with the modded drivers by the moment. Seems that AMD fixes some things and fucks another ones...

**Closed** 2023-02-16 14:14 UTC
Labels: needs feedback, windows, amd proprietary
