### ISSUE TITLE
[Feature request] Allow moving DXVK_HUD to another corner

### ISSUE THREAD

**Issue by alvarlagerlof** [doitsujin/dxvk#671] opened 2018-09-26 10:09 UTC
![nfs](https://user-images.githubusercontent.com/14835120/46073737-09438b00-c186-11e8-99d9-963ce3893892.png)
Some games have GUI under the DXVK_HUD, which makes it hard to read.

I propose either adding `tl, tr, bl, br` to `DXVK_HUD`
or 
Adding another variable something like `DXVK_HUD_CORNER`

**Comment by K0bin** [comment] 2018-09-26 11:02
Duplicate of #488

**Comment by doitsujin** [comment] 2018-09-26 11:03
People have suggested feature creep for the HUD many times, and I've rejected feature creep for the HUD many times, see https://github.com/doitsujin/dxvk/issues/488#issuecomment-403622075.

**Closed by doitsujin** 2018-09-26 11:03 UTC
Labels: duplicate, wontfix
