### ISSUE TITLE
Grand Theft Auto IV Artifacting 

### ISSUE THREAD

**Issue by DeathlySin** [doitsujin/dxvk#2208] opened 2021-08-04 23:23 UTC
Hi, I get great framerates using DXVK 1.9.1 with Grand Theft Auto IV. 
But sadly, I have some really bad artifacting going on. I've tested other games and they are all fine, so I know it's not an issue with my GPU. 

It only occurs if I am using DXVK with Grand Theft Auto IV.

I have tried both DXVK 1.9.1 and DXVK 1.9 to no success, the artifacting is present still. If I remove the files from my game folder, it works without artifacting no problem. 

I am using the d3d9.dll. 

My System Specs are:
- CPU: i7 10700kf @ Stock speeds
- RAM: HyperX Fury RGB @ 3200MHz
- GPU: MSI Mech X2 6700 XT 12GB
- Driver: Adrenalin 21.7.2
- Wine version: None, running Windows 10 
- DXVK version: 1.9.1

All my drivers are up to date.

### Log files
- d3d9.log: [GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/6934840/GTAIV_d3d9.log)

Hope this helps and thank you for the work you've done to date on DXVK!

**Comment by K0bin** [comment] 2021-08-04 23:32
Duplicate of #1862
Duplicate of #2179

**Closed by K0bin** 2021-08-04 23:32 UTC
