### ISSUE TITLE
DXVK hangs GPU for some reason in Darksiders 3.

### ISSUE THREAD

**Issue by Monsterovich** [doitsujin/dxvk#794] opened 2018-12-01 18:02 UTC
This happens during the game start up.

This Unreal Engine 4 D3D11 game works with wined3d but not with dxvk:

![qtox_image_2018-12-01 19-07-52 576](https://user-images.githubusercontent.com/3750982/49331566-cf3c9e00-f5a7-11e8-9344-b94a36bf2707.png)

### System information
- GPU: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
- Driver: Mesa 19.0.0-devel - padoka PPA
- Wine version: wine-4.0-rc1 (Staging)
- DXVK version: v0.93

### apitrace

https://drive.google.com/open?id=1bHUkIt2tkF96sbT9BGEunEV0LdYP-czq

### Log files
[Darksiders3-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2636154/Darksiders3-Win64-Shipping_d3d11.log)
[Darksiders3-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/2636155/Darksiders3-Win64-Shipping_dxgi.log)

**Comment by K0bin** [comment] 2018-12-01 18:59
Try running the game with validation layers (https://github.com/doitsujin/dxvk#debugging) and post the logs with that please.

**Comment by Monsterovich** [comment] 2018-12-01 19:51
[Darksiders3-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2636281/Darksiders3-Win64-Shipping_d3d11.log)
[Darksiders3-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/2636282/Darksiders3-Win64-Shipping_dxgi.log)

**Comment by Jrugia** [comment] 2018-12-01 21:42
Most likely an ANV issue, the game clearly works fine on Nvidia: https://www.youtube.com/watch?v=GD6DxKIKzrY

**Comment by Monsterovich** [comment] 2018-12-01 21:53
>Most likely an ANV issue, the game clearly works fine on Nvidia:

I'm happy for you but your comment is now helping.

**Comment by Jrugia** [comment] 2018-12-01 22:08
> > Most likely an ANV issue, the game clearly works fine on Nvidia:
> 
> I'm happy for you but your comment is not helping.

I apologize if my comment sounded the wrong way, I was merely pointing out that dxvk works with this game and the issue may be related to ANV.  Didn't mean to offend or anything.

**Comment by Monsterovich** [comment] 2018-12-01 22:09
>game and the issue may be related to ANV.
I thought you made a mistake, what is ANV by the way?

**Comment by Jrugia** [comment] 2018-12-01 22:13
> > game and the issue may be related to ANV.
> 
> I thought you made a mistake, what is ANV by the way?

Intel ANV is the name of their open source Vulkan driver.

**Comment by Monsterovich** [comment] 2018-12-01 22:15
I think that my system freezes because dxvk allocates a lot of memory for unknown reason. I don't know how can I figure it out.

**Comment by Leopard1907** [comment] 2018-12-03 14:21
https://github.com/doitsujin/dxvk/issues/707

https://github.com/doitsujin/dxvk/issues/632

Sounds similar to your problem

**Comment by K0bin** [comment] 2018-12-03 14:46
It's probably just a gpu hang and not related to allocations at all.

**Comment by Monsterovich** [comment] 2018-12-03 16:18
>It's probably just a gpu hang and not related to allocations at all.

I can't detect any error because my system freezes instantly and I can only reboot through poweroff button. Any ideas?

**Comment by Monsterovich** [comment] 2018-12-11 18:39
https://bugs.freedesktop.org/show_bug.cgi?id=109020

**Comment by djdeath** [comment] 2018-12-14 22:21
I'm guessing you're not running the game from Steam right?
If I try that the game won't even start and I get the following message : 
```
DX11 feature level 10.0 is required to run the engine
```

What's the setup to reproduce this?

**Comment by FurretUber** [comment] 2018-12-24 18:50
What kernel version are you using now? There is a [serious regression](https://bugs.freedesktop.org/show_bug.cgi?id=107945) with `i915` starting with 4.18, which was fixed in 4.20-rc7. This regression makes the system crash hard, which seems similar to what is happening on your case.

**Comment by Jrugia** [comment] 2019-07-21 12:48
I've been trying to figure out the cause of this issue. I'm currently testing it on 2 systems with Intel HD and having mixed results.

System 1: Laptop i3-5005U with 16GB ram. The game runs fine here barring the low performance and it's able to allocate 3.9GB V-Ram. 
![DS3_5005](https://user-images.githubusercontent.com/13750621/61591261-f8588000-abc4-11e9-8b6c-a5a3fcf6d478.jpg)


System 2: Desktop i3-7100 with 8GB ram. The game runs and freezes same as OP. DXVK logs remain empty. I checked my motherboard and on the spec sheet it clearly states "Max Shared Memory 1024MB", however when I run Guild Wars 2 using D9VK it is able to allocate and use over that amount without issues: 
![GW2_D9VK](https://user-images.githubusercontent.com/13750621/61591250-e1199280-abc4-11e9-803e-3bc048d1885e.jpg)

For consistency both of these tests were ran with fresh installations of Xubuntu 19.04 and using stock kernel/mesa. On the 8GB system I upgraded the Kernel to 5.1 and Mesa to latest using Oibaf and the situation remained the same.

Currently I'm running out of options of what else to try. I'll remove one of the 8GB Ram modules on my laptop to bring the ram amount the same as the desktop and see what happens.


**Log Files**
[Darksiders3-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/3414587/Darksiders3-Win64-Shipping_dxgi.log)
[Darksiders3-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/3414588/Darksiders3-Win64-Shipping_d3d11.log)

**Comment by Jrugia** [comment] 2019-07-21 13:21
Update:  Removing one of the two 8GB sticks on my laptop still launched the game successfully. At this point this is most likely looking like an issue specific to Gen9 graphics.

**Comment by DenKos363** [comment] 2019-09-04 09:22
hello guys. I found out, that this bug is very similar to other, reported in mesa:
https://bugs.freedesktop.org/show_bug.cgi?id=110228 (here is the first one, other you may find in links to it). As I see here, Darksides also uses UE4 engine, so I checked attached trace with this kernel patch from => https://bugs.freedesktop.org/show_bug.cgi?id=110998
And it fixed the hang. Now trace reproduces up to splash screen and crashes (what, I think, is ok). Tested 3 times, no hangs. 
Also interesting fact, that on CFL cpu I couldn't reproduce the hang in all kernels I had (4.19, 5.+, and even patched)... what might be a bit strange (because during testing UE4 issue I used exactly CFL machine...). Anyway, current tests were made on KBL cpu.

**Closed** 2020-09-07 17:22 UTC
Labels: intel anv
