### ISSUE TITLE
Getting Over It with Bennett Foddy (Unity 2017.1.2p4) opens an unresponsive fullscreen window that doesn't render anything

### ISSUE THREAD

**Issue by zekesonxx** [doitsujin/dxvk#85] opened 2018-02-17 04:10 UTC
### Software information
Getting Over It with Bennett Foddy, Humble DRM-free release

### System information
- GPU: GTX 970
- Driver: Nvidia prop 390.25
- Wine version: 2.21-staging
- DXVK version: fd1fd40

### Apitrace file(s)
- apitrace doesn't behave with Unity and spits out a useless trace file

### Log files
- d3d11.log: [GettingOverIt_d3d11.log](https://github.com/doitsujin/dxvk/files/1733402/GettingOverIt_d3d11.log)
- dxgi.log: [GettingOverIt_dxgi.log](https://github.com/doitsujin/dxvk/files/1733403/GettingOverIt_dxgi.log)

**Comment by libcg** [comment] 2018-04-08 19:43
Having the same issue with Firewatch.

[d3d11.log](https://pastebin.com/raw/rsUkeaE0)
[dxgi.log](https://pastebin.com/raw/DEsaaiWw)

**Comment by libcg** [comment] 2018-04-24 18:09
Getting Over It was running fine last time I tried on Intel ANV, @doitsujin close this?

**Comment by doitsujin** [comment] 2018-04-24 18:42
@libcg Does it work in fullscreen mode?

**Comment by libcg** [comment] 2018-04-25 06:08
just tested. it works when launched in fullscreen mode. switching to windowed mode works, but switching to fullscreen causes the game to not be responsive. another issue is that the video modes list 60 and 120Hz even though my laptop only supports 60Hz.

**Comment by doitsujin** [comment] 2018-04-25 08:40
another DXGI issue then. This is seriously starting to get annoying because I cannot reproduce it.

**Comment by doitsujin** [comment] 2018-07-12 20:11
Please re-test with latest master.

**Comment by doitsujin** [comment] 2018-07-19 14:53
Closing due to lack of activity.

**Closed by doitsujin** 2018-07-19 14:53 UTC
Labels: bug, dxgi
