### ISSUE TITLE
Gwent crash when trying to render premium cards

### ISSUE THREAD

**Issue by magist3r** [doitsujin/dxvk#223] opened 2018-03-29 13:54 UTC
Gwent crashes when trying to render premium cards (using DX11 for this I guess).
I think that these lines from d3d11.log are important, because they appeared when crash occurs:

> err:   D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported
err:   D3D11Device::CreateGeometryShaderWithStreamOutput: Not implemented

Unfortunately, apitrace call
`wine ~/code/apitrace-msvc/x64/bin/apitrace.exe trace -a dxgi Gwent.exe`
crashed wineserver.exe after game loading, so no apitrace log, sorry.

### Software information
Gwent: The Witcher Card game

### System information
- GPU: Geforce 660 Ti
- Driver: 390.42
- Wine version: 3.4-staging
- DXVK version: [b286b51](https://github.com/doitsujin/dxvk/commit/b286b518c526d81e4cf5efaf6b79011749533ef7)

### Log files
[Gwent_d3d11.log](https://github.com/doitsujin/dxvk/files/1860286/Gwent_d3d11.log)
[Gwent_dxgi.log](https://github.com/doitsujin/dxvk/files/1860287/Gwent_dxgi.log)

**Comment by doitsujin** [comment] 2018-03-29 14:00
See #135, closing this because you're right in that this crash is likely caused by missing stream output.

**Closed by doitsujin** 2018-03-29 14:00 UTC
Labels: duplicate
