### ISSUE TITLE
Monster Hunter World weird reflection on objects

### ISSUE THREAD

**Issue by BlazeKl** [doitsujin/dxvk#701] opened 2018-10-15 04:20 UTC
The game has some weird metallic looking objects when using DXVK. disabling ingame setting z-prepass fixes some of the objects look when close to the camera but others stay bugged

Recorded an apitrace of the game on windows 7 with native d3d11, the trace reproduces the bug on linux with dxvk (noticeable in the red sign on the back and the wooden floor)

here is a comparison of the game on windows and proton:
- Windows: https://www.youtube.com/watch?v=7QctglngEk4
- Proton: https://www.youtube.com/watch?v=WPXIl5cOhls

This bug is present on both wine+dxvk and proton.

### Software information
Monster Hunter World
high settings

### System information
- GPU: AMD R9 270
- Driver: Mesa-git
- Wine version: Proton 3.16-1
- DXVK version: Proton's 0.81

### Apitrace file(s)
- https://drive.google.com/open?id=1x8FzRT1dZKjc-6KtcE8QHua3rXcrSzu3

it is more noticeable in the red sign on the back and the wooden floor

### Log files
- d3d11.log: [MonsterHunterWorld_d3d11.log](https://github.com/doitsujin/dxvk/files/2477376/MonsterHunterWorld_d3d11.log)
- dxgi.log: [MonsterHunterWorld_dxgi.log](https://github.com/doitsujin/dxvk/files/2477377/MonsterHunterWorld_dxgi.log)

**Comment by doitsujin** [comment] 2018-10-15 05:14
Someone complained about this before and it seems to happen only on RADV, so I tagged it accordingly.

I have a very hard spotting the issue in the apitrace though, can you take a screesnhot showing what it's supposed to look like?

**Comment by BlazeKl** [comment] 2018-10-15 05:39
Here it is another example if you need it:
Windows:
![screenshot_1](https://user-images.githubusercontent.com/17534468/46931853-54351d80-d023-11e8-99bd-e1a4fd2f0603.png)
DXVK:
![screenshot_20181015_023607](https://user-images.githubusercontent.com/17534468/46931902-8ba3ca00-d023-11e8-859a-8ba852669e9f.png)

**Comment by doitsujin** [comment] 2018-10-15 06:06
Bad news, while I can reproduce the problem, I cannot actually debug it right now because Renderdoc refuses to work.

**Comment by BlazeKl** [comment] 2018-10-15 14:47
don't worry, the game is still pretty playable rn so no need to hurry. I hope you can get renderdoc working

**Comment by urmamasllama** [comment] 2018-10-19 14:53
Dropping in to confirm the issue.
RX580 Mesa-git. 
I've also tried on mesa 18.2 and tried different proton releases. I honestly wasn't sure if it was a driver issue, DXVK issue, or some combination. I would have mentioned it a couple of weeks ago but I was busy tracking down my stutter issue that was apparently from using TearFree.

**Comment by doitsujin** [comment] 2018-12-04 11:01
Apparently this is an LLVM regression, it appears to render fine on LLVM 6.

**Comment by ZyxionQuiksilver** [comment] 2018-12-14 18:09
Just wanted to add that I have tested this one pretty thoroughly. I've seen it using LLVM6, 7, 8. Mesa versions from 18.1.1 to current git (19.0?). 

- GPU: R9 Fury
- Driver: Mesa-git
- Kernel: 4.20RC5
- Wine: Proton 3.16-5
- DXVK: (TODO: Double check most recent)
- Distro: Kubuntu 18.10 (Have also tested U18.04, Arch)

I've been messing with all sorts of different Mesa packages since SteamPlay was released, and there have only bee 2 consistencies that whole time- Monster Hunter World will ALWAYS launch (no idea why, but it really always does), and it will always have this metallic issue. 

No hurry, but glad this is still being looked at. If anyone wants any specific software configurations tested, I've got no issue playing around with stuff. I really doubt it's hardware related, but I'll have a Vega 64 here soon. If things change, I'll be sure to shout.

**Comment by hakzsam** [comment] 2019-05-07 14:07
I found the root cause of the reflection issue, here's the workaround for Mesa and LLVM 7&8 https://patchwork.freedesktop.org/series/60376/ and the LLVM 9 fix is here https://reviews.llvm.org/D61313

**Comment by BlazeKl** [comment] 2019-05-07 23:25
@hakzsam mesa patch worked, will test the llvm 9 patch on the weekend when I have time for compiling. thanks for looking into it

**Comment by hakzsam** [comment] 2019-05-17 09:41
Fixed with LLVM r361008 (LLVM 9+) and fixed inside Mesa for LLVM 7&8, see https://cgit.freedesktop.org/mesa/mesa/commit/?id=d7501834cd86f9ec0b7c3dea17448dc523e36390

**Closed** 2019-05-17 09:45 UTC
Labels: amd radv
