### ISSUE TITLE
ABZU: black screen after developer logos

### ISSUE THREAD

**Issue by roothorick** [doitsujin/dxvk#77] opened 2018-02-14 21:13 UTC
### Software information
ABZU: http://www.abzugame.com/
Default settings (cannot reach options menu)

Displays developer logos, then stops on a black screen. Can hear music.

### System information
- GPU: Radeon RX 480
- Driver: Mesa 17.3.2 RADV
- Wine version: 2.21 (Staging)
- DXVK version: git 0c2058e

### Apitrace file(s)
Impossible due to limitations in apitrace

### Log files
- d3d11.log: https://pastebin.com/fbGkeREr
- dxgi.log: https://pastebin.com/83EZvkAQ

**Comment by doitsujin** [comment] 2018-02-15 13:32
Is this by any chance an Unreal Engine 4 game? Because I'm starting to see a pattern here:

> `err:   DxbcCompiler: Unhandled PS SV input: DxbcSystemValue::RenderTargetId`

Fixing this is going to be a bit tricky though.

**Comment by GabrielMajeri** [comment] 2018-02-15 13:46
@doitsujin It is using Unreal Engine, it is even featured on the UE4 main page.

**Comment by doitsujin** [comment] 2018-02-15 17:17
Please try with 8ebffc1018173903b4bfaf41561fb9bd2b006f74.

**Comment by roothorick** [comment] 2018-02-15 19:39
Seems to take longer now, and I can just make out the edge of what might be a loading spinner at the bottom oft he screen, but that disappears after a while and it still hangs.

**Comment by roothorick** [comment] 2018-02-15 19:55
There may be a driver bug involved... now if I try to kill the game, it just zombifies, still taking up the screen, and no amount of killing Wine processes recovers the desktop. Attempting to VT switch blacks out the screen, with no way to get that back either. Machine fails to restart, necessitating a hard reset.

**Comment by doitsujin** [comment] 2018-02-15 22:55
What's your `dmesg` output? This could be caused by a VM fault on the GPU.

**Comment by roothorick** [comment] 2018-02-15 23:56
I initially wasn't getting any dmesg output. The secret appears to be to wait a really long time. In excess of 7 minutes. Rendering the process a zombie may have been necessary.

https://pastebin.com/yni3U4by

Some anomalies:

* It took a lot longer than 120 seconds between the hang and when this appeared in dmesg
* 3046 was not the PID of the game.

**Comment by doitsujin** [comment] 2018-04-17 19:33
Since the game itself seems to work (see [here](https://www.youtube.com/watch?v=ivYFG2207no)), I'll close this. Please comment on #252 if the GPU hang is still a thing.

**Closed by doitsujin** 2018-04-17 19:33 UTC
Labels: dxbc, feature set

**Comment by tristan-k** [comment] 2021-09-16 12:33
I'm having the same issue on an Apple MacBook Air (M1) with legendary and Crossover 20.0.4. Not sure where to go from here.

![ms_cap_full_2021-16-09-023109](https://user-images.githubusercontent.com/732025/133612822-edb550f4-3252-4cec-b083-83c73026007c.png)

**Comment by doitsujin** [comment] 2021-09-16 14:49
We do not support Apple hardware. Please report this to Codeweavers directoy.
