### ISSUE TITLE
Bloodstained: Ritual of the Moon crashing

### ISSUE THREAD

**Issue by Rugaliz** [doitsujin/dxvk#1099] opened 2019-06-19 11:05 UTC
I get a crash when after loading from the first hub (at around 1h of game time after the ship crashes you reach this place) and i travel 2 to 3 screens in any direction.
### Software information
Bloodstained: Ritual of the Moon version 1.03
I tested various graphical settings, fullscreen, windowed, with and without vsync...

The odd thing is, when i started from the beginning i had over 1 h of gameplay with no crashes, but now when i load from that save i get this crash.

### System information
Fedora 30 kernel:  5.1.11-300.fc30.x86_6
- GPU: Nvidia GTX 770
- Driver: 418.74
- Wine version: 4.2 (Proton version)
- DXVK version: 1.2.2 (also testes previous down to 1.1.1)

### Log files
[BloodstainedRotN-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/3305731/BloodstainedRotN-Win64-Shipping_dxgi.log)

[BloodstainedRotN-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/3305728/BloodstainedRotN-Win64-Shipping_d3d11.log)

**Comment by doitsujin** [comment] 2019-06-19 12:37
Looks like the Nvidia driver runs out of VRAM. This is a known issue and seems to happen in many games as of late (see #1087), but the root cause is unknown.

If you have desktop effects enabled, disable them, and close **all** other applications, especially your web browser, to mitigate this issue.
```
err:   DxvkMemoryAllocator: Memory allocation failed
  Size:      11206656
  Alignment: 65536
  Mem flags: 0x1
  Mem types: 0x82
```

**Comment by doitsujin** [comment] 2019-06-19 12:51
Can you please try this build and upload new logs?
[dxvk-master.tar.gz](https://github.com/doitsujin/dxvk/files/3306151/dxvk-master.tar.gz)

This is **not** going to fix your issue, but should hopefully shed some light on what is going on.

**Comment by Rugaliz** [comment] 2019-06-19 13:14
Okay, here are the new logs. hope this helps.
Oh and thanks for your great work so far :) 

[BloodstainedRotN-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/3306239/BloodstainedRotN-Win64-Shipping_d3d11.log)


[BloodstainedRotN-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/3306240/BloodstainedRotN-Win64-Shipping_dxgi.log)

**Comment by doitsujin** [comment] 2019-06-19 13:28
So from the application's point of view, you're not even **close** to running out of memory. Weird.

Here's one more build I'd like you to run (and again post new logs). Same deal as before, won't fix the problem but shows additional information about what exactly DXVK is actually doing when allocating memory.
[dxvk-test.tar.gz](https://github.com/doitsujin/dxvk/files/3306298/dxvk-test.tar.gz)

**Comment by Rugaliz** [comment] 2019-06-19 13:54
New batch of logs ready
[BloodstainedRotN-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/3306417/BloodstainedRotN-Win64-Shipping_d3d11.log)


[BloodstainedRotN-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/3306418/BloodstainedRotN-Win64-Shipping_dxgi.log)

**Comment by doitsujin** [comment] 2019-06-19 14:05
So it is as I thought, my memory allocator correctly iterates over all memory types but the driver fails with `VK_ERROR_OUT_OF_DEVICE_MEMORY`. Not much I can do there, sorry - you might have to try to run this game with wined3d instead.

Closing in favour of #1100.

**Closed by doitsujin** 2019-06-19 14:05 UTC
Labels: nvidia

**Comment by dlshinobi** [comment] 2019-06-19 14:19
It's weird. I run this game on GTX 960 2GB everything on Epic settings in 1080p, 4 bosses down, not a single crash, or memory related issue. But I run on nVidia beta drivers: 418.52.10. Maybe try different driver version.
P.S. The game is 64-bits.

**Comment by doitsujin** [comment] 2019-06-19 14:27
I believe this kind of depends on your environment as well, i.e. the window manager and other applications running in the background. This issue is particularly common when users have Chromium open, but apparently closing that does not always fix the problem.

> P.S. The game is 64-bits.

Thanks for confirming.

**Comment by Rugaliz** [comment] 2019-06-19 15:14
> It's weird. I run this game on GTX 960 2GB everything on Epic settings in 1080p, 4 bosses down, not a single crash, or memory related issue. But I run on nVidia beta drivers: 418.52.10. Maybe try different driver version.
> P.S. The game is 64-bits.

can you post your distro and desktop environment?

**Comment by dlshinobi** [comment] 2019-06-19 16:06
> > It's weird. I run this game on GTX 960 2GB everything on Epic settings in 1080p, 4 bosses down, not a single crash, or memory related issue. But I run on nVidia beta drivers: 418.52.10. Maybe try different driver version.
> > P.S. The game is 64-bits.
> 
> can you post your distro and desktop environment?

Oh boy mine OS setup is very old and outdated. And I'm to lazy to update and honestly kinda pointless 'cause everything is working without issues. 2 years+ and not a single DE crash since installation.
Distribution: openSUSE 15.0
DE: KDE 5.12.5
Kernel: 4.12.14
