### ISSUE TITLE
Winlator dx9 regression at 2.5.x builds

### ISSUE THREAD

**Issue by gurachan** [doitsujin/dxvk#4489] opened 2024-11-25 07:51 UTC
### System information
- GPU: Adreno 735
- Driver: Turnip 25.0
- Wine version: 9.2
- DXVK version: 2.5.1
- Box64: c30a392 ( action build artifact )
- App: Simple d3d9 test environment 

# **DXVK 0.4 ~ 2.4.1**
![Screenshot_2024-11-25-15-41-10-494_com winlator](https://github.com/user-attachments/assets/fbd924f3-c57b-45dc-b468-f473f050d042)

# **DXVK 2.5 ~ 2.5.1**
![Screenshot_2024-11-25-15-42-14-753_com winlator](https://github.com/user-attachments/assets/16f7e9e9-e8a0-463d-8aa0-06421df0c5d9)

What happened? :'( wheres my cute 4 digit fps.

**Comment by K0bin** [comment] 2024-11-25 07:57
Duplicate of #4484

**Closed** 2024-11-25 10:22 UTC

**Comment by doitsujin** [comment] 2024-11-25 23:58
Yeah someone worked out that this is almost certainly caused by turnip having to emulate timeline semaphores when running on top of the proprietary Qualcomm kernel driver. It's not really viable for us to revert back to the old path, so future versions of DXVK will remain slow.

**Comment by hisham2630** [comment] 2024-11-26 07:51
> Yeah someone worked out that this is almost certainly caused by turnip having to emulate timeline semaphores when running on top of the proprietary Qualcomm kernel driver. It's not really viable for us to revert back to the old path, so future versions of DXVK will remain slow on this platform.

what about an environment variable or an option in config file to disable that timeline semaphores?

**Comment by K0bin** [comment] 2024-11-26 08:31
> what about an environment variable or an option in config file to disable that timeline semaphores?

Too much maintenance overhead to keep both paths around.
