### ISSUE TITLE
God Of War - Black screen crash on 750ti

### ISSUE THREAD

**Issue by FatBouk** [doitsujin/dxvk#2459] opened 2022-01-26 08:44 UTC
Hey,
I just got GoW and I'm trying to play it on my 750ti (feature level 11_0) and i keep running into a crash. 

The game turns on, doesn't throw the directx error and just turns off. 

Are there any known fixes for this problem? Buying a new gpu really isn't an option in this economy.

### System information
- GPU: GTX 750ti
- Driver: 511.23
- Wine version: /
- DXVK version: 1.9.4

### Log files
[GoW_dxgi.log](https://github.com/doitsujin/dxvk/files/7945765/GoW_dxgi.log)
[GoW_d3d11.log](https://github.com/doitsujin/dxvk/files/7945766/GoW_d3d11.log)

**Comment by K0bin** [comment] 2022-01-26 13:46
Most likely a driver problem. The game works fine on pretty much every other system. Could also be some external overlay like RivaTuner that messes with DXVK.

**Comment by FatBouk** [comment] 2022-01-26 21:07
Can this somehow be fixed?

**Comment by K0bin** [comment] 2022-01-26 21:18
¯\\\_(ツ)_/¯
We still don't know what is the problem because you didn't provide the info that was in the issue template.

**Comment by FatBouk** [comment] 2022-01-26 21:43
I'm so incredibly sorry, for some reason github didn't take me to the templates page when i submitted the issue. I will add all the required information in the original comment. 

The directx error that i was talking about was this: 
![image](https://user-images.githubusercontent.com/81118249/151251935-1c528d2c-b628-402b-a0f4-d95196e76661.png)

**Comment by K0bin** [comment] 2022-01-26 21:59
FYI that image is so small that I wouldn't be able to read it if I didnt know the error message already.

DXVK supports D3D11 feature level 11_1 (and higher) **if** your GPU and driver supports the necessary Vulkan features.

**Comment by K0bin** [comment] 2022-01-26 22:03
Please upload DXVK logs so we can check why it doesn't report FL11_1.

**Comment by FatBouk** [comment] 2022-01-26 22:08
It should be supported. People have gotten this game running with the same gpu.

**Comment by K0bin** [comment] 2022-01-26 22:08
> info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_1

DXVK reports that FL11_1 is supported. I don't know why it doesn't work.

Just play the game without DXVK, it's most likely gonna be a lot slower than regular D3D11 anyway.

**Comment by FatBouk** [comment] 2022-01-26 22:10
I run into the D3D_FEATURE_LEVEL error when running without dxvk. I guess that i'll have to find a way to patch the executable so that it doesn't check for the feature level. 

Thank you for your help.

**Comment by DadSchoorse** [comment] 2022-01-26 22:11
If I had to guess this is probably another duplicate of #2435.

**Comment by FatBouk** [comment] 2022-01-26 22:13
I already tried the fix in that thread (disabled ansel using NvCameraConfig). It didn't work unfortunately :(

**Comment by K0bin** [comment] 2022-01-26 22:19
No, that PR will not fix the problem.

**Comment by FatBouk** [comment] 2022-01-26 22:31
It looks like that this is a problem isolated to my system configuration. Multiple people have gotten this game running (slowly) on my gpu, but i can't even get past the black screen.

**Comment by FatBouk** [comment] 2022-01-26 22:33
Would the apitrace file help? I don't really know how to make it on windows, but i bet that i can figure it out.

**Comment by K0bin** [comment] 2022-01-26 22:34
Not really and you'd need to get the game to run to make one anyway.

**Closed by K0bin** 2022-01-26 22:34 UTC
Labels: windows
