### ISSUE TITLE
Black Mesa opening; then closing. (Windows)

### ISSUE THREAD

**Issue by Mkilbride** [doitsujin/dxvk#2723] opened 2022-07-14 11:47 UTC
Error log

> info:  Game: bms.exe
info:  DXVK: v1.10.2-async
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: VR_InitInternal or VR_ShutdownInternal not found
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  NVIDIA GeForce RTX 3080 Ti:
info:    Driver: 512.59.0
info:    Vulkan: 1.3.194
info:    Memory Heap[0]: 
info:      Size: 12108 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:    Memory Heap[1]: 
info:      Size: 16344 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: bms.exe
info:  DXVK: v1.10.2-async
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: VR_InitInternal or VR_ShutdownInternal not found
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  NVIDIA GeForce RTX 3080 Ti:
info:    Driver: 512.59.0
info:    Vulkan: 1.3.194
info:    Memory Heap[0]: 
info:      Size: 12108 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:    Memory Heap[1]: 
info:      Size: 16344 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
warn:  DxgiAdapter::QueryInterface: Unknown interface query
warn:  7abb6563-02bc-47c4-8ef9-acc4795edbcf

> 

Using the latest, Async or not.

**Comment by Blisto91** [comment] 2022-07-14 12:27
@Mkilbride Does this also happen with 1.10.1 or 1.10?

**Comment by doitsujin** [comment] 2022-07-14 12:41
The game uses both D3D9 and D3D11, from the log it doesn't look like you're using our D3D9 DLL.

That said, it won't work anyway because it requires shared resources for the UI, and the way it does use them is incredibly broken on the game's side.

**Comment by Blisto91** [comment] 2022-07-14 13:03
As far as i remember it should work with `-oldgameui` since from what i know that doesn't use shared resources. I think.
But i'll have to check when i get home. Might not have checked on windows.

**Comment by aufkrawall** [comment] 2022-07-14 14:45
Yes, then also d3d9.dll suffices.

**Comment by thekovic** [comment] 2022-07-20 17:00
The issue I have found with Black Mesa is that `-oldgameui` has stopped working when added through Steam's Launch Options menu for some reason. If I make my own shortcut to the .exe and apply the launch command there, then it works and I can launch the game with DXVK.

**Comment by K0bin** [comment] 2022-09-06 07:14
Closing this because it's mostly likely just caused by the new UI using shared resources, something we cannot support on Windows.

The game works fine on Linux.

**Closed** 2022-09-06 07:14 UTC
Labels: windows
