### ISSUE TITLE
[Resident evil 2 Remake Demo] invisible object 

### ISSUE THREAD

**Issue by nickfaces** [doitsujin/dxvk#855] opened 2019-01-12 18:18 UTC
### Software information
Name of the game, settings used etc.

### System information
- GPU: RX590
- Driver: mesa-git
- Wine version: wine-git
- DXVK version: latest dev-branch

### Log files

- d3d11.log: [re2_d3d11.log](https://github.com/doitsujin/dxvk/files/2752369/re2_d3d11.log)
- dxgi.log:     [re2_dxgi.log](https://github.com/doitsujin/dxvk/files/2752370/re2_dxgi.log)

![2019-01-12 21-57-25](https://user-images.githubusercontent.com/3217851/51076915-c9ff6280-16c0-11e9-9c5b-468c33690f4a.png)

**Comment by doitsujin** [comment] 2019-01-12 18:36
I already did some debugging on this. It's a game bug, a compute shader that relies on undefined behaviour. This cannot be fixed in DXVK.

The Vulkan driver from the AMDGPU-PRO package renders this game correctly.

**Comment by nickfaces** [comment] 2019-01-12 18:40
So, maybe I have to issue a bug report on mesa bugtracker ?

**Comment by doitsujin** [comment] 2019-01-12 18:50
Not necessary.

**Comment by mixalis1987** [comment] 2019-01-13 02:42
how you even get the demo to start? I try to launch and black screen comes for a minute and quits. Using steam and latest nvidia drivers.

**Comment by Arias800** [comment] 2019-01-13 12:18
@mixalis1987 You need DXVK 0.95 ^^

**Comment by laichiaheng** [comment] 2019-01-13 13:40
@Arias800 How to run the game with DXVK 0.95 in Steam Play or Wine?

**Comment by laichiaheng** [comment] 2019-01-13 13:42
> Not necessary.

Why not?

**Comment by Arias800** [comment] 2019-01-13 13:43
I don't know . I use dxvk-docker for automatically compile and setup dxvk on lutris https://github.com/cheald/dxvk-docker

**Comment by doitsujin** [comment] 2019-01-13 13:45
@laichiaheng it's not helpful when multiple people report the same thing on different channels. I already did inform RADV developers about the issue.

**Comment by laichiaheng** [comment] 2019-01-13 13:54
@doitsujin I see, thank you.

**Comment by nickfaces** [comment] 2019-01-13 14:07
@laichiaheng At least two amd developers(Samuel and Marek) are monitoring dxvk bug reports. :)

**Comment by kassindornelles** [comment] 2019-01-13 15:06
to fix any graphic issue on Resident Evil 2 Remake you need to change that line in the game config file (is on the .exe path)
"UseOptimizeShader=Disable"
the default value is enabled and seems like it causes the issues, please test and let me now if this fix everything for you guys.
![Alt text](https://i.imgur.com/ub0GOSs.png?raw=true "Optional Title")

**Comment by laichiaheng** [comment] 2019-01-13 15:19
> to fix any graphic issue on Resident Evil 2 Remake you need to change that line in the game config file (is on the .exe path)
> "UseOptimizeShader=Disable"
> the default value is enabled and seems like it causes the issues, please test and let me now if this fix everything for you guys.
> ![Alt text](https://camo.githubusercontent.com/35b62e9a31b8b07783017775e3cee77d5e734cbd/68747470733a2f2f692e696d6775722e636f6d2f756230474f53732e706e673f7261773d74727565)

My default is disable.

**Comment by kassindornelles** [comment] 2019-01-13 15:20
> 
> 
> > to fix any graphic issue on Resident Evil 2 Remake you need to change that line in the game config file (is on the .exe path)
> > "UseOptimizeShader=Disable"
> > the default value is enabled and seems like it causes the issues, please test and let me now if this fix everything for you guys.
> > ![Alt text](https://camo.githubusercontent.com/35b62e9a31b8b07783017775e3cee77d5e734cbd/68747470733a2f2f692e696d6775722e636f6d2f756230474f53732e706e673f7261773d74727565)
> 
> My default is disable.

it was enabled by default with my GTX 750, i had weird graphic issues with that on.

**Comment by mixalis1987** [comment] 2019-01-13 17:44
yea using dxvk 0.95 works, game wont crash now when launched. But when you go to start the video on the laptop in the police station nothing happens and then you cant interface with anything, cant even pick up bullets etc but you can still move around and run but you also cant access your inventory. This only happens when trying to start the video on the laptop. If you don't do that everything works fine. So my guess is something to do with video. Also HUD disappears, can't see bullets left or anything once you activate the laptop.

**Comment by doitsujin** [comment] 2019-01-13 17:54
That's some sort of wine bug (you might be right about it being related to the video). It does work with DXVK on Windows.

**Comment by mixalis1987** [comment] 2019-01-13 17:59
hmm ill try other wine versions and see, i only tried wine 4.0-rc4 staging

**Comment by laichiaheng** [comment] 2019-01-14 03:20
Why does the AMDGPU-PRO driver render the game correctly if there is a game bug?

**Comment by laichiaheng** [comment] 2019-01-14 09:47
> I already did some debugging on this. It's a game bug, a compute shader that relies on undefined behaviour. This can probably not be fixed in DXVK and may require a driver hack.
> 
> The Vulkan driver from the AMDGPU-PRO package renders this game correctly.

I still get the incorrect result with AMDGPU-PRO driver.

**Comment by doitsujin** [comment] 2019-01-14 11:13
> Why does the AMDGPU-PRO driver render the game correctly if there is a game bug?

Because it is undefined behaviour. The driver is allowed to do whatever it wants to, that includes rendering the game correctly.

> I still get the incorrect result with AMDGPU-PRO driver, the objects are still invisible.

Did you set `VK_ICD_FILENAMES` to point to the correct json file? It definitely does work with the 18.50 version on Polaris.

**Comment by laichiaheng** [comment] 2019-01-14 12:08
Where do you add this property?
Like this? `VK_ICD_FILENAMES="/etc/vulkan/icd.d/amd_icd/amd_icd64.json"`

**Comment by doitsujin** [comment] 2019-01-14 13:10
@laichiaheng make sure to set your launch options to `VK_ICD_FILENAMES=/etc/vulkan/icd.d/amd_icd/amd_icd64.json %command%` (notice the `%command%`), otherwise it'll just append your option to the command which has no effect.

`radeon_icd.x86_64.json` is the JSON file for RADV.

**Comment by laichiaheng** [comment] 2019-01-14 13:17
@doitsujin It's the result that I didn't add the `%command%` behind it in Steam Properties.
There are lots of blocks in the image.
![2019-01-14 21-09-30](https://user-images.githubusercontent.com/9532105/51114783-4456f080-1841-11e9-992e-1cea6f377867.png)
![2019-01-14 21-09-38](https://user-images.githubusercontent.com/9532105/51114784-4456f080-1841-11e9-8805-822f5fb8c629.png)
![2019-01-14 21-10-22](https://user-images.githubusercontent.com/9532105/51114785-4456f080-1841-11e9-832e-30abf798ddda.png)
If I add the %command% at behind, it crashes.
![2019-01-14 21-15-33](https://user-images.githubusercontent.com/9532105/51114871-8b44e600-1841-11e9-8ec6-ee2f934a1e87.png)
![2019-01-14 21-16-06](https://user-images.githubusercontent.com/9532105/51114947-c6dfb000-1841-11e9-8945-970456c755c6.png)

**Comment by laichiaheng** [comment] 2019-01-14 13:44
@doitsujin It looks really better on the AMDGPU-PRO driver.
I still get the error message if I add the %command% behind it.
Do you play it with Lutris? Or Steam Native?

**Comment by mixalis1987** [comment] 2019-01-14 15:16
Well about that video error when activating the laptop. I'm pretty convinced now that its some type of video bug because when I try to start demo trailers in-game from the menu I just get a black screen but I can still hear the menu sound (Rain I think) but video wont start, so I have to force quit. Terminal doesn't really show anything of interest.

**Comment by mixalis1987** [comment] 2019-01-14 15:31
@laichiaheng that rendering error you see, I had that when I tried to start the game with windows steam version through steam if however when I used Lutris and Lutris launched steam for me and the game I didn't see the error and game started. Just something to try.

**Comment by doitsujin** [comment] 2019-01-18 10:50
The invisible object issue on RADV is fixed in Mesa as of [this commit](https://gitlab.freedesktop.org/mesa/mesa/commit/8424cd8fbd1671c4c13f57cfa34bf8145d0fffcf).

**Closed by doitsujin** 2019-01-18 10:50 UTC
Labels: amd radv, game bug

**Comment by laichiaheng** [comment] 2019-01-18 14:04
@doitsujin Do we still need to add `VK_ICD_FILENAMES=/etc/vulkan/icd.d/amd_icd/amd_icd64.json %command%` to the property if it is fixed?

**Comment by doitsujin** [comment] 2019-01-18 14:12
@laichiaheng with that environment variable you force it to use the -PRO driver, so the answer should be obviously "no"?

**Comment by laichiaheng** [comment] 2019-01-19 03:06
Haven't they merged it to the master branch?

**Comment by laichiaheng** [comment] 2019-01-19 04:47
There seem to be judders with RADV in this game, but my RX580 8G can stay at 60fps in most of the time.

**Comment by ahmed-elsayed2017** [comment] 2019-01-19 15:09
There is another bug related to Wine!

https://bugs.winehq.org/show_bug.cgi?id=46458

**Comment by ahmed-elsayed2017** [comment] 2019-01-19 17:13
It is a bug related to missing mfplat implementation. It is a duplicate bug of RE7.

**Comment by mixalis1987** [comment] 2019-01-21 21:41
@ahmed-elsayed2017 Any way we can fix it temporarily till they add the fix in master WINE?

**Comment by doitsujin** [comment] 2019-01-21 22:10
Short answer: No.

Long answer: It's possible to get the Windows 7 mfplat DLLs to work with wine, but it's rather complicated and should better be discussed elsewhere.

**Comment by mixalis1987** [comment] 2019-01-21 22:13
I have a WINE prefix with mfplat dlls on it I remembered I was using it for Gris the game. I will add DXVK to it when the game comes out and I'll see if it works.

**Comment by laichiaheng** [comment] 2019-01-22 11:22
@mixalis1987 Would you share it with me?

**Comment by mixalis1987** [comment] 2019-01-22 11:32
@laichiaheng Sure I can give it to you now if you like. Just add DXVK I think it has an old version of DXVK on it. You just got to replace the DXVK dlls I think. When the game comes out just install it in the "game" folder you will see a folder Called RE2 in it.

**Comment by laichiaheng** [comment] 2019-01-22 14:25
@mixalis1987 I usually get 4Xfps in the game with my RX580. Do you get the same result?

**Comment by mixalis1987** [comment] 2019-01-22 14:33
I cant test it now again because my minutes ran out.

**Comment by laichiaheng** [comment] 2019-01-22 14:36
@mixalis1987 I have 5 minutes left.

**Comment by laichiaheng** [comment] 2019-01-22 14:52
> @laichiaheng No I get good FPS with my nvidia 1080ti. Do you set your CPU to performance mode? That always helps for me.

It doesn't work, still 4Xfps.

**Comment by nickfaces** [comment] 2019-01-22 14:53
65-80 fps on my RX590 (even with OBS+ffmpeg patch)

**Comment by mixalis1987** [comment] 2019-01-22 15:12
@nickfaces 65-80 is still pretty good. You shouldn't see any lag with that.

**Comment by laichiaheng** [comment] 2019-01-22 15:21
> 65-80 fps on my RX590 (even with OBS+ffmpeg patch)

How? I run RE2 with proton-3.16-6BETA+DXVK0.95 with linux4.20.3+mesa 19.0.0(padoka PPA)
Does RX580 and RX590 have huge difference in performance?

**Comment by mixalis1987** [comment] 2019-01-22 15:26
@laichiaheng Unfortunately I wouldn't know because I always used nvidia. I didn't use proton for RE2 I used WINE-staging-rc4 at the time.

**Comment by ahmed-elsayed2017** [comment] 2019-01-22 16:00
> @ahmed-elsayed2017 Any way we can fix it temporarily till they add the fix in master WINE?

I tried the fix that people used with some games that use WMF, but it didn't work with RE7 and will not work with RE2 Remake, because it is the same old bug.

It is good to see Wine developers fixing old bugs, but I don't think that this bug will be fixed any time soon, so if you need to play any of these games, use Windows.

RE7 on Windows will be more stable on Windows if you use DXVK, and to use DXVK on Windows you need to copy d3d11.dll and dxgi.dll from x64 folder of DXVK to the game folder.

**Comment by ahmed-elsayed2017** [comment] 2019-01-22 16:08
> @ahmed-elsayed2017 Any way we can fix it temporarily till they add the fix in master WINE?

I tried the fix that people used with some games that use WMF, but it didn't work with RE7 and will not work with RE2 Remake, because it is the same old bug. You could try deleting all videos of the game if you can find their location.

**Comment by laichiaheng** [comment] 2019-01-22 16:52
> > @ahmed-elsayed2017 Any way we can fix it temporarily till they add the fix in master WINE?
> 
> I tried the fix that people used with some games that use WMF, but it didn't work with RE7 and will not work with RE2 Remake, because it is the same old bug.
> 
> It is good to see Wine developers fixing old bugs, but I don't think that this bug will be fixed any time soon, so if you need to play any of these games, use Windows.
> 
> RE7 will be more stable on Windows if you use DXVK, and to use DXVK on Windows you need to copy d3d11.dll and dxgi.dll from x64 folder of DXVK to the game folder.
> 
> @doitsujin I am sorry to go off topic, but I had to point that out.

Why do we need DXVK on Windows?

**Comment by ahmed-elsayed2017** [comment] 2019-01-22 17:02
> > > @ahmed-elsayed2017 Any way we can fix it temporarily till they add the fix in master WINE?
> > 
> > 
> > I tried the fix that people used with some games that use WMF, but it didn't work with RE7 and will not work with RE2 Remake, because it is the same old bug.
> > It is good to see Wine developers fixing old bugs, but I don't think that this bug will be fixed any time soon, so if you need to play any of these games, use Windows.
> > RE7 will be more stable on Windows if you use DXVK, and to use DXVK on Windows you need to copy d3d11.dll and dxgi.dll from x64 folder of DXVK to the game folder.
> > @doitsujin I am sorry to go off topic, but I had to point that out.
> 
> Why do we need DXVK on Windows?

I deleted this reply after posting it. Anyway, RE7 gives good performance without using DXVK, but it shutters a lot, and DXVK stabilizes the game for me. I don't know if it does the same for anyone else!

**Comment by mixalis1987** [comment] 2019-01-25 17:50
@laichiaheng No I had the same problem constant loading after the gas station. I also borked my linux instalation so I will be using windows for a bit.

**Comment by mozo78** [comment] 2019-01-25 18:43
@mixalis1987 
use fsarchive and make a backup on a tuned installation. When needed you can back in game literally for 1-2 minutes with brand new and operational installation with all the needed settings and apps. There are no excuses for using Windows.

**Comment by james-munson** [comment] 2019-01-25 20:48
https://github.com/jzengc/wine/tree/proton_3.16_mf

https://github.com/ValveSoftware/Proton/files/2705555/WMF_workaround.zip for people looking for the dlls

**Comment by mixalis1987** [comment] 2019-01-26 00:59
@mozo78 Trust me I dont want to use windows but I want to dual boot but for some reason I cant get linux to detect windows so it will ask me to dual-boot (take care of the partitioning for me) as im not that good with partitioning I hate to say. The only options it gives me is erase disk or manually parition. If Lutris implemented the proton with MF on it I would erase the hard drive and install just linux lol

**Comment by mixalis1987** [comment] 2019-01-26 02:18
Ok fixed my Linux installation dual-booting working so i can continue testing, just got to set up the linux install again how I like.

**Comment by laichiaheng** [comment] 2019-01-26 03:33
> https://github.com/jzengc/wine/tree/proton_3.16_mf
> 
> https://github.com/ValveSoftware/Proton/files/2705555/WMF_workaround.zip for people looking for the dlls

It crashed after I tried the WMF_workaround.zip, I have followed the tutorial command in readme.txt.
How to use the Proton_3.16_mf stuff?

**Comment by mixalis1987** [comment] 2019-01-26 04:47
I get this error when I try to make proton_3.16_mf.
`fatal error: gnutls26/gnutls.h: No such file or directory`
Anyone know how to fix this?

**Comment by mixalis1987** [comment] 2019-01-26 05:30
@ahmed-elsayed2017 Oh so that's the same fix. Damn. I guess we gotta leave it in the hands of the WINE developers and hope they come up with a fix at least a temporary work around.

**Comment by james-munson** [comment] 2019-01-26 05:33
https://github.com/ValveSoftware/Proton/issues/2266

talk here, try the other fix i posted there,

**Comment by mozo78** [comment] 2019-01-26 08:45
> @mozo78 Trust me I dont want to use windows but I want to dual boot but for some reason I cant get linux to detect windows so it will ask me to dual-boot (take care of the partitioning for me) as im not that good with partitioning I hate to say. The only options it gives me is erase disk or manually parition. If Lutris implemented the proton with MF on it I would erase the hard drive and install just linux lol

All you need to do is just update GRUB for 5 seconds, not whole new installation :)

**Comment by ahmed-elsayed2017** [comment] 2019-01-26 12:52
> @ahmed-elsayed2017 Oh so that's the same fix. Damn. I guess we gotta leave it in the hands of the WINE developers and hope they come up with a fix at least a temporary work around.
Don't hold your breath :D

**Comment by ahmed-elsayed2017** [comment] 2019-01-26 12:53
> @ahmed-elsayed2017 Oh so that's the same fix. Damn. I guess we gotta leave it in the hands of the WINE developers and hope they come up with a fix at least a temporary work around.

Don't hold your breath :smile:

**Comment by mixalis1987** [comment] 2019-01-26 16:36
@ahmed-elsayed2017 I'm not lol

**Comment by ahmed-elsayed2017** [comment] 2019-01-26 20:07
> https://github.com/jzengc/wine/tree/proton_3.16_mf
> 
> https://github.com/ValveSoftware/Proton/files/2705555/WMF_workaround.zip for people looking for the dlls

Neither of them work according to my test and TK-Glitch tests.

https://github.com/Tk-Glitch/PKGBUILDS/issues/106#issuecomment-457845489

**Comment by mixalis1987** [comment] 2019-01-26 20:15
@ahmed-elsayed2017 Real shame. The game runs great if it wasn't for that damn mf. I had a save from windows that bypassed some videos so now im playing the game on linux I'm at the underground facility sewers with ada. Who knows when a video file will come up again till then just gotta keep saving often.

**Comment by ahmed-elsayed2017** [comment] 2019-01-28 00:33
Some people managed to run Resident Evil 2 Remake, but they didn't mention what they did exactly

https://www.reddit.com/r/linux_gaming/comments/ajyx51/resident_evil_2_playable_with_the_latest_dxvk_and/

**Comment by mixalis1987** [comment] 2019-01-28 04:47
@ahmed-elsayed2017 Looks interesting but the instructions are not very clear maybe if some one more skilled can make a video?

**Comment by laichiaheng** [comment] 2019-01-29 15:16
@mixalis1987 He did it: #886

**Comment by mixalis1987** [comment] 2019-01-29 22:30
@laichiaheng Got the game to work! FPS is good.

**Comment by ahmed-elsayed2017** [comment] 2019-01-29 23:54
Nice! Resident Evil 7 Biohazard works as well

![screenshot_20190130_014143](https://user-images.githubusercontent.com/29783425/51948623-dc53fd00-2431-11e9-99be-e47379b3abb5.png)

The modified script to be used directly:

[python-installcab-master.zip](https://github.com/doitsujin/dxvk/files/2810226/python-installcab-master.zip)

**Comment by mixalis1987** [comment] 2019-01-30 01:10
@ahmed-elsayed2017 Yes can confirm RE7 is also working fully and on high settings. Good FPS.

**Comment by laichiaheng** [comment] 2019-01-30 01:13
@mixalis1987 How good is it?
What CPU and GPU are you using?

**Comment by mixalis1987** [comment] 2019-01-30 01:32
@laichiaheng oh right lol forgot the `%command%` at the end.

**Comment by ahmed-elsayed2017** [comment] 2019-01-30 01:38
> @ahmed-elsayed2017 Yes can confirm RE7 is also working fully and on high settings. Good FPS.

It is working great. I changed Display Mode to borderless window to force Vsync, and Rendering Method to Normal to be able to read the text well.

**Comment by mixalis1987** [comment] 2019-01-30 01:46
@laichiaheng I think the issue is both (CPU and DE) that's why I always use xfce4 for Linux so it doesn't use up too much CPU power when playing in the background so WINE can have most of it.

**Comment by laichiaheng** [comment] 2019-01-30 16:27
@mixalis1987 There is no more stuttering problem in XFCE4, thanks. But still low frame rates.

**Comment by mixalis1987** [comment] 2019-01-30 16:30
@laichiaheng That might be the CPU then. Also if you haven't try lower graphics.

**Comment by ahmed-elsayed2017** [comment] 2019-01-30 16:51
> @mixalis1987
> How good is it in RE2? No stutter in game and audio desync in cut scene?
> 
> What CPU and GPU are you using? Is anyone also in Gnome3 on Ubuntu18.04.1?

XFCE and KDE are lighter than Gnome and Cinnamon.

Look at this [guide](
https://github.com/ValveSoftware/Proton/wiki/Requirements) to know how to update your Nvidia or AMD card to the latest version if you haven't done it yet

Ubuntu 18.10 uses kernel 4.18, and Ubuntu 18.04 uses kernel 4.15. You might need to upgrade your system. Here is a guild to how to upgrade your system >>> https://www.omgubuntu.co.uk/2018/10/how-to-upgrade-to-ubuntu-18-10

**Comment by mixalis1987** [comment] 2019-01-30 17:07
Yea always update GPU drivers that helped a lot with `Nier: Automata` FPS jumped straight up after updating for that game.

**Comment by mixalis1987** [comment] 2019-01-30 17:35
@laichiaheng Mesa are opensource drivers right? I read everywhere that the native ones from the companies are always better to use for gaming on linux. I always use the non-free drivers.

**Comment by laichiaheng** [comment] 2019-01-30 17:39
@mixalis1987 Isn't Mesa RADV better than the proprietary AMDGPU-PRO driver on Linux now?

**Comment by ahmed-elsayed2017** [comment] 2019-01-30 17:45
Resident Evil 7 Biohazard was unstable even on Windows, so I expect fps drops with Resident Evil 2 Remake.

**Comment by mixalis1987** [comment] 2019-01-30 17:55
@laichiaheng Sorry can't say much about the drivers, never owned AMD.

**Comment by mixalis1987** [comment] 2019-01-30 18:37
Side note. Also got game trainer working with this game. I can make video if there is an interest.

**Comment by mozo78** [comment] 2019-01-30 20:41
> Nice! Resident Evil 7 Biohazard works as well
> 
> ![screenshot_20190130_014143](https://user-images.githubusercontent.com/29783425/51948623-dc53fd00-2431-11e9-99be-e47379b3abb5.png)
> 
> The modified script to be used directly:
> [python-installcab-master.zip](https://github.com/doitsujin/dxvk/files/2810379/python-installcab-master.zip)
> 
> **You need to write:**
> winetricks mf
> export WINEPREFIX=/where the prefix of the game is
> ./install-mf-64.sh
> You need to copy mfplat.dll version 12.0.7601.23471 (64bit) to the game folder

Is it the latest Gold version or the old one?

**Comment by ahmed-elsayed2017** [comment] 2019-01-30 20:49
> > Nice! Resident Evil 7 Biohazard works as well
> > ![screenshot_20190130_014143](https://user-images.githubusercontent.com/29783425/51948623-dc53fd00-2431-11e9-99be-e47379b3abb5.png)
> > The modified script to be used directly:
> > [python-installcab-master.zip](https://github.com/doitsujin/dxvk/files/2810379/python-installcab-master.zip)
> > **You need to write:**
> > winetricks mf
> > export WINEPREFIX=/where the prefix of the game is
> > ./install-mf-64.sh
> > You need to copy mfplat.dll version 12.0.7601.23471 (64bit) to the game folder
> 
> Is it the latest Gold version or the old one?

The old one.

**Comment by mozo78** [comment] 2019-01-30 20:54
Thank you :)
Did you try the newest Gold version? I tried it but it crashes at Start game selection.

**Comment by ahmed-elsayed2017** [comment] 2019-01-30 21:00
> Thank you :)
> Did you try the newest Gold version? I tried it but it crashes at Start game selection.

Did you copy mfplat.dll to the game folder?
You need mfplat.dll version 12.0.7601.23471 (Windows7 - 64bit).
IF you don't have the file, send me a private message and I will send it to you.

**Comment by mozo78** [comment] 2019-01-30 21:10
Yes I copied the mfplat.dll version 12.0.7601.23471 to the game folder but no go :(

**Comment by mixalis1987** [comment] 2019-01-30 21:11
@mozo78 I think i'm using the gold edition as it has extra content in it `banned footage` etc

**Comment by mixalis1987** [comment] 2019-01-30 21:12
and ran the mfplat install script?

**Comment by ahmed-elsayed2017** [comment] 2019-01-30 21:12
> Yes I copied the mfplat.dll version 12.0.7601.23471 to the game folder but no go :(

Did you get any errors while executing the script?

**Comment by mixalis1987** [comment] 2019-01-30 21:14
@mozo78 whats your distro?

**Comment by mozo78** [comment] 2019-01-30 21:19
> > Yes I copied the mfplat.dll version 12.0.7601.23471 to the game folder but no go :(
> 
> Did you get any errors while executing the script?

Nope, everything is allright wit no errors at all:
https://pastebin.com/d2Mf7dxm


> @mozo78 whats your distro?

Arch Linux.

**Comment by mozo78** [comment] 2019-01-30 21:33
Yes, I downloaded it from the net and I installed Windows 7 on a Virtualbox VM. The game doesn't work with both dlls...

**Comment by mixalis1987** [comment] 2019-01-30 21:37
@mozo78 And you sure of the version? did you right click mfplat in windows and go to the details tab to see if its the correct one?

**Comment by mixalis1987** [comment] 2019-01-30 21:50
latest WINE version?

**Comment by mozo78** [comment] 2019-01-30 21:59
Yeah - Wine-Staging 4.0. I tried it with wine-3.16-6-proton also.

**Comment by mixalis1987** [comment] 2019-01-30 22:01
Am I right? Do I have the gold version if I have banned content included?

**Comment by mozo78** [comment] 2019-01-30 22:16
I don't know. I'll try 2017 Deluxe version :)

**Comment by mozo78** [comment] 2019-01-30 23:40
Now I tried the oldest version and it actually runs without problems. The problem is in the Gold version :)

**Comment by mixalis1987** [comment] 2019-01-30 23:53
@mozo78 Do you have banned content?

**Comment by mozo78** [comment] 2019-01-31 08:16
How can I check it? I actually don't play this game. It's a hobby to set games in Wine and just wish to try that too :)
