### ISSUE TITLE
Fallout 4: Dark overlay on inside locations

### ISSUE THREAD

**Issue by baldrianbandit** [doitsujin/dxvk#872] opened 2019-01-20 17:04 UTC
From v0.94-27-g9faf841 to latest, in certain inside locations in Fallout4, I experience some kind of shadow overlay on the bottom half of the screen, e.g. in Fort Strong:
![fallout4](https://user-images.githubusercontent.com/12493502/51442429-c2e9dd00-1cdc-11e9-9adb-1d3406fab3a7.jpg)

4.20.3-arch1-1-ARCH
xf86-video-amdgpu 18.1.0 (Radeon 480)
wine-4.0-rc7

[Fallout4_d3d11.log](https://github.com/doitsujin/dxvk/files/2776836/Fallout4_d3d11.log)
[Fallout4_dxgi.log](https://github.com/doitsujin/dxvk/files/2776837/Fallout4_dxgi.log)

**Comment by doitsujin** [comment] 2019-01-20 19:30
Can you please either record an apitrace or attach a save game so that I at least have a **chance** to reproduce the problem locally?

**Comment by doitsujin** [comment] 2019-01-21 17:35
@baldrianbandit ping?

**Comment by doitsujin** [comment] 2019-01-21 17:56
Please test latest mesa-git and LLVM 8.0. Renders fine for me:
![bildschirmfoto-540](https://user-images.githubusercontent.com/25567304/51491284-2859ce80-1dae-11e9-93e6-6506ec575fa5.png)

**Comment by t14462** [comment] 2019-02-12 17:25
This problem also exist on mesa-git + radv

**Comment by doitsujin** [comment] 2019-02-13 08:02
What's your LLVM version? As shown above, it renders fine with llvm-git on my RX 480.

**Comment by t14462** [comment] 2019-02-14 12:16
I reverted mesa to stock, but LLVM version was latest svn from mesa-git unofficial arch repo. I think it's 8.0.0

**Comment by radcapricorn** [comment] 2019-02-17 11:49
I'm observing the same with the binary release of 0.96, running on a GTX980 Ti (415.27). The issue appears from the start of the game, and is especially apparent throughout Vault 111. Also with that release most decals (both pre-placed and dynamic, i.e. bullet holes) flicker in and out depending on camera position and angle. Reverting to 0.94 removes both problems.

**Comment by doitsujin** [comment] 2019-02-17 12:26
@radcapricorn can you please bisect the problem? I'm unable to reproduce it.

**Comment by radcapricorn** [comment] 2019-02-17 14:37
@doitsujin Yes, just after character creation while walking around in the house. It's intermittent, i.e. only appears when you're looking in certain directions. I'll try bisecting as soon as I get a mingw toolchain set up.

I wonder, are you running with dxvk.conf customized for the game?

**Comment by doitsujin** [comment] 2019-02-17 16:11
no.

**Comment by radcapricorn** [comment] 2019-02-17 17:11
@doitsujin Ok, bisect suggests that the issue in question starts with 17398e47bda823eeb84815603e1f470002d6149b. The "overlay" is present and there's wild intermittent decal clipping. I don't know if the two are related though. One commit before that also shows *some* decal clipping, but not nearly as bad. I'll try bisect to isolate that one as well. But anyway, *this* issue's culprit is 17398e47bda823eeb84815603e1f470002d6149b.

**Comment by radcapricorn** [comment] 2019-02-17 19:26
@doitsujin Update, that was a silly mistake to make, but I haven't actually tested master when I got mingw installed. The issue isn't there, and bisecting from 0.96 shows that it's fixed by 311661e4041e182e9bd6d8a6bd3d168901bb5c87.

**Comment by t14462** [comment] 2019-02-17 21:43
Bug was accessible in 0.96 from game start, but in dxvk-git version it completely disappeared.

**Comment by baldrianbandit** [comment] 2019-02-23 02:44
I can confirm that.

**Closed** 2019-02-23 02:45 UTC
Labels: can't reproduce

**Comment by t14462** [comment] 2019-02-25 16:10
Fixed on 0.96 by latest mesa-git + llvm-svn
