### ISSUE TITLE
Star Wars: The Old Republic MSAA bugs

### ISSUE THREAD

**Issue by elinmyr** [doitsujin/dxvk#3135] opened 2022-12-12 21:15 UTC
I don't know if this is something you can help with because I cannot get an apitrace. Game crashes immediately with apitrace d3d9.dll in the folder. In-game FXAA works fine, as does NVIDIA DSR, so this issue doesn't seem like a very big deal.

Shader glitches while using in-game MSAA or overriding MSAA through dxvk.conf as seen in screenshots. Using in-game MSAA causes heavily pixellated or broken visual effects.

https://imgur.com/a/RRhZCvC

Using dxvk.conf d3d9.forceSwapchainMSAA set to ANY value causes several game elements to become various forms of transparent/missing without seeming to apply MSAA.

https://imgur.com/a/kYeSc37

No change if running/not running as administrator, enabling/disabling fullscreen optimization, enabled or disabled Steam overlay, no geforce experience installed. Whether fullscreen or fullscreen [windowed].

### Software information
Star Wars: The Old Republic, ultra graphics preset
32-bit
d3d9 game
Game runs two swtor.exe processes simultaneously.

### System information
GPU: NVIDIA GeForce GTX 970
Driver: 527.56
Wine version: Windows 10
DXVK version: 2.0

### Apitrace file(s)
- Game fails to launch when apitrace is in game folder. Should just be d3d9.dll? I have deleted EVERYTHING in this folder and verified local files to ensure nothing but swtor game assets are in there (i.e. no reshade leftovers etc). Apitrace will not launch.

### Log files
- d3d9.log: unavailable, apitrace will not launch.

**Comment by Blisto91** [comment] 2022-12-12 21:27
Hello. I will check out the game on Linux here when i have time as i've tested it with dxvk before.
Does this also happen with 1.10.3 as i don't remember spotting this issue? Tho i've mostly tested on Linux with AMD

> Using dxvk.conf d3d9.forceSwapchainMSAA set to ANY value causes several game elements to become various forms of transparent/missing without seeming to apply MSAA.

This is not unheard of as there can be a conflict when the game has it turned off but dxvk enbaled in config or vice versa.

> d3d9.log: unavailable, apitrace will not launch.

The log needed is the one generated by dxvk when the issue occurs without apitrace.

**Comment by K0bin** [comment] 2022-12-12 21:32
> Using dxvk.conf d3d9.forceSwapchainMSAA set to ANY value causes several game elements to become various forms of transparent/missing without seeming to apply MSAA.

Forcing MSAA will usually break things. Do not do that.

**Comment by Blisto91** [comment] 2022-12-12 22:23
I've not been able to reproduce so far on Linux with a R9 380X and the radv driver with either AA set to high or very high. The former i gather is MSAA x2 and latter MSAA plus FXAA.
I will check on my Geforce 960 later

**Comment by Blisto91** [comment] 2022-12-13 22:29
Okay i am confirming this on my Geforce 960 on Linux.
I have made a trace together with dxvk <https://mega.nz/file/lkx33KJC#W5UQ9LvkpaL1LHvmAKB9DTN0-82zB3-CcUjo742ntoQ>

**Comment by elinmyr** [comment] 2022-12-14 03:27
Thank you so much! I've been busy with work and haven't had much time to keep fiddling around with the apitrace. If needed, I can try again tomorrow because I won't be as busy.

**Comment by Blisto91** [comment] 2022-12-14 07:37
No worries., the devs will try to look into it. 
Thank you for reporting the issue.

**Comment by Blisto91** [comment] 2022-12-14 19:13
Bisected to be a regression with commit https://github.com/doitsujin/dxvk/commit/e406484b84f7ebf9b3a6ebeea187c4d127aa0856

**Comment by K0bin** [comment] 2022-12-15 21:20
This very much looks like a Nvidia driver bug. DXVK does an empty render pass (with VK_KHR_dynamic_rendering) and uses that to resolve a depth stencil image. That doesn't seem to work correctly on Nvidia drivers.

Before e406484b84f7ebf9b3a6ebeea187c4d127aa0856 DXVK used a different code path that uses a shader.

**Comment by Whitestrak3** [comment] 2023-02-23 15:03
Just reporting that I have the same problem on Windows 10 64-bit RTX 3070 gpu. Any anti-aliasing above medium setting will cause artifacts.

**Comment by K0bin** [comment] 2023-03-01 17:56
https://drive.google.com/file/d/1vIiOA4riPbzCvSUhdLCFfDI2MkGlIJf-/view?usp=share_link

Apitrace + RDC reupload

**Comment by K0bin** [comment] 2023-03-07 02:25
Nvidia have informed me that they reproduced and fixed the bug. The next Vulkan beta driver should fix this issue.

**Comment by elinmyr** [comment] 2023-03-07 19:15
Thank you so much for looking into this and for all that you do.

**Comment by pdaniell-nv** [comment] 2023-03-11 18:02
A fix for this bug is available in our latest Vulkan beta drivers found here: https://developer.nvidia.com/vulkan-driver. Use Linux driver version 525.47.13 or Windows driver version 531.32.

**Closed** 2023-03-11 18:05 UTC
Labels: nvidia, d3d9

**Comment by dagrboii** [comment] 2023-04-05 13:45
@K0bin Still experiencing this bug.. and updated drivers for Nvidia. For a layman, are the apitrace / rdc files you uploaded fixes for a recompile? SWTOR recently released a 64bit client.

**Comment by K0bin** [comment] 2023-04-05 13:53
No, you just need to install the Nvidia Vulkan beta driver.

**Comment by Blisto91** [comment] 2023-04-05 14:00
Note the beta drivers, as the name implies, aren't as tested and can have bugs. The fix will arrive in the stable drivers at a later date.
