### ISSUE TITLE
Frequent freezes in certain games(ELEX/Monster Hunter: World)

### ISSUE THREAD

**Issue by rsw0x** [doitsujin/dxvk#925] opened 2019-02-19 00:57 UTC
When playing ELEX & Monster Hunter: World I get seemingly random freezes after 15 mins-2+ hours of gameplay(it would be impossible to play it with APITrace enabled for this long), with this in dmesg:

```
NVRM: Xid (PCI:0000:01:00): 31, Ch 00000033, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_PE_2 faulted @ 0x1_0841a000. Fault is of type FAULT_PTE ACCESS_TYPE_READ
```

### Software information
 - Elex, tried changing the graphics configurations, windowed, vsync, etc., — problem still persists
 - Also happens with Monster Hunter: World

### System information
- GPU: GTX 970
- Driver: Nvidia 415.27
- Wine version: 4.1 staging and 4.2 staging, tried both dll and winelib versions of DXVK

 and the problem persists
- DXVK version: 0.96

### Log files
- d3d11.log:[ELEX_d3d11.log](https://github.com/doitsujin/dxvk/files/2877806/ELEX_d3d11.log)
- dxgi.log: [ELEX_dxgi.log](https://github.com/doitsujin/dxvk/files/2877805/ELEX_dxgi.log)

Unsure if this will be any use, but I did manage to capture some maybe interesting stuff using VK_LAYER_LUNARG_standard_validation
[elex_dump.txt](https://github.com/doitsujin/dxvk/files/2877821/elex_api_dump.txt)

Possibly related issues:

#816 
https://github.com/doitsujin/dxvk/issues/759#issuecomment-453108515

**Comment by doitsujin** [comment] 2019-02-19 08:14
Closing as a duplicate of #816, please drop a comment there.

The validation errors are not relevant, the invalid subpass barrier is how transform feedback barriers were originally meant to be implemented, but right now there is no satisfactory and "valid" solution.

Binding an `UINT` format view to a slot that expects `SFLOAT` format is a common game bug and should also not cause GPU hangs, since at worst it alters how the same data is interpreted.

Anyway, I'm unable to reproduce the issue with Elex, and even if I could, I wouldn't know how to debug Nvidia driver hangs.

**Closed by doitsujin** 2019-02-19 08:14 UTC
Labels: duplicate
