### ISSUE TITLE
WWE 2K22: colors flashing

### ISSUE THREAD

**Issue by us21d** [doitsujin/dxvk#2654] opened 2022-05-27 21:37 UTC
Hi, when I launch WWE 2K22 all I can see are plain colors that flash or just dark colors, I can hear sound and I can access the main menu with the controller despite seeing anything but colors.

![Screenshot 2022-05-27 223641](https://user-images.githubusercontent.com/106408551/170792288-328e83e6-e978-4a31-92ad-5c3e6604aff4.png)

### Software information
WWE 2K22
Graphics Setting: low preset

### System information
- GPU: EVGA GTX GeForce 660
- Driver: 473.47
- DXVK version: v1.9.4-async

### Log files
[WWE2K22_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/8789715/WWE2K22_x64_dxgi.log)

**Comment by Blisto91** [comment] 2022-05-28 12:35
From the driver version i assume you are using windows.
Are you launching the game with `-force-dx11` or `-dx11`? if either of those actually do anything. dxvk doesn't handle dx12 games.

Also make sure to try with the latest dxvk version

**Comment by doitsujin** [comment] 2022-05-29 21:57
Please note that we cannot support Kepler GPUs anymore since they aren't getting the latest drivers anymore. DXVK is known to be somewhat dodgy on those older cards.

**Comment by Blisto91** [comment] 2022-07-04 06:35
@us21d Friendly ping

**Comment by pethesdaniel** [comment] 2022-10-03 16:13
I have a similar issue when trying to run CP2077 with vkd3d-proton and dxvk dxgi.dll. 

OS: Windows 10 21H2
GPU: NVIDIA GTX 860M 517.48

**Comment by K0bin** [comment] 2022-10-03 16:23
Cyberpunk 2077 is a different game and doesn't even use the same graphics api.

Open an issue on the vkd3d-proton repo but the problem is most likely something with either Windows or Nvidia Optimus. The game is known to work fine on Linux with the exact same code.

**Comment by K0bin** [comment] 2022-10-03 16:24
Closing this because the reporter disappeared. We're dropping support for Kepler soon anyway.

**Closed by K0bin** 2022-10-03 16:24 UTC
Labels: needs apitrace, needs feedback
