### ISSUE TITLE
Return of Reckoning Hitching.

### ISSUE THREAD

**Issue by Scottx125** [doitsujin/dxvk#2568] opened 2022-03-29 14:00 UTC
Hi, I understand that this is probably not designed specifically for an old game from 2009. However the RoR community has recently been looking at your work and attempting to utilise it to solve performance issues in such an old and poorly optimised game. So far we've experimented around with your proxy and it's boosted performance. However we've been encountering 'Hitching' issues where frame times go from between 6-12ms and spike randomly up to anywhere between 200-400ms. Do you know of any way this could be minimised or reduced utilising your proxy?

Thanks.
![htiching_LI (2)](https://user-images.githubusercontent.com/31070452/160630530-6c22690d-70a5-4689-8255-cc512f12e419.jpg)

**Comment by Scottx125** [comment] 2022-03-29 21:02
Hi, I don't know if I'm doing something wrong but the API Trace download from this guide https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace#on-windows isn't working.

**Comment by Scottx125** [comment] 2022-03-29 21:15
> I need an apitrace to look into this.

Hi, I tried following the instructions to make an API Trace, but when attempting to download the prebuilt APITrace files from here https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-latest-win32.7z?branch=master&job=msvc32 it comes up with this: {"message":"Artifact not found or access denied."}

**Comment by DadSchoorse** [comment] 2022-03-29 21:21
Yeah the CI is dead, just use the release build from here https://github.com/apitrace/apitrace/releases/tag/10.0

**Comment by Scottx125** [comment] 2022-03-29 22:55
Here you go: https://1drv.ms/u/s!ApoZP4Tu_uJmnFwOHRIUgiKsO78b

**Comment by K0bin** [comment] 2022-03-29 23:53
Note to self:
Forcing the staging buffer path fixes the hitches. This might be something we can revisit after merging the unmapping PR.

**Comment by Scottx125** [comment] 2022-03-30 00:14
> Note to self: Forcing the staging buffer path fixes the hitches. This might be something we can revisit after merging the unmapping PR.

That sounds promising. Thanks for the quick reply. I'll be keeping an eye out for the new releases as well as the rest of the RoR community!

**Comment by indal-andal** [comment] 2022-03-31 17:39
Good afternoon! I'm not sure if I should open a new bug report so for now if you dont mind I will use this one. 
As OP said, some Return of Reckoning players like myself have been trying DXVK recently to try to improve the game's performance and reduce the FPS drops and stuttering.

Link here -> https://www.returnofreckoning.com/forum/viewtopic.php?f=66&t=43680&start=120

Last night downloaded the DXVK 1.10.1 but couldn't make it work, then downloaded DXVK 1.7 and got it partially working (d3d9.dll) , like someone else said, I was getting the "black-ish" launcher and the VULKAN message displayed on it.
https://i.imgur.com/KicEiqv.png
However after pressing "connect" the game shutsdown itself without any warning / message. I tried disabling NVIDIA DSR and Afterburner / RIVATuner just in case these layers were causing some conflict but didn't work. Also tried in fullscreen / windowed (with and without frame) ingame.  Tried again with DXVK 1.5 and 1.0 but didn't work neither.  
Windows 10, i5 4690k , gtx 970  (drivers 512.15) , SSD.  Visual-C-Runtimes-All-in-One-Feb-2022 was installed.

I'm uploading both logs in case it helps to find out where the issue is

`info:  Game: WAR-64.exe
info:  DXVK: v1.7
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 970:
info:    Driver: 512.15.0
info:    Vulkan: 1.3.194
info:    Memory Heap[0]: 
info:      Size: 4043 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8166 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[11]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Game: WAR-64.exe
info:  DXVK: v1.7
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 970:
info:    Driver: 512.15.0
info:    Vulkan: 1.3.194
info:    Memory Heap[0]: 
info:      Size: 4043 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8166 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[11]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Game: WAR-64.exe
info:  DXVK: v1.7
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 970:
info:    Driver: 512.15.0
info:    Vulkan: 1.3.194
info:    Memory Heap[0]: 
info:      Size: 4043 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8166 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[11]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Game: WAR-64.exe
info:  DXVK: v1.7
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 970:
info:    Driver: 512.15.0
info:    Vulkan: 1.3.194
info:    Memory Heap[0]: 
info:      Size: 4043 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8166 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[11]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : NVIDIA GeForce GTX 970
info:    Driver version   : 512.15.0
info:  Enabled device extensions:
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_conditional_rendering
info:    conditionalRendering                   : 0
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 0
info:    robustImageAccess2                     : 0
info:    nullDescriptor                         : 0
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
`

`info:  Game: RoRLauncher.exe
info:  DXVK: v1.7
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 970:
info:    Driver: 512.15.0
info:    Vulkan: 1.3.194
info:    Memory Heap[0]: 
info:      Size: 4043 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8166 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[11]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : NVIDIA GeForce GTX 970
info:    Driver version   : 512.15.0
info:  Enabled device extensions:
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_conditional_rendering
info:    conditionalRendering                   : 0
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 0
info:    robustImageAccess2                     : 0
info:    nullDescriptor                         : 0
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
warn:  DXVK: No state cache file found
warn:  DXVK: Creating new state cache file
info:  DXVK: Using 2 compiler threads
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1
info:      - Height:             1
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           true
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_LASTPIXEL
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
err:   Failed to create swap chain
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  776x500
info:    Image count:  2
info:    Exclusive FS: 0
err:   Failed to create swap chain
`
If there is anything else needed let me know.
Thank you for your time.

**Comment by K0bin** [comment] 2022-03-31 19:02
That looks like a Windows specific issue and those are usually out of our control.

**Comment by Solganis** [comment] 2022-04-01 01:36
> Note to self: Forcing the staging buffer path fixes the hitches. This might be something we can revisit after merging the unmapping PR.

Can I test those settings too?

> Note to self: Forcing the staging buffer path fixes the hitches. This might be something we can revisit after merging the unmapping PR.

Can I help to test/download this version somehow with forced staging buffer path? or where to force this setting.

**Comment by dnblank123** [comment] 2022-04-01 11:41
@indal-andal can you try `d3d9.shaderModel = 1` (for the launcher)

**Comment by xpander69** [comment] 2022-04-01 12:23
> @indal-andal can you try `d3d9.shaderModel = 1` (for the launcher)

OMG, that seems to actually work
dxvk.conf file with:
```
[RoRLauncher.exe]
d3d9.shaderModel = 1
```

**Comment by indal-andal** [comment] 2022-04-01 15:39
> @indal-andal can you try `d3d9.shaderModel = 1` (for the launcher)

It fixed the black-launcher issue for me on Windows10.

I've been continuing testing but the game still shutdown itself after "connect" , it's just an instant blackscreen then back to desktop , I'm starting to wonder if maybe olds nvidia gens like mine (gtx970)  can't make it work

Thank you for your time.

**Comment by wils0nyan** [comment] 2022-04-02 23:30
I can confirm this patch fixes the black window on the launcher thanks alot for fixing it.

**Comment by Blisto91** [comment] 2022-04-03 00:17
@indal-andal I can check on my nvidia 960 system here when i have time.

**Comment by Blisto91** [comment] 2022-04-04 11:31
I see some of you in the forum are talking about crashes after playing with dxvk for half an hour or so?
If you are running into memory issues [K0bin's PR ](https://github.com/doitsujin/dxvk/pull/2524) might help once it has been merged. If that is the issue that is.

**Comment by Blisto91** [comment] 2022-06-02 16:22
Anyone that had crash issues after running the game for a while can try K0bin's new PR https://github.com/doitsujin/dxvk/pull/2663
Link to latest version as of this moment: https://github.com/doitsujin/dxvk/actions/runs/2429353083

**Comment by K0bin** [comment] 2022-07-29 13:26
The hitching should be fixed now.

**Closed** 2022-07-29 13:26 UTC
Labels: needs apitrace, d3d9
