### ISSUE TITLE
Assassin's Creed Origins - Shadows Issue

### ISSUE THREAD

**Issue by jh0bc** [doitsujin/dxvk#1710] opened 2020-08-06 03:43 UTC
I started using DXVK with Origins since this amazing tool are making wonders with some games on Windows

I'm getting about 10 to 20 fps more in comparison when the game is running on DX11 and in overall is much more stable and less demanding

But an issue is happening when I use DXVK the shadows are flashing/flickering when I move the camera when I'm close to a wall (mainly visible inside of some building)

Used the x64 dlls from latest 1.7 release and from dev build (07/20/2020) but the issue persisted

Video of the issue: https://drive.google.com/file/d/11O4uuezaSsefVctzjnKJWEorWNZhsLzs/view?usp=sharing

Running the game on DX11 this doesn't happen

Don't know why but I managed to use DXVK with the game only with uPlay overlay enabled and RTSS disabled.

### Software information

- Assassin's Creed Origins 1.5.1 (Legit uPlay)
- Max Graphics Settings
- Windows 10 (2004)

### System information

- GPU: GTX 1070
- Driver: 451.85 Hotfix
- DXVK version: 1.7 and Dev (07/20/2020)

### Log files

- [d3d9.log](https://github.com/doitsujin/dxvk/files/5032376/ACOrigins_d3d9.log)

- [d3d11.log](https://github.com/doitsujin/dxvk/files/5032377/ACOrigins_d3d11.log)

- [dxgi.log](https://github.com/doitsujin/dxvk/files/5032379/ACOrigins_dxgi.log)

**Comment by K0bin** [comment] 2020-08-06 11:15
Can you try a handful of older DXVK versions to see if this is a regression?

The problem is that without an apitrace this is next to impossible to debug. As far as I remember AC Origins also didn't allow Renderdoc either.

**Comment by doitsujin** [comment] 2020-08-06 12:12
Known issue, probably driver bug.

**Comment by jh0bc** [comment] 2020-08-07 02:47
> Can you try a handful of older DXVK versions to see if this is a regression?
> 
> The problem is that without an apitrace this is next to impossible to debug. As far as I remember AC Origins also didn't allow Renderdoc either.

Tested from version 1.6.1 to 0.7.2 but the bug persisted in all of them


> Known issue, possibly driver bug, can't reproduce on my AMD system.
> 
> So yeah, can't really do much.

Sad about it... really appears to be a driver bug because I tested all versions like I said before and the issue persisted in all them

**Comment by jh0bc** [comment] 2020-08-07 02:58
> Can you try a handful of older DXVK versions to see if this is a regression?
> 
> The problem is that without an apitrace this is next to impossible to debug. As far as I remember AC Origins also didn't allow Renderdoc either.

Tested from version 1.6.1 to 0.7.2 but the shadow flickering persisted in all of them

> Known issue, possibly driver bug, can't reproduce on my AMD system.
> 
> So yeah, can't really do much.

Sad about it... really appears to be a driver bug because I tested all versions like I said before and the issue persisted in all them

**Comment by Ryusennin** [comment] 2020-08-18 12:30
I haven't met any shadow flickering issue either (indoors or outdoors) on my Vega 56.

PS: thanks Doitsujin for this wonderful layer, which does wonders in Origins and Odyssey on Windows (especially Origins, in which micro-stuttering has completely disappeared).

**Comment by Blisto91** [comment] 2022-08-18 19:07
@jh0bc friendly ping. Are you able to verify this has been fixed in newer drivers and or dxvk?

**Closed** 2022-08-18 22:32 UTC
Labels: can't reproduce
