### ISSUE TITLE
Astroneer Now fails to launch

### ISSUE THREAD

**Issue by zmrodriguez91** [doitsujin/dxvk#468] opened 2018-06-30 23:11 UTC
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Launching the game Astroneer with default settings results in an error dialog: "DX11 feature level 10.0 is required to run the engine".

### System information
- GPU: Nvidia GTX 1070
- Driver: Linux driver, version 396.18
Where did you get the nvidia driver recommended for dxvk v0.60 (396.24.02)?  
- Wine version: 3.10, 3.11, 3.11-staging
- DXVK version: v0.61 (Previous working version: DXVK v0.52 )

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log: 
[Astro-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2152230/Astro-Win64-Shipping_d3d11.log)
[Astro-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/2152231/Astro-Win64-Shipping_dxgi.log)

**Comment by varris1** [comment] 2018-06-30 23:13
You can get 396.24.02 here: https://developer.nvidia.com/vulkan-driver

**Comment by doitsujin** [comment] 2018-06-30 23:19
Duplicate of #435. Please read the driver support page on the Wiki.

**Closed by doitsujin** 2018-06-30 23:19 UTC
