### ISSUE TITLE
Far Cry 3 game with rendering error in directx 11

### ISSUE THREAD

**Issue by MarlonCRPeluci** [doitsujin/dxvk#3576] opened 2023-07-23 15:00 UTC
Far Cry 3 game with rendering error in directx 11

Windows 10 x64

### Software information
Far Cry 3 game with rendering error in directx 11, error occurs ONLY IN CACHOEIRAS...

MSI Afterburner does not work in this version of directx, the game does not open

Settings all on "Ultra" with maximum resolution "1920 X 1080" (My monitor goes up to this one)

OBS: during the recording the error did not occur, however when I add the files "d3d11.dll" and "dxgi.dll" the error occurs, I cannot remove a print of the screen because the image comes out all black.

### System information
- GPU: Geforce GTX 1070TI
- Driver: Version 536.67
- DXVK version: 2.2
 
### Apitrace file(s)
https://drive.google.com/file/d/1YRjggvtA5OMZ4MSyomvx0RGBKJCme2cq/view?usp=sharing
![Sem título](https://github.com/doitsujin/dxvk/assets/140324799/b363a87e-fea1-4c77-bab2-8f9344c94f1a)

**Comment by K0bin** [comment] 2023-07-23 15:11
Duplicate of #2863

**Closed by K0bin** 2023-07-23 15:11 UTC
Labels: windows
