### ISSUE TITLE
Feature Request DXVK_HUD Location Placement

### ISSUE THREAD

**Issue by ryanmusante** [doitsujin/dxvk#526] opened 2018-08-02 07:54 UTC
Request DXVK_HUD configuration options to change location of HUD on screen. It defaults to top-left hand side. Request option to place specific coordinates of location OR top-left, top-right, bottom-left, bottom-right, center-left, center-right, center-top, center-bottom.

### System information
- GPU: 980M
- Driver: Nvidia 396.45
- Wine version: 3.13
- DXVK version: .63

**Comment by K0bin** [comment] 2018-08-02 08:14
Duplicate of #488

**Comment by doitsujin** [comment] 2018-08-02 08:16
See https://github.com/doitsujin/dxvk/issues/488#issuecomment-403622075 for why I won't implement this.

**Closed by doitsujin** 2018-08-02 08:16 UTC
Labels: duplicate, wontfix

**Comment by ryanmusante** [comment] 2018-08-02 08:35
I apologize. I didn't see the previous ticket until now.
