### ISSUE TITLE
[d3d9] Beyond Good & Evil

### ISSUE THREAD

**Issue by Riesi** [doitsujin/dxvk#1545] opened 2020-04-02 19:53 UTC
Only remaining issue is the Settings Application crashing when running through dxvk, galliumNine, or dgVoodoo.
Not sure if this is really a dxvk issue or a wine interaction issue though

~~With dxvk the game stays in a really tiny window with 320x200. This does not happen with wined3d, which renders the game at full 1080p. Apitraces with dxvk and wined3d attached.~~
^This has been fixed

### Software information
Beyond Good & Evil CD Version

### System information
- GPU: GTX970
- Driver: 440.66.07
- Wine version: 5.5
- DXVK version: 904d3e6c9014bff7aa0843630b009c51879a1d06

### Apitrace file(s)
[BGE_dxvk.trace.zip](https://github.com/doitsujin/dxvk/files/4423266/BGE_dxvk.trace.zip)

[BGE_wined3d.trace.tar.gz](https://github.com/doitsujin/dxvk/files/4423264/BGE_wined3d.trace.tar.gz)

### Log files
- d3d9.log: [BGE_d3d9.log](https://github.com/doitsujin/dxvk/files/4423278/BGE_d3d9.log)

**Comment by WinterSnowfall** [comment] 2020-04-03 21:26
@Riesi Does the BGE SettingsApplication work for your with DXVK? For me it crashes, though it seems to work just fine with WineD3D. I think the problems are related.

In my case the game does not use the resolution I set, though it seems to switch to something close to it. For example, when configured (via the settings app using WineD3D) to run at 1280x1024, it runs at 1280x1024 in WineD3D, but at 1280x800 in DXVK.

Here's a trace of the crash captured while trying to launch the SettingsApplication with DXVK (for some reason it doesn't capture a trace with WineD3D): [SettingsApplication.trace](https://drive.google.com/open?id=1SEtKfyuGx3V6aWUMQRyh9sRKW5wQH8XA)

**Comment by Blisto91** [comment] 2022-03-19 20:31
With the steam version i have not been able to reproduce this with my 960 with 470.103 driver.
Tried with both dxvk 1.6 & 1.6.1 through proton.

I couldn't reproduce a settings app crash either. Tho for the current steam version you have to edit a registry entry in the prefix because either the games install script or proton does something wrong. Else it won't launch cuz it says the game isn't installed properly.

**Comment by Riesi** [comment] 2022-03-21 09:57
To update things:
1) The SettingsApplication still crashes with dxvk and works fine with wined3d.
2) The game seems to pick the resolution correct now even with dxvk. Not sure if that was fixed somehow or if my old prefix had broken registry entries.
3) There is a regression from the following commit that reproduces with the attached wined3d trace of the report.
```
c12cd1952cf8593f3f6064f7b785c7fc7bcf1c74 is the first bad commit
commit c12cd1952cf8593f3f6064f7b785c7fc7bcf1c74
Author: Robin Kertels <robin.kertels@gmail.com>
Date:   Wed Feb 2 19:39:46 2022 +0100

    [d3d9] Handle different mip chain lengths in UpdateTexture
```

**Comment by Riesi** [comment] 2022-03-21 13:19
https://github.com/doitsujin/dxvk/pull/2553
fixes the regression

the SettingsApp crash also happens with dgVoodoo and galliumNine
so its either something all 3 implementations are doing wrong or maybe some interaction between d3d9 and another api that only works with wined3d

**Comment by Riesi** [comment] 2022-03-21 15:27
Maybe Proton is disabling DXVK for the Settings Application?
Its clearly not working with my non steam version running in wine.

**Comment by Blisto91** [comment] 2022-03-21 19:17
Oh derp ye you are running wine not proton. Excuse my slow head.
Will keep that in mind when i test it.

**Comment by Blisto91** [comment] 2022-04-01 22:41
Just checked on my amd system through wine (still steam version) and still no crash. Will try the same when with nvidia when i have time.

**Comment by Blisto91** [comment] 2022-04-16 15:16
@Riesi Just tried on my Nvidia 960 with 510 driver on wine and i still can't reproduce a crash with dxvk.

Can you upload your `SettingsApplication.exe` ? Maybe steam uses a different version than the cd one.

**Comment by Riesi** [comment] 2022-04-16 15:20
Uploading copyrighted contend is a big no go.
I can at best share a hash at some point.

**Comment by Blisto91** [comment] 2022-04-16 15:21
Hash will have to do then.

**Comment by Riesi** [comment] 2022-04-19 08:25
these are all SHA256
```
4520a3fac8be76854acfae7f98a25bf3876d4082ea48256064eeed0e1e630630  CheckApplication.exe
ed02902cb2c57e3184bba6353ab07b1b4c6ef85c287c5a952a68fe750f750298  SettingsApplication.exe
fc8bd732acfdadc7c72070c85b9f8bb0811ead2cbb5dff842e993d96feb1993b  BGE.exe
```

**Comment by Blisto91** [comment] 2022-04-19 15:30
```
aaccb80946ccb8daa6e614e4f00fb0e04c30cb2d0b860742528741555e2eb4a6  CheckApplication.exe
b6d8fb7b7a65de0a4060fbf7b2051ee6d307f005f02e985d4eef355782989d1e  SettingsApplication.exe
70ae232d58bafe5cbf5c27712538af91e8b13a98104ae1bf6aea6dcf3506f5db BGE.exe
```
It would seem they are not the same.
If this is anything to go by maybe that is why i can't reproduce the issue.

**Comment by WinterSnowfall** [comment] 2022-04-19 15:52
FYI, the GOG version of the game has:

```
8943ac6044d07b1df0e9ca1a072be69497b6c7bf0c2e46c1960ba55300c4057b  CheckApplication.exe
a7d977dc59ccaa09afdee7fadb09a072156f01e7619b7894d5447be35d349675  SettingsApplication.exe
fc8bd732acfdadc7c72070c85b9f8bb0811ead2cbb5dff842e993d96feb1993b  BGE.exe
```

... and it also crashes with dxvk, while working fine with WineD3D. I can confirm the resolution problem seems to have gone away though, it's now using the proper resolution - namely the one set via the settings app, using WineD3D.

**Comment by WinterSnowfall** [comment] 2022-04-22 20:56
Hate to be the bearer of bad news, but I was planning to start a new playthrough and noticed the sun and bloom effect (planetary glow) are again missing with dxvk-1.10.1... See [here](https://github.com/Joshua-Ashton/d9vk/issues/195) for more details on what I mean by that. Can someone confirm this on AMD, just to rule out who-knows-what Nvidia jank?

**Comment by WinterSnowfall** [comment] 2022-04-24 20:37
.. *sigh*... guess a lot of people play this game on a regular basis, since the sun broke somewhere between dxvk 1.5.1 and 1.5.2, lol. Should I... do a bisect? What that even help at this point?

**Comment by K0bin** [comment] 2022-04-24 21:12
A bisect would be useful.

**Comment by WinterSnowfall** [comment] 2022-04-25 10:53
> A bisect would be useful.

6fa28bf9371ee40eb350d8e296adfae77c8236de is the first bad commit
commit 6fa28bf9371ee40eb350d8e296adfae77c8236de
Author: Joshua Ashton <joshua@froggi.es>
Date:   Fri Jan 24 05:32:01 2020 +0000

    [d3d9] Don't block on GetRenderTargetData
    
    Fixes perf in #1363

**Comment by WinterSnowfall** [comment] 2022-06-12 07:47
@K0bin I've been looking deeper into this issue (and at the affected bits of code, but as a graphics API noob), trying to figure out what is going on here. Looks like `d3d9.allowDoNotWait = False` brings back the sun and "god rays". I've been playing the game for 2 hours and noticed no ill effects so far with this workaround. Should I submit a PR, or is this something which should be fixed some other (better) way? I mean, it used to work without any workarounds until the above commit... and this config option sure has been getting more use lately :sweat_smile:.

**Comment by K0bin** [comment] 2022-06-12 09:26
Sounds good, I'm looking forward to your PR. :)

**Comment by WinterSnowfall** [comment] 2022-08-10 12:23
@K0bin There's one more issue with the game, but I'm not sure if it warrants a separate bug report. 

I'm certain it has something to do with desktop compositing because when I disable it the randomly occuring [weird geometry clipping](https://drive.google.com/file/d/1iSMdbv9KvXAH_1mi9xsGSJAKWpUfzVK5/view?usp=sharing) goes away (recording is done with compositing enabled, when it's at its worst with dxvk). It also goes away with an alt+tab when compositing is enabled, but always starts acting up again soon afterwards... and I haven't been able to capture it in a trace, which means rasterization is doing its job just fine, I guess. 

Disabling compositing mostly fixes things. I briefly see some clipping when an area transition loads or very rarely in other places, but it's gone after a few frames and doesn't consistently resurface. It's rather rare, minimal and hard to reproduce in this case.

Any idea what's going on here and why WineD3D doesn't seem to care about compositing at all? I'm not even getting the above described minimal clipping with WineD3D, even with compositing on (which causes clipping havoc in dxvk, as per the recording).

**Comment by WinterSnowfall** [comment] 2022-08-10 19:16
> Can you make an apitrace of the area please? (Regardless of whether the issue shows up with that or not.)

I'm glad [I never deleted it](https://drive.google.com/file/d/1PbPA1HPFMKmYiVZO7n1l9D3HzvMkCFru/view?usp=sharing). The outside area, usually around the lighthouse, triggers the problem with compositing enabled.

**Comment by WinterSnowfall** [comment] 2023-03-13 10:55
Regarding the crash in the SettingsApplication, it seems to boil down to the `D3DFMT_X1R5G5B5` format not returning any display modes. If it does, that will cause a crash.

With WineD3D:
`IDirect3D9::GetAdapterModeCount(this = 0x745940, Adapter = D3DADAPTER_DEFAULT, Format = D3DFMT_X1R5G5B5) = 0`

With DXVK:
`IDirect3D9::GetAdapterModeCount(this = 0x15369d0, Adapter = D3DADAPTER_DEFAULT, Format = D3DFMT_X1R5G5B5) = 40`

Ensuring no modes get cached with this format, for example by altering the behavior of D3D9Adapter::CacheModes, gets the SettingsApplication going with dxvk. Not saying that would be a proper way to handle things, but it's how I makeshift tested the "fix".

**Comment by Joshua-Ashton** [comment] 2023-03-14 06:23
Hmm, I guess we should find out what native drivers are returning here for D3DFMT_X1R5G5B5 and D3DFMT_A1R5G5B5, and see if we should app profile this or just remove it.

**Comment by Riesi** [comment] 2023-03-14 09:57
Windows trace from my nvidia gt540m laptop
[SettingsApplication.trace.zip](https://github.com/doitsujin/dxvk/files/10966955/SettingsApplication.trace.zip)

**Closed** 2023-03-14 13:17 UTC
Labels: needs apitrace, d3d9

**Comment by mrdeathjr28** [comment] 2023-03-14 17:14
Confirmed here too works in my uhd 630 but in my case use d3d9 as native and dxgi as internal because without this show directx9 dont installed error (occur in various games) however directx installation works ok

![uhd630a](https://user-images.githubusercontent.com/6601480/225085100-e4dd6244-14c3-4cd4-9d4e-76290d1d1025.png)

**Comment by Blisto91** [comment] 2023-03-14 17:34
Many thanks Winter!
