### ISSUE TITLE
Texture glitches and terrain explosion on Fallout New Vegas

### ISSUE THREAD

**Issue by GaylordStarfucker** [doitsujin/dxvk#3054] opened 2022-11-12 03:57 UTC
Please see screenshots.

### Software information
Fallout New Vegas
d3d9.floatEmulation = Strict
d3d9.evictManagedOnUnlock = True

### System information
- GPU: RTX 3080
- Driver: 526.86.0
- Win 10
- DXVK version: 2.0

### Apitrace file(s)
- this is over 5gb. i can upload if necessary 

### Log files

![20221021 02 45 25](https://user-images.githubusercontent.com/118027424/201454465-1db61b59-2295-4923-aa86-a65a47d9e241.jpg)

![20221111 23 46 19](https://user-images.githubusercontent.com/118027424/201454454-b7a267f6-9a48-4013-8cb9-fc27d2ee9d74.jpg)

[FalloutNV_d3d9.log](https://github.com/doitsujin/dxvk/files/9993960/FalloutNV_d3d9.log)

**Comment by Blisto91** [comment] 2022-11-12 07:27
> this is over 5gb. i can upload if necessary

Yes please

**Comment by GaylordStarfucker** [comment] 2022-11-12 11:47
i couldn't get the terrain explosion bug to happen and texture glitches are different with the api trace and appear immediately on game launch. like for example dollar sky : ))

api trace: https://sendgb.com/f4AuFDKxqoB

![20221112 12 15 18](https://user-images.githubusercontent.com/118027424/201472059-e7c06e9c-afcc-4301-8275-0491e08cefb9.jpg)
![20221112 04 40 21](https://user-images.githubusercontent.com/118027424/201472060-465963a8-00a3-48d4-8198-a0ff6da157d6.jpg)

**Comment by K0bin** [comment] 2022-11-12 12:15
If that happened with apitrace and you're on Windows, it's probably not a DXVK issue.

When you use apitrace on Windows, DXVK isn't used.

**Comment by K0bin** [comment] 2022-11-12 12:33
Can you upload your save game?

**Comment by Blisto91** [comment] 2022-11-12 13:52
@GaylordStarfucker could you try setting the Nvidia settings app and or Geforce Experience to default values. To make sure nothing is interfering

**Comment by GaylordStarfucker** [comment] 2022-11-12 14:14
The issue in the first post happens only with dxvk. I am not the only person to experience this issue. I have asked others to contribute to this post. I tried disabling the experience overlay completely and the issue from the first post still happens.

**Comment by K0bin** [comment] 2022-11-12 14:42
Fallout NV works perfectly fine for me on a RTX 3090 with DXVK.

**Comment by Blisto91** [comment] 2022-11-12 15:12
Using any mods?

**Comment by StarComrade** [comment] 2022-11-12 19:00
Hi, I'm one of the other users experiencing this issue. It happens to me after several hours of playing the game, gets worse over time, at one point I bluescreened despite clean Nvidia drivers, showing an error to dxgmms2.sys .

Using RTX 3080, moderately modded game, Windows 10. This happened to me on DXVK v1.10.3 as well. 

![image](https://user-images.githubusercontent.com/118075657/201490332-1ca5db4b-46df-4d7b-a92d-eca48824c99d.png)

![image](https://user-images.githubusercontent.com/118075657/201490339-3c9d15f7-4e84-433d-bd71-99f0ddf6c375.png)

**Comment by Blisto91** [comment] 2022-11-12 19:03
Can post the mods and settings used?
The apitrace posted earlier uses an insane amount of vram (10GB) so it must be some heavy stuff.

**Comment by StarComrade** [comment] 2022-11-12 19:10
Here is my modlist: https://pastebin.com/wxSuJf5V

As for settings, it's pretty much all default. I'm running New Vegas Reloaded 4.0 alongside this as well. It definitely appears to be a memory-related issue.

**Comment by Blisto91** [comment] 2022-11-12 19:19
Where do you download New Vegas Reloaded. It looks like it has been pulled from Nexus mod?

**Comment by StarComrade** [comment] 2022-11-12 19:20
Download it off their Discord. It's still a WIP beta.

**Comment by K0bin** [comment] 2022-11-12 20:05
@StarComrade Please make an apitrace of that and it doesn't even matter whether the issue shows up while you're making the apitrace.

**Comment by StarComrade** [comment] 2022-11-12 21:07
Apitrace here: https://sendgb.com/BQSsIDHJwR4

Ran my game for about 5-ish minutes, the issue for me mainly appeared after about 4 hours or less of playtime initially, hope this helps.

**Comment by StarComrade** [comment] 2022-11-12 22:35
New Apitrace here, with environment variable set: https://sendgb.com/npLwkEb0gAF

**Comment by K0bin** [comment] 2022-11-12 23:06
Thanks but unfortunately, that one runs just fine too.

![image](https://user-images.githubusercontent.com/1131720/201498013-a703a5bf-b966-4237-9c5b-63185ffa7443.png)

This is probably a driver bug.

**Comment by GaylordStarfucker** [comment] 2022-11-13 13:56
For documentation purposes, there were several things suggested. Using one of these in dxvk.conf:
dxvk.enableGraphicsPipelineLibrary = False
d3d9.customVendorId = 1002
d3d9.allowDirectBufferMapping = False

For me only d3d9.allowDirectBufferMapping = False seemed to almost completely alleviate the issue.
Let's hope in future driver release this will be fixed.

**Comment by Blisto91** [comment] 2023-03-10 12:14
@GaylordStarfucker Hi again. Have you tried with recent DXVK and driver versions to see if it is still an issue?

**Comment by Blisto91** [comment] 2023-05-06 15:02
@GaylordStarfucker Friendly ping

**Comment by K0bin** [comment] 2023-05-06 18:23
I'm closing this because I could never reproduce any of this. I strongly suspect this is caused one of the following:

- driver bug
- unstable OC
- dying hardware

**Closed by K0bin** 2023-05-06 18:23 UTC
Labels: nvidia, d3d9, can't reproduce, windows
