### ISSUE TITLE
Laggy, jittery X11 window geometry with World of Warcraft VSync on

### ISSUE THREAD

**Issue by spell** [doitsujin/dxvk#1145] opened 2019-07-26 16:17 UTC
Hey, first of all, DXVK is an amazing project, thanks for all your hard work.

Now, on to the problem. Running World of Warcraft with VSync turned on (in-game) causes window geometry related actions in X11 to become incredibly laggy to the point of being unresponsive for at least half a second. Specifically the creation, resizing, moving, iconifying and closing of windows causes this lag. 

This makes doing anything on the OS very unpleasant, whether that's searching in Firefox (the dropdown with suggestions lags out), but also makes gaming with notifications on very problematic.

There is a work around, however. Turning VSync off and instead limiting frame rate to 60 in the advanced options completely eliminates the issue; making the desktop as responsive as ever, though dragging/moving windows does still appear to be slightly jittery (though barely.) Turning VSync off and leaving the framerate unlimited causes the exact same issue as turning VSync on.

My guess is that whatever VSync implementation DXVK is using, uses a mailbox algorithm, where it keeps rendering at full speed and discards unneeded frames? Either way, this has proven to be a massive issue.

### Software information
World of Warcraft, installed through Lutris.

### System information
- GPU: MSI Gaming X NVIDIA GeForce GTX 1080 Ti
- Driver: 430.26 (happens on 418.74, 390.x, etc too)
- Wine version: 4.12, 4.9, doesn't matter
- DXVK version: 1.31, but occurs on older versions too.
- OS: Debian 9, Debian 10, Manjaro, Arch, Fedora, OpenSUSE - it doesn't seem to matter.

### Log files
- d3d11.log:
[Wow_d3d11.log](https://github.com/doitsujin/dxvk/files/3436573/Wow_d3d11.log)

- dxgi.log: 
[Wow_dxgi.log](https://github.com/doitsujin/dxvk/files/3436574/Wow_dxgi.log)

**Comment by Joshua-Ashton** [comment] 2019-07-26 16:21
What DE/WM

**Comment by spell** [comment] 2019-07-26 16:22
This occurs on any DE/WM that I've tried:
XFCE (with and without compositor), KDE+Kwin (with and without compositor), GNOME3

**Comment by aufkrawall** [comment] 2019-07-26 18:12
Vsync in DXVK fifo and thus saves resources (if it wasn't, fps could exceed refreshrate).
I suppose it's Nvidia's terrible Xorg window management performance that's the issue for you, it can't be fixed.
Vulkan vsync is broken too with Nvidia (inside their driver) on Linux, it falls back to some kind of fifo-relaxed instead of normal fifo.

**Comment by doitsujin** [comment] 2019-07-26 20:10
> Either way, this has proven to be a massive issue.

That's unfortunate, but I'm not really sure how this could be fixed inside DXVK (since Vsync is literally just enabling the `FIFO` present mode for the swap chain). It doesn't have **any** control over how exactly presentation is implemented and how that might affect the environment.

**Comment by spell** [comment] 2019-07-27 23:19
Like I said, the result on my desktop experience is exactly the same whether I have FPS uncapped or using VSync; something weird is going on. I am going to try some other games and see if I can repeat the behaviour.

Otherwise, perhaps its possible to fake the VSync and cap to refresh rate instead? Just an idea, I have no idea how feasible that is.

I plan to order a 5700 RX once driver support matures on Linux, but until then I gotta stomach the weather. :)

**Comment by doitsujin** [comment] 2019-07-28 00:26
> Otherwise, perhaps its possible to fake the VSync and cap to refresh rate instead?

The main reason people use Vsync is to avoid tearing, not to have an FPS cap. You can achieve FPS caps with libstrangle (and many games offer an option on their own anyway).

I don't think there's any good reason to implement weird hacks like this in DXVK just because some drivers can't handle a game and a desktop at the same time.

**Comment by turol** [comment] 2019-08-06 11:52
This is an nvidia bug with PRIME sync, it happens even with Linux native Vulkan apps. Nvidia people apparently can't reproduce it which is strange since it seems to happen to many people. Go bug them at [NVIDIA developer forums thread](https://devtalk.nvidia.com/default/topic/957814/linux/prime-and-prime-synchronization/)

**Comment by SveSop** [comment] 2019-08-28 13:05
@spell 

> Otherwise, perhaps its possible to fake the VSync and cap to refresh rate instead? Just an idea, I have no idea how feasible that is.
> 

Did you solve this problem? 

If not, what happens if you run WoW with "fullscreen windowed" and/or limit FPS using WoW's own fps limit settings?

**Closed** 2019-12-11 21:10 UTC
