### ISSUE TITLE
The Surge The Good the Bad and the Augmented - Cannot map a depth-stencil texture error

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#654] opened 2018-09-22 14:09 UTC
The game The Surge The Good the Bad and the Augmented has problems with characters missing. The log spams the "err:   D3D11: Cannot map a depth-stencil texture" error.

![2](https://user-images.githubusercontent.com/38666396/45918081-347a6180-be8a-11e8-932b-4d3d6de5d177.png)

Unfortunately the game crashes after the second logo with apitrace thus it's incomplete.

### Software information
The Surge The Good the Bad and the Augmented

### System information
- GPU: GTX 1080 Ti
- Driver: 369.54.0/369.54.6
- Wine version: 3.16
- DXVK version: 0.72/master

### Apitrace file(s)
- Put a link here
https://my.pcloud.com/publink/show?code=XZfU5e7ZqEjmiuyzkQbfXbpp2k6KhYGCr35X
### Log files
- d3d11.log 369.54.0:
https://pastebin.com/mXcnUwhg
- d3d11.log 369.54.6:
https://pastebin.com/80WdwWmc
- dxgi.log 369.54.0: 
https://pastebin.com/UcsKZF6N
- dxgi.log 369.54.6: 
https://pastebin.com/GGRphKpx

**Comment by K0bin** [comment] 2018-09-22 14:11
Same issue as in #285

**Comment by doitsujin** [comment] 2018-09-22 15:32
Closing this in favour of the original bug report.

Did you record the apitrace on Windows or on Linux? Having one from Windows would be nice in order to actually confirm what the issue is, the Linux ones are obviously all broken because they have the missing characters baked in.

**Closed by doitsujin** 2018-09-22 15:32 UTC
Labels: duplicate

**Comment by mozo78** [comment] 2018-09-22 15:58
It's Linux's one. I don't use Windows, sorry.
