### ISSUE TITLE
Heroes of the Storm game crashes when match start - VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by HenriqueAJNB** [doitsujin/dxvk#1758] opened 2020-09-07 13:50 UTC
When I start a match in Heroes of the Storm game, it crashes. 

Above the final lines from Lutris log.

```
Game is considered started.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
esync: up and running.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Initial process has exited.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
INTEL-MESA: error: ../src/intel/vulkan/anv_device.c:3179: GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)
```

### Software information
Heroes of the Storm using lowest graphics configuration

### System information
- GPU: Nvidia GeForce 5500
- Driver:
![driver](https://user-images.githubusercontent.com/54143210/92394022-2c5b7100-f0f7-11ea-92f2-5f18b6c0414d.png)

- Wine version: wine-5.12 (Staging)
- DXVK version: how can I get it? 

### Log files
Can someone help me to reach the log files?

### Error
![Screenshot from 2020-09-07 08-43-49](https://user-images.githubusercontent.com/54143210/92394234-84927300-f0f7-11ea-8c7f-0be7876c98cf.png)

**Comment by K0bin** [comment] 2020-09-07 14:33
The only Nvidia Geforce 5500 I could find was released in 2003 and therefor doesn't support Vulkan.

Your logs show that you're using an Intel HD GPU instead.
`INTEL-MESA: error: ../src/intel/vulkan/anv_device.c:3179: GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)`

Can you make sure those are up to date? Ubuntu (especially if it's an older release or even the LTS flavour of it) has the habit of shipping really dated graphics drivers that can cause problems.

**Comment by iWeaker4you** [comment] 2020-09-07 15:12
@K0bin  You are wrong, it refers to the Intel HD 5500

@HenriqueAJNB  But your problem is because you don't have NVIDIA graphics as your main GPU.

**Comment by HenriqueAJNB** [comment] 2020-09-07 15:51
@iWeaker4you, how could I set it as my main GPU?

**Comment by HenriqueAJNB** [comment] 2020-09-07 15:57
I have found this 3 commands and I'm still confused about my GPU's model...

```
@ubuntu:~$ sudo ubuntu-drivers devices
== /sys/devices/pci0000:00/0000:00:1c.4/0000:09:00.0 ==
modalias : pci:v000010DEd00001140sv0000103Csd00002337bc03sc02i00
vendor   : NVIDIA Corporation
model    : GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (GeForce 820M)
driver   : nvidia-driver-450 - third-party free recommended
driver   : xserver-xorg-video-nouveau - distro free builtin
```

```
@ubuntu:~$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 5500 (BDW GT2) (0x1616)
    Version: 20.3.0
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.3.0-devel (git-3d5bed0 2020-09-07 focal-oibaf-ppa)
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.0-devel (git-3d5bed0 2020-09-07 focal-oibaf-ppa)
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.0-devel (git-3d5bed0 2020-09-07 focal-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

```
@ubuntu:~$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
```

**Comment by HenriqueAJNB** [comment] 2020-09-07 16:02
Maybe this image helps.

![nvidia](https://user-images.githubusercontent.com/54143210/92404582-50747d80-f10a-11ea-9346-bf05a856dbd3.png)

**Comment by DadSchoorse** [comment] 2020-09-07 17:00
The nvidia card (what ever it is, some fermi card) is not supported by the latest nvidia driver anymore.

**Comment by Leopard1907** [comment] 2020-09-07 17:02
First ; without disabling secure boot on your machine Nv driver is not likely to load ; therefore switching to NV only performance mode won't actually work. 

Second; copy paste output of this command here.

`inxi -SMGxx`

**Comment by DadSchoorse** [comment] 2020-09-07 17:03
@Leopard1907 the driver will not load because the card is too old.

**Comment by HenriqueAJNB** [comment] 2020-09-07 17:10
> `inxi -SMGxx`
 
This is the output result: 

```
@ubuntu:~$ inxi -SMGxx
System:
  Host: ubuntu Kernel: 5.4.0-45-generic x86_64 bits: 64 compiler: gcc 
  v: 9.3.0 Desktop: Gnome 3.36.4 wm: gnome-shell dm: GDM3 
  Distro: Ubuntu 20.04.1 LTS (Focal Fossa) 
Machine:
  Type: Laptop System: Hewlett-Packard product: HP 15 Notebook PC 
  v: 0974120000405F00000620180 serial: <superuser/root required> Chassis: 
  type: 10 serial: <superuser/root required> 
  Mobo: Hewlett-Packard model: 2337 v: 05.31 
  serial: <superuser/root required> UEFI: Insyde v: F.46 date: 11/22/2018 
Graphics:
  Device-1: Intel HD Graphics 5500 vendor: Hewlett-Packard driver: i915 
  v: kernel bus ID: 00:02.0 chip ID: 8086:1616 
  Device-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT 
  620M/625M/630M/720M] 
  vendor: Hewlett-Packard driver: N/A bus ID: 09:00.0 chip ID: 10de:1140 
  Display: x11 server: X.Org 1.20.8 driver: N/A compositor: gnome-shell 
  resolution: 1366x768~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2) 
  v: 4.6 Mesa 20.3.0-devel (git-3d5bed0 2020-09-07 focal-oibaf-ppa) 
  direct render: Yes
```

**Comment by K0bin** [comment] 2020-09-07 17:14
Your Nvidia GPU does not support Vulkan so DXVK will never work on that.

The Intel GPU should work but doesn't for some reason. Hangs are usually very hard to fix, especially with Blizzard games that usually dont work with dev tools.

**Comment by Leopard1907** [comment] 2020-09-07 17:15
As you can see from that output you are on Intel HD despite you choose NV only performance mode. OpenGL renderer part would have print NV otherwise.

Also @DadSchoorse is right. 450 driver doesn't support your NV gpu.

https://www.nvidia.com/Download/driverResults.aspx/163238/en-us

You should be using 390 driver. 

To sum it up:

1-) Your NV gpu doesn't support Vulkan.
2-) You are on Intel HD.

**Comment by HenriqueAJNB** [comment] 2020-09-07 17:16
> Can you make sure those are up to date? Ubuntu (especially if it's an older release or even the LTS flavour of it) has the habit of shipping really dated graphics drivers that can cause problems.

I ran `sudo apt update` and `sudo apt upgrade` and its all up to date. 
> You can generate DXVK logs by setting the environment variable `DXVK_LOG_LEVEL` to for example `WARN` (like its described in the README). Lutris can do that in the properties. After that DXVK generates the log files in the same folder as the exe file of your game.

Does this log help solving this issue?

**Comment by K0bin** [comment] 2020-09-07 17:17
> Does this log help solving this issue?

I guess it wouldn't hurt but it's usually useless.

**Comment by Leopard1907** [comment] 2020-09-07 17:20
He is on Oibaf Ppa already , which means he is using Mesa git stuff.

If you want to be sure about if Mesa version is really related to your problem ( maybe there are regressions?) , you can try with Kisak Mesa fresh ppa but i wouldn't have high hopes.

**Comment by lavilao** [comment] 2021-11-24 15:21
try adding this to lutris enviroment tab ANV_QUEUE_THREAD_DISABLE=1, this fixed a lot of device lost errors on my intel laptop

**Comment by Blisto91** [comment] 2022-05-31 19:52
Sorry to necro. Was this issue solved with later driver versions or dxvk?

**Comment by Blisto91** [comment] 2022-07-06 06:26
@HenriqueAJNB Friendly ping

**Closed** 2022-09-22 17:35 UTC
Labels: intel anv, needs feedback
