### ISSUE TITLE
GTA IV mirror bug 

### ISSUE THREAD

**Issue by MiesThies** [doitsujin/dxvk#2901] opened 2022-09-09 18:02 UTC
As seen in the screenshots, the mirrors look off, when DXVK is installed. 

Actually, when I wanted to create the trace file, I couldn't reproduce the problem. Before I only had d3d9.dll, dxgi.dll, and dxvk.conf in the game directory, then I put in d3d9.dll, d3d11.dll, dxgi.dll and dxgitrace.dll from the folder: apitrace-msvc/x86/lib/wrappers

This is weird. So if I just keep these files in the game directory, I guess my problem is "solved", but again, with only the aforementioned files from \dxvk-1.10.3.tar\dxvk-1.10.3\x32, the mirrors looked off. I hope you can work with what I provided.

### Software information
GTA IV, downgraded to patch 1.0.8.0, Max ingame settings

### System information
- GPU: RTX 2080
- Driver: 516.94
- Wine version: 
- DXVK version: Version 1.10.3

### Apitrace file(s)
(https://drive.google.com/file/d/1LfolKr0Izyb1WXXDF2bk7QLlMfk_9MmB/view?usp=sharing)

### Log files
- d3d9.log: 
[GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/9537767/GTAIV_d3d9.log)

[PlayGTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/9537768/PlayGTAIV_d3d9.log)

- dxvk.conf: https://drive.google.com/file/d/1xFXOcM6HG5rTKr2xOY6T0eMDt4VO9IgS/view?usp=sharing

- screenshots: https://drive.google.com/drive/folders/1uoHgSh4uWM4wZUsmaLMjX6huaj_a7Bo0?usp=sharing

- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment] 2022-09-09 18:46
Like Blisto said, your apitrace is basically empty.

Please make another one where you actually run the game and look into the mirror. It doesn't matter that the issue isn't there when you make the apitrace, it will show up when we replay it.

**Comment by renatopereyra** [comment] 2022-09-10 02:58
A while ago, I tried to trace GTA V and my traces were broken in a similar way. IIRC, I determined that the launcher is 32-bit but the game is 64-bit. I didn't spend too much time on it but I wasn't able to get my traces to work in the end, though, even after trying to account for this.

**Comment by K0bin** [comment] 2022-09-10 11:07
The game is 32bit.

I cannot fix this without an apitrace.

**Comment by Blisto91** [comment] 2022-09-11 11:38
From what i can tell this is just how the mirrors look in the game on non native Nvidia. I'm guessing the game uses some nvapi magic which doesn't work together with dxvk even when you don't tell the game you are on a amd gpu (which is done atm for this game). This also doesn't work on Linux atm it seems and it will probably never work on Windows. If that is what the issue is ofc.

<details>
  <summary>Screenshots</summary>
  
 Native AMD
![native amd](https://user-images.githubusercontent.com/47954800/189525351-4d303829-92a0-498a-8d11-61e61cb88770.png)

Native Nvidia
![nvidia native](https://user-images.githubusercontent.com/47954800/189525354-f04ba34d-ea83-45bc-914b-9c765991ef1f.png)
</details>

I have made a apitrace on both native amd and nvidia. Mirror is at the end.
AMD
https://mega.nz/file/ApZhALrC#PkW8HubveSML5k_HRhmLpJMAV9y82T79cB7TuKqDSE0

Nvidia
https://mega.nz/file/I0p0jAKR#9r6PHSx133k-JnxUjM1UfKjyqVAyENeyRLWhnA3yrwU

**Comment by pchome** [comment] 2022-09-11 15:50
`-forcehighqualitymirrors` ?

**Comment by Blisto91** [comment] 2022-09-11 16:50
Great option lol.

Yes that did seem to make them high quality on native amd. It didn't seem to help with dxvk on windows.
But it did help with dxvk on linux. Just don't change reflection quality while ingame or else they will look bad again until you restart.

Reading online it described as `-forcehighqualitymirrors: Enable 64 bit mirrors`. But i'm not really sure what that means in the context of a 32bit game or with dxvk on windows.

**Comment by doitsujin** [comment] 2022-09-11 16:55
Probably refers to the render target being 64 bit (i.e. RGBA16).

**Comment by K0bin** [comment] 2022-09-11 21:46
![image](https://user-images.githubusercontent.com/1131720/189550213-bb7abdd8-cb59-49c5-b0bb-eb0e18974079.png)

![image](https://user-images.githubusercontent.com/1131720/189550216-644c0634-1f17-42ea-bb09-c32327f33807.png)


Both apitraces look just fine with DXVK.

**Comment by K0bin** [comment] 2022-09-17 12:17
Looks like the game simply renders higher quality reflections if it detects a Nvidia GPU.
The problem is that we have to lie to the game and say it's running on an AMD GPU to avoid it calling NvAPI.

**Comment by K0bin** [comment] 2022-09-17 15:32
We did dig a bit more and found out how to make the game use the Nvidia render path for mirrors. That PR above will make the game enable better looking mirrors with DXVK.

**Comment by pchome** [comment] 2022-09-17 20:02
I found this option in my old EFLC config marked as `# Shadows`. I don't remember details.

Game bugs/overrides should be the same as GTA IV, executables `EFLC.exe` and `LaunchEFLC.exe` btw. Currently not in default config overrides.

**Comment by K0bin** [comment] 2022-09-19 14:07
LaunchEFLC.exe is a launcher though, isnt it?

**Comment by K0bin** [comment] 2022-09-19 14:09
Reopening this until we merge the PR.

**Closed** 2022-09-19 14:11 UTC
Labels: d3d9, not a bug
