### ISSUE TITLE
winelib build fails with meson 0.50

### ISSUE THREAD

**Issue by gasinvein** [doitsujin/dxvk#970] opened 2019-03-15 11:39 UTC
With meson 0.50, winelib check fails.
Corresponding `meson-log.txt` part:
```
Native C++ compiler: c++ (gcc 8.3.1 "c++ (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)")
Cross C++ compiler: wineg++ (gcc 8.3.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Running compile:
Working directory:  /tmp/tmphnxfqgtd
Command line:  c++ /tmp/tmphnxfqgtd/testfile.cpp -pipe -D_FILE_OFFSET_BITS=64 -c -o /tmp/tmphnxfqgtd/output.obj -m64 --no-gnu-unique -O0 -fpermissive 

Code:
 #ifndef __WINE__
#error 1
#endif
Compiler stdout:
 
Compiler stderr:
 /tmp/tmphnxfqgtd/testfile.cpp:2:2: error: #error 1
 #error 1
  ^~~~~

Checking if "winelib check" compiles: NO
```
With meson 0.48 dxvk builds fine. I guess the problem is that meson uses native compiler instead of cross-compiler to run the compiler test (`dxvk_compiler.compiles(code, name: 'winelib check')`).

**Comment by doitsujin** [comment] 2019-03-15 11:45
Hm, do you have any idea how to fix this?

**Comment by gasinvein** [comment] 2019-03-15 11:54
No, I'm not a developer. Not sure if it is expected behavior in meson, however.

**Comment by Joshua-Ashton** [comment] 2019-03-15 11:59
I'm not at home right now, but can you try

``CC=winegcc CXX=wineg++ [your meson command]``

and see if that fixes it?

**Comment by doitsujin** [comment] 2019-03-15 12:02
This is weird though, since `dxvk_compiler` should be the compiler that is used to compile the entire project, and that is `wineg++` as defined in the crossfile. Anyway, looks like this might need some digging.

**Comment by gasinvein** [comment] 2019-03-15 12:30
@Joshua-Ashton Yes, it helps. Would it break something?

**Comment by Joshua-Ashton** [comment] 2019-03-15 21:03
> 
> 
> @Joshua-Ashton Yes, it helps. Would it break something?

By saying it helps, do you mean it fixed the issue? or..

**Comment by gasinvein** [comment] 2019-03-15 22:10
I mean it compiles. Didn't try to run it.

**Comment by Valmar33** [comment] 2019-03-15 23:35
I get these errors:

`WARNING: Env var CC seems to point to the cross compiler.`
`WARNING: Env var CXX seems to point to the cross compiler.`

**Comment by Joshua-Ashton** [comment] 2019-03-25 10:10
For some reason meson decided to run these tests with the native compiler for some reason now it seems?

If this is an intended change, it is rather misguided.

**Comment by dhewg** [comment] 2019-03-26 13:53
This may be the root cause https://github.com/mesonbuild/meson/issues/5102

**Comment by libcg** [comment] 2019-03-29 00:01
following this thread, looks like there's an error here: https://github.com/doitsujin/dxvk/blob/master/build-wine64.txt#L15

should be `windows` and not `linux`. host machine is the machine that's running the final binary.

**Comment by doitsujin** [comment] 2019-03-29 07:24
@dhewg Thanks for digging into this, I'm still on 0.49 and frankly have better things to do than worry about build issues, so this is really appreciated.

**Comment by dhewg** [comment] 2019-03-29 07:50
Hehe, same here. I just ran into the same issue on https://github.com/iXit/wine-nine-standalone and downgraded too ;)

**Comment by Valmar33** [comment] 2019-04-13 10:10
Bug report here:

https://github.com/mesonbuild/meson/issues/5246

**Comment by dhewg** [comment] 2019-04-18 08:07
0.50.1 is out, which should fix this issue

**Comment by gasinvein** [comment] 2019-04-18 12:58
I can confirm that 0.50.1 fixes the issue.

**Comment by doitsujin** [comment] 2019-04-18 13:23
Nice, closing then.

**Closed by doitsujin** 2019-04-18 13:23 UTC
Labels: build
