### ISSUE TITLE
[Trace Testing] Crysis - Missing cloud shadow

### ISSUE THREAD

**Issue by flightlessmango** [doitsujin/dxvk#3299] opened 2023-03-21 11:50 UTC
In the game Crysis a shadow from a cloud does not render.
This bug was introduced somewhere between 36f523bbf5cf5308ea4b18af3a5dc1c646d9e415 and a9bdea72e9603de85411e3b41f8a49c9cbd11182 ([list of commits](https://github.com/doitsujin/dxvk/compare/36f523b...a9bdea7)).

### Bug can be reproduced on the following configurations

- VANGOGH, RENOIR, NAVI21
- radv 22.1.4, 22.3.3

Check out https://ci-dashboard.steamos.cloud/bugs/28 for the full history!

### Sample frame showing the issue

![frame](https://ci-dashboard.steamos.cloud/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU8wQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0976ee1a64ddc1aaded85574873ccfd7129c283/0000833797.png)

Click [here](https://ci-dashboard.steamos.cloud/deduped_frame_outputs/44933?q%5Bjob_id%5D=742) to compare this frame with the reference frame or other GPUs.

**Comment by K0bin** [comment] 2023-03-21 20:48
Is it possible to download the trace somehow?

**Comment by flightlessmango** [comment] 2023-03-22 04:34
> Is it possible to download the trace somehow

Yes! make an account on [ci-dashboard](https://ci-dashboard.steamos.cloud/) by authenticating with github or gitlab and then I can give you permissions to download traces

**Comment by K0bin** [comment] 2023-03-24 13:22
I'm not sure this is actually a cloud shadow. I think it's a bug and the reference frame is the one thats wrong.

Here's a screenshot of the benchmark running on Windows (Nvidia D3D9 driver).
![image](https://user-images.githubusercontent.com/1131720/227532393-111d65eb-1f17-491e-ab29-12daf483fde5.png)

**Comment by K0bin** [comment] 2023-03-24 13:27
I also can't reproduce that shadow with older DXVK builds on my Nvidia GPU, so it was probably fixed by a9bdea72e9603de85411e3b41f8a49c9cbd11182.

**Closed by K0bin** 2023-03-24 13:27 UTC
Labels: d3d9, not a bug
