### ISSUE TITLE
BioShock Infinite: green menus with 1.10.2

### ISSUE THREAD

**Issue by totof3110** [doitsujin/dxvk#2757] opened 2022-07-28 01:40 UTC
Using latest Manjaro, latest Lutris, and BioShock Infinite, I was experiencing the game menu texture rending green and unreadable. After some trial and error I was able to isolate it to a specific version of DXVK. With latest 1.10.2, the bug is reproducible. Downgrading to 1.10.1 (and all other settings identical), the menus render fine.

See pics for comparison:

![bioshock-infinite-dvxk-1 10 1](https://user-images.githubusercontent.com/294891/181401755-7b993c0a-416c-4b7a-a9a9-cebcfa252919.jpg)
![bioshock-infinite-dvxk-1 10 2](https://user-images.githubusercontent.com/294891/181401759-2e56d1cf-c10d-4c2a-a7d3-d7f2b142fd8a.jpg)

**Comment by Iglu47** [comment] 2022-07-28 06:56
I confirm, I can reproduce on 1.10.2, but it's already fixed by https://github.com/doitsujin/dxvk/commit/5aa943f47594aefd20a7441386bc7e105b927dfd

<details><summary>screenshot</summary>
<p>

broken on dxvk-1.10.2.r0.g https://github.com/doitsujin/dxvk/commit/40e4ea1fce3a26af1ef6e28fc3aba7f8df4787e4
![broken](https://user-images.githubusercontent.com/25866099/181439292-afe1e226-995b-4d80-989b-d4eb8d030532.png)
fixed on 1.10.x branch (dxvk-1.10.2.r7.g https://github.com/doitsujin/dxvk/commit/f5fe2596e35f1c8f78b20cfed4dbcc3118c155dd )
![fixed](https://user-images.githubusercontent.com/25866099/181439312-e26180b6-27af-4177-b73f-741c512f3976.png)

</p>
</details>

@tannisroot could you update dxvk 1.10.2 to https://github.com/doitsujin/dxvk/commit/5aa943f47594aefd20a7441386bc7e105b927dfd for Lutris?
@totof3110 could you check with this version of dxvk? https://github.com/doitsujin/dxvk/actions/runs/2741467764

**Comment by Iglu47** [comment] 2022-07-28 07:26
I confirm, I can reproduce on 1.10.2, but it's already fixed by https://github.com/doitsujin/dxvk/commit/5aa943f47594aefd20a7441386bc7e105b927dfd

<details><summary>screenshots</summary>
<p>

broken on dxvk-1.10.2 ( https://github.com/doitsujin/dxvk/commit/40e4ea1fce3a26af1ef6e28fc3aba7f8df4787e4 )
![broken](https://user-images.githubusercontent.com/25866099/181439292-afe1e226-995b-4d80-989b-d4eb8d030532.png)
fixed on 1.10.x branch (dxvk-1.10.2.r7.g https://github.com/doitsujin/dxvk/commit/f5fe2596e35f1c8f78b20cfed4dbcc3118c155dd )
![fixed](https://user-images.githubusercontent.com/25866099/181439312-e26180b6-27af-4177-b73f-741c512f3976.png)
also should work on master ( https://github.com/doitsujin/dxvk/commit/6c5f73ac26205fe9cdb98a450e12206c6caf2510 )
![fixed_on_master](https://user-images.githubusercontent.com/25866099/181442255-2499477f-f75d-4cd8-8010-c610d09f2b3e.png)

</p>
</details>

@tannisroot could you update dxvk 1.10.2 to https://github.com/doitsujin/dxvk/commit/5aa943f47594aefd20a7441386bc7e105b927dfd or 1.10.x branch for Lutris?
@totof3110 could you check with this version of dxvk? https://github.com/doitsujin/dxvk/actions/runs/2741467764

**Comment by doitsujin** [comment] 2022-07-28 11:03
Closing because this is already fixed.

**Closed by doitsujin** 2022-07-28 11:03 UTC

**Comment by totof3110** [comment] 2022-07-29 07:38
Thanks for confirming @Iglu47 ! I'll see if I can test it out.

**Comment by Iglu47** [comment] 2022-07-29 16:55
> I'll see if I can test it out.

Lutris now provides https://github.com/lutris/dxvk/releases/tag/v1.10.2-f5fe259,
@totof3110 just select it in the internal list of available DXVK versions.

**Comment by totof3110** [comment] 2022-07-30 02:34
> > I'll see if I can test it out.
> 
> Lutris now provides https://github.com/lutris/dxvk/releases/tag/v1.10.2-f5fe259, @totof3110 just select it in the internal list of available DXVK versions.

Confirmed! Latest DVXK solved the issue. Thanks @Iglu47 !
