### ISSUE TITLE
[D3D9] Cannot select proper resolutions using dxvk with GTA IV

### ISSUE THREAD

**Issue by recklessnl** [doitsujin/dxvk#1831] opened 2020-11-23 21:59 UTC
### Software information
GTA IV Complete Edition, up to date as of today, running on Windows 10 Professional.

### System information
- GPU: RTX 3090
- Driver: 457.30.0
- Wine version: N/A (Windows 10 DLLs only: d3d9.dll + dxgi.dll + dxvk.conf)
- DXVK version: 1.7.2
- Monitor: LG TV, 4K resolution @ 120hz, connected with HDMI 2.1 cable

### Log files
- d3d9.log: https://pastebin.com/7zuSnHMs

### dxvk.conf:
```
dxgi.maxFrameLatency = 1
d3d9.maxFrameLatency = 1
d3d9.maxAvailableMemory = 16384
```

### The problem

I cannot select the correct native resolution when using dxvk. The native resolution is 4k (3840x2160) and 120hz. The game allows me to select a max resolution of 1600x1200 at 100hz for some reason, not allowing me to go any higher in resolution nor refresh rate. See logs for more info. Resolution and refresh rate selection works fine when running it without dxvk (meaning I can select 4k@120hz). Any ideas on how to fix this?

**Comment by doitsujin** [comment] 2020-11-24 16:34
We get available display modes from wine via win32 APIs. Does this work properly in other games?

**Comment by recklessnl** [comment] 2020-11-24 19:24
Thanks for the reply @doitsujin — I haven't tested any other games on Windows 10 yet with dxvk.

When I open GTA IV without dxvk (running it normally), I can set the correct resolution just fine (3840x2160@120) so it must have something to do with dxvk + GTA IV. 

Any ideas of things I could try to get it set to the right resolution and refresh rate? The game currently won't allow anything higher than 1600x1200@100hz.

**Comment by recklessnl** [comment] 2020-12-03 04:04
@doitsujin Anything I can try to fix this?

**Comment by ViNi-Arco** [comment] 2020-12-07 19:25
Beauty Reck ?!
Try this:
Steam Launch Options: `-norestrictions -width 3840 -height 2160 %command%`
No Steam Launch Options: `-norestrictions -width 3840 -height 2160`

**Comment by MrEWhite** [comment] 2020-12-12 21:07
> Beauty Reck ?!
> Try this:
> Steam Launch Options: `-norestrictions -width 3840 -height 2160 %command%`
> No Steam Launch Options: `-norestrictions -width 3840 -height 2160`

This works, but it's still obviously broken.
![Screenshot (218)](https://user-images.githubusercontent.com/8465017/101994895-116b4080-3c94-11eb-830e-c839c06d0b67.png)

**Comment by Joshua-Ashton** [comment] 2020-12-13 15:58
I still cannot replicate this :(

I wonder if for some reason on your setup, WineD3D exposes less modes and DXVK more modes and the game has a fixed size list that we're reaching here.

I'll try adding a hack to remove some modes that the game probably shouldn't be using.

In the meantime, you can try using something like:
`d3d9.forceAspectRatio = 16:9`

**Comment by Kristijan1001** [comment] 2021-01-03 13:32
> d3d9.forceAspectRatio = 16:9

i have the sasme issue, that command looks like it fixes it as a temp fix. Also if u dont mind i ask, How do i use MSAA on GTA IV what is the command i should input , also is there way to make reshade work with it . Thank you.

**Comment by DaRkL3AD3R** [comment] 2021-01-06 04:45
I reported this bug ages ago, back in the D9VK Github. It's a monitor issue. For some odd reason, some displays will flood the API with erroneous duplicates of the same resolution x refresh rate listing straight down the line save for native resolution. I speculate it has something to do with the way monitor EDIDs  contain the timing information for G-Sync and ULMB/strobing modes so the driver can read these modes and understand what options are available. When I disconnect my G-Sync monitor and switch to a 60hz regular display, I can select any resolution I want because every resolution only gets 1 listing per refresh rate.

Here's my original issue report about this: https://github.com/Joshua-Ashton/d9vk/issues/341

You'll note that when I closed the thread I mentioned how I replicated the issue in an OpenGL emulator. The program in question was SNES9x set to OpenGL mode. It's strange that certain programs generate the list of resolutions incorrectly and others don't. But from what I can gather, this might not be fixable at all from the DXVK perspective. It's more DXVK is exposing a flaw somewhere else in the OS and driver code.

**Comment by Joshua-Ashton** [comment] 2021-02-06 09:01
Can you test with this? It would be interesting to see if this affects the problem for you.

[dxvk-format-exposure.tar.gz](https://github.com/doitsujin/dxvk/files/5936535/dxvk-format-exposure.tar.gz)

**Comment by DaRkL3AD3R** [comment] 2021-02-06 18:47
Sadly no dice.

**Comment by Kainey** [comment] 2021-05-16 20:46
Same issue with a 3440x1440 120Hz monitor, is it still unfixed ?

**Comment by FIocker** [comment] 2021-08-12 17:55
Same issue on a 3090. Trying for 5120x1440

Displays a ton of different resolutions without DXVK but with it I can't go beyond 1152x864 (120hz)

**Comment by vanhalendlrband** [comment] 2022-01-15 02:39
LG 4K same issue. Unsure if this can be fixed. Cant go past 1400x900 or something close to that i can’t remember it’s something by x900

**Comment by Joshua-Ashton** [comment] 2022-01-15 05:29
Pretty sure this is just because we expose more modes than Windows and the game has a fixed size. Not super sure what to do here. I guess we could just not expose some modes or not expose ones that aren't the target refresh or something for this game.

**Comment by recklessnl** [comment] 2022-01-29 02:37
@Joshua-Ashton But without dxvk you can run the game at native 4k...

**Comment by vanhalendlrband** [comment] 2022-01-29 03:17
Yes thats the same for me as well, without DXVK it runs up to 4k native as well just not great of course. Would be nice if it was DXVK then it would run amazing at 4k

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ancalimonungol** [comment] 2022-02-01 16:49
I have the same issue using a 1440p 144hz gsync monitor and RTX2070S

**Comment by KiralyCraft** [comment] 2022-02-06 20:23
In my case, I was stuck at 25 Hz for some reason, connected to an LG OLED 4K (HDR enabled). By passing the launch arguments: `-width X -height Y -refreshrate Z` as well as `-availablevidmem T` I was able to get 4K 60 going smoothly. 

Much to my surprise, and not diving too much into details, I'm running 2 x 970 in SLI - It looks like SLI support was also gone with DXVK, whereas without it it scales beautifully and gives decent performance.

HDR seems to have been broken too, but I can't confirm just yet, will do some more tests soon.

**Comment by Uncasted** [comment] 2022-03-08 17:46
> In my case, I was stuck at 25 Hz for some reason (as well as limited res options), connected to an LG OLED 4K (HDR enabled). By passing the launch arguments: `-width X -height Y -refreshrate Z` as well as `-availablevidmem T`, I was able to get 4K 60 going smoothly.

Thanks! This fixed it for me, I wasn't aware there was a refresh rate option and was stuck at 1080p 50hz. I encourage everyone else to try this too.

Something interesting that I found too is that if I alt-tab when the game is initially loading (i.e. Rockstar logo intro) the game would switch back to 800x600, alt-tabbing after that is fine though so if it happens to anyone just be patient.

**Comment by Karpadre** [comment] 2022-10-01 19:02
I feel like this issue could have been resolved in the meantime by an updated dxvk release as i suffered from it a year ago and luckily cant get it to occur anymore.  
what i did just to be safe for anyone:

copied the 32bit versions of d3d9.dll and dxgi.dll into the main folder 

dxvk.conf content:
dxgi.maxFrameLatency = 1
d3d9.maxFrameLatency = 1

commandline.txt content:
-rglLanguage=en-US
-availablevidmem=8000

slightly off topic
after that i followed [http://ant-sh.blogspot.com/2021/01/antialiasing-with-dxvk-and-gta-iv.html](url)
to get smoother edges thats it

**Comment by K0bin** [comment] 2022-10-01 19:21
The driver has no impact on this and I don't think the DXVK code that impacts this has been touched either.

**Comment by DaRkL3AD3R** [comment] 2022-10-27 07:05
Just an update. I recently dropped a 4090 into my PC and this issue no longer occurs. It's either an update to DXVK that resolved this or the newer graphics card did. Everything software side is the same regarding driver and monitor configuration. Only potential changes are the new GPU or a DXVK update. I'm going to try a much older build of DXVK and see if I can re-replicate the issue or not. If not, then I think it's safe to say this is GPU specific.

**Comment by Blisto91** [comment] 2022-10-27 07:08
It's probably not anything on the dxvk side that has fixed it.

**Comment by DaRkL3AD3R** [comment] 2022-10-27 07:21
It was the graphics card. I rolled back to DXVK 1.9.2 from Sept 2021, and the issue was still fixed. What's strange is, I tested a newer graphics card than my old one in the past, 1080 Ti vs 2080, and the same problem was present on the 2080 for me but not for my friend. He didn't have the multiple refresh rate reports like I did. But now upgrading my 1080 Ti to a 4090 resolved the issue. It's just bizarre.

I think it's safe to say either way this is not a DXVK issue and this topic can be closed. I had the same 3x listing issue in an emulator too which implies it's not a strictly DXVK thing but rather how the program polls the device on certain APIs.

To anyone still suffering this problem, a bandaid solution is to use Custom Resolution Utility to strip the EDID of all refresh rates besides your maximum and that should clean up the list enough to allow you to select your desired resolution. Otherwise, maybe eventually when you upgrade your GPU you'll find the problem solves itself.

**Comment by Blisto91** [comment] 2022-10-27 08:07
No it's fine to keep the issue open imo. dxvk can be weird in this regard sometimes, even on linux depending on your setup (monitors and such).

**Comment by EPtoMEnt** [comment] 2023-04-28 21:26
For me, what worked is disconnecting second monitor while playing GTA IV with DXVK. Then, all resolutions appear properly as they should. Main monitor is 1440p@144Hz (without Gsync/Freesync enabled) and second is 1080p@60Hz.

**Comment by Gloaf69** [comment] 2023-06-14 22:22
I just wanted to add my experience and I'm still having issues. I used the downgrader after making sure game was stable from downgrade I installed DXVK. Game ran great for like 10 hours and It was very nice overall. I was having issues with how grey everything looked but that's a GTA 4 issue not a DXVK one so I decided to try a ENB. After installing the ENB and getting in-game I didn't like how the colors looked so I used my backup copy of GTA 4 and reinstalled DXVK. Now I cannot select higher than 1440x1080. I have read through this entire thread and searched many more threads. I have tried different monitors and a third backup copy of GTA now for some reason I'm getting that issue only when DXVK is installed every other time I can select 4k.

**Comment by Gloaf69** [comment] 2023-06-15 00:08
> To anyone still suffering this problem, a bandaid solution is to use Custom Resolution Utility to strip the EDID of all refresh rates besides your maximum and that should clean up the list enough to allow you to select your desired resolution. Otherwise, maybe eventually when you upgrade your GPU you'll find the problem solves itself.


May I ask how you use the Custom Resolution Utility to do this I have downloaded it and tried to do it but I made my monitor stop working.

**Comment by ArdaCsknn** [comment] 2023-06-23 19:50
Same issue with a 4090 and I switched from 1080ti too. Forcing game arguments to launch in specified resolution. Default game detects resolutions without a problem.
[GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/11852429/GTAIV_d3d9.log)
<img width="1920" alt="Screenshot 2023-06-23 224742" src="https://github.com/doitsujin/dxvk/assets/16168336/0300f266-0b97-430d-9562-0a04dd2042cf">

**Comment by K0bin** [comment] 2023-06-23 19:52
Probably a Windows-only issue. The game also tries to use NvAPI which cannot work on Windows.

**Comment by ArdaCsknn** [comment] 2023-06-23 20:09
"d3d9.forceAspectRatio = 16:9"
This fix actually works without a problem and it wasn't a temporary fix. I don't know why the other guy said it like that. It also detects DSR resolutions too. No arguments needed.
<img width="1920" alt="image" src="https://github.com/doitsujin/dxvk/assets/16168336/77b398ab-c49d-4d91-8f07-92ee34e7541f">

**Comment by r3538987** [comment] 2023-08-13 16:37
> d3d9.forceAspectRatio = 16:9

THIS. Fixed for me being stuck on low resolutions, despite limits and resolution for game was increased in commandline.txt.

**Comment by DG0011-01** [comment] 2023-08-13 22:13
> > d3d9.forceAspectRatio = 16:9
> 
> THIS. Fixed for me being stuck on low resolutions, despite limits and resolution for game was increased in commandline.txt.

where do I put this?

**Comment by r3538987** [comment] 2023-08-14 07:48
> where do I put this?
Once DLL copied to game folder, next to it create file named dxvk.conf and insert this parameter there. 
PCGamingWiki also suggests few more lines, but in this case those are irrelevant.

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment] 2023-08-17 08:14
> > where do I put this?
> 
> Once DLL copied to game folder, next to it create file named **dxvk.conf** and insert this parameter there. PCGamingWiki also suggests few more lines, but in this case those are irrelevant.
> 
> For me in game settings I get 2GBs of memory available, but so far no problems observed with that.

thanks for the info, now I can properly use dxvk d3d9.dll at max supported resolution and refresh rate on Windows 10.

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment] 2023-08-17 08:57
also I want to point out this is not dxvk issue, this is Windows issue.
I have tested dxvk on diffierent systems with same games, I also asked friends to do same test, for the same game max res was different on each system even using same graphics driver version.

the only way to fix this mess on windows is by forcing the asepct ratio, and then adjusting the res to max from within the game.

thank you for making dxvk.

**Comment by PsxMicha** [comment] 2023-10-27 14:08
this problem still exists.. I tried with 3 different Monitors and one TV. only 1360x768 available. 

d3d9.forceAspectRatio = 16:9 doesn't fix this for me

**Comment by r3538987** [comment] 2023-10-27 16:01
> this problem still exists.. I tried with 3 different Monitors and one TV. only 1360x768 available.
> d3d9.forceAspectRatio = 16:9 doesn't fix this for me
Does DXVK itself work at all? Had you made config file? 
I have these in file, but that's ones from PCGAMINGWIKI. Probably not necessary.
`d3d9.presentInterval = 1
d3d9.numBackBuffers = 3
d3d9.forceAspectRatio = 16:9
d3d9.maxAvailableMemory = 3072`

**Comment by PsxMicha** [comment] 2023-10-27 17:34
nevermind.. I am a moron.. instead of dxvk.conf I named the config file dxkv.conf -.-

**Comment by sjain882** [comment] 2023-12-19 19:23
Just here to add my experience - had the same issue:

- latest DXVK v2.3
- RTX 3060M Max-Q
- NVIDIA Driver 537.42
- Asus Zephyrus G15 2021
- External 1080p Display MSI Optix G241 connected directly to NVIDIA dGPU via USB-C to HDMI cable

Oddly, with some new ZolikaPatch versions (which also made the rest of the game unstable), this commandline in Steam launch options and commandline.txt worked well:

`-novblank -noprecache -noswapdelay -availablevidmem 10.0 -usedirectinput -w 3840 -h 2160 -refreshrate 144`

despite the in-game UI looking like this:

<details>
![20231219185700_1](https://github.com/doitsujin/dxvk/assets/43217178/2fe72821-b8c7-4764-a6dd-bd9590231df2)

![GTAIV_GTAIV_2023-12-19_17-03-28](https://github.com/doitsujin/dxvk/assets/43217178/6878e12e-42de-4088-98e9-7dfe625d4ec1)
</details>

But with an older ZolikaPatch version, it just would refuse to work, regardless if I set BorderlessWindowed to 1 or 0 in the ini.

I had to use `d3d9.forceAspectRatio = 16:9` in dxvk.conf for me to be able to set it via in-game options, and only then did it work fine.

This is the first instance I've seen here where commandline arguments didn't work, so I thought I'd report in.

As a side note, the commandline above means I have a locked 60fps everywhere with zero stutters and texture loss after 8+ hours of gameplay, on a fully stock GTA IV (asset wise), with DXVK, using these graphics settings (ignore resolution):

<details>
![PlayGTAIV_GTAIV_2023-12-19_19-15-10](https://github.com/doitsujin/dxvk/assets/43217178/b4591836-6be6-419a-94f9-08984bd9a4f6)
</details>

**Comment by Blisto91** [comment] 2024-01-19 17:50
Can you guys give it a try with latest dxvk master. Can be downloaded from here https://github.com/doitsujin/dxvk/actions/runs/7586479700

**Comment by MrEWhite** [comment] 2024-01-19 17:57
> Can you guys give it a try with latest dxvk master. Can be downloaded from here https://github.com/doitsujin/dxvk/actions/runs/7586479700

That fixes this!

**Comment by wojtasskorcz** [comment] 2024-02-17 09:55
> > Can you guys give it a try with latest dxvk master. Can be downloaded from here https://github.com/doitsujin/dxvk/actions/runs/7586479700
> 
> That fixes this!

Confirmed. Version 2.3 was causing very low resolution and manually setting `-width` and `-height` in `commandline.txt` caused the game to crash.

This master version works great! I can run with all max settings (+4x AA in nvidia control panel) in 3440x1440 with ~60fps, coming up to the max 144fps in some scenes. My GTX 1080 is finally utilized properly.

**Closed** 2024-04-15 09:10 UTC
Labels: d3d9, windows
