### ISSUE TITLE
Playhome: black screen with game cursor

### ISSUE THREAD

**Issue by ineedhelphelper** [doitsujin/dxvk#1097] opened 2019-06-18 00:01 UTC
"Game"
wine ./PlayHome32bit.exe

Setup
echo 'export WINEARCH=win32' >> ~/.bashrc
winetricks dxvk
wine msiexec /i wine-mono-4.9.0.msi

System
Linux debian 4.19.0-5-amd64 #1 SMP Debian 4.19.37-3 (2019-05-15) x86_64 GNU/Linux
- GPU: GTX 750ti
- Driver: 418.74.0
- Wine version:  wine-4.0 (Debian 4.0-2)
- DXVK version: v1.2.2

### Apitrace file(s)
[PlayHome32bit.trace.zip](https://github.com/doitsujin/dxvk/files/3299207/PlayHome32bit.trace.zip)

### Log files
- d3d11.log:
[PlayHome32bit_d3d11.log](https://github.com/doitsujin/dxvk/files/3299209/PlayHome32bit_d3d11.log)
- dxgi.log: 
[PlayHome32bit_dxgi.log](https://github.com/doitsujin/dxvk/files/3299210/PlayHome32bit_dxgi.log)

**Comment by doitsujin** [comment] 2019-06-18 01:16
Looks like this game crashes your graphics driver instantly on launch:

> err:   DxvkSubmissionQueue: Command submission failed with VK_ERROR_DEVICE_LOST
> err:   DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST

The apitrace doesn't really contain anything useful, did it crash while you were recording it?

**Comment by nogamenoname** [comment] 2019-06-18 02:15
Nothing happens. If I try to close the game window it says it's not responding.
I did get it to crash a few times. I don't know if this is any better.
[crash.dmp.zip](https://github.com/doitsujin/dxvk/files/3299513/crash.dmp.zip)
[error.log](https://github.com/doitsujin/dxvk/files/3299516/error.log)

**Comment by doitsujin** [comment] 2019-06-18 02:58
I was asking whether or not the game crashed while you recorded the (**very** small) apitrace. As it stands I cannot reproduce any issues with the trace you posted.

**Comment by nogamenoname** [comment] 2019-06-18 05:40
I apologize, but it's as clear as mud how to install Windows apitrace inside wine.
This wiki doesn't really cover it.
https://github.com/apitrace/apitrace/wiki/WINE

I followed I_Got_2_Pickles instructions from Reddit.
Download: https://people.freedesktop.org/~jrfonseca/apitrace/apitrace-msvc-latest.7z
Copy the apitrace lib folder to the game exe's parent folder
Copy all the files/folders from the apitrace bin folder and place them in the folder containing the game exe

Yes, this is the exact command entered.

wine '/home/wren/.wine/drive_c/Program Files/PlayHome/apitrace.exe' trace -a dxgi ./PlayHome32bit.exe

I hit control C in the terminal to exit.

This gives me a (**very** **slightly** **bigger)** apitrace here.
[PlayHome32bit.trace.zip](https://github.com/doitsujin/dxvk/files/3299899/PlayHome32bit.trace.zip)

I have little more to tell you beyond.
> black screen with game cursor
> Nothing happens. If I try to close the game window it says it's not responding.

If this is not helpful, go ahead and close this out because I simply cannot give you more.

**Comment by doitsujin** [comment] 2019-06-18 10:32
[Here](https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace)'s another apitrace build that you can just drop next to the game exe, but make sure to use `native,builtin` for the DLL overrides. Maybe that'll produce something more useful.

In general it's best to record apitraces on Windows since that's basically the only thing that ever works correctly and produces useful results, but if you don't have access to a Windows install that's obviously not going to work either.

**Closed** 2019-07-03 07:04 UTC
