### ISSUE TITLE
Assassin's Creed Odyssey game frezen and fps not a stable

### ISSUE THREAD

**Issue by kabutu2021** [doitsujin/dxvk#4174] opened 2024-07-29 08:46 UTC
Please describe your issue as accurately as possible.
Assassin's Creed Odyssey game frezen and fps not a stable when play around 30 min.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Assassin's Creed Odyssey, settings used etc.  ultra settings WINDOW 11

### System information
- GPU: RTX 3090
- Driver: 555.85-560.70
- Wine version: 
- DXVK version: 2.4
[ACOdyssey_d3d11.log](https://github.com/user-attachments/files/16409903/ACOdyssey_d3d11.log)
[ACOdyssey_dxgi.log](https://github.com/user-attachments/files/16409905/ACOdyssey_dxgi.log)

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by K0bin** [comment] 2024-07-29 08:59
It would've been enough to mention in the Origins issue that Odyssey is affected too. Both games use pretty much the same engine.

**Comment by doitsujin** [comment] 2024-07-29 09:13
Closing as duplicate of #4173

**Closed by doitsujin** 2024-07-29 09:13 UTC
