### ISSUE TITLE
[Windows 10] [d3d9] Raceroom Racing Experience - artefacts on certain parts of the image

### ISSUE THREAD

**Issue by Harrier-Du-Bois** [doitsujin/dxvk#2271] opened 2021-09-02 10:45 UTC
I'm trying to use dxvk with Raceroom Racing Experience on Win10. Other users seem to be able to run it without issues: https://www.youtube.com/watch?v=cYcunmawBBA

When I'm trying to run it on my AMD system (see below) I see some impressive fps gains but sadly I also get some artefacts: https://youtu.be/Hj1m57bPAaE

### Software info:
Raceroom Racing Experience
(You can chose between 64 and 32 bit version, both produced the same issue)

### System information
- CPU: AMD FX6350
- GPU: AMD RX570 8GB
- Driver: 21.6.1 / 2.0.183
- Wine version: - (Windows10) 
- DXVK version: 1.9.1
- RAM: 8GB DDR3-1600

### Apitrace file(s)
- I did create an api trace but when I used the d3d9.dll from the trace guide those artefacts did not happen. The game was running very slow/choppy, but I assume that's simply due to the logging going on, but there were no artefacts visible on screen. 
If I should upload that trace nonetheless, let me know.

### Log files
- d3d9.log: 
[RRRE_d3d9.log](https://github.com/doitsujin/dxvk/files/7098243/RRRE_d3d9.log)

I'll happily provide more info and data if needed.

**Comment by K0bin** [comment] 2021-09-02 11:02
> If I should upload that trace nonetheless, let me know.

Yes, please do that. It's completely normal that the problem doesn't show up when you're making the apitrace because DXVK is not loaded when the apitrace dll is used. We can later replay the apitrace **with** DXVK which should make the issue show up again.

Please also try the latest master build of DXVK. You can download it here: https://github.com/doitsujin/dxvk/actions/runs/1174007847

**Comment by Harrier-Du-Bois** [comment] 2021-09-02 11:40
Hi, thank you for your swift reply.

I tried the latest master build you linked but I got the exact same artefacts (around windscreen/wipers & the sky textures) using that.

I created the trace by launching the game and loading into the same car-track-combo briefly, then alt-f4'ed out of it.
Hopefully it's of any use.
Link: https://mega.nz/file/TI1ihI5Y#z8UAGTQJAYsqXBr5WAp5x6Sjh-nUXfG76aFWXop6gyQ 

Thanks you for taking the time and again, I'll gladly do more tests or provide additional info/data.

**Comment by Davizmg** [comment] 2021-09-02 13:53
Hi! just discovered this, does it work in raceroom vr?  RR its dx9 but for VR uses dx10

**Comment by K0bin** [comment] 2021-09-02 14:00
It won't work on Windows but will probably work on Linux. And for the record, it probably uses D3D11 as VR doesn't support D3D10.

**Comment by Harrier-Du-Bois** [comment] 2021-09-02 14:27
_AfaIk_ this game cannot be run on Linux.
Not entirely sure if this has any relevance when it comes to dxvk, but it's also listed as "borked" on proton db: https://www.protondb.com/app/211500

I think the problem might be that the game uses some chromium stuff for their menu implementation, but I'm really not sure if that's what's breaking it for Linux.

**Comment by IOBYTE** [comment] 2021-12-26 19:33
I'm still seeing the shadow problem and micro stuttering with the latest artefacts build ecd7b67069a6e2a4b78a8a929fd287030d283ccb.

**Comment by Blisto91** [comment] 2022-04-09 15:03
Can reproduce the funky color artifacts on `amdvlk-2021.Q2.5`.
It seems to be the Multi Sampling option as it goes away when it's set to 0.

**Comment by K0bin** [comment] 2022-08-07 23:52
The apitrace is no longer available.

**Comment by IOBYTE** [comment] 2022-08-19 20:15
I'm getting a black screen and crash with 76ee76d6da6a3d4ec010aab43f1f6ccaaaf491f1

[RRRE64_d3d9.log](https://github.com/doitsujin/dxvk/files/9385140/RRRE64_d3d9.log)

**Comment by Blisto91** [comment] 2022-08-19 20:19
@IOBYTE Open a new issue.
Fill out the issue template and try to include a apitrace

**Comment by Blisto91** [comment] 2022-08-20 00:01
I am not reproducing a black screen and crash on Linux with that commit and the mesa drivers. This is with a R9 380.
Not able to check amd's own drivers as my card isn't supported.

Anyway i made a trace. Hopefully it works as a replacement for the original one.
https://mega.nz/file/Bhwx0KLD#jW34lao7mNkX07YcRxRJ04R_nbltuEukAb5L7PpC1cA

**Comment by Blisto91** [comment] 2023-03-13 09:05
@Harrier-Du-Bois Friendly ping. Could i get you to retest this? The Vulkan extension that can help some of these issues is available in AMD's Windows driver now.

**Comment by K0bin** [comment] 2023-05-06 17:04
Closing this because it's likely a driver bug that may have even been fixed in the time since this was reported.

**Closed by K0bin** 2023-05-06 17:04 UTC
Labels: d3d9, windows
