### ISSUE TITLE
Frostpunk crash on startup.

### ISSUE THREAD

**Issue by rogowskys** [doitsujin/dxvk#385] opened 2018-05-22 01:34 UTC
When attempting to start Frostpunk through Steam(which runs ok), the game attempts to start and then crashes immediately.  

### Software information
Frostpunk V1.0.1 using Steam

### System information
- GPU: AMD RX 580
- Driver: RADV 18.2.0-devel
- Wine version: 3.8-staging
- DXVK version: 51

### Log files
[Frostpunk_d3d11.log](https://github.com/doitsujin/dxvk/files/2024586/Frostpunk_d3d11.log)
[Frostpunk_dxgi.log](https://github.com/doitsujin/dxvk/files/2024587/Frostpunk_dxgi.log)

**Comment by doitsujin** [comment] 2018-05-22 09:19
Can you provide an apitrace?

The game seems to require geometry shader instancing, which is not implemented yet. Shouldn't be too hard to do, but I'd like to have a test case.

**Comment by rogowskys** [comment] 2018-05-22 17:33
Here is the apitrace:
https://drive.google.com/file/d/123krX7j2IIbkvOqXXsIwobSsRY2DmuwR/view?usp=sharing

Hopefully I made it properly.  It's a shame that the game developers are not going to release this game to Linux, considered all their other games have been.

**Comment by doitsujin** [comment] 2018-05-22 17:39
Thanks.

fb11acbc9139ea2567a4b60ff1ea5ff9330c9e8c implements geometry shader instancing. Please let me know if that fixes the crash.

Looking at the trace file, the game may also require DXGI 1.2, which DXVK doesn't support at all yet. In that case, the game still won't run.

**Comment by rogowskys** [comment] 2018-05-22 18:30
The errors about the geometry shader instancing are gone, but the game still crashes with "Not Responding"

Here is the wine output:
[Frostpunk_wine.log](https://github.com/doitsujin/dxvk/files/2028105/Frostpunk_wine.log)

**Comment by doitsujin** [comment] 2018-05-22 23:11
Here's an initial implementation of the required DXGI 1.2 stuff (in a separate branch for now): https://github.com/doitsujin/dxvk/tree/dxgi1_2

Please test if the game works with that. I can replay your trace file with those patches.

**Comment by rogowskys** [comment] 2018-05-22 23:33
Progress!  I am able to successfully start the game, however the screen is all black and the cursor.  I am able to move the cursor and click on menu options, and I can hear menu changing - I just can't see it. 

[Frostpunk_wine.log](https://github.com/doitsujin/dxvk/files/2028942/Frostpunk_wine.log)
[Frostpunk_dxgi.log](https://github.com/doitsujin/dxvk/files/2028943/Frostpunk_dxgi.log)
[Frostpunk_d3d11.log](https://github.com/doitsujin/dxvk/files/2028944/Frostpunk_d3d11.log)

**Comment by doitsujin** [comment] 2018-05-22 23:39
Is it black if you replay your own trace file with `d3dretrace.exe`? Because that works for me, although I'm not sure if it's rendering correctly.

**Comment by rogowskys** [comment] 2018-05-22 23:50
Using d3dretrace.exe does appear to work and render correctly.

**Comment by doitsujin** [comment] 2018-05-23 09:18
To give you an update, the issue is that the game uses D3D9 to render a single frame shortly after starting the game, which implicitly creates an OpenGL context. This prevents the Vulkan swap chain from getting through.

Here's a **very** dirty workaround for the issue:
[dxvk-frostpunk.patch.txt](https://github.com/doitsujin/dxvk/files/2030335/dxvk-frostpunk.patch.txt)

Not sure if this can be fixed in a proper way.

**Comment by doitsujin** [comment] 2018-05-23 11:08
I came up with a better workaround, which I pushed to the `dxgi1_2` branch:
https://github.com/doitsujin/dxvk/commit/38c5e570257e8cd9dcb78ab227baa2a2c877bd0f

Please let me know if that makes the game work for you.

**Comment by doitsujin** [comment] 2018-05-23 18:11
I'm aware of the freeze, it's unrelated. It's likely a driver issue, I'm looking into it.

**Closed by doitsujin** 2018-05-23 18:11 UTC
Labels: d3d9, feature set, interop
