### ISSUE TITLE
Steam Link + native Steam Overlay + DXVK = Black screen

### ISSUE THREAD

**Issue by ssorgatem** [doitsujin/dxvk#649] opened 2018-09-19 07:26 UTC
Note that I'm referring to native Steam overlay, from Steam for Linux, applied on a wine game. 
The same happens when using Proton:

Steam Link + Steam Overlay + wined3d = works
Steam Link + DXVK = works
Steam Overlay + DXVK = works
Steam Link + Steam Overlay + DXVK = Black screen on the Steam Link (on the PC it works normally)

This behaviour has always been like this for DXVK. But DXVK used not to work at all with the Steam Overlay, so I thought that was the issue. But now that DXVK works with the Steam Overlay, I tried again and it's still there.

I'm not sure which log files would be helpful here, since it looks like the issue is at the Vulkan level, but I'll provide everything I can when I get home.
I'll also test streaming to the Steam Link Android app to see if the same issue shows there too (I guess that'd make it easier to replicate, since not everyone has a Steam Link...).

Maybe I should open an issue on the Proton tracker too?

### System information
- GPU: Vega 56
- Driver: 18.2.99
- Wine version: 3.16.r37.g8a985174eb.staging.esync.pba
- DXVK version: 

### Apitrace file(s)
- Soon

### Log files
- Soon

**Comment by doitsujin** [comment] 2018-09-19 07:44
How do I reproduce that?

**Comment by ssorgatem** [comment] 2018-09-19 15:49
I'm trying to reproduce this on Android but now the streaming won't work for me at all for some reason (maybe the Steam beta...?).

Yes, it only happens when the Steam Overlay is enabled.

And there must be some interaction, otherwise it wouldn't happen only when streaming with both the overlay and DXVK...

**Comment by doitsujin** [comment] 2018-09-19 15:55
But there is none. DXVK doesn't even know that the Steam Overlay exists, so this is almost certainly not my bug.

**Comment by tpruzina** [comment] 2018-09-21 20:52
On GL they basically hook glSwapBuffers (and GL context/drawable related functions) in steam overlay library, then readout completed frame during swap.

No idea sure how they do it with VK swap chain, last time I looked at the code in IDA there was no Vulkan support. I think this should be reported this to Valve directly.

**Comment by ssorgatem** [comment] 2018-09-25 21:40
If anyone wants to try it, I could reproduce it on the Android app.
Steps to reproduce:
1 - install the Steam Link app on an Android device: https://play.google.com/store/apps/details?id=com.valvesoftware.steamlink&hl=en
2 - Start it and stream your computer's Steam to your Android device (you can keep controlling from the computer, no need to connect a controller to your android device)
3 - Start a wine or proton game with DXVK from Steam with the Steam overlay enabled (it can be a non-Steam game too)

**Comment by ryao** [comment] 2018-10-07 23:58
I cannot reliably reproduce the black screen issue on my steamlink. I did have it happen once, although I did not make note of which game it was. It was either on Dungeons III or A Hat In Time. Neither involve DXVK. When it did happen, it was a black screen on my console too. I had to alt tab out of it and kill the process. I even had to kill the steam process too if I recall correctly as it was playing music from the game according to pulse audio (while being non responsive).

**Comment by lordkitsuna** [comment] 2018-10-08 00:12
I also can not get this to occur, using Proton i have no issues bringing up the overlay and using it. I have been unable to test with Steam in Wine as i cant even get the stream to launch with it complaining about failure to create the surface it needs which appears to be a known wine issue.

**Comment by mikebwilliams** [comment] 2018-11-24 15:33
This happens pretty often during The Stick of Truth. Pressing the guide button twice to open and then close the overlay fixes it.

**Comment by mikebwilliams** [comment] 2018-12-01 15:03
Ok, so the black screen issue for me is apparently due to the screens being suspended on the host PC due to lack of activity. Press the guide/steam button twice to open and then dismiss the overlay is seen as activity and the screens are woken up, fixing the black screen. This is on Ubuntu 18.04 using KDE/Kwin as the window manager.

**Comment by K0bin** [comment] 2022-08-30 22:21
I'm gonna close this because the issue is ancient and most likely not caused by DXVK anyway.

**Closed by K0bin** 2022-08-30 22:21 UTC
