### ISSUE TITLE
GTA V white spot/cursor issue in cutscenes (maybe DoF related)

### ISSUE THREAD

**Issue by fls2018** [doitsujin/dxvk#712] opened 2018-10-18 15:07 UTC
I reported this issue on the Proton github but chances are the issue is more related to recent dxvk changes. 

Mainly in cut scenes there is a white dot/cursor that floats on screen, here's an example (by the yellow fire hydrant):

![gta](https://user-images.githubusercontent.com/43592670/47164048-22f07200-d2ef-11e8-9e26-75e9d26141d0.jpg)

Rolling back Proton to 3.7.8 makes it go away, as well as maybe disabling in game DoF in the options (more testing needed on this).

It's only a small issue, game runs perfectly otherwise.

### Software information
GTA V, Mostly max settings /w 2x MSAA (ingame DoF enabled).

### System information
- GPU: GTX 1070
- Driver: 396.54.09
- Wine version: Proton 3.16-3 beta
- DXVK version: 0.90 (Proton)

**Comment by doitsujin** [comment] 2018-10-18 16:53
Can you please
- either bisect DXVK to find out which commit introduce the issue,
- or provide an apitrace as documented on the [Wiki](https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace)

I don't have access to the game at the moment, so I cannot debug it.

**Comment by libcg** [comment] 2018-10-21 02:04
I'm able to reproduce it on RADV:
![screenshot from 2018-10-20 18-59-42](https://user-images.githubusercontent.com/490159/47262335-eb262d80-d49a-11e8-9c82-e53d31dc980b.png)

Could be a game bug, I'll look into it when I have some time.

**Comment by doitsujin** [comment] 2018-10-21 06:47
Can you try to record a trace? This is going to be an insane pain to debug as it is, but right now I'm not even allowed to start the game thanks to Rockstar being stupid.

**Comment by fls2018** [comment] 2018-10-21 18:49
Don't know if I can do an app trace as it requires DXVK to start up.

This issue only popped up with the whole transform feedback thing, maybe something to do with how new changes interact with the in game depth of field.

**Comment by pedrofleck** [comment] 2018-10-29 01:41
I have this problem too, I thought it maybe was related to subtitles, it looks like a dot from the text.

**Comment by doitsujin** [comment] 2018-10-29 07:51
@fls2018 The game doesn't use transform feedback and it has been confirmed to happen on drivers that don't even support it.

**Comment by JamesChenChina** [comment] 2018-11-19 15:53
How to play GTA-V on Ubuntu 16.04？
Could you please show a detailed instruction？
e.g. wine version and link ,dxvk version, vulkan version and other requirements. I have updated nvidia driver to 396.54.09.
Many thanks!

**Comment by doitsujin** [comment] 2018-11-26 07:07
So reverting that commit fixes the issue? Any chance you can record an apitrace?

I'd like to understand **why** this is broken.

**Comment by libcg** [comment] 2018-11-26 15:53
Yes it looks like master + 161fb62 reverted makes the issue disappear. I'll record a trace soon.

**Comment by doitsujin** [comment] 2018-11-26 16:20
Can you test 08b403f65507f4beac47d7d6816bad243cd811e9? Closer inspection did actually reveal a subtle bug introduced by the optimization.

**Comment by doitsujin** [comment] 2018-11-27 06:05
Thanks for testing, closing the issue.

**Closed by doitsujin** 2018-11-27 06:05 UTC
Labels: bug
