### ISSUE TITLE
[d3d9] GTA IV, different game versions, stutters and Mappable & Mapped amount. 

### ISSUE THREAD

**Issue by r3538987** [doitsujin/dxvk#3768] opened 2023-12-26 21:09 UTC
There are multiple game version, and when tested these two, noticed that one plays almost smoothly, and other one has frequent stutter or even frame skips. Especially it's noticeable when player traverses city quickly or pan camera smoothly. 

Here are two video samples:
https://www.youtube.com/watch?v=wgamTJ4H1mc Complete Edition 1.2.0.59 (latest) --- not smooth
https://www.youtube.com/watch?v=SrYO_HQ85U4  Older game version 1.0.7.0 --- smooth

Older version has frametime spikes, but those during gameplay rarely noticeable. 
Latest version on other hand have stutters very often.

When captured these two videos, noticed that if DXVK has HUD enabled, there are Mappable & Mapped values, and those differ significantly. 
And older game version which runs way smoother, has multiple times higher value. 
https://i.imgur.com/UlXSZpL.png
![image](https://github.com/doitsujin/dxvk/assets/33725345/b4041705-591a-4838-9598-43fd7dace5ab)
1) **These two mentioned parameters, what are these**, and could these actually boost performance?
2) **Or these could be some cache values for compiled shaders**, and simply represent that I played 1 version more, and so it computed more data which now result in smoother performance? 

Rewatched videos few times more, and overall I'm making conclusion that in v1070 frametime spikes are around 40ms, but in latest game version these can shoot to 70-80ms, that's why player notices slowdowns more. 

### Software information
GTA IV, pretty much almost maxed out in-game settings.
Tried few mods applied that limit framerate, or implement borderless window functionality, but results are similar still. 

In commandline.txt as game config. 
-availablevidmem 3072.0
-percentvidmem 100
-nomemrestrict
-norestrictions

In dxvk.conf
-d3d9.presentInterval = 1
-d3d9.numBackBuffers = 3
-d3d9.maxFrameLatency = 1
-d3d9.forceAspectRatio = 16:9
-d3d9.maxAvailableMemory = 3072
-dxvk.hud=full

### System information
- GPU: RTX 2070 Super
- Driver: NVIDIA 537.42
- DXVK version: 2.2 / 2.3 - behavior is same with 2.2 and 2.3 DXVK files.

**Comment by HunterCZ122** [comment] 2023-12-26 21:57
> And older game version which runs way smoother, has multiple times higher value.
Mods taking address space.

I think ZolikaPatch or FusionFix does some hacks that might improve frametimes.

**Comment by K0bin** [comment] 2023-12-26 22:50
I don't know what you're expecting here.

Rockstar changed how the game does its texture streaming and the new implementation has worse performance (but better memory and address space usage) than the old one.

I guess if you could provide apitraces of both versions showing an identical scene (similar to the videos), I could take a look if there's anything we could improve on the DXVK side but I wouldn't hold my breath. I assume it's all caused by the game itself, not DXVK.

**Comment by Blisto91** [comment] 2023-12-26 22:54
To address the question also, the values seen is dxvk trying to free some resources from system memory in 32bit (d3d9 only) games. In the past dxvk had alot of issues in 32bit games because it tended to use more memory than the native Direct3D version and so this system was implemented to try and alleviate the issue. I can't explain the technical details though.

**Comment by r3538987** [comment] 2023-12-26 22:55
> I don't know what you're expecting here.

Thought maybe Mappable & Mapped, are the culprit here, and there ways to adjust these via config. 
Thanks for response still. 
Once I got some more time, I will try to figure out APItraces thing, should be not that complicated on Windows too.

**Comment by K0bin** [comment] 2023-12-26 22:58
> Thought maybe Mappable & Mapped, are the culprit here, and there ways to adjust these via config.

The reason those numbers are that much higher in the old version is simply because the old version used a lot more memory. The new version works differently but that's a game decision, not something DXVK can control.

I'll close this issue for now. Feel free to reopen it when you post the apitraces and I'll take a look.

**Closed by K0bin** 2023-12-26 22:58 UTC
Labels: performance, d3d9, not our bug

**Comment by r3538987** [comment] 2023-12-26 23:35
1) You would need an similar sequence? And does it need to be long enough, like videos?
Asking because maybe if there is no need in that. And smaller sample would do the trick. 
Usually good measure in community is where player runs from safehouse through doors, and often it spikes frametime, as world gets rendered there. 

Because if wanting to reproduce videos, then it usually takes time to reach location and with 15FPS in-game I'm not sure long file will be usable and show useful info. 

2) One game version launches and tracer loads properly, but other one uses launcher for main executable, and because of that tracer and game itself fail to start.

**Comment by K0bin** [comment] 2023-12-26 23:38
> You would need an similar sequence? And does it need to be long enough, like videos?

Yes it should be roughly similar. It doesn't have to be as long as the videos but it shouldn't just be 2 seconds either.

**Comment by r3538987** [comment] 2023-12-26 23:43
Complete Edition, one where stutters are more pronounced.  
https://drive.google.com/file/d/1RJcMUWkXTSrkQ5f2Vgl3V75Psf2xk1qD/view?usp=sharing

Will see if anything can be done to create 2nd.

**Comment by K0bin** [comment] 2023-12-27 00:20
Yeah, there isn't really anything we can do on our end.

The way the new version does texture streaming is actually very optimal for DXVK, it just seems that the game itself does a worse job.
