### ISSUE TITLE
[d3d9] TrackMania United Forever: dirt trail smoke of stadium tracks cars is not rendered properly

### ISSUE THREAD

**Issue by AlexTMjugador** [doitsujin/dxvk#1376] opened 2020-01-26 10:51 UTC
Again, this is a issue originally reported in #1363 by @Iglu47 and me.

> upd2. shader PC3 High - look at the dust from under/after the wheels
> dxvk-1.5.1-bin no have this ussue with color
> upd3. i checked for issue like on screenshot - first problem commit - dxvk-git-1.5.1.r55.g[6fa28bf9](https://github.com/doitsujin/dxvk/commit/6fa28bf9371ee40eb350d8e296adfae77c8236de)
> ![shader PC3 High](https://user-images.githubusercontent.com/25866099/73117650-25159780-3f5a-11ea-87f2-680ae92a8aca.png)
> PC2 no have this issue and freeze issue - so game still good playble

In my case, the smoke isn't even visible, so this issue might be driver dependent, or not related to DXVK.

### Software information
TrackMania United Forever, maximum settings.

### System information
@Iglu47 system specs:
- GPU: NVIDIA GTX 1080 Ti.
- Driver: NVIDIA propietary driver, 440.48.2.
- Wine version: Wine-TkG 5.0.r2.
- DXVK version: DXVK 1.5.1-53-g38a0d2c5.

My system specs:

- CPU: Intel Core i3-2100 @ 3209 MHz.
- GPU: NVIDIA, MSI GeForce GTX 1650 Ventus XS.
- Driver: Debian Bullseye NVIDIA propietary driver, 430.64 (package version 430.64-6).
- Wine version: wine-4.21 (Debian 4.21-2).
- DXVK version: 1.5.2.

### Apitrace file(s)
- I'll post one soon.

### Log files
- d3d9.log: I'll post one soon.
- d3d11.log: N/A.
- dxgi.log: N/A.

**Comment by Iglu47** [comment] 2020-01-26 16:25
in fact, in order to see "this", you need to enable a very specific option from the compatibility category, which may already be not a good idea.
![very_specific_config_eng](https://user-images.githubusercontent.com/25866099/73137212-c5f17900-4066-11ea-9cad-78b6fa180c67.png)
so I don't think that this is really a issue

**Comment by doitsujin** [comment] 2020-01-27 19:23
> I'll post one soon.

Any news on that?

Would be nice to have apitraces right away, right now there's not much we can do and if we don't get a trace within the next 2-3 days, we might as well close this.

@Iglu47 If it doesn't happen on native d3d9, this might still be a bug worth investigating (but again, we need a trace that shows the problem).

**Comment by Iglu47** [comment] 2020-01-28 16:31
recorded ~15sec full race on dirt where "colored" smoke was drawn [trace file - google drive](https://drive.google.com/open?id=1Ucgaz-1DIouXWL5890I-6FSzjVBi_0i6)
- Driver: NVIDIA propietary 440.48.2
- Wine version: Wine-TkG-5.0.r4
- DXVK version: dxvk-git-1.5.2.r10.g[b1edf227](https://github.com/doitsujin/dxvk/commit/b1edf227f8a6e87a3115e2b0839d9bfb9454d117)

**Comment by AlexTMjugador** [comment] 2020-01-29 21:49
> > I'll post one soon.
> 
> Any news on that?
Sorry for the delayed response. I've been busy these days. Luckily @Iglu47 apitrace is fine :)

**Comment by Iglu47** [comment] 2020-02-19 00:35
now after a while, with the current versions of video-driver, wine and kernel, this the "compability-option" just "instantly close the game" when trying to enter the race. so i can't resproduce it more even with dxvk 1.5.2

- nvidia proprietary driver: 440.59; gtx nvidia 1080ti
- arch linux, liquorix-5.4.17
- wine-tkg 5.1.r7
- dxvk 1.5.2

but the game continues to work perfectly if don't turn on it

**Comment by Joshua-Ashton** [comment] 2020-02-21 20:24
Unfortunately I can't reproduce this on the trace, and I can't get the actual game to work for me on native or DXVK anymore (I feel like this game is super janky/broken in some way on Win 10.)

Could you record a trace with DXVK?

**Comment by pchome** [comment] 2020-02-22 19:01
@Joshua-Ashton 
Reproducible with Nations Forever version from Steam, the game is free (demo?) and small, same engine.

Version from the official website starts crashing, when I trying to change settings, but Steam version is ok. With disabled antialiasing I can see the smoke, also with 4 samples AA still noticeable. With 8 samples AA everything looks normal.

**Comment by Iglu47** [comment] 2020-02-23 09:01
TrackMania United Forever v2.11.25

- nvidia proprietary driver: 440.59; gtx nvidia 1080ti
- arch linux, liquorix-5.4.17
- Proton-5.1-GE-2
- dxvk 1.5.4.r37.g4405b551b

game settings (main is "Enable rander read backs")![game-config](https://user-images.githubusercontent.com/25866099/75109377-3aeaab00-5633-11ea-986a-547680d09572.png)

ingame screen with dxvk and apitrace dlls (idk why forced low texture, so usually i don't use steam)
![color_smoke](https://user-images.githubusercontent.com/25866099/75109381-5786e300-5633-11ea-83cf-66a2a100730b.png)


dxvk trace: https://drive.google.com/open?id=1QB3GujLiCp89eoEy5hd15E4zhdEOTHGn

**Comment by Iglu47** [comment] 2020-03-24 00:12
ok, there seems to be a problem around the `render read backs`
because dxvk crash on windows too
question. what is mean `render read backs`? it's why the number of frames in the trace-file ~twice as large if it enable, but it doesn't seem that I will be happier if I enable this >_<
record native dx9 on windows with and without `render read backs`: https://drive.google.com/open?id=11Bsw3DhKUoY38YN6W5VSXtjCTaogfdWC

**Comment by Iglu47** [comment] 2020-04-01 07:13
> I checked, `trackmania nations forever` aka trackmania 1 demo have the same game engine and repeatable problem
game site - <http://trackmaniaforever.com/nations/>
and direct link `http://files.trackmaniaforever.com/tmnationsforever_setup.exe`

**Comment by Iglu47** [comment] 2020-05-29 16:46
I checked the dxvk master and many old versions (including those that did not work previously).
Seems now option `render read backs` works at least (probably) starting with nvidia 440.66.15

- nvidia proprietary driver: 440.66.15; gtx nvidia 1080ti
- arch linux, liquorix-5.6.15
- wine-staging 5.9.r11.g4e692b53 (with revert fd79929)
- dxvk 1.7.r37.gf92d6049 and earlier versions

but now I also use mingw-w64-binutils 2.34-20200521 with patch (pr25993)

**Comment by Iglu47** [comment] 2020-05-29 18:03
smoke color still here
![tm-color](https://user-images.githubusercontent.com/25866099/83290589-84790200-a1ef-11ea-96c2-37000539fb1d.png)

should not be color and not so bright
![tm-normal](https://user-images.githubusercontent.com/25866099/83290610-8d69d380-a1ef-11ea-8353-28b8bbed26c8.png)

dxvk-trace: [link](https://drive.google.com/file/d/1VSDnBmIjrxT9njRMQfTpw0Cx619MgtB5)
wined3d-trace: [link](https://drive.google.com/file/d/1wJY6RM8aKlg9_2Sau-cn1RVYx3GU1uzs)

**Comment by Joshua-Ashton** [comment] 2020-06-01 14:52
Can you please try with the latest froggi.es build?

Thanks!

https://git.froggi.es/doitsujin/dxvk/-/jobs/1309

**Comment by Iglu47** [comment] 2020-06-01 17:03
I checked on `master` (dxvk-git-1.7.r40 5558460853f155550cf63b03bb682afce029630b)
now even with the option `render read backs` the smoke looks right

**Closed** 2020-06-01 17:14 UTC
