### ISSUE TITLE
Particle corruption in Assassin's Creed Odyssey under Windows

### ISSUE THREAD

**Issue by EPOCHvoyager** [doitsujin/dxvk#2468] opened 2022-01-29 18:28 UTC
![12378083983190130688_20220129145330_1](https://user-images.githubusercontent.com/39300993/151672217-ae53a1bb-55fe-46a2-868d-299ce9eaa87e.png)

This is running on the latest 22.1.2 Optional (WHQL) driver with a 5700XT, but this issue has persisted throughout multiple driver iterations until now; previously on Windows 10, now under Windows 11 with the latest updates. I've made sure this isn't happening because of a dxvk.conf flag or environment variable. 

I haven't tested dxvk versions below 1.9.1, but it could be some sort of regression, as I remember it being an issue and having been fixed after an update a while(years - likely 2020) back.

It appears to affect only some specific type of particle, only in specific parts of the world map, and especially at night - although step dust particles in caves are always a surefire way to reproduce this. Here's the location pictured in the screenshot above:

![12378083983190130688_20220129151406_1](https://user-images.githubusercontent.com/39300993/151672613-a64a63e1-27b5-465f-9cae-211143d2f2ec.png)

PS: I've filed a bug report to AMD describing this bug approximately half a year ago(as they have had some driver woes in the past), and have gotten no response in return; it does only affect the game running through dxvk, I suppose. Game runs perfectly otherwise.

**Comment by K0bin** [comment] 2022-01-29 18:50
Driver bug.

Duplicate of:
#2390 #2326 #2355 #2390

**Closed by K0bin** 2022-01-29 18:50 UTC
