### ISSUE TITLE
World of Final Fantasy Offset issue

### ISSUE THREAD

**Issue by kust2708** [doitsujin/dxvk#1216] opened 2019-10-05 18:50 UTC
Rendering in game seems to have some issue, the screen is splitted by multiple horizontal bands with offset.

![20190818174433_1](https://user-images.githubusercontent.com/6338427/66259045-ed1cf580-e7ac-11e9-80fc-e172e67a84ec.jpg)
![20190818174534_1](https://user-images.githubusercontent.com/6338427/66259046-ed1cf580-e7ac-11e9-86ed-935a77708aba.jpg)
![20190928200535_1](https://user-images.githubusercontent.com/6338427/66259047-edb58c00-e7ac-11e9-8abc-2d1a2568e203.jpg)
![20190928200640_1](https://user-images.githubusercontent.com/6338427/66259048-edb58c00-e7ac-11e9-9842-dbeb69c52f02.jpg)

### Software information
Name : World of Final Fantasy
Setting doesn't have influence on the result, only full screen is required in order to launch the game.

### System information
- GPU: NVIDIA GeForce GTX 1080 Ti
- Driver: nvidia 435.21
- Wine version: 4.17 & Proton 4.11-6
- DXVK version: 1.4.2

### Apitrace file(s)
No result, the game crashes without DXVK enabled : 
wine apitrace.exe trace -a dxgi /run/media/jeux/WindowsSteamLibrary/steamapps/common/WOFF/WOFF.exe
apitrace: loaded into Z:\run\media\jeux\WindowsSteamLibrary\steamapps\common\WOFF\WOFF.exe
0031:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000022FCD0
002f:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000022FCD0

### Log files
- d3d11.log: 
[WOFF_d3d11.log](https://github.com/doitsujin/dxvk/files/3693592/WOFF_d3d11.log)
- dxgi.log: 
[WOFF_dxgi.log](https://github.com/doitsujin/dxvk/files/3693593/WOFF_dxgi.log)
- Proton log : 
[steam-552700.log](https://github.com/doitsujin/dxvk/files/3693597/steam-552700.log)

**Comment by doitsujin** [comment] 2019-10-05 20:29
Yes, this is a known game bug and cannot easily be fixed inside DXVK.

**Comment by kust2708** [comment] 2019-10-06 08:07
Thanks for your hard work @doitsujin. Just keep this in the current state. It's better to maintain DXVK stability and performance.

**Comment by doitsujin** [comment] 2019-10-06 09:05
Do you know if this works with wined3d?

I'd be surprised if it did to be honest because of how texture binding works there, but it would be interesting regardless.

**Comment by kust2708** [comment] 2019-10-06 10:17
I managed once to launch this game using wined3d. The result is a black screen in game, only maps and sub are rendered. I'll try to clean my prefix and make a apitrace with wined3d.

**Comment by doitsujin** [comment] 2019-10-06 10:23
wrt apitrace, you can try copying the `dxgi.dll`, `dxgitrace.dll` and `d3d11.dll` from the `x86/lib/wrappers` directory (or `x64/lib/wrappers` if this is a 64-bit game) and launch the game; it's usually more reliable than using the command line app.

There's also no need to use wined3d to record a trace in this particular case.

**Comment by kust2708** [comment] 2019-10-06 16:33
I tried many time to make an apitrace without success. With Proton, the game crashes at the begin with a dx11 error. With wine, there is no .trace file generated. 
I tried both command line and putting wrappers files directly into the game folder (with the executable) as you suggested.

Some screenshot without DXVK : 
![Screenshot_20191006_123450](https://user-images.githubusercontent.com/6338427/66272268-be178a00-e867-11e9-8ca0-2f5e52853aff.png)
![Screenshot_20191006_123524](https://user-images.githubusercontent.com/6338427/66272269-be178a00-e867-11e9-880d-040a38a8adc6.png)



I'm probably making something wrong, even it seems to be not that difficult...

**Comment by kust2708** [comment] 2019-10-10 17:46
An apitrace is coming soon...

**Comment by kust2708** [comment] 2019-10-10 19:32
Okay, here is the apitrace : https://drive.google.com/file/d/110U3qR09wmSSHaBs1tIb-nLSpvwwXtiy/view?usp=sharing

**Comment by kust2708** [comment] 2020-04-21 20:14
Hi, I tried to launch this game using my Intel iGPU and the game works without any issue. It's seems to be a Nvidia specific problem.

**Comment by Joshua-Ashton** [comment] 2020-04-22 04:38
Yes, but this is still technically a problem caused by invalid behaviour cause the game does invalid stuff.

**Comment by iWeaker4you** [comment] 2020-05-09 18:07
@kust2708  Did it work without problems with DXVK or was it with WineD3D?

**Comment by Joshua-Ashton** [comment] 2020-05-09 20:09
It's because that just works on Intel.

**Comment by kust2708** [comment] 2020-05-10 10:26
@iWeaker4you It was with DXVK, but as Joshua-Ashton said, it's because that just works on Intel (and AMD according to some youtube videos I saw). I can give another try with WineD3D.

**Comment by kust2708** [comment] 2020-05-10 10:49
So, Here is the result with WineD3D : 
![Screenshot_20200510_124651](https://user-images.githubusercontent.com/6338427/81497106-90db0080-92bc-11ea-85c1-85b14871f19f.png)

**Comment by doitsujin** [comment] 2020-05-10 12:49
i think wined3d suffers from more or less the same problem because GL wants you to bind multisampled textures as `GL_TEXTURE_2D_MULTISAMPLE` rather than `GL_TEXTURE_2D`, but doing that would obviously result in the same undefined behaviour that breaks DXVK.

But yeah I don't really see a sane way to work around this problem.

**Comment by iWeaker4you** [comment] 2020-11-17 16:25
I confirm it works on Intel iGPU and AMD GPU (Tested on Radeon RX 580 and RX5500) it is an NVIDIA issue.

**Closed** 2021-07-02 14:11 UTC
Labels: game bug
