### ISSUE TITLE
Add Direct3D 7 support

### ISSUE THREAD

**Issue by Sagatt** [doitsujin/dxvk#4199] opened 2024-08-09 19:23 UTC
Is that possible?

**Comment by Blisto91** [comment] 2024-08-09 19:55
Yes. But the devs have also stated they aren't interested in having anything like that merged in to this repository. So if  someone decides to make a go at d3d7 it will be a separate project.

**Comment by K0bin** [comment] 2024-08-09 20:21
Duplicate of #3234 and Blisto answered it.

**Closed by K0bin** 2024-08-09 20:21 UTC
Labels: question

**Comment by WinterSnowfall** [comment] 2024-08-09 20:51
> so if someone decides to make a go at d3d7 it will be a separate project.

Stop making me sneeze!
