### ISSUE TITLE
Mass Effect Legendary Edition: a line across the screen is visible on some materials when Ambient Occlusion is enabled

### ISSUE THREAD

**Issue by adolfintel** [doitsujin/dxvk#2592] opened 2022-04-07 12:39 UTC
In Mass Effect 1 Legendary Edition, a diagonal line going from the top left corner of the screen to the bottom right corner is visible on some materials when Ambient Occlusion is enabled. The line looks like a typical ambient occlusion shadow so it's visible enough to be annoying in movement but not enough to be very noticeable in screenshots.

Here's a magnified screenshot where  the problem can be seen:
![photo_2022-04-07_13-21-15](https://user-images.githubusercontent.com/16307689/162200154-c2823f04-a936-4a2b-b158-b12dddd31c42.jpg)

I wasn't able to solve this by reinstalling the game, with different versions of DXVK (including current master), or by changing any of the settings in the DXVK configuration file.

The only unusual thing I can see in the logs is this:
```
warn:  D3D11Query: Unknown interface query
warn:  9eb576dd-9f77-4d86-81aa-8bab5fe490e2
```

Video of the issue: [ME1-video.mkv](https://downloads.fdossena.com/issues/ME1-video.mkv)
Apitrace file: [ME1-trace.tar.zst](https://downloads.fdossena.com/issues/ME1-trace.tar.zst)
DXVK log files: 
[MassEffect1_d3d11.log](https://github.com/doitsujin/dxvk/files/8442686/MassEffect1_d3d11.log)
[MassEffect1_dxgi.log](https://github.com/doitsujin/dxvk/files/8442688/MassEffect1_dxgi.log)

### Software information
Mass Effect 1 Legendary Edition

### System information
- GPU: AMD Radeon RX 6900XT
- Driver: Mesa 21.3.7 (tested both RADV and AMDVLK)
- Wine version: [Wine-GE-Proton7-8](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-8)
- DXVK version: tested 1.8 through 1.10.1 incl. current master
- OS: Manjaro 21.2.5, KDE, Xorg, Kernel 5.16

**Comment by K0bin** [comment] 2022-04-07 12:41
Are you sure this is actually a DXVK problem rather than just a game bug?

**Comment by adolfintel** [comment] 2022-04-07 12:42
I don't see this line on Windows and I can't find anyone complaining about it online so I guess it's either DXVK or Mesa.

**Comment by adolfintel** [comment] 2022-04-07 12:47
Looks like the HBAO shader source file is present in the game files in the Engine/Shaders folder, maybe I can do something to it...

**Comment by adolfintel** [comment] 2022-04-07 13:22
Still present in Mesa 22.0.1 :(

![image](https://user-images.githubusercontent.com/16307689/162208724-12a00d76-7a29-4a2b-b7c9-85706f9c4684.png)

**Comment by doitsujin** [comment] 2022-04-07 14:02
Can't reproduce here. It also doesn't make much sense for this to happen since the AO texture itself is computed via a compute shader, and then blended onto a render target with regular linear filtering.

Do you have any options enabled to enforce anisotropic filtering or something?

**Comment by adolfintel** [comment] 2022-04-08 05:35
The problem still occurs with a clean install of the OS (tried both Xorg and Wayland just in case) but it works fine in Windows. WineD3D seems to be affected as well.

@doitsujin can you tell me how you're running the game? OS, screen resolution, etc.? The problem is not visible in every area of the game, I can give you a save file if you want.

**Comment by adolfintel** [comment] 2022-04-10 16:05
Quick update on this, I just tested this on two more PCs (i5 6400+R9 290x, i7 6700k+RX 5500XT) with the same results, the line is present on linux but not on windows.

Are you 100% sure that you don't have this problem on your 6900XT? What else can I try to analyze this problem?

**Comment by Blisto91** [comment] 2022-04-14 21:11
If you can share the save file i can try to see if i can reproduce it

**Comment by adolfintel** [comment] 2022-04-14 21:13
Sure! [BioWare.zip](https://github.com/doitsujin/dxvk/files/8492232/BioWare.zip)

Just load the last save in the citadel presidium and move around, you should see it.

**Comment by Blisto91** [comment] 2022-04-14 21:56
Ah yes i see it. Easier to see in that spot when you turn stuff like film grain off.
R9 380 mesa 22.0.1 and also on amdvlk 2021Q2.5 (latest i can use). The game or launcher crashes before it's starts when i try with WINED3D.

Didn't find that any dxvk conf options affected it.

**Comment by adolfintel** [comment] 2022-04-15 06:17
@Blisto91 you can bypass the launcher and launch the game directly with this command:
```
MassEffect1.exe -NoHomeDir -SeekFreePCConsole
```
The line is visible with WineD3D as well on my PC.

Can you confirm that it goes away if you set it to windowed mode instead of fullscreen?

**Comment by Blisto91** [comment] 2022-04-15 11:37
Ye can confirm windowed gets rid of the issue.

Still having some issues with WINED3D, but since you've confirmed it's also present there thats not so important.
I can try to launch the game on my nvidia setup when i have time, and if it can handle it. Only 2GB vram hehe.

**Comment by CME42** [comment] 2022-04-15 23:55
I can repro it on my 6900xt with both radv and amdvlk but not on my 1060, radv_disable_aniso_single_level=true doesn't help.

**Comment by Blisto91** [comment] 2022-04-20 13:48
Thanks for testing on Nvidia. My 960 was screaming in pain just attempting to boot it 😁 

I also tried various radv variables without a change.

**Comment by doitsujin** [comment] 2022-04-22 14:44
Figured out what's wrong, D3D and Vulkan use different rules for computing texture coordinates when sampling with `NEAREST` filtering, and since the game uses a fullscreen quad to apply the AO effect, one triangle has tiny interpolation errors that lead to sampling offsets.

Unfortunately this is pretty much impossible to fix on our end.

**Comment by Blisto91** [comment] 2022-04-22 15:12
Good work. Followed the Convo on discord. 😁
So mesa issue and cross fingers? 👀

**Comment by adolfintel** [comment] 2022-04-22 15:46
@doitsujin Thanks for investigating the issue.

Do you happen to know why I can't edit any of the .usf files? I want to try and modify the shaders to work around this issue but the game won't start if I change even a comment in those files.

**Comment by Herobrine24** [comment] 2022-10-21 09:49
> Do you happen to know why I can't edit any of the .usf files? I want to try and modify the shaders to work around this issue but the game won't start if I change even a comment in those files.

Legendary Edition does not come with a shader compiler. Thats why shaders arent editable.

**Comment by adolfintel** [comment] 2023-06-24 11:52
Just checked again, the issue is still present as of june 2023 on the latest mesa master, was this reported to mesa? I can't find it in their issues

**Comment by Blisto91** [comment] 2023-06-24 12:02
I don't believe so

**Comment by adolfintel** [comment] 2023-06-24 13:21
Ok, opened an issue on mesa gitlab: https://gitlab.freedesktop.org/mesa/mesa/-/issues/9253

**Comment by adolfintel** [comment] 2023-08-11 08:48
Still here :(

I'm willing to put a bounty on this issue if the project allows it, I'm tired of having to reboot into windows every time I want to play this game, and this issue likely affects other late UE3 games that use the same ambient occlusion shader.

**Comment by mbriar** [comment] 2023-08-11 11:57
I saw this issue mentioned [here](https://gitlab.freedesktop.org/mesa/mesa/-/issues/6395), have you tried the workaround posted there?

**Comment by adolfintel** [comment] 2023-08-11 12:36
@mbriar that seems to have fixed it. The code was moved to radv_sampler.c but once I found it and patched it, the line was gone and AO looks correct.

I'm not sure what the implications of this change are though, maybe one of you veterans can explain: if this was only enabled when using the nearest filter, I assume there's a reason for that, what could this break? how do coordinates get truncated?

**Comment by Blisto91** [comment] 2023-11-17 17:12
Fixed in mesa https://gitlab.freedesktop.org/mesa/mesa/-/commit/9e9eb87dd3a2ffe782ac85998a69623f59306caf

**Closed** 2023-11-17 18:09 UTC
Labels: d3d11
