### ISSUE TITLE
[d3d9] Medieval 2 Total War produces black lines on world map

### ISSUE THREAD

**Issue by Metalhead33** [doitsujin/dxvk#1669] opened 2020-06-16 23:39 UTC
The game produces weird lines at the map with DXVK.
**Examples:**
[https://cdn.discordapp.com/attachments/561359616135397396/722564654089371738/2020-06-16-231806-screenshot.jpg](https://cdn.discordapp.com/attachments/561359616135397396/722564654089371738/2020-06-16-231806-screenshot.jpg)
[https://cdn.discordapp.com/attachments/561359616135397396/722564654995603476/2020-06-16-231759-screenshot.jpg](https://cdn.discordapp.com/attachments/561359616135397396/722564654995603476/2020-06-16-231759-screenshot.jpg)
**How it is intended to look:**
[https://cdn.discordapp.com/attachments/561359616135397396/722564773933350982/2020-06-16-233053-screenshot.jpg](https://cdn.discordapp.com/attachments/561359616135397396/722564773933350982/2020-06-16-233053-screenshot.jpg)
[https://cdn.discordapp.com/attachments/561359616135397396/722564774839189504/2020-06-16-233050-screenshot.jpg](https://cdn.discordapp.com/attachments/561359616135397396/722564774839189504/2020-06-16-233050-screenshot.jpg)

### Game log:
[https://cdn.discordapp.com/attachments/461958894306983947/722595766941646899/m2tw.log](https://cdn.discordapp.com/attachments/461958894306983947/722595766941646899/m2tw.log)

### Software information
Medieval 2 Total War. 32-bit Direct3D9 game from 2006.

### System information
- GPU:x86_64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz GenuineIntel
- GPU: Nvidia GeForce GTX 960/PCIe/SSE2
- Driver: x11-drivers/nvidia-drivers-440.82-r3
- Wine version: Wine 5.10
- DXVK version: DXVK_170

### Apitrace file(s)
-Unfortunately, the game really doesn't want to be traced. It basically froze while I tried to trace it. I did manage to get an apitrace, but I did not get as far as the point where the bug happens.
[https://cdn.discordapp.com/attachments/461958894306983947/722593740367200326/m2tw.trace.tar.gz](https://cdn.discordapp.com/attachments/461958894306983947/722593740367200326/m2tw.trace.tar.gz)

### Log files
- [https://cdn.discordapp.com/attachments/461958894306983947/722593996567740506/medieval2_d3d9.log](https://cdn.discordapp.com/attachments/461958894306983947/722593996567740506/medieval2_d3d9.log)
- [https://cdn.discordapp.com/attachments/461958894306983947/722594215078527066/medieval2_dxgi.log](https://cdn.discordapp.com/attachments/461958894306983947/722594215078527066/medieval2_dxgi.log)

**Comment by tpurde** [comment] 2021-03-21 16:09
###Note
I transferred this report from #1985 because I couldn't check for duplicates properly. I'm having the same problem.

Medieval II: Total War with it's retail release on DVD has black lines on the campaign map. I have tested battles and haven't seen this issue. This also doesn't happen with WineD3D.

I have been using Lutris, as it really made installing a DVD game with Wine a lot easier. I hope that won't cause any problems for tackling this issue.

DXVK:
![unknown](https://user-images.githubusercontent.com/62025836/111910416-56142e00-8a72-11eb-8276-409de2b0b71d.png)

WineD3D (How it should look):
![Screenshot_20210321_181427](https://user-images.githubusercontent.com/62025836/111910435-64fae080-8a72-11eb-90a9-cad2e287231a.png)
### Software information
Medieval II: Total War (Tested both the main game and the expansion, I have logs for the expansion.)
Highest graphic settings, 1920x1080

### System information
- GPU: Nvidia GeForce GTX 1050Ti
- Driver: 460.67Medieval II: Total War with it's retail release on DVD has black lines on the campaign map. I have tested battles and haven't seen this issue. This also doesn't happen with WineD3D.

I have been using Lutris, as it really made installing a DVD game with Wine a lot easier. I hope that won't cause any problems for tackling this issue.

DXVK:
![unknown](https://user-images.githubusercontent.com/62025836/111910416-56142e00-8a72-11eb-8276-409de2b0b71d.png)

WineD3D (How it should look):
![Screenshot_20210321_181427](https://user-images.githubusercontent.com/62025836/111910435-64fae080-8a72-11eb-90a9-cad2e287231a.png)
### Software information
Medieval II: Total War (Tested both the main game and the expansion, I have logs for the expansion.)
Highest graphic settings, 1920x1080

### System information
- GPU: Nvidia GeForce GTX 1050Ti
- Driver: 460.67
- Wine version: lutris-5.7-11-x86_64 (The game needs .NET which can't be installed on newer Wine versions.)
- DXVK version: v1.7.3L-03f11ba on Lutris, tried with other, older versions and had no luck.

### Apitrace file(s)
I haven't had the chance to create apitrace files as of now, but I'll make sure to add them soon.

### Log files
- d3d9.log: [kingdoms_d3d9.log](https://github.com/doitsujin/dxvk/files/6177737/kingdoms_d3d9.log)
The dxgi.log is empty.


- Wine version: lutris-5.7-11-x86_64 (The game needs .NET which can't be installed on newer Wine versions.)
- DXVK version: v1.7.3L-03f11ba on Lutris, tried with other, older versions and had no luck.

### Apitrace file(s)
I haven't had the chance to create apitrace files as of now, but I'll make sure to add them soon.

### Log files
- d3d9.log: [kingdoms_d3d9.log](https://github.com/doitsujin/dxvk/files/6177737/kingdoms_d3d9.log)
The dxgi.log is empty.

**Comment by tpurde** [comment] 2021-03-21 18:16
Another bug to add is, Alt+Tabbing won't work at all. The game is always on top with DXVK, but WineD3D again works.

**Comment by K0bin** [comment] 2021-03-21 18:43
This is a known issue with DXVK but unlikely to be fixed.

**Comment by tpurde** [comment] 2021-03-21 18:44
I see. Thanks for the information.

**Comment by K0bin** [comment] 2021-03-21 18:45
The problem with Medieval 2 needs an apitrace so we can look into this.

**Comment by tpurde** [comment] 2021-03-21 18:46
> The problem with Medieval 2 needs an apitrace so we can look into this.

I'll try creating one now. The [wiki page](https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace) for it recommends using WineD3D but I can't reproduce the issue with it, so I'm supposed to use DXVK, right? Just making sure.

**Comment by K0bin** [comment] 2021-03-21 18:56
I doesnt matter whether you can reproduce the issue while making the trace. Either WineD3D or DXVK is fine.

**Comment by tpurde** [comment] 2021-03-21 18:58
Alright, I have created the file but it will take some time to upload as it is huge. (2.6GB)
I'll get back to you as soon as possible.

**Comment by tpurde** [comment] 2021-03-21 19:47
Hi, @K0bin 
Here is the trace file on Google Drive: https://drive.google.com/file/d/1p2b3bLJqcCRThXHU8yYuo2GtPi7aK6p9/view?usp=sharing

One other is that loading screens go fully black with DXVK. This is too insignificant, so I don't know if you'll even want to check it.

**Comment by K0bin** [comment] 2021-03-21 22:06
You forgot to change the access permissions on that file. I'm not allowed to download it.

**Comment by tpurde** [comment] 2021-03-21 22:37
Sorry, my bad. Should be fixed now. @K0bin

**Comment by tpurde** [comment] 2021-03-24 12:28
Hey @K0bin, excuse me for disturbing but have you had a chance to look at it?

**Comment by K0bin** [comment] 2021-03-24 12:29
No, not yet.

**Comment by tpurde** [comment] 2021-03-24 12:32
Alright then. Have a good day.

**Comment by K0bin** [comment] 2021-08-22 19:55
Putting this here so we don't forget about it:

@CME42 found out that the problem is caused by DXVK returning incorrect pitch values when locking a RGB8 D3DPOOL_SCRATCH texture. The problem is that RGB8 is not supported but we allow creating scratch textures for unsupported formats. We do however rely on a valid format mapping in various places like when locking an image.

**Closed** 2021-08-23 16:38 UTC
Labels: needs apitrace, d3d9
