### ISSUE TITLE
minor texture issue with fear

### ISSUE THREAD

**Issue by rakantoh** [doitsujin/dxvk#2841] opened 2022-08-20 21:42 UTC
With the fix of megaissue #1318, F.E.A.R. can run with dxvk (and with "dinput8.dll fix" for fps drop issue fix) very good, including hd textures without any problems and without apply or use "4GB patch fix", however, with dxvk, appears a little bug with the guns in the hands, appears a semi transparency in the guns. For now, is the only bug that i discovered; without "dinput8 fix", still with dxvk, the fps drops, but with "dinput8 fix", the fps drop are fixed.
![FEAR_2022_08_20_16_07_17_360](https://user-images.githubusercontent.com/59809634/185766904-03c14cc0-5dcb-4641-a14c-cd2b0d8083bc.jpg)
![FEAR_2022_08_20_16_07_24_976](https://user-images.githubusercontent.com/59809634/185766906-528ae1ba-4a8f-4619-bd28-82b911c3ad78.jpg)
![FEAR_2022_08_20_16_07_30_576](https://user-images.githubusercontent.com/59809634/185766907-f8fe5639-eedf-42fa-a8c5-39b7f9a0b913.jpg)
![FEAR_2022_08_20_16_07_36_708](https://user-images.githubusercontent.com/59809634/185766908-85eadab2-e06a-4b5d-ad0b-49c654b8fad0.jpg)
![FEAR_2022_08_20_16_07_43_575](https://user-images.githubusercontent.com/59809634/185766910-b8adb5f4-073a-4188-82c7-10b82932da4c.jpg)

**Comment by K0bin** [comment] 2022-08-20 21:44
Known issue. Duplicate of #1461

**Closed by K0bin** 2022-08-20 21:44 UTC
