### ISSUE TITLE
[d3d9] Flickering rectangles in Starcraft 2 when post-processing is set to ultra.

### ISSUE THREAD

**Issue by Venemo** [doitsujin/dxvk#2338] opened 2021-10-18 10:34 UTC
I use Lutris to play Starcraft 2. When post-processing is set to ultra, some strange flickering rectangles appear on the screen.

![Screenshot from 2021-10-18 12-20-37](https://user-images.githubusercontent.com/722813/137714573-76bc21e2-d8c4-4bd6-9669-02e267d710d4.png)

### Software information

* Fedora 34, Gnome 40.4, mesa 21.1.8
* Starcraft 2

### System information
- GPU: AMD RX 6900XT
- Driver: RADV (mesa 21.1.8)
- Wine version: lutris-fshack-6.14-4-x86_64
- DXVK version: 1.9.2L

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log: [SC2_x64_d3d9.log](https://github.com/doitsujin/dxvk/files/7364030/SC2_x64_d3d9.log)
- d3d11.log: N/A
- dxgi.log: [SC2_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/7364031/SC2_x64_dxgi.log)

**Comment by doitsujin** [comment] 2021-10-18 13:16
Does this happen with PR #2294 as well?

**Comment by Blisto91** [comment] 2022-06-11 20:21
The earliest radv driver i was able to get working was 21.2.5 (If i remember correctly) and i wasn't able to reproduce this. This was on a R9 380, dxvk 1.9.2 and with ultra/extreme graphics (also post processing). Unless a game update got rid of it or a driver update fixed it then it might be card/gen specific issue.

**Comment by Venemo** [comment] 2022-06-14 08:00
@Joshua-Ashton Can you confirm that the "good old sampling from render target issue" was solved? This was about `VK_VALVE_attachment_feedback_loop_layout` as far as I remember.

**Comment by Venemo** [comment] 2022-06-14 08:01
Or maybe the reworked float emulation has fixed this?

**Comment by DadSchoorse** [comment] 2022-06-14 21:18
Yes this is about feedback loops. It's only an issue in practice on GFX10+(rdna/rdna2) because dxvk's current feedback hazard detection uses VK_IMAGE_LAYOUT_GENERAL, which causes dcc decompression on older gpus. So it makes sense that @Blisto91 can't reproduce the issue on GFX8.

**Comment by doitsujin** [comment] 2022-08-08 12:04
Should be fixed with `attachment_feedback_loop_layout`.

**Closed as completed by doitsujin** 2022-08-08 12:04 UTC
Labels: d3d9
