### ISSUE TITLE
[d3d9] [GTA IV] Can't set the game to Full HD on a 3080Ti

### ISSUE THREAD

**Issue by CordY5** [doitsujin/dxvk#2098] opened 2021-06-14 08:10 UTC
Upgraded from a 960 to a 3080Ti, the maximum resolution allowed by the game when running with dxvk (does not happen when  running without dxvk) is 1152x864 (85Hz)

![image](https://user-images.githubusercontent.com/31861401/121859558-1e76f400-ccf8-11eb-9359-5c9720f382cb.png)

This issue did not happen when running the game on a GTX 960.

### Software information
GTAIV 1.0.7.0

Running with the following `commandline.txt`:

```
-norestrictions
-nomemrestrict
-managed
-reservedApp 0
```

### System information
- GPU: RTX 3080Ti
- Driver: 466.77
- Wine version: N/A
- DXVK version: 1.8.1

### Apitrace file(s)
- Could not reproduce while recording the apitrace, but feel free to ask if this file is needed.

### Log files
- [d3d9.log](https://mega.nz/file/zl4h1C5J#I5To0Vves82_GeR9OvsQ-guVT32vCN3DMeWfWmJHf6I)

**Comment by K0bin** [comment] 2021-06-14 09:22
Duplicate of #1831

**Closed by K0bin** 2021-06-14 09:22 UTC
