### ISSUE TITLE
Rendering issues with Saints Row Franchise

### ISSUE THREAD

**Issue by XenonPK** [doitsujin/dxvk#24] opened 2018-01-21 15:13 UTC
The game boots normally, the menus are rendered without issues, however upon loading, only the HUD is rendered correctly, on a black background. (Using latest master)

### Software information
Saints Row IV (also happens with Saints Row The Third). Confirmed regardless of settings, went from high+4xmsaa to low+noaa, with the same results.

### System information
- Distro: openSUSE Tumbleweed
- GPU: RX 560
- Driver: Mesa 17.3.2
- Wine version: wine-staging-2.20

### Apitrace file(s)
- Unfortunately, apitrace crashes before it can do anything, here is the wine output: [apitrace_fail.log](https://github.com/doitsujin/dxvk/files/1650043/apitrace_fail.log)
- Wine debugger output: [wine_apitrace_output.log](https://github.com/doitsujin/dxvk/files/1650046/wine_apitrace_output.txt)

### Log files
- d3d11.log: [d3d11.log](https://github.com/doitsujin/dxvk/files/1649839/d3d11.log)

- dxgi.log: [dxgi.log](https://github.com/doitsujin/dxvk/files/1649840/dxgi.log)

**Comment by XenonPK** [comment] 2018-01-21 18:36
It fails right after this:
```
warn:  DxgiSwapChain: Display mode changes not implemented
warn:  DxgiFactory::MakeWindowAssociation: Ignoring flags
fixme:driver:D3DKMTOpenAdapterFromHdc (0x33ee44): stub
```

**Comment by doitsujin** [comment] 2018-01-22 13:48
Please run apitrace *without* DXVK. If you can, it would be best to run it on Windows, but Wine with their OpenGL backend may work as well. I edited the issue template accordingly to make this clear.

The log shows a few features that are still missing, which is likely the reason why the game doesn't render anything.

**Comment by skry** [comment] 2018-02-06 02:33
Apitrace run on Windows [here](https://mega.nz/#!tVEHiBzS!-Y-YiqXk9OZaquzxMsIWdf1NmtydY_N0Xf6KItvOf4w).

**Comment by XenonPK** [comment] 2018-02-06 12:37
I have an update on this issue, after updating to latest master and Mesa 18.0, here are the results:

![saints row iii](https://user-images.githubusercontent.com/8293194/35859956-16205aa4-0b3a-11e8-8d2b-3949c2bc4a33.png)
![saints row iv](https://user-images.githubusercontent.com/8293194/35860008-3d07ed58-0b3a-11e8-8770-a6f8a69ae6e5.png)
![saints row goh](https://user-images.githubusercontent.com/8293194/35860017-43fb80de-0b3a-11e8-9956-63c8752a116f.png)

And It seems The Witcher 3 started rendering something too:

![witcher3_1](https://user-images.githubusercontent.com/8293194/35860033-5ef98d40-0b3a-11e8-976e-1edcd990cead.png)
![witcher3_2](https://user-images.githubusercontent.com/8293194/35860036-60e2f600-0b3a-11e8-968c-67f4a20d8af6.png)
![witcher3_3](https://user-images.githubusercontent.com/8293194/35860038-633248ac-0b3a-11e8-9f54-99bc032f671f.png)
![witcher3_4](https://user-images.githubusercontent.com/8293194/35860040-653f2f7a-0b3a-11e8-98f0-960cb440f5e3.png)

**Comment by doitsujin** [comment] 2018-02-19 22:03
Since an apitrace could not be provided, can someone please test this again with a recent DXVK build? The missing features mentioned in the log files have been implemented.

**Comment by ZeroFault** [comment] 2018-02-20 08:46
@doitsujin 
Saint's row 4 crashes after loading a saved game.

OS: Native Windows
Nvidia GTX 1080 ( driver 390.77)

[SaintsRowIV_d3d11.log](https://github.com/doitsujin/dxvk/files/1739388/SaintsRowIV_d3d11.log)
[SaintsRowIV_dxgi.log](https://github.com/doitsujin/dxvk/files/1739389/SaintsRowIV_dxgi.log)
[vulkanlog.txt](https://github.com/doitsujin/dxvk/files/1739390/vulkanlog.txt)

There were a large a large amount of errors in the vulkan debug output.

[saintsrow4.trace](https://drive.google.com/open?id=16081PJufyVcd0jmEKKNaLFNkrXrPrPmk)

Please excuse  the stuttery apitrace. For some reason  the apitrace was making saints row run like a slideshow and took a while to generate.

**Comment by doitsujin** [comment] 2018-02-20 09:43
I'll look into it, looks like there is a bug with resource tracking somewhere.

> For some reason the apitrace was making saints row run like a slideshow and took a while to generate.

That's normal, doesn't matter though.

**Comment by ZeroFault** [comment] 2018-03-28 20:51
I am providing an updated apitrace for Saint's Row IV. This one removes the intro videos since they were really slow to replay in a trace.

[saintsrowIV.trace](https://mega.nz/#!aCBVXThD!gWPBCrbNpsmD95TPL6jerjPzBale_Sg1XEg3UrcRacs)

**Comment by mandruis** [comment] 2018-06-17 20:58
Saint's Row IV is working like a charm in RADV the only failure is that doesn't charges with the right resolution 
Tested with mesa-git and dxvk master f519a0f .

**Comment by doitsujin** [comment] 2018-07-20 09:56
Closing since this appears to be fixed.

**Comment by pchome** [comment] 2019-06-01 18:41
### Saints Row The Third
Several regressions (`master` vs `DXVK-0.81`):
1. transparent textures (almost nothing rendered)
2. black(grey) patches on the ground (depend on view/position)

**For (2.)** I don't remember such issue when last checked (near 0.81 version, according to dxvk log files). Present in both dx9 (D9VK) and dx11(DXVK) versions, same as flickering faces(which was the issue in 0.81). Renders fine in wined3d mode (w/o any issues but slower). Likely Nvidia driver changes (430.14 and 418.52.07 was tested).

Apitraces still not producible on linux, none of provided saintsrowIV.trace files available to check (3 and IV usually has common issues).

**For (1.)** 
https://github.com/doitsujin/dxvk/commit/6eeb3b6da9ec9359318a7fd2786e6d8cc5c4878e
https://github.com/doitsujin/dxvk/commit/53aa27336bb6ee3b04f38a4e7d60016c7a4785fa

following patch fixes the issue
```patch
diff --git a/src/dxvk/dxvk_util.h b/src/dxvk/dxvk_util.h
index 86bb44e9..dcb853b6 100644
--- a/src/dxvk/dxvk_util.h
+++ b/src/dxvk/dxvk_util.h
@@ -182,8 +182,8 @@ namespace dxvk::util {
    * \returns \c true if the depth aspect for images in this layout is read-only.
    */
   inline bool isDepthReadOnlyLayout(VkImageLayout layout) {
-    return layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL
-        || layout == VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL;
+    return layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL;
+        //|| layout == VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL;
   }
   
   /**
```

`standard_validation` layer fails almost instantly after start (for both master and patched), but OK for 0.81, so here the both logs:
[SR3-1.2.1-patched.log](https://github.com/doitsujin/dxvk/files/3244095/SR3-1.2.1-patched.log)
[SR3-0.81.log](https://github.com/doitsujin/dxvk/files/3244096/SR3-0.81.log)

**Comment by doitsujin** [comment] 2019-06-01 19:08
That patch is incorrect and would only breaks a workaround for a game bug in Spellforce 3.

Use the native Linux version instead.

**Closed by doitsujin** 2019-06-01 19:08 UTC
Labels: d3d11, needs apitrace

**Comment by pchome** [comment] 2019-06-01 19:37
> That patch is incorrect ...

I don't saying it's correct, otherwise could PR it. 

> Also it would be nice if you could post the validation output for the UNPATCHED 1.2.1/master.

Output exactly the same, both crashing with validation enabled. Anyway : [SR3-1.2.1-master.log](https://github.com/doitsujin/dxvk/files/3244142/SR3-1.2.1-master.log)

> Thank you for spending your time ...

Nevermind.
