### ISSUE TITLE
Corruptions in the Witcher 3 when vignetting is enabled

### ISSUE THREAD

**Issue by shmerl** [doitsujin/dxvk#1600] opened 2020-04-28 01:06 UTC
I noticed, that in The Witcher 3 I'm getting some rectangular graphical corruptions in the [second world](https://witcher.gamepedia.com/File:Tw3_2nd_world_2.jpg) of [Through Time and Space](https://witcher.gamepedia.com/Through_Time_and_Space). Disabling vignetting removes the corruptions.

![tw3_corruption](https://user-images.githubusercontent.com/310927/80435264-0d87db00-88ca-11ea-9b9c-480db51a665b.jpg)

Here is the save of that location: [tw3_save.tar.xz.zip](https://github.com/doitsujin/dxvk/files/4542821/tw3_save.tar.xz.zip)

Note: all attached files are really tar.xz, but with added .zip to allow Github attaching.

### Software information
The Witcher 3 GOTY, max settings, ambient occlusion: HBAO+, hairworks disabled, depth of field disabled.

### System information
- GPU: AMD Sapphire Pulse RX 5700 XT
- Kernel / amdgpu: 5.6.7
- Driver: radv/aco, Mesa 20.1.0-devel (git-9bc5b2d169) (NAVI10, DRM 3.36.0, 5.6.7, LLVM 11.0.0)
- Wine version: 5.7 + esync patches
- DXVK version: 1.6.1-6-6d5f5580

Corruption happens regardless of using aco or llvm.

### Apitrace file(s)
Renderdoc frame: https://ufile.io/8aej0kbz

### Log files
[dxvk_logs.tar.xz.zip](https://github.com/doitsujin/dxvk/files/4542820/dxvk_logs.tar.xz.zip)

If it's really a Mesa issue, I can open upstream bug.

**Comment by doitsujin** [comment] 2020-04-28 01:16
You sure this isn't a driver bug?

**Comment by doitsujin** [comment] 2020-04-28 01:19
Works fine on my Polaris.
![Bildschirmfoto-1276](https://user-images.githubusercontent.com/25567304/80436300-1cd54b80-88ff-11ea-8b78-bae25ee830db.png)

**Comment by shmerl** [comment] 2020-04-28 01:22
It could be a driver bug, but interestingly it's not specific to aco or llvm - happens in both. May be amdgpu bug then? I can report it to Mesa/radv first.

**Comment by doitsujin** [comment] 2020-04-28 01:23
Not all driver issues are necessarily compiler-related, could just be a general problem with RADV+Navi.

**Comment by doitsujin** [comment] 2020-04-28 01:28
Does AMDVLK render coreectly?

**Comment by shmerl** [comment] 2020-04-28 01:33
Opened Mesa bug [here](https://gitlab.freedesktop.org/mesa/mesa/issues/2852).

**Comment by shmerl** [comment] 2020-04-28 01:33
Let me try amdvlk, I haven't built it in a long time.

**Comment by shmerl** [comment] 2020-04-28 01:59
amdvlk renders fine:

![tw3_amdvlk](https://user-images.githubusercontent.com/310927/80438539-6c515280-88d2-11ea-8eb6-f5520525122b.jpg)

**Comment by shmerl** [comment] 2020-04-28 06:03
Interesting, if I load an older save and then load that save, the corruption goes away.

**Comment by doitsujin** [comment] 2020-10-15 15:38
Closing since nobody seems to be able to reproduce this.

**Closed by doitsujin** 2020-10-15 15:38 UTC
Labels: amd radv, can't reproduce
