### ISSUE TITLE
DXVK in the game mass effect andromeda renders correctly on RX480 but BAD on VEGA

### ISSUE THREAD

**Issue by giovannilaura** [doitsujin/dxvk#439] opened 2018-06-14 17:17 UTC
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
mass effect andromeda low settings

### System information
- GPU: AMD VEGA
- Driver:Mesa GIT 14.06.18
- Wine version: 3.-10 Staging
- DXVK version: GIT 14.06.18

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log: 
[STARTJOE.ExE_d3d11.log](https://github.com/doitsujin/dxvk/files/2103325/STARTJOE.ExE_d3d11.log)
![andro_rx480](https://user-images.githubusercontent.com/25445576/41427418-2c69a9aa-7007-11e8-821a-12565520afdb.png)
![andro_vega](https://user-images.githubusercontent.com/25445576/41427425-34f92c3a-7007-11e8-8ddb-fea6debd809c.png)

[winelog.txt](https://github.com/doitsujin/dxvk/files/2103326/winelog.txt)
I noticed that the pipeline generates some shaders wich are without filename vs: instead of vs.: xxxxxxx
in the wine log
all shaders are validated though

**Comment by jarrard** [comment] 2018-06-20 21:57
Load up windows and do a apitrace that way. 
I could do it for you however I have a 1080ti which might not be the best comparison. 

apitrace often gives you very low framerate (sometimes 1fps) so it can be a trial at times.

**Comment by giovannilaura** [comment] 2018-06-22 18:40
i could make an apitrace on win7 with a rx480 is this useful?

**Comment by doitsujin** [comment] 2018-06-22 18:42
Sure.

**Comment by giovannilaura** [comment] 2018-06-22 20:15
here the apitrace
use cat part1ofmazip part20fmazip > ma.zip
unzip ma.zip
sorry but the file is very large more than 14 gb
here the firedrop links
http://frd.li/1925dd8cc6109b7741d0ad6389a316dc
http://frd.li/4b58ec13f649fbc1c15156031932745b

**Comment by jarrard** [comment] 2018-06-22 20:38
I found 7zip ultra compression to work well traces,

**Comment by doitsujin** [comment] 2018-06-22 20:47
I'm getting an error that the second file is encrypted.

In general I wouldn't mind if you could upload it to a hoster that isn't straight-up scam. Mega or Google Drive should work.

Compressing trace files with 7z should reduce the file size considerably as well.

**Comment by giovannilaura** [comment] 2018-06-22 22:07
in fact it is a zipfile split in 2 parts but any one of the two parts is not a a zip you must cat the two parts to asingle file with the zip extension and then unzip this file did you do so? i used split on a large zipfile btw the 7z file is 8.6 gb long wich is to much for firedrop if you cannot get the trace i will find to stop it before and see if i can go under 8GB 7zipped

**Comment by giovannilaura** [comment] 2018-06-22 22:08
firedrop is no good?

**Comment by doitsujin** [comment] 2018-06-22 22:20
@giovannilaura my point is that I cannot even download the second part of the zip because the website says it's encrypted. In general that site seems to be quite shady.

**Comment by giovannilaura** [comment] 2018-06-22 23:48
sorry did not know will upload shortly to google drive

**Comment by giovannilaura** [comment] 2018-06-23 03:11
link of trace in 7z format for trace
https://drive.google.com/open?id=13_RUcB1853FXkdeofBJoD0fA_5nQtkhM

**Comment by giovannilaura** [comment] 2018-06-23 07:41
Sorry for the firedrop try i was not aware of the limitations and did not really understand what was wrong hope with googledrive you can download the trace

**Comment by hakzsam** [comment] 2018-08-21 08:01
Like I said here https://bugs.freedesktop.org/show_bug.cgi?id=106958 , the apitrace is corrupted and can't be replayed correctly. Can you try to record a new trace using renderdoc instead? I don't have that game so I can't do anything without being able to reproduce the problem. Thanks!

**Comment by egon2003** [comment] 2018-11-17 13:56
I have the same problem on my Vega 64. Mesa 18.3.0-rc3

I made an apitrace in Windows but I'm not sure if it works since I dont know how to replay it.
When I try to replay it in Linux I get error: failed to execute: d3dretrace.exe

Please let me know if the trace does not work and how I could provide a working trace.

[https://www.dropbox.com/s/jf8m9banx2nufxo/MassEffectAndromeda.7z?dl=0](url)

**Comment by egon2003** [comment] 2018-11-17 14:54
Realized I had to run it under wine but wine crashes for me before i reach where the glitches are.

**Comment by hakzsam** [comment] 2018-12-05 08:46
The problem is fixed with LLVM 8 (master).
See https://bugs.freedesktop.org/show_bug.cgi?id=106958 for more information about the issue.
Thanks for the report!

**Closed** 2018-12-05 08:54 UTC
Labels: amd radv, bug
