### ISSUE TITLE
Earth Defense Force 5: Stutter with vsync enabled

### ISSUE THREAD

**Issue by junglerobba** [doitsujin/dxvk#2128] opened 2021-06-28 04:32 UTC
### Software information
Earth Defense Force 5

### System information
- GPU: RX 5700XT
- Driver: Mesa 21.1.1
- Wine version:  Proton experimental-6.3.-20210625
- DXVK version: 1.9

### Apitrace file(s)
- https://drive.google.com/file/d/1ZbXVJJwd1I_jNG8ya8WneEWV_qYQdGI3/view?usp=sharing

### Log files
- d3d9.log: [EDF5_d3d9.log](https://github.com/doitsujin/dxvk/files/6723377/EDF5_d3d9.log)
- d3d11.log: [EDF5_d3d11.log](https://github.com/doitsujin/dxvk/files/6723374/EDF5_d3d11.log)
- dxgi.log: [EDF5_dxgi.log](https://github.com/doitsujin/dxvk/files/6723372/EDF5_dxgi.log)

Transferring over from https://github.com/doitsujin/dxvk/pull/2127, as described there the game shows heavy stuttering while vsync is enabled. Couldn't get the game to load into a mission while running apitrace but since the issue is already visible on the main menu I hope that is enough.

**Comment by doitsujin** [comment] 2021-06-28 15:37
Game bug, it does indeed toggle vsync on and off between presents, which unfortunately is a high-overhead operation because we have to recreate the Vulkan swap chain. I cannot reproduce the problem on my system, but your trace 
and d3d11.log prove it.

Does `dxgi.syncInterval = 1` fix the problem for you? #2127 switches it off unconditionally but I'd rather turn it on by default since a) this is what the game clearly intends to do, and b) turning it off would cause horrendous tearing on 60 Hz displays.

**Comment by junglerobba** [comment] 2021-06-28 16:03
Yes, working just fine with those options :+1: (only tested on sway though)

**Comment by doitsujin** [comment] 2021-06-28 16:05
I don't thing Wayland supports `FIFO_RELAXED`, can you give it a quick test on X11?

Feel free to update your PR afterwards with those options.

**Comment by junglerobba** [comment] 2021-06-28 16:10
I don't really use Xorg anymore so I'm not sure if it's even set up correctly, but it seems fine on Plasma.

**Comment by doitsujin** [comment] 2021-06-28 16:30
Thanks, merged new PR.

**Closed by doitsujin** 2021-06-28 16:30 UTC
