### ISSUE TITLE
Shared resources for FiveM

### ISSUE THREAD

**Issue by nemgamboioeee** [doitsujin/dxvk#1896] opened 2021-01-14 17:16 UTC
im not sure does this mean that wine has external memory support but yeah

https://wiki.winehq.org/Wine_Features
External memory checker support using Valgrind

referring to
https://github.com/doitsujin/dxvk/issues/899

also if you want you can add me on discord since im more active there: NemGamBoi#5863

**Comment by K0bin** [comment] 2021-01-14 17:21
Duplicate of #1723, #1722, #1033, #899, 836

**Comment by nemgamboioeee** [comment] 2021-01-14 17:28
"It is not possible to implement this in any useful way without support for external memory, and Wine does not support that"
-doitsujin
what about this: https://www.phoronix.com/scan.php?page=news_item&px=Wine-Vulkan-Shared-Resources ?

**Comment by K0bin** [comment] 2021-01-14 17:30
As far as I remember, that didnt really work properly and was more of a RFC. Either way, it didnt go anywhere.

**Comment by doitsujin** [comment] 2021-01-14 17:36
What @K0bin said. There's no work being done on it as far as I'm aware and Valgrind is a debugging tool.

**Closed by doitsujin** 2021-01-14 17:36 UTC

**Comment by nemgamboioeee** [comment] 2021-01-14 18:02
alright thanks for responding
