### ISSUE TITLE
[DX9] Race Driver: GRID - game and menu are black and bloomy

### ISSUE THREAD

**Issue by ManoaNosea** [doitsujin/dxvk#1493] opened 2020-03-03 10:54 UTC
### System information
- GPU: 780Ti
- Driver: 440.58.02
- Wine version: compiled Proton 5.0-3 on Wine 5.2
- DXVK version: 1.5.5

[trace](http://manoa.dream.org.il/Data/GRID_NoNet_4GB.trace.xz)

### Log files
I don't see him, whare it's ?

it working grate in GL no problems, I would test also nine but I don't have that at the moment :x

**Comment by ManoaNosea** [comment] 2020-03-03 11:44
I notice quite a few games on the list of problems they are mostly DX9, I diden't know DX9 is so hard to do, looks like it harder than DX11 :x

**Comment by Joshua-Ashton** [comment] 2020-03-03 15:36
The game works fine on my end with DXVK on Windows.

Could always be a d3dx9 problem.

**Comment by ManoaNosea** [comment] 2020-03-03 15:40
I have the direx installed in the prefix :x

**Comment by ManoaNosea** [comment] 2020-03-03 15:41
and the vc runtimes

**Comment by Joshua-Ashton** [comment] 2020-03-03 15:46
Works fine for me on NVIDIA too.

**Comment by ManoaNosea** [comment] 2020-03-03 15:54
it's funny but other DX9 games are working grate :) like left 4 dead 2, only GRID the problem :x

**Comment by ManoaNosea** [comment] 2020-03-03 15:56
could it be enabled anti aliasing in the game ? I will test this now...

**Comment by Tk-Glitch** [comment] 2020-03-03 15:56
The game needs LAA to run correctly. So `PROTON_FORCE_LARGE_ADDRESS_AWARE=1 %command%` in launch options. Also there's a quirk I can't remember with openal to get working sound.

If it persists, I would try with a different graphics driver? 440.58.02 is known to be dodgy for many users, so I'd give 440.48.02 a try instead (or 440.59 - I haven't had *good* feedback about 440.64 yet).

**Comment by ManoaNosea** [comment] 2020-03-03 16:04
no change with disabled AA :x
[this what I see](http://manoa.dream.org.il/Pics/grid/GRID.png)

**Comment by ManoaNosea** [comment] 2020-03-03 16:06
nvidea still haven't fixed the VK problems ? but they say on they site that it pass conformance tests... :x

**Comment by Joshua-Ashton** [comment] 2020-03-03 16:07
Conformance tests don't cover everything

**Comment by WinterSnowfall** [comment] 2020-03-03 16:14
It does need LAA, indeed, but otherwise it looks good to me on 440.59, Wine Staging 5.3.

![grid_menu](https://user-images.githubusercontent.com/6306593/75795230-adb5fd80-5d7a-11ea-873b-d8ce023e3e8b.jpg)

**Comment by ManoaNosea** [comment] 2020-03-03 16:24
yhe it look like a problem in nvidea VK 1.2 :x
they need more time development this :x
true is not long ago I was running nvidea driver with VK 1.1 I decide to update becuase I thought DXVK is latest technology so must be using latest functions of VK 1.2, mybe even give more performance :)

**Comment by ManoaNosea** [comment] 2020-03-23 03:35
I retested with 440.64 it have a similar problem: this time the screen is not glowing only all black except the "select" thing

**Comment by Joshua-Ashton** [comment] 2020-03-23 04:06
Renders fine for me on 442.47

**Comment by Joshua-Ashton** [comment] 2020-03-23 04:09
Can you make sure to install native d3dcompiler and d3dx9

**Comment by WinterSnowfall** [comment] 2020-03-23 09:07
I'm on 440.64 now and it still looks fine (with native d3dcompiler & d3dx9)

**Comment by ManoaNosea** [comment] 2020-03-23 09:56
yes I did install the direX

**Comment by ManoaNosea** [comment] 2020-03-23 10:09
I think it worth to mention the reaction of the game to the drivers: thare is a change between the drivers: black and glowing black, I see people have no problems, could this be a thing with the card iteself ? the 780 Ti ? I meen like a hardware problem ? mybe it terms of vulkan extension suported ?

**Comment by ManoaNosea** [comment] 2020-03-23 10:14
LAA is enable, too

**Comment by ManoaNosea** [comment] 2020-03-23 10:28
how do you set d3dcompiler & d3dx9 ? install direX not enough ?

**Comment by WinterSnowfall** [comment] 2020-03-23 10:56
> how do you set d3dcompiler & d3dx9 ? install direX not enough ?

Installing DirectX redistributables is not enough in Wine, as games will keep using the builtin Wine dlls unless overrides are configured.

The easiest way to get it done is by using winetricks. Run winetricks, then **Select the default wineprefix** -> **Install a Windows dll or component** -> tick the appropriate ones (as shown below), click **OK** and winetricks will set everything up for you.

![winetricks](https://user-images.githubusercontent.com/6306593/77309618-a2b11600-6d05-11ea-83a9-e0a992e872ae.jpg)

**Comment by ManoaNosea** [comment] 2020-03-24 03:14
I did this, diden't helped :x also added the vc runtimes into the winetricks
it's now like in the picture I sent before, glowing on black background :x

**Comment by ManoaNosea** [comment] 2020-03-24 06:36
I also started a new prefix with all the winetricks and 1.6, same problem :x

**Comment by Joshua-Ashton** [comment] 2020-03-24 14:37
Works for me 🤷‍♀️

**Comment by WinterSnowfall** [comment] 2020-03-24 19:23
![grid_440_64](https://user-images.githubusercontent.com/6306593/77467661-142bba00-6e15-11ea-8f5f-e3eb3acb989c.jpg)

@ManoaNosea I'm not sure what the problem is in your case, but it doesn't seem to be an issue with DXVK.

**Comment by jrugia** [comment] 2020-03-26 00:26
@ManoaNosea can you please provide a screenshot (or photo with phone) of the issue.

As like all the others, it works fine for me and I play this game daily.

Tested GPUs -
 GTX 1060, RTX 2060S (various drivers)
 RX5500 XT (Mesa 19.3.x and 20.0.x)

**Comment by ManoaNosea** [comment] 2020-03-26 12:06
[this what I see](http://manoa.dream.org.il/Pics/grid/GRID.png)

**Comment by guihkx** [comment] 2020-03-27 06:41
I wanted to test this too, since I own the game on Steam and I have an (old) GPU from NVIDIA.

I installed the game normally via Steam and ran it using Proton 5.0-5, with no extra launch options except `DXVK_HUD=full`.

The main menu is rendering correctly, as far as I can tell:

![20200327032803_1](https://user-images.githubusercontent.com/626206/77728684-c57c4c80-6fdb-11ea-86cc-410d6c4a554b.jpg)

Here are the graphic settings (they're defaults):

<details>
 <summary>4 images (click to expand)</summary>

![20200327032816_1](https://user-images.githubusercontent.com/626206/77728872-36bbff80-6fdc-11ea-9057-568b4dc5b110.jpg)

![20200327032825_1](https://user-images.githubusercontent.com/626206/77728879-391e5980-6fdc-11ea-84cd-60b6aa3b0e3e.jpg)

![20200327032832_1](https://user-images.githubusercontent.com/626206/77728889-3c194a00-6fdc-11ea-8480-13acadc9447e.jpg)

![20200327032837_1](https://user-images.githubusercontent.com/626206/77728902-40456780-6fdc-11ea-81c2-2d05e4d21ee5.jpg)
</details>

I played one race and finished it without any issues as well.

**Comment by guihkx** [comment] 2020-03-27 07:38
Hmm, I just realize there's actually a small rendering issue when DXVK is enabled. And it's definitely related to DXVK because it's reproducible on Windows as well, but it doesn't happen with native D3D9.

The navigation bar (is that what it's called?), below the main menu, renders differently with DXVK.

Native D3D9 (on Windows):

![Race Driver Grid Screenshot 2020 03 27 - 04 34 18 17](https://user-images.githubusercontent.com/626206/77732840-8272a700-6fe4-11ea-8ecd-799d18700763.png)

DXVK 1.6 (also on Windows):

![Race Driver Grid Screenshot 2020 03 27 - 04 28 34 95](https://user-images.githubusercontent.com/626206/77732870-928a8680-6fe4-11ea-9fe2-47a3a581a215.png)

**Comment by WinterSnowfall** [comment] 2020-03-27 11:33
> Hmm, I just realized there's actually a small rendering issue when DXVK is enabled.

Nice catch. I can confirm that the pop-up menus at the bottom of the screen are solid black with WineD3D as well, while transparent with DXVK.

**Comment by Iglu47** [comment] 2020-03-30 11:37
@ManoaNosea what language do you use in game? 
maybe this instriction can help:
https://www.pcgamingwiki.com/wiki/Race_Driver:_Grid#Fixing_Menu_Text_Glitch

**Comment by WinterSnowfall** [comment] 2020-03-30 13:13
@Iglu47 I'm using (standard) English and I see it. In any case, simply toggling between DXVK and WineD3D changes the behaviour as shown by @guihkx , so it's not an issue with the game.

**Comment by Joshua-Ashton** [comment] 2020-04-05 06:39
This should be fixed now.

**Comment by guihkx** [comment] 2020-04-05 08:45
Confirming it's fixed:

![20200405054151_1](https://user-images.githubusercontent.com/626206/78470521-a2028180-7700-11ea-830d-442c7c9b6535.jpg)

Thank you ❤️

**Closed** 2020-04-06 06:53 UTC
Labels: can't reproduce, d3d9, nvidia

**Comment by ManoaNosea** [comment] 2020-04-21 10:33
the problem is fixed in 1.6.1 :)))
thank :)) you win 10,000 internets !!!11
it's time to smoke them...
