### ISSUE TITLE
Yakuza 0 fullscreen crash and crash after intro video

### ISSUE THREAD

**Issue by thirdeyefunction** [doitsujin/dxvk#533] opened 2018-08-05 02:59 UTC
So there are two issues with Yakuza 0 under DXVK, which I'll split out to separate bug reports if needed.

Firstly, fullscreen and borderless mode are broken with DXVK and this game, while windowed + virtual desktop works. The game will immediately crash if launched with fullscreen or borderless, or switched to after the game is running.
The bug does not affect vanilla Wine. The bug does also affect native Windows + DXVK (but not Windows without DXVK).

Secondly, with DXVK + Wine and windowed + virtual desktop mode, the game will crash after the intro video. The bug does not affect vanilla wine, and it does **not** affect native Windows + DXVK. So the issue only affects Wine + DXVK, specifically.

I've attached an apitrace for native Windows (I could not successfully generate an apitrace with vanilla wine). 
I also couldn't replay the trace with Linux apitrace (I'm not sure if windows apitrace is required), but it appears to have worked. DXVK traces do work so if that is useful in addition, I can also supply an apitrace for that.

### Software information
Yakuza 0, windowed mode, then switched to fullscreen at the end of the trace

### System information
- GPU: Nvidia 980ti (also affects RX 550 + radv)
- Driver: 396.24.10
- Wine version: wine-staging-3.13
- DXVK version: 0.64

### Apitrace file(s)
- [Native windows trace](https://ufile.io/7axj4)

### Log files
- d3d11.log: 
[Windowed mode](https://pastebin.com/0eqr5atb) (both fullscreen and windowed were the same here)

- dxgi.log:
[Windowed mode](https://pastebin.com/YcNH7EZh)
[Fullscreen mode](https://pastebin.com/b3SZ6RMX)

**Comment by doitsujin** [comment] 2018-08-05 11:02
While I can't reproduce the crash after the intro video with the apitrace, the game seems to heavily rely on DXGI's internal COM reference counting behaviour which seems to be causing the issues when using DXVK.

I'll try to figure something out, but this is going to be incredibly hard to figure out. Not sure if I can fix this at all.

**Comment by doitsujin** [comment] 2018-08-05 12:03
The following patch should fix the crash after the intro video. This is semi-related to #302 with some additional issues mixed in.
[dxvk-ref-hack.patch.txt](https://github.com/doitsujin/dxvk/files/2260285/dxvk-ref-hack.patch.txt)

Please keep in mind that this is **not** a proper fix and may break other games. This also will not affect any fullscreen-related issues.

**Comment by Lahvuun** [comment] 2018-08-05 12:18
With this patch the game runs as expected in windowed mode.

**Comment by doitsujin** [comment] 2018-08-05 13:12
This patch adds another hack to allow the game to start in fullscreen mode. Note that this *includes* the previous patch, so if you have that applied, run `git reset --hard`.

[dxvk-yakuza0-hacks.patch.txt](https://github.com/doitsujin/dxvk/files/2260341/dxvk-yakuza0-hacks.patch.txt)

Again, no proper fix as that will be a lot more involved and may require some refactoring. While DXVK's internal reference counting *does* differ from native D3D11/DXGI behaviour in some ways, the game doesn't do proper reference counting by itself and just deletes **all** references of an object when it thinks that the object is no longer needed. This is exceptionally poor coding on Sega's side.

**Comment by doitsujin** [comment] 2018-08-05 19:37
Both the fullscreen crash and the crash after the intro are fixed in latest `master`. The solution is bad but it's the best thing I could come up with for now. This also fixes the aforementioned Unreal Engine 4 issues.

Feel free to re-open or file a new report if you run into new issues with the game (given how broken the game is, I wouldn't be surprised at all).

**Comment by Lahvuun** [comment] 2018-08-05 20:01
I'm not sure what happened, but the game only launched successfully once in fullscreen and crashes on subsequent restarts. I had a very similar issue with wined3d, but it looks like DXVK's dlls are involved.
```
Module  Address                                 Debug info      Name (263 modules)
PE              3b400000-        3b441000       Deferred        steam_api64
PE              64ce0000-        68000000       Deferred        dxgi
PE              6a340000-        6f4d9000       Deferred        d3d11
ELF             7b400000-        7b816000       Deferred        kernel32<elf>
  \-PE          7b420000-        7b816000       \               kernel32
ELF             7bc00000-        7bd43000       Deferred        ntdll<elf>
  \-PE          7bc40000-        7bd43000       \               ntdll
ELF             7c000000-        7c004000       Deferred        <wine-loader>
```

**Comment by Lahvuun** [comment] 2018-08-05 20:10
The game indeed does not crash when launched in full screen anymore, but it only renders the first frame and then the whole window just turns black.

**Comment by doitsujin** [comment] 2018-08-05 20:17
Hm, I can actually get into the game without issues, with both wined3d and dxvk. What hardware/drivers are you running?

**Comment by Lahvuun** [comment] 2018-08-05 20:34
Radeon RX560 with llvm7-git and mesa-git.

**Comment by Lahvuun** [comment] 2018-08-06 11:09
Is there any way to verify this? `perf top` doesn't show anything related to `MoveWindow`.

**Comment by doitsujin** [comment] 2018-08-06 11:26
It's a deadlock. You can attach gdb to the process and check what the threads are doing with `thread apply all bt`. One of them should have `MoveWindow` or a similar win32 function in it's call stack.

For me, this happens with both DXVK and wined3d.

**Comment by Lahvuun** [comment] 2018-08-06 18:05
Well, once I rebuilt Wine with debugging symbols the game started crashing again in fullscreen, windowed, with wined3d and DXVK. Maybe OP will have more luck with this.

**Comment by doitsujin** [comment] 2018-08-08 23:54
Just a quick note that this game is completely unplayable at least on AMD hardware at the moment, even with wined3d, and that I will ignore any future bug reports about it.

**Closed by doitsujin** 2018-08-08 23:54 UTC
Labels: bug, dxgi, game bug
