### ISSUE TITLE
Path of Exile unplayable stutter

### ISSUE THREAD

**Issue by dumpsters** [doitsujin/dxvk#464] opened 2018-06-29 03:43 UTC
Not sure if I'm the only one but Path of Exile is actually unplayable (leveling/endgame) on linux due to the extreme stuttering experienced when

- Loading into an area
- Moving
- Seeing enemies being hit/attack an enemy/pack of enemies
- Player being hit
- Other players loading into an area (town)
- Skills or effects in general being casted/triggered

**Regarding apitrace:**
I had two apitraces ready but due to some confusion I believe I recorded them in a prefix I had DXVK installed and I guess that's not how it's supposed to be, I tried running the game on a **clean** wine prefix with no vulkan or DXVK but wine crashed as soon as the login screen rendered, should an apitrace be recorded anyway until it crashes? should I try to record the apitrace on windows instead? wouldn't that defeat the purpose of showing the stuttering in the situations described above? any guidance would be appreciated.

_Note 1: wine was patched manually trying to replicate [this patch](https://bugs.winehq.org/attachment.cgi?id=59204&action=diff) in the newest wine source (some syntax differences and the auto patch failed)_
_Note 2: i tested [this DXVK patch](https://github.com/jomihaka/dxvk-poe-hack) ([more info](https://www.pathofexile.com/forum/view-thread/8980/page/194#p15575600)) and it solved some of the stuttering, maybe worth looking into_

### Software information
Path of Exile DX11 mode windowed

- VSync: off
- Textures: medium
- Texture filtering: 16x
- Engine multithreading: disabled
- Dynamic resolution: disabled (doesn't seem to work properly on linux anyway)
- Water detail: low
- Shadow quality: low
- Antialiasing: off
- Lightning quality: off
- Post processing: off
- Screen shake: off

### System information
- GPU: R7 260x
- Driver: AMDGPU Mesa 18.2.0-devel (git-ab2643e4b0)
- Wine version: wine-3.11-74-g86864486be (Staging)
- DXVK version: https://github.com/doitsujin/dxvk/commit/4520b1ca8fc6cf089da354df8ab7f6e058eefa4e

Using `DXVK_USE_PIPECOMPILER=1 VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation DXVK_LOG_LEVEL=trace WINEARCH=win64 WINEPREFIX=~/.wine_vms/PoE wine 'C:\Games\Path of Exile\PathOfExile_x64.exe' --nointro --nologo --noasync --garbage-generation 2`

### Log files
[PathOfExile_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/2147687/PathOfExile_x64_d3d11.log)
[PathOfExile_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/2147688/PathOfExile_x64_dxgi.log)

**Comment by gonX** [comment] 2018-06-29 07:37
The game uses a lot of varying combinations of shaders that need to be cached before the game starts to run smoothly. I've leveled a character to maps (endgame), and play just about as smoothly as on Windows. Make sure not to touch your graphics settings as they may require recompiling of a lot of shaders. I run everything on the highest settings (even 8x MSAA) and get a consistent +60FPS aside from the occasional shader compilation stutters that `DXVK_LOG_LEVEL=debug` will confirm.

My settings:
`DXVK_USE_PIPECOMPILER=1`
The game doesn't need any args.

Attached is a patch that makes the pipecompiler use 8 threads rather than 1 thread, which helps significantly if you don't have a relatively full shader cache.
[tc8.zip](https://github.com/doitsujin/dxvk/files/2148216/tc8.zip)

**Comment by doitsujin** [comment] 2018-06-29 08:02
This is an inherent issue with DXVK that cannot be fixed, sadly.

**Comment by gonX** [comment] 2018-06-29 08:18
Do you think contacting the developer about this would be a wise idea? I know they were originally hesitant about their D3D11 renderer, keeping it opt-in for quite a while.

The game does stutter slightly on Windows from what I would conclude to be the same root cause, but not quite as significantly as here - ie. the problem may lie outside of DXVK's scope?

I recorded a 5 minute video here of me running the same map thrice: https://www.youtube.com/watch?v=cKwUT4V3vjM

The video confirms the stuttering, but it is obviously only occuring during new effects that had not been encountered so far. This was from a relatively cold cache, using some relatively lenient encoder settings as to not affect the recording (the game is quite CPU intensive, even moreso with DXVK)

**Comment by doitsujin** [comment] 2018-06-29 08:40
> ie. the problem may lie outside of DXVK's scope?

The main difference is that a native D3D11 driver can do all sorts of code transformations when the game calls a `D3D11Device::Create*Shader` and save a lot of time when the shader is actually needed for the first time. DXVK can only do the DXBC->SPIR-V translation at that time, but it has to time-consuming part when the shader is first used.

The only thing the developers could do to counter this is to "warm up" the shader cache by submitting draw calls with all possible shader configurations before actually starting to run the game. Some games do this, but it's a rare and it's not really needed on Windows.

**Comment by doitsujin** [comment] 2018-06-29 13:56
You didn't mention what CPU you have, but pipeline compile times in excess of 200ms *are* normal a lot of games. I know it's annoying but it's just impossible to do anything about it, sorry.

That said, you should check whether your Mesa is compiled with `-DNDEBUG`, and if not, do so, but if that wasn't the case you would probably see compile times taking several seconds.

**Comment by dumpsters** [comment] 2018-06-29 14:29
My CPU is a FX6300, Regarding mesa, I'm not sure if my mesa is compiled with that arg, I don't compile it myself since I've always used [this repo](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#mesa-git) but I'll look into it

**Comment by andy-d1969** [comment] 2018-06-29 19:47
Would it be possible to dump the shaders to a cache dir and pre-compile them to native isa on every game start with the drivers shader compiler? I think this is the workaround that cemu and rpcs3 use for this issue. This way the stuttering only occurs the first time you play a game.

**Comment by doitsujin** [comment] 2018-06-29 19:53
> This way the stuttering only occurs the first time you play a game

That's what happens with DXVK as well unless you disable your driver's shader cache, but that's literally what we are trying to fix...

**Comment by andy-d1969** [comment] 2018-06-29 20:03
Yes, if the shaders are in the driver's cache all games run smooth, but if i update my driver the cache is not valid anymore and the stuttering is back. I update my mesa every few days so pre-compiling would be a cool feature.

**Comment by doitsujin** [comment] 2018-06-29 20:43
The way to do that in DXVK would be to cache pipeline state. I did make several attempts in implementing that but it ultimately didn't work.

**Comment by andy-d1969** [comment] 2018-06-29 20:58
If the dumped dxbc or spv shaders are compiled once in advance with the driver's shader compiler, the way dxvk does it in runtime, wouldn't this fill up the driver's cache?

**Comment by doitsujin** [comment] 2018-07-03 12:09
You can't compile SPIR-V shaders directly, you need to compile full Vulkan pipelines including **all** associated state.

**Comment by andy-d1969** [comment] 2018-07-03 13:24
[RPCS3](https://github.com/RPCS3/rpcs3) has one cache folder for the raw shaders and one for the vulkan pipelines. Maybe it would be helpful to take a look at how the caching is done there?

**Comment by doitsujin** [comment] 2018-07-03 13:28
It doesn't really matter how RPCS3 does it since the theory behind it is trivial. I'm just incapable of implementing it for some reason, and I don't really care since the driver's shader cache works well enough in practice. It doesn't improve the first-time experience anyway.

**Comment by jarrard** [comment] 2018-07-09 00:40
Dunno if I said this before but is it related to the WIC error? There is a patch.

https://github.com/GloriousEggroll/ge-wine/blob/master/pathofexile.patch

**Comment by Tk-Glitch** [comment] 2018-07-09 02:31
@jarrard Unrelated.

**Comment by FedoraTipper** [comment] 2018-07-12 10:19
I think the issue might be linked to nvidia's (soft) maximum limit of 128mb shader cache. This game needs far more. The same problem can be seen with Overwatch currently, even when you have played the game a million times over.

[Discussion about it](https://devtalk.nvidia.com/default/topic/1032059/linux/opengl-shader-disk-cache-max-size-garbage-collection-/)

**Comment by tgharib** [comment] 2018-07-15 08:06
If you're a nvidia user like me, then your shader cache is probably tiny enough to not do any actual caching... In that case, check out this patch: https://github.com/jomihaka/dxvk-poe-hack (releases tab has precompiled)

**Comment by doitsujin** [comment] 2018-07-17 22:45
Closing since root problem cannot be solved.

**Closed by doitsujin** 2018-07-17 22:45 UTC
Labels: performance, wontfix

**Comment by abriasffxi** [comment] 2019-02-04 20:55
> > ie. the problem may lie outside of DXVK's scope?
> 
> The main difference is that a native D3D11 driver can do all sorts of code transformations when the game calls one of the `D3D11Device::Create*Shader` methods and save a lot of time when the shader is actually needed for the first time. DXVK can only do the DXBC->SPIR-V translation at that time, but it has to do the time-consuming part when the shader is first used.
> 
> The only thing the developers could do to counter this is to "warm up" the shader cache by submitting draw calls with all possible shader configurations before actually starting to run the game. Some games do this, but it's a rare and it's not really needed on Windows.

Hi Doitsujin - can you expand on the problem a little more?  I tried following the D11 api to find the potential transformations but couldn't find the right section.  Where do you think the problem could be solved - does Vulkan need parity transformations for SPIR-V or would recompiling to DXIL and using DXIL > SPIR-V solve the problem?

On one hand, I play PoE a ton and this is really the last remaining big issue with it.  I know it also impacts other games, PoE is just shader-heavy, but it seems like it could be such a huge improvement it would be nice if it was scoped out some (even if outside of DXVK's scope).

**Comment by doitsujin** [comment] 2019-02-05 09:41
> Where do you think the problem could be solved

It simply can't. The only solution is to write a native driver that supports shader patching (this could be a Gallium state tracker).

**Comment by maddannik** [comment] 2020-04-25 09:14
Hi all!
For myself, I found this solution:
1) Install dixvk version of poe through lutris
2) Install the latest version of wine staging
3) In the settings of Lutris to POE, turn on the staging wine
4) Download and install this: https://github.com/jomihaka/dxvk-poe-hack/releases (not sure if it works correctly with the latest versions of dixvk)
5) We play. I personally have significantly decreased friezes and stutter, checked on the league delirium.
I hope someone helped. You can see this guide in more detail: https://www.reddit.com/r/pathofexile/comments/9x47or/guide_getting_path_of_exiledx11_to_run_smoothly/?sort=new
