### ISSUE TITLE
Version 2.5 forces low anisotropic filtering on some games

### ISSUE THREAD

**Issue by HitoM43** [doitsujin/dxvk#4459] opened 2024-11-15 16:26 UTC
Please describe your issue as accurately as possible.

Running some games, usually dx9, with dxvk 2.5  will force anisotropic filtering to be very low despite setting it to max in the game. Issue not present on older versions like 2.4.1, 2.4. 
Workaround found: creating a config in the game folder with d3d11.samplerAnisotropy = 16 and d3d9.samplerAnisotropy = 16.

### Software information
Name of the game, settings used etc.
NFS Most Wanted 2005, Carbon, Race driver GRID, Overspeed, maybe more.

### System information
- Windows 11 x64
- GPU: Radeon 540X 2Gb Mobile
- Driver: 31.0.14057.5006
- DXVK version: 2.5

**Comment by Blisto91** [comment] 2024-11-15 16:30
It has already been fixed on master. A 2.5.1 will likely release in the near future with a few fixes.

**Comment by doitsujin** [comment] 2024-11-15 18:54
Duplicate of #4452 , #4456

**Closed** 2024-11-15 18:53 UTC
