### ISSUE TITLE
[d3d9] Tomb Raider: Legend has some form of flickering with DXVK, does not occur with wined3d

### ISSUE THREAD

**Issue by Leopard1907** [doitsujin/dxvk#4319] opened 2024-10-03 21:28 UTC
### Software information

Tomb Raider: Legend, GOG copy, all settings maxed, everything enabled

![Ekran Görüntüsü_20241004_000622](https://github.com/user-attachments/assets/cb048934-b383-40d5-979d-d9593348fe65)

### System information
- GPU: 7900 XTX
- Driver: Mesa 24.2.3
- Wine version: Proton Experimental
- DXVK version: Whatever Experimental has and also tested with latest release, occurs with master too

### Apitrace file(s)

- wined3d trace:

https://drive.google.com/file/d/1l1bGAeI62rfjLC91BePooemQTipn6i0H/view?usp=sharing

- dxvk trace:

https://drive.google.com/file/d/1_k7pPDNML1ki_AWsHQKdd7iXhv0TfFJh/view?usp=sharing

### Log files

[steam-heroic-Tomb Raider Legend.log](https://github.com/user-attachments/files/17250195/steam-heroic-Tomb.Raider.Legend.log)

Has this in it but not sure if that is related:

```
warn:  Failed to create global buffer:
warn:    size:  157810696
warn:    usage: 1ff
warn:    type:  0
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 181
```

### Video that shows the issue

https://youtu.be/PGoJLkdbvvA?si=c6WlcYPici43iT79

**Comment by K0bin** [comment] 2024-10-03 23:37
Looks like an issue with a depth prepass. That buffer error is definitely interesting too. I'll take a look tomorrow.

**Comment by dungeon007** [comment] 2024-10-04 03:36
It more looks like a driver bug to me, since i cant reproduce it with GCN. So i guess that must me an RDNA specific driver issue.
Could be anything that triggers it, try disabling options one by one to see if anything exactly clearly triggers it.
Maybe try disabling reflections, AFAIR compilers potentionally got such glitches when there is some sort of reflections around.

**Comment by doitsujin** [comment] 2024-10-04 07:14
The buffer error is already fixed on master and not related.

**Comment by mrdeathjr28** [comment] 2024-10-04 08:30
in my case dont appear this flickering in same scene using dxvk 2.4.1

![trlc](https://github.com/user-attachments/assets/566c511c-3c94-4aba-b6bd-8f6ae5e22f00)

**Comment by dungeon007** [comment] 2024-10-04 10:17
>in my case dont appear this flickering in same scene using dxvk 2.4.1

In your case... you dont have enabled everything there 🤣
So first enable in a registry ExtendedDialog. And then enable everything with -setup switch, so make sure it is same settings just like on picture that he posted.

**Comment by K0bin** [comment] 2024-10-04 10:19
I'm not seeing any issues when replaying the apitraces on Nvidia.

**Comment by Blisto91** [comment] 2024-10-04 10:32
@Leopard1907 Out of curiosity could you try running it with `d3d9.invariantPosition = False`

**Comment by Leopard1907** [comment] 2024-10-04 10:53
> > in my case dont appear this flickering in same scene using dxvk 2.4.1
> 
> In your case... you didnt have enabled everything there 🤣 But you have to enable everything to start reproducing it. So first create in a registry ExtendedDialog and enable it. After that enable everything with -setup switch, so make sure it is same settings just like on picture that he posted. There are more setting hidden there, that he didnt showed, but i assume he didnt touched that. 👯 If you do exactly that, then we can figure out if bug is RDNA specific (if it happens also for you with everything enabled) or maybe just happens on RDNA specific ASIC. like his card (if it dont happen for you with everything enabled)..

Yes, i didnt touch those "Dev" options.

![Ekran Görüntüsü_20241004_135214](https://github.com/user-attachments/assets/832308f9-b09f-4fbe-b36a-cc410edb4d43)

**Comment by Leopard1907** [comment] 2024-10-04 10:54
> @Leopard1907 Out of curiosity could you try running it with `d3d9.invariantPosition = False`

Yep, that fixes the issue.

**Comment by qinlili23333** [comment] 2024-10-04 23:49
<img width="326" alt="image" src="https://github.com/user-attachments/assets/5c06ff54-059c-4e0f-89b2-2c3c949eaf50">

Hardware related issue I think.
Cannot reproduce on Nvidia & Windows.

PS: The game seems lock the usage of Windows key on keyboard in setup dialog.

**Comment by Blisto91** [comment] 2024-10-20 19:47
We've found that the issue shows itself when `d3d9.floatEmulation` is set to `Strict` which is only default on radv, nvk and amdvlk open as of writing.

**Comment by Leopard1907** [comment] 2024-11-07 17:00
@qinlili23333 Can you try with dxvk master?

**Comment by qinlili23333** [comment] 2024-11-08 12:49
> @qinlili23333 Can you try with dxvk master?

Interesting. I can reproduce on master 8584fc7.

**Comment by qinlili23333** [comment] 2024-11-08 13:02
> Yes, as expected. MR linked above enables same behaviour for NV driver too now so you have same behaviour as RADV now. So not a driver or hw specific issue.
> 
> `Strict: Use a slower but more correct approach. Necessary for some games`
> 
> @mrdeathjr28 https://github.com/doitsujin/dxvk/blob/master/dxvk.conf#L489
> 
> Probably should be able to repro too with his Intel if he sets this to Strict.

d3d9.floatEmulation=False fix for me.
Maybe we need to add a config for this game, or maybe strict emulation need to be reverted

**Comment by qinlili23333** [comment] 2024-11-08 13:15
> Yes, as expected. MR linked above enables same behaviour for NV driver too now so you have same behaviour as RADV now. So not a driver or hw specific issue.
> 
> `Strict: Use a slower but more correct approach. Necessary for some games`
> 
> @mrdeathjr28 https://github.com/doitsujin/dxvk/blob/master/dxvk.conf#L489
> 
> Probably should be able to repro too with his Intel if he sets this to Strict.

Verified on Intel Xe 80eu (1135G7) 101.5768 (24H2), if set to Strict, same issue.

**Comment by qinlili23333** [comment] 2024-11-08 13:19
I've found something already in config
```
    /* Tomb Raider: Legend, Anniversary, Underworld  *
     * Read from a buffer created with:              *
     * D3DPOOL_DEFAULT,                              *
     * D3DUSAGE_DYNAMIC | D3DUSAGE_WRITEONLY buffer. *
     * Legend flickers with next gen content option. */
    { R"(\\(trl|tra|tru)\.exe$)", {{
      { "d3d9.cachedDynamicBuffers",        "True" },
      { "d3d9.maxFrameRate",                "60" },
    }} },
```

**Closed as completed** 2024-11-11 11:33 UTC
Labels: d3d9
