### ISSUE TITLE
Mass Effect Andromeda: Weird image offset

### ISSUE THREAD

**Issue by ximik1987** [doitsujin/dxvk#397] opened 2018-05-26 19:09 UTC
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
good afternoon. I ask for the translation for Google translator.
find bug in the game mass effect andromed.
at video setting in adjustments 720, all is very fine, at installation 1080 - a picture to be rendered with distortion. all can be seen in the screenshots.

### System information
- GPU:radeon r290x
- Driver:mesa 18.2-git
- Wine version: 3.9 -stading and 3.8
- DXVK version: 0.51 - 0.52

### Apitrace file(s)
- Put a link here

### Log files

- d3d11.log: [MassEffectAndromeda_d3d11.log](https://github.com/doitsujin/dxvk/files/2041885/MassEffectAndromeda_d3d11.log)
- dxgi.log:  [MassEffectAndromeda_dxgi.log](https://github.com/doitsujin/dxvk/files/2041886/MassEffectAndromeda_dxgi.log)
![2018-05-26 01-34-23](https://user-images.githubusercontent.com/29666515/40579503-36f830f6-6131-11e8-9927-2c7e858d9e10.png)
![2018-05-26 01-36-19](https://user-images.githubusercontent.com/29666515/40579504-3715208a-6131-11e8-81e4-538d7cda678a.png)
![2018-05-26 01-36-44](https://user-images.githubusercontent.com/29666515/40579505-37332922-6131-11e8-9062-83ac21925315.png)
![2018-05-26 01-37-01](https://user-images.githubusercontent.com/29666515/40579506-374f6876-6131-11e8-9bfa-2248dd75b722.png)

**Comment by doitsujin** [comment] 2018-05-26 19:12
The same issue also exists in Battlefield 1, but I don't know what causes it.

**Comment by soredake** [comment] 2018-05-27 03:47
Same problem, `POST PROCESS QUALITY` on high causes this

**Comment by Kerrung** [comment] 2018-05-27 05:33
@ximik1987 can you write apitrace?

**Comment by ximik1987** [comment] 2018-05-27 10:05
after setting the "POST PROCESS QUALITY
![2018-05-27 13-02-48](https://user-images.githubusercontent.com/29666515/40584727-93c19534-61ae-11e8-809b-caeb023d1017.png)
" values to low, the game started at 1080 quality without distortion. Thank you.

**Comment by doitsujin** [comment] 2018-05-27 10:14
Thanks for the hint with the Post Process Quality. I have the game myself, sadly I cannot run it on Linux because I can't get Origin to work, but that should give me something to work with.

**Comment by ximik1987** [comment] 2018-05-28 19:58
@AccountOneOff 
apitrace not work
comand ->> WINEPREFIX="/home/ximik/games/andrameda" wine64 apitrace trace -v -a dxgi MassEffectAndromeda.exe

000b:fixme:winediag:start_process Wine Staging 3.9 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
info: did not find C:\Mass Effect Andromeda\..\wrappers\RelWithDebInfo\dxgitrace.dll
info: did not find C:\Mass Effect Andromeda\..\lib\wrappers\dxgitrace.dll
error: failed to find dxgitrace.dll wrapper (rerun with -v option for more details)
0009:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffffffffffa, 0x23fd00

**Comment by AccountOneOff** [comment] 2018-05-28 20:15
Try using Plagman's apitrace dlls. Just put them next to the game's exe and launch like normal. You don't need to run `wine64 apitrace -v -a dxgi MassEffectAndromeda.exe` just `wine64 MassEffectAndromeda.exe` is good enough.

https://www.dropbox.com/sh/o769ius47wpu3pw/AABYFKQFFNsCsosXhl7_HReDa?dl=0

**Comment by ximik1987** [comment] 2018-05-28 21:44
setting the "POST PROCESS QUALITY" ultra, and video setting 1080 p.
Apitrace file:    https://mega.nz/#!2mgyDByK!7k6aeIYDD7QM5VXQEg2G3p-dhmbbtNjWM4Sx2l1ijDE

**Comment by K0bin** [comment] 2018-06-07 00:19
Might be a driver issue. I can't reproduce it on Windows with an Nvidia gpu.

**Comment by doitsujin** [comment] 2018-06-22 20:06
Can you re-test this game with latest mesa-git, llvm-svn, and DXVK 0.60? I got a report recently that apparently the problem disappeared in Battlefield 1.

**Comment by ximik1987** [comment] 2018-06-22 20:31
the game is going well. FPS fell from 45-55 to 35-45, but all graphics problems disappeared.

**Comment by doitsujin** [comment] 2018-06-22 20:38
Okay, thanks for the feedback. Will close the issue then.

**Closed by doitsujin** 2018-06-22 20:38 UTC
Labels: amd radv, bug
