### ISSUE TITLE
[d3d9] Texture artifacts in Everquest 2

### ISSUE THREAD

**Issue by rsw0x** [doitsujin/dxvk#1832] opened 2020-11-24 13:09 UTC
Some textures in Everquest 2 render incorrectly as shown in the screenshots attached at the bottom.

### Software information
Everquest 2, any settings.

### System information
- GPU: Nvidia GTX 970
- Driver: 455.46.01
- Wine version: wine-staging 5.22/wine-staging 5.11
- DXVK version: 1.7.2

### Apitrace file(s)
- https://drive.google.com/file/d/1EG4Y7DVe_lgjVmxegKAQxzfk9l21VOhz/view?usp=sharing

The trace was captured using Wine-staging 5.11 as the newest wine versions run the game very slowly when using wined3d.

### Log files
- d3d9.log: [EverQuest2_d3d9.log](https://github.com/doitsujin/dxvk/files/5590013/EverQuest2_d3d9.log)
- d3d11.log: N/A
- dxgi.log: empty

Example of the issue(clothing on the female character in the mid-left):
![1](https://user-images.githubusercontent.com/7722833/100095943-4882ca80-2e29-11eb-8e67-f2e42acc94c3.jpeg)
I thought it was black pixels at first, but using the in-game command to scale the framebuffer I noticed that the problem textures became transparent:
![2](https://user-images.githubusercontent.com/7722833/100095953-4b7dbb00-2e29-11eb-9466-ead6fd72b0b3.jpeg)

It appears to be strictly limited to some clothing textures.

**Comment by Joshua-Ashton** [comment] 2020-11-24 13:16
Thanks for the report, will take a look :-)

**Comment by Joshua-Ashton** [comment] 2020-11-24 16:48
Doesn't happen on RADV or AMDVLK.

This is caused by the alpha emitted in the pixel shader for that lady's clothes.

In the vertex shader, changing the output vertex color to 1,1,1,1 changes nothing.
In the pixel shader, changing the recieved vertex color to 1,1,1,1 fixes it.
Removing `centroid` changes nothing.

This is truly bizzare and I feel like it *may* be a driver bug; but this game is so simple and we're not doing anything crazy so I feel it has to be on our end...

**Comment by rsw0x** [comment] 2020-11-24 20:51
Just realized this happens with wined3d too. Because of the bad performance I never used it beyond the quick apitrace and alt+f4 so I didn't realize it. This might not be a DXVK bug?

But when using wined3d if I disable GLSL shaders and use ARB instead with a compatibility context the issue goes away. So, maybe it's a shader issue that's present in both wined3d and DXVK? Or just a nvidia driver bug, as you said.

**Comment by Joshua-Ashton** [comment] 2020-11-26 12:17
Should be fixed in master as of bbfd6d06908d3545a11bb8f322300b4e724851cb

**Closed** 2020-11-26 12:17 UTC
Labels: d3d9

**Comment by Sturmlocke86** [comment] 2022-02-19 23:49
> Should be fixed in master as of [bbfd6d0](https://github.com/doitsujin/dxvk/commit/bbfd6d06908d3545a11bb8f322300b4e724851cb)

Hey Josh, I have a question about a different issue related to EQ2. I can't open a dxvk bug report for this, because it's a bug that can be reproduced on Windows too, but I thought you might have the knowledge to further diagnose the glitch. Tried reaching out to you via the e-mail in your github profile, but then realised it might just be a placeholder, lol. How can I get in touch with you? Cheers, Alex
