### ISSUE TITLE
The Surge 2 - the workaround for DXVK doesnt work

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#1254] opened 2019-11-25 14:49 UTC
I know that this game is a vulkan game, but please read first, before saying anything

The game has many issues one of them is this wine bug:
https://bugs.winehq.org/show_bug.cgi?id=48165
The last comment recommended me to install the windows version of vulkansdk, and vulkanrt to use DXVK instead of Vulkan directly! I don't know how is that works, and he told me to report the issue here if this workaround doesn't work.

### Software information
The Surge 2, Medium settings, Vsync off, fullscreen off, and Antialiasing =TAA

### System information
- GPU: AMD HD 8750M
- Driver: Mesa 19.99 (Obiaf PPA)
- Wine version: Wine-staging 4.20
- DXVK version: 1.4.5

### Log files
[Terminal.log](https://github.com/doitsujin/dxvk/files/3887139/Terminal.log)

**Comment by doitsujin** [comment] 2019-11-25 15:32
This is not a DXVK issue. The problem is that the new Windows Vulkan runtime uses DXGI to enumerate Vulkan devices, but DXVK's DXGI uses Vulkan to enumerate DXGI devices. Obviously this does not work, and cannot be fixed inside DXVK.

Instead, you should set the DLL override for `vulkan-1.dll` to **builtin** in order to bypass the Windows Vulkan loader.

**Closed by doitsujin** 2019-11-25 15:32 UTC
