### ISSUE TITLE
Freeze system in GTA5 and Witcher3

### ISSUE THREAD

**Issue by sr-tream** [doitsujin/dxvk#251] opened 2018-04-07 15:42 UTC
This problem occurs after 5-10 minutes, after the game starts.

### Software information
GTA5, Witcher3

### System information
- GPU: AMD RX560
- Driver: RADV, mesa 18.0
- Wine version: 3.5
- DXVK version: 0.41

### Log files (Witcher 3)
- [d3d11.log](https://pastebin.com/BavYrcTZ)
- [dxgi.log](https://pastebin.com/ziQUWr03)

### Log files (GTA5)
- [d3d11.log](https://pastebin.com/3shEyhrT)
- [dxgi.log](https://pastebin.com/4rKy0yEv)

**Comment by doitsujin** [comment] 2018-04-07 15:50
It's a known issue for GTA V. Please provide information on how to reproduce this with Witcher 3, this game runs fine on my end.

**Comment by sr-tream** [comment] 2018-04-07 16:38
As a rule, problems occur during the battle, or in cut scenes. If you just run around the world, then the game works well.
At one point there is a small freeze, as when compiling the shader, but at the same time the keyboard and mouse cease to work, and this freeze lasts forever

**Comment by doitsujin** [comment] 2018-04-07 16:41
Can you provide a save file where this issue occurs? Again, I cannot reproduce it, and I have played Witcher 3 for a few hours without issues.

**Comment by sr-tream** [comment] 2018-04-07 16:44
Yeah. At the end of the battle with griffin.
[The Witcher 3.zip](https://github.com/doitsujin/dxvk/files/1886568/The.Witcher.3.zip)

**Comment by sr-tream** [comment] 2018-04-07 16:47
P.S. Im using LLVM 6.0 by default system. Now I building mesa-git (18.1) with LLVM 7.0 for tried. After I'll try use system mesa (18.0) and mesa-git (18.1) with LLVM 5.0

**Comment by sr-tream** [comment] 2018-04-08 08:28
With this save a 100% freeze system after oneshot kill.
https://dl.prime-hack.net/The%20Witcher%203.zip

`export RADV_DEBUG=allbos,syncshaders,vmfaults`
`wine witcher3.exe &> witcher3.out`
https://dl.prime-hack.net/witcher3.out

**Comment by doitsujin** [comment] 2018-04-09 11:16
I updated the instructions in #252 to get a hang report since I apparently messed up there. Anyway, I'll see if I can reproduce this with your saves.

**Comment by Hi-Angel** [comment] 2018-04-18 17:47
Oh, I occasionally stumbled upon the issue, having same problem with GTAⅤ, I think I know the reason.

What happens is that DXVK seems to report too big values as amount of VRAM, screenshot:
![screenshot_20180418_204100](https://user-images.githubusercontent.com/7935057/38948649-d16ee848-4348-11e8-9827-4d067c161330.png)

So, after some minutes of gameplay the driver takes all available RAM *(it can be seen in `free` output, the field `buff/cache`)*, leading to system freeze.

What's interesting, is that the number you see on screenshot, the `5909`, never change, so it probably simply some percentage of system RAM. FWIW, total amount of RAM my laptop here have is 8GB.

**Comment by Hi-Angel** [comment] 2018-04-18 17:50
…so, the solution would be to somehow limit the number of VRAM being reported.

**Comment by sr-tream** [comment] 2018-04-18 17:55
@Hi-Angel, may be problem in VRAM, but not in RAM 100%. Total amount RAM in my PC - 24GB

**Comment by Hi-Angel** [comment] 2018-04-18 20:52
@sr-tream can you please take a look if for playing GTAⅤ the field `buff/cache` of the command `free` on your system is unstoppably increasing, like, 8GB, 10GB, 13GB…?

**Comment by kleest** [comment] 2018-05-27 14:52
@Hi-Angel 
I also get the freeze in GTA5. My video card has 8GB of VRAM. My system has 16GB of RAM. In graphics settings, GTA5 reports 8GB of VRAM, which is correct. While playing, the system RAM usage does not increase to the point where it fills up. Except for the graphics driver, every part of the system is working fine while freezing: audio, disk, network, etc.

**Comment by hakzsam** [comment] 2018-06-09 12:27
I recently fixed a bunch of issues with RADV. You shouldn't be able to reproduce any GPU hangs with GTA V and TW3. If I'm wrong, let me know.

**Comment by doitsujin** [comment] 2018-06-09 12:29
Closing since these should work with latest mesa-git and llvm-svn. (see #252).

**Closed by doitsujin** 2018-06-09 12:29 UTC
Labels: amd radv
