### ISSUE TITLE
[RFE] create a script to automatically install DXVK into a wine prefix

### ISSUE THREAD

**Issue by Hi-Angel** [doitsujin/dxvk#3211] opened 2023-01-25 10:43 UTC
Having to copy dlls into wine prefix and then starting `winecfg` manually and adding overrides is tedious and error-prone. Would be great if there was some script that automate that effort.

Release 2.1 [mentions at the bottom](https://github.com/doitsujin/dxvk/releases/tag/v2.1)

> setup script `setup_dxvk.sh` was no longer deemed useful and got removed

Sounds like a usecase was found! ☺

### System information
- GPU: Intel HD 620
- Driver: Mesa
- Wine version: 7.22
- DXVK version: 2.1

**Comment by Hi-Angel** [comment] 2023-01-25 10:50
I can send a PR to fix that btw, unless there's opposition

**Comment by Riesi** [comment] 2023-01-25 11:35
IIRC the issue with the setup script was that it didn't fit the use cases of **ALL** people and that a lot of people had issues with it all the time when it worked fine for others. Just look up some issues.

Also people felt entitled to make a whole lot of PRs to "fix" issues regarding their own weird setups or shell ideals, which is also something that was just polluting the PR tracker for no good reason.

IMHO inexperienced users should use a tool like Lutris, Heroic, etc... so they don't need a setup script.
And on the other hand more experienced users can roll their own script to fit their special setups anyway. 

The script is gone for good reasons and we should keep it that way.

**Comment by Hi-Angel** [comment] 2023-01-25 11:46
> IMHO inexperienced users should use a tool like Lutris, Heroic, etc... so they don't need a setup script.

I am not a gamer but a developer. However I do set up Linux configurations sometimes for friends, etc. So, I'm not really familiar with Lutris and Heroic, however I do know well that if I setup gaming environment for someone, latest WINE and DXVK is preferred.

With that said, count me in to the list of "inexperienced users" I guess, and please answer: given a latest tarball release and a WINEPREFIX with games, how to I use any of these tools to install DXVK into it? And while at it: can we replace the current text "copy/override" with that description?

> Also people felt entitled to make a whole lot of PRs to "fix" issues regarding their own weird setups or shell ideals, which is also something that was just polluting the PR tracker for no good reason.

I see… Not sure what to suggest here other than marking such PRs with a special label, then ignoring if there's no resources moral or timewise. I mean, unless you have a solution through Lutris or whatever, the current state is worse from a user standpoint.

**Comment by mbriar** [comment] 2023-01-25 11:52
I'm almost certain it would have caused less friction to just immediately "won't fix" close the occasional PR/issue about weird non-bash setups and POSIX purists that came in once a year then it was to remove the script outright, but what is done is done.

**Comment by Hi-Angel** [comment] 2023-01-25 11:54
Right. Can we just introduce a policy a là "no weird shell setups for `setup_dxvk.sh`"? Document that in a README, and just close any PR trying to fix that as part of that policy.

**Comment by Hi-Angel** [comment] 2023-01-25 11:56
I am even willing to help with formulating such policy if there's an agreement. I will probably need some links to related discussions to figure out what exactly are the problems we are trying to avoid and some spare time, but I can do that.

**Comment by Riesi** [comment] 2023-01-25 12:03
As far as I know Heroic can pull the latest DXVK releases automatically and it can use existing prefixes as far as I can tell.
Bottles also has a nice GUI for people to pull latest DXVK.
Lutris currently is in the weird situation that they ship their own DXVK due to some special configs, which is outdated... but they can also use existing prefixes.

The benefit of using such manager GUIs is also that its a nicer experience to interact and start added games.

Another solution would be the skip all that and simply add your game installs as non-steam games to steam and use proton instead.

> With that said, count me in to the list of "inexperienced users" I guess, and please answer: given a latest tarball release and a WINEPREFIX with games, how to I use any of these tools to install DXVK into it? And while at it: can we replace the current text "copy/override" with that description?

**Comment by ksterker** [comment] 2023-01-25 16:06
I've always used the setup_dxvk.sh script without any issue, so I am a bit perplexed by it being removed. I guess I can just copy it over from an older release and it hopefully will continue to work. But I find the mindset of "since it was broken for a select few people, we break it for everyone" a bit indifferent to the, perhaps, silent majority of users that were happily enjoying the ease of use that script provided.

I understand the frustration of having something that's not perfect, especially if it's only tangential to the actual body of work, and when there are plenty working alternatives. But perhaps this could live on as a separate project for those of us that prefer the command line for basic tasks like installing software.

**Comment by katawful** [comment] 2023-01-25 16:11
I use setup_dxvk.sh quite often to test applications/get around application incompatibility. It is much simpler for me, someone who maintains Wine AppDB entries, to work directly from the terminal rather than GUI managers that abstract away installation and management of Wine prefixes. So the removal of this script, which has never failed for me in any case, seems silly when the issues around it were about POSIX compliance

**Comment by Riesi** [comment] 2023-01-25 18:01
Well the script should continue working as long as nothing on the wine side changes.
So you can just use your working copy.

Winetricks also ships dxvk verbs if you dont want a GUI tool to install it.

One could argue that its out of this projects scope to setup your wine prefix or whatever. 🐸

**Comment by Monsterovich** [comment] 2023-01-25 20:35
> setup script setup_dxvk.sh was no longer deemed useful and got removed

I used it all the time. Why?????

**Comment by Monsterovich** [comment] 2023-01-25 20:41
> The script is gone for good reasons and we should keep it that way.

Well, thank you, now I have to move files by hand every time, and then configure dll libraries in winecfg for each new prefix. This is so f*cking inconvenient. This is what the installation script was created for.

**Comment by Monsterovich** [comment] 2023-01-25 20:47
> So you can just use your working copy.

New users don't know how to move the libraries, you need to know exactly where to put and what to configure after that.

**Comment by Leopard1907** [comment] 2023-01-26 00:55
If someone is using Wine without any of the front ends like Lutris, Bottles and Heroic, figures out what is needed for a game to work from winedebug channel outputs, applies winetricks components, can handle manual installation of an app and needed components within Wine without screwing up the prefix , actually willing enough to use latest upstream Wine releases with the risk of regressions and also being content with upstream Wine releases that lacks patches from Proton etc etc can handle a manual installation or can spin their own scripts.

People that are not in that group are basically clueless about what DXVK is, what is a d3dcompiler, what is a dll override, what even "upstream Wine" means and they need those mentioned frontends for non Steam use cases for many of the reasons listed above.

So there is no benefit in pursuing a script in upstream release for general availability and arguing over that as if it would be a benefit for everyone is pointless. 

So many times that people have tried to shape that script for their will/desire/use case/workflow , there was no way to satisfy anyone with the script so right now everyone can go wild with their own, specifially tailored for their use case scripts imo :)

**Comment by Monsterovich** [comment] 2023-01-26 02:28
> So there is no benefit in pursuing a script in upstream release for general availability and arguing over that as if it would be a benefit for everyone is pointless.

I strongly disagree with this. I have a good understanding of how wine works, but it's not about that at all, it's about applying/removing dxvk to the prefix more conveniently. All of your arguments are out of thin air and I hope you will stop acting like a child and understand what I mean.

All sorts of frontends like winetricks, of course, are useful but don't know how to remove dxvk or reinstall it and it's better not to rely on them and always have a fallback solution.

> So many times that people have tried to shape that script for their will/desire/use case/workflow , there was no way to satisfy anyone with the script so right now everyone can go wild with their own, specifially tailored for their use case scripts imo :)

All these years while there was dxvk script I was quite satisfied.

**Comment by Riesi** [comment] 2023-01-26 08:45
The decision to drop the script was made due to multiple factors, not only the mass on PRs, so don't hang yourselves up on only that argument. 

The old script will continue to work, because dxvk will continue to be a bunch of DLLs. Nothing more...

I don't understand the big drama of getting rid of a thing that simply didn't **just work:tm:** for all users and due to that created maintenance burden that was just not worth to deal with. It is out of the projects scope to handle setting stuff up. Why is this such a big problem

I get the feeling everybody here is fine with setting up their wine prefixes and managing them by hand, but using the old script or other tools to properly install dxkv is too much work.
This is a work flow that imho an inexperienced user should not have to deal with, so an upstream install script would simply lure them into it. Instead of them using managers that are aimed to such users.

**Comment by Hi-Angel** [comment] 2023-01-26 08:52
Alright, so to give some decision: how about changing the README.md so it would refer to multiple ways of installing the DXVK, *including* the old script being inside the last commit it existed at, and would add that the script is no longer maintained due to the difficulties it brought to the project.

I think it's a nice compromise that would allow DXVK to no longer maintain the script, but at the same time would document some way people may use it.

**Comment by leikareipa** [comment] 2023-01-26 10:00
Seems a bit abrupt to nuke an end-user point of entry like this. I can understand it from the developer's perspective, but as a user I haven't had problems with the script. The way the manual installation process is currently described in the README does beg the question of whether there couldn't be an automated way.

**Comment by katawful** [comment] 2023-01-26 10:50
I understand the importance of helping newcomers, but as it stands this change now makes the project less accessible overall. The readme does not state in anyway how to use DXVK with one of the various GUI managers, or that it is even integrated into Proton. Providing manual install instructions first will only lead to further confusion on this front, and if this _was_ meant to be a change for clarity then the readme should be reflected to show this. Manual install instructions as the first header is not the way to go

**Comment by birdie-github** [comment] 2023-01-26 11:52
> IIRC the issue with the setup script was that it didn't fit the use cases of **ALL** people and that a lot of people had issues with it all the time when it worked fine for others. Just look up some issues.
> 
> Also people felt entitled to make a whole lot of PRs to "fix" issues regarding their own weird setups or shell ideals, which is also something that was just polluting the PR tracker for no good reason.
> 
> IMHO inexperienced users should use a tool like Lutris, Heroic, etc... so they don't need a setup script. And on the other hand more experienced users can roll their own script to fit their special setups anyway.
> 
> The script is gone for good reasons and we should keep it that way.

Show a warning when the script runs and ask for the user input. Everyone's happy.

```bash
echo "This script is potentially dangerous and can break stuff. Are you sure you want to continue (y/n)? "
read answer
test "$answer" != "y" && echo "Goodbye" && exit
```

**Comment by doitsujin** [comment] 2023-01-26 11:55
I'm not an expert on shell scripts, and the one we had just clearly didn't meet the quality standards that were expected of it.

And in a world where literally the first line causes controversy I just don't see myself qualified to maintain that kind of script anymore (and yes, if it's in this repository I *am* responsible for maintaining it even if it's originally a third-party contribution). I'm also just tired of the back and forth of some people wanting one thing and others wanting the opposite.

If you were using the old script and it worked for you - great, grab a copy of it from 2.0, maybe modify it in such a way that you can point it to a DXVK directory without having to move the entire script around and keep using it I guess. At least that's what I've done locally. Might as well put it up here: https://gist.github.com/doitsujin/1652e0e3382f0e0ff611e70142684d01

Our README/Wiki could be improved, arguably, but I'm just not going to have a script in the repo again, that ship has sailed.

**Closed by doitsujin** 2023-01-26 11:55 UTC

**Comment by Hi-Angel** [comment] 2023-01-26 11:57
@doitsujin so, how about the compromise [I suggested here](https://github.com/doitsujin/dxvk/issues/3211#issuecomment-1404705684)? You don't have to maintain the script.

**Comment by Riesi** [comment] 2023-01-26 13:29
Thats what Doitsujin meant with:

> Our README/Wiki could be improved

**Comment by Hi-Angel** [comment] 2023-01-26 13:33
> Thats what Doitsujin meant with:
> 
> > Our README/Wiki could be improved

Cool. Just wanted to make sure there's no misunderstanding or anything. Unless someone else is willing to do that *(which I would be totally fine with)*, I'll carve up some time in the next few days and will send a PR to update README per the comment referred above.

**Comment by Riesi** [comment] 2023-01-27 09:32
I created a PR #3216 to cover the concerns listed here.
Please comment there if I missed something important.

**Comment by gabriele2000** [comment] 2023-01-29 22:32
> > The script is gone for good reasons and we should keep it that way.
> 
> Well, thank you, now I have to move files by hand every time, and then configure dll libraries in winecfg for each new prefix. This is so inconvenient. This is what the installation script was created for.

Jesus...
`export WINEPREFIX=path to your wineprefix
export DXVK_FOLDER=path to a folder where you extract the archive
cp -v $DXVK_FOLDER/x64/* $WINEPREFIX/drive_c/windows/system32
cp -v $DXVK_FOLDER/x32/* $WINEPREFIX/drive_c/windows/syswow64`

**Comment by katawful** [comment] 2023-01-29 23:00
The script allowed easy uninstallation of DXVK, which was the far more important issue for someone like me who tests applications (for Wine's AppDB) and needs to do this very often. This is only a solution for people who just need to install DXVK and never uninstall it

**Comment by gabriele2000** [comment] 2023-01-30 00:51
> @gabriele2000
> 
> It's possible to make a Windows registry file to add these entries without going into winecfg, but it is better to use a ready-made shell script.
> 
> Now it's gone. The Valve overlords are satisfied. (C)
> 

Sure it's an inconvenience not having it anymore, but most users won't need to manually install DXVK, plus those who can do it are able to write a basic script like mine...
Disclaimer: this is my second script of my lifetime, the first one is to compile obs-vkcapture both for 32-bit and 64-bit, it's like: 12 lines long.

> @katawful Exactly. Have you ever seen a Windows user treated like: setup.exe is not standardized and it's a clusterfuck, install programs in Program Files manually!

Actually I used Windows most of my life, until I was 20 so until 3 years ago: I shit you not, most installers don't even know how to install stuff in a proper way and their uninstaller can't uninstall stuff properly and you'll have to use "Advanced Uninstaller PRO" or similar crapware.

**Comment by Trinity3e** [comment] 2023-01-30 21:41
> Then `winecfg` -Libraries -> dxvk (native); d3d9 (native); d3d10core (native); d3d11 (native); ![image](https://user-images.githubusercontent.com/12186181/215359695-a6fa42bb-a23a-43dd-87eb-537a2c19d211.png)

This can also be easily automated, just looking through the install script:

`/path/to/wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v {dxgi,d3d9,d3d10core,d3d11} /d native /f `

It can even be improved because by exporting these variables you can use any wine version completely portably:
(this is optional)
`PATH="$winepath/bin:$PATH" LD_LIBRARY_PATH="$winepath/lib:$LD_LIBRARY_PATH" WINEDLLOVERRIDES="winemenubuilder.exe=d" WINESERVER="$winepath/bin/wineserver" WINELOADER="$winepath/bin/wine" WINEDLLPATH="$winepath/lib/wine"`

**Comment by zlice** [comment] 2023-02-09 00:15
\>_< now i have to kick this script around or diy. who tf doesnt have bash installed!??!?!

anyway =/ thx for saving gaming on linux

**Comment by gabriele2000** [comment] 2023-02-09 01:59
> >_< now i have to kick this script around or diy. who tf doesnt have bash installed!??!?!
> 
> anyway =/ thx for saving gaming on linux

I'll create an install script as soon as possible for you, if you want.

Tomorrow I'll write everything and you'll be free to do what you want with it.
I suppose that your ".wine" folder is in your home, right?

By the way "bash" is what you use everytime you open the terminal, you have it, everyone has it.

**Comment by es20490446e** [comment] 2023-04-18 12:28
I'm working on a drop in replacement for setup_dxvk.sh.

When it is ready I will let you know.

**Comment by es20490446e** [comment] 2023-04-18 16:29
Here's the **replacement**: [dxvk-installer](https://gitlab.com/es20490446e/dxvk-installer)
