### ISSUE TITLE
Nebulous: Fleet Command having graphical glitches/defects.

### ISSUE THREAD

**Issue by ElijahRS** [doitsujin/dxvk#2951] opened 2022-09-22 08:53 UTC
There is only one other game that i have found that has this same issue but i'll be simple and stick primarily to the game in question. TLDR Nebulous Fleet Command is a tactical sci-fi simulation game and i'll just leave it at that. I dual boot windows and Garuda Linux, and on Windows, the game runs without issues. Though since my machine is a little bit less than average i primarily main Linux.

Onto the issue at hand. First time i ever started the game it was an absolute glitchfest of a hellhole. Graphics wise. The background video that plays of ships flying was yellow and riddled with horiizonztal black and red lines, compared to the usual monocolor video that is usually in place. When i enter the fleet editor (which will show the same issue if i were to say, go into an actual round) and the issue at heart lays here. The ship is rendered and has black and red lines cutting through it. Horizontal no matter how i orient the ship, as if it's on my screen not the ship itself. As of today, the background video being glitchy is no longer an issue. I think i fixed that somehow but i cannot remember as it was a long time ago. The ship models however being graphically thrown off however is still a thing and it is a large issue because things get really slow and ugly once the graphical glitches come into view and persist even after i go back into the main menu as if my graphics card got drunk or something. I hopefully described it right but i am prettty sure i am. You will see from the screenshot and the apitrace. Should also add i tried many proton versions and even wine at one point. This is a steam game.

**_NAME OF THE GAME:_**
Nebulous: Fleet Command, using Proton. Settings used are not important.

_**OS INFO:**_
CPU: AMD A9-9425 RADEON R5 2C+3G (2) @ 3.1GHz
GPU: AMD ATI Radeon R7 M260/M265 / M340/M360 / M440/M445 /
GPU: AMD ATI Radeon R2/R3/R4/R5 Graphics
RAM: 8GB
OS: Garuda Linux

_**APITRACE FILE:**_
https://mega.nz/file/yAA3wI7J#h8KRoBhVPuBonJaDwuxJ42FyhG03sL1fqTGMj-GhKH4

**_LOG FILES:_**
[Nebulous_d3d11.log](https://github.com/doitsujin/dxvk/files/9623965/Nebulous_d3d11.log)
[Nebulous_dxgi.log](https://github.com/doitsujin/dxvk/files/9623966/Nebulous_dxgi.log)

**_SCREENSHOTS_**
![unknown-282-1](https://user-images.githubusercontent.com/99289427/191702721-aeb0273f-1648-434c-b4b2-4f0e4024d801.png)
![Screenshot_28](https://user-images.githubusercontent.com/99289427/191703190-639318ae-935c-40ee-9e1f-91d9f3ccb917.png)

**Comment by doitsujin** [comment] 2022-09-22 11:18
What exactly is this supposed to look like? Replaying the trace looks like this here which doesn't show any obvious issues:
![Bildschirmfoto](https://user-images.githubusercontent.com/25567304/191733144-28a45dd2-1307-4f2c-88b2-d5650f852d5b.png)

That said, the game **heavily** relies on shared resources for some annoying reason, so I'll need to install and test the game manually anyway.

**Comment by doitsujin** [comment] 2022-09-22 11:57
Yeah, even the videos render fine here. Kinda hard to tell what's going on since Renderdoc doesn't work with this game, but might be a driver issue specific to very old GPUs.

**Comment by mbriar** [comment] 2022-09-22 12:04
Try `RADV_DEBUG=nohiz %command%` as launch option in steam @ElijahRS

**Comment by doitsujin** [comment] 2022-09-22 12:05
`nodcc` might be the more useful thing to test since it's mostly the videos that are broken.

**Comment by mbriar** [comment] 2022-09-22 12:08
I think dcc isn't even supported on that [GPU](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/amd/vulkan/radv_image.c#L233), but there are multiple issues fixed with `nohiz` on these old cards on the Mesa bug tracker.

**Comment by Blisto91** [comment] 2022-09-22 21:50
ElijahRS confirmed on discord that `RADV_DEBUG=nohiz %command%` makes the issue go away. So seems like a driver issue.
I wasn't able to reproduce myself either in the trace with my R9 380

**Closed** 2022-09-23 00:53 UTC
Labels: d3d11, amd radv
