### ISSUE TITLE
World of Warcraft Classic Unable to start up 3D Acceleration [Linux/Lutris/Wine]

### ISSUE THREAD

**Issue by gcapris90** [doitsujin/dxvk#2062] opened 2021-05-13 01:52 UTC
Hello to all.

I’ve been using Lutris + Wine to play World of Warcraft Classic for quite some time now, maybe around 5 months. During this time I only had minor issues quickly fixable. The game was working correctly, including the DXVK, Esync, graphics and stability.

This week I’ve noticed that I had a lot of packages to update and, among those, Mesa-Vulkan (from kisak-mesa PPA) and Wine staging. Update+Upgrade all done. All installed. Rebooted the system. But now a massage pops up when trying to open WoW via Lutris: **“World of Warcraft Classic was Unable to start up 3D Acceleration”.**

Already having the latest Lutris version installed, that’s what I’ve tried to do so far to try fixing it:

- Disabling DXVK on Lutris: by doing this the game opens but soon enough it crashed when trying to play on different maps;
- Using a different Wine version: lutris versions 5.1 to 6.4 with DXVK on. None worked.
- Using a different DXVK version: tried to use every previous versions available on Lutris, from versions 1.7L, 1.7.1L to 1.7.3L-03f11ba (the most recent version available on Lutris for me). None worked.
- Downloading/Updating DXVK to the latest version: downloaded versions 1.8 and 1.8.1 from the official Github and installed them on Lutris’ .local file path. Didn’t work.

I’ve looked on the internet for the same problem and found a couple of results, although none with a solution. Many suggesting to update Lutris, Wine, Kernel, but I have the most recent version avaiable of it all - and it still doesn’t work.

Here are the current versions of my system - _all recently updated_:

- OS: Ubuntu 20.04
- Kernel: 5.8.0-53-generic
- Lutris: 0.5.8.3
- Wine: 6.8 Staging
- Mesa-Vulkan: 21.1.0 (kisak-mesa ppa / stable Mesa version)
- DXKV: 1.7.3L-03f11ba (latest on Lutris) / 1.8.1 (latest on the official Github)
- GPUs: AMD ATI Radeon R7 M260/M265 + Intel UHD Graphics 620

Follow as well the **log** from Lutris using **-d command** on terminal: https://paste.ubuntu.com/p/HjDK86rD6W/

I'm also attaching a txt file with the log:
[WoW Error Log (Lutris).txt](https://github.com/doitsujin/dxvk/files/6469909/WoW.Error.Log.Lutris.txt)

Battle.net and other games via Lutris are running just fine. It updated WoW today with no issues, by the way (after the problem was already occurring). And I use **no overlay** (discord or whatever)

Is any one having the same issue and/or just happened to find a solution for it?

Any help is very much welcome!

Many thanks,

**Comment by runboy93** [comment] 2021-05-13 11:26
Yeah I got same error since monday's (?) small patch (around 46MB) applied to WoW Classic, before it was all fine.

I think this is not the right place to report this problem, nothing to do with DXVK.

**Comment by wu-yue** [comment] 2021-05-13 12:10
Just tried mine. It still work fine.

I'm with a May 7th version WoW classic.

Running on official Steam Proton Experimental.

**Comment by runboy93** [comment] 2021-05-13 15:31
> Just tried mine. It still work fine.
> 
> I'm with a May 7th version WoW classic.
> 
> Running on official Steam Proton Experimental.

Latest version for WoW Classic is from 10th May, which caused this problem on my side, I was able to play still on 7th May update.

**Comment by gcapris90** [comment] 2021-05-13 15:43
> Yeah I got same error since monday's (?) small patch (around 46MB) applied to WoW Classic (latest small patch to 1.13.7), before it was all fine.
> 
> Retail version + PTR (Classic) with 2.5.1 patch works without any problems, so problem is only with Classic (1.13.7)
> 
> I just really hope TBC prepatch version in next week doesn't have this error...
> 
> I think you should do error reports also on lutris github / getting help on lutris discord.

**Comment by gcapris90** [comment] 2021-05-13 15:45
> Yeah I got same error since monday's (?) small patch (around 46MB) applied to WoW Classic (latest small patch to 1.13.7), before it was all fine.
> 
> Retail version + PTR (Classic) with 2.5.1 patch works without any problems, so problem is only with Classic (1.13.7)
> 
> I just really hope TBC prepatch version in next week doesn't have this error...
> 
> I think you should do error reports also on lutris github / getting help on lutris discord.

I've seen a post of yours from a week ago talking about the same problem. And just checked you already mentioned this topic in Lutris' Discord! Many thanks for that! I already posted this on other channels in the hope of finding a solution. If I get anything, I will reach out for you here on in Discord.

**Comment by gcapris90** [comment] 2021-05-13 15:47
> Just tried mine. It still work fine.
> 
> I'm with a May 7th version WoW classic.
> 
> Running on official Steam Proton Experimental.

I might try using Steam Proton Experimental. At this point I'm reinstalling the whole thing in Lutris to see if it works.

**Comment by gcapris90** [comment] 2021-05-13 23:59
Just to update this post, I've tried to reinstall all of the game, including Battle.net and it didn't work.

@wu-yue Could you explain how you made it possible to run using Steam Proton Experimental, please?

**Comment by amcduffee** [comment] 2021-05-14 05:08
I am encountering the same issue on DXVK versions starting somewhere in the v1.7 series.  I only spot checked various versions via Lutris, but came up with the following results:

Working
---------------------
v1.7L-9f6f6a7
v1.6.1L 

Broken
---------------------
v1.7.3L-03f11ba
v1.7.2L-5ca255d
v1.7.1L-743f309
v1.7.1L

So, maybe a dev with a bit more familiarity as to what might cause this could take a closer look and/or bisect between v1.7 and v1.7.1.

**Comment by doitsujin** [comment] 2021-05-14 10:23
> err:   D3D11CoreCreateDevice: Requested feature level not supported

Try using `DXVK_FILTER_DEVICE_NAME` to force DXVK to run on a proper GPU. For whatever reason the game is trying to run on llvmpipe.

**Comment by runboy93** [comment] 2021-05-14 11:39
> > err:   D3D11CoreCreateDevice: Requested feature level not supported
> 
> Try using `DXVK_FILTER_DEVICE_NAME` to force DXVK to run on a proper GPU. For whatever reason the game is trying to run on lavapipe.

Where to use that setting on lutris? Never used these DXVK settings, so this is new to me.

**Comment by wu-yue** [comment] 2021-05-14 11:40
> Could you explain how you made it possible to run using Steam Proton Experimental, please?
@gcapris90 Sure. I got these in my ~/.bash_aliases file:
`alias proton='/home/MY_USERNAME/.steam/steam/steamapps/common/Proton\ -\ Experimental/proton'

alias wow='cd "/home/MY_USERNAME/Downloads/world-of-warcraft-classic/drive_c/Program Files (x86)/Battle.net";export LANG=zh_CN.UTF-8;export STEAM_COMPAT_DATA_PATH=/home/MY_USERNAME/Downloads/world-of-warcraft-classic;proton run "/home/MY_USERNAME/Downloads/world-of-warcraft-classic/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe"'`

Then type"wow" to launch Battle.net

And I just received May 10th version, it works either.

**Comment by runboy93** [comment] 2021-05-14 12:12
But I wonder what is different on v1.7L-9f6f6a7 and v1.6.1L, compared to newer ones that don't cause this problem...

**Comment by runboy93** [comment] 2021-05-14 13:41
**Update!**

I got it working with ENV variable: DXVK_FILTER_DEVICE_NAME="GeForce" (I have NVIDIA MX150)

As I put only generic information there is error about "**warn: DXVK: No adapters found. Please check your device filter settings**"

**Comment by runboy93** [comment] 2021-05-14 15:12
Alright here some more testing:

With Vulkan loader = auto, everything seem to be correctly:
![vulkanloaderauto](https://user-images.githubusercontent.com/21213705/118290916-a42c3780-b4df-11eb-893b-c875f36917c6.jpg)

Vulkan loader = nvidia, there are errors about vulkan extension not supported and dxvkinstance error:
![vulkanloadernvidia](https://user-images.githubusercontent.com/21213705/118291086-dd64a780-b4df-11eb-91dc-edfbcf889724.jpg)

Despite all errors on Vulkan nvidia loader setting, everything is working ingame.

**Comment by gcapris90** [comment] 2021-05-14 16:58
> I am encountering the same issue on DXVK versions starting somewhere in the v1.7 series. I only spot checked various versions via Lutris, but came up with the following results:
> 
> ## Working
> v1.7L-9f6f6a7
> v1.6.1L
> 
> ## Broken
> v1.7.3L-03f11ba
> v1.7.2L-5ca255d
> v1.7.1L-743f309
> v1.7.1L
> 
> So, maybe a dev with a bit more familiarity as to what might cause this could take a closer look and/or bisect between v1.7 and v1.7.1.

I’ve tried some of those versions before but just to be certain, I’ve deleted the dxvk folder and let Lutris download it again. After that, I’ve downloaded 1.7 and 1.6.1 releases. None worked for me, though. And I could not find the v.1.7L-9f6f6a7 specific.

**Comment by gcapris90** [comment] 2021-05-14 17:07
> > Could you explain how you made it possible to run using Steam Proton Experimental, please?
> 
> @gcapris90 Sure. I got these in my ~/.bash_aliases file
> 
> alias proton='/home/MY_USERNAME/.steam/steam/steamapps/common/Proton\ -\ Experimental/proton'
> 
> alias wow='cd "/home/MY_USERNAME/Downloads/world-of-warcraft-classic/drive_c/Program Files (x86)/Battle.net";export LANG=zh_CN.UTF-8;export STEAM_COMPAT_DATA_PATH=/home/MY_USERNAME/Downloads/world-of-warcraft-classic;proton run "/home/MY_USERNAME/Downloads/world-of-warcraft-classic/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe"'
> 
> Then type"wow" to launch Battle.net
> 
> And I just received May 10th version, it works either.

I'm so sorry but I could not understand the information you've provided.

Do you play WoW in the Steam app? Do you use Lutris to start it? Or do you even start it from the terminal?
I had the idea you used Steam with Proton Experimental to play WoW in a Linux environment.

I wouldn't mind using both Steam or Lutris to set up the game. But I've tried on both and didn't succeed.

**Comment by amcduffee** [comment] 2021-05-14 17:14
Here are additional details about my setup:
- OS: Ubuntu 18.04.5 LTS
- Kernel: 5.4.0-72-generic
- Lutris: 0.5.8.3
- Wine: 6.8~bionic-1 (staging)
- Mesa-Vulkan:  21.1.0~kisak1~b (kisak-mesa ppa)
- GPU: AMD Radeon RX 5700 XT (NAVI10)

@gcapris90 We seem to be fairly close on configuration except for Ubuntu/Kernel version, which I don't yet suspect is the issue.

**Comment by amcduffee** [comment] 2021-05-14 17:44
Ok, I can confirm that forcing the following environment variable worked for me:

`DXVK_FILTER_DEVICE_NAME="NAVI10"`

The newest DXVK version I see in Lutris (v1.7.3L-03f11ba), which I previously marked as broken, is now working.  It is a bit odd that only the Classic version of the game seems to have an issue with selecting the GPU, but that appears to be the case.  The retail version of the game does *NOT* have the same problem.

To find an appropriate value to set for the DXVK_FILTER_DEVICE_NAME variable read the device filter info at https://github.com/doitsujin/dxvk#device-filter.  I used the following command and selected the unique enough 'NAVI10' value for my own GPU.  The correct value will be different for others:

`glxinfo | grep Device:`

If you are missing the 'glxinfo' command it can be installed via the 'mesa-utils' package on Ubuntu.

In Lutris, right click the game and select 'Configure' from the context menu.  Go to the 'System options' tab and scroll down to where it says 'Environment variable' and click the 'Add' button to add a new variable.  Put the variable name 'DXVK_FILTER_DEVICE_NAME' in the left column of the new row and an appropriately unique GPU string in the right column (found using 'glxinfo' above).  Click the 'Save' button and try launching WoW Classic again.

**Comment by gcapris90** [comment] 2021-05-14 18:17
@amcduffee @runboy93 

Amazing tips with great results, guys! Thanks!

I've tried altering just the **Vulkan ICD Loader** option on _System Options_ in Lutris and it worked for me (selecting the x86_64 version on both AMD and Intel graphics that I have).

Also tried altering just the Environment Variable setting up **DXVK_FILTER_DEVICE_NAME**. On my case, I've used the AMD RADV ICELAND value (no quotation marks).

Applying also the variable **DXVK_HUD=1, version**, when entering WoW, the Hud activates! Both worked for me for now! :)

It is also important to highlight that I've disabled the VSync option inside the game and I've deleted Lutris' dxvk folder (/home/user/.local/share/lutris/runetime/dxvk) just to let it download the latest version for itself. I've managed to this testing using **Wine 6.8 staging with DXVK 1.8.1 version**.

I will keep on testing to see if the game crashes or keep going smooth and stable. So far, so good!

**Comment by runboy93** [comment] 2021-05-14 18:48
@doitsujin 

Is there any way to get more specific device name to "DXVK_FILTER_DEVICE_NAME" for NVIDIA, than "GeForce", "NVIDIA" or "NVIDIA GeForce MX150"

Because there is still error "**warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.**", but yeah even there is that error, WoW Classic launches without any errors and game works smooth as usual before this problem.

**Comment by doitsujin** [comment] 2021-05-17 23:17
`vulkaninfo | grep deviceName` will print the device name for your GPU.

FWIW, unless the game is being weird, DXVK 1.8.1 should work without any env var trickery.

**Closed** 2021-05-18 08:52 UTC

**Comment by tie304** [comment] 2023-06-24 21:02
Hey for anyone who stumbles on this problem using: , DIVX 1.8.1 fixed it for me.

**Comment by agattorno** [comment] 2024-01-03 15:21
i solved this remove the line:
SET gxApi "OpenGL"
in wowfolder/WTF/Config.wtf
