### ISSUE TITLE
Bioshock (2007) crashes at loading screen in DX9 mode, low resolution textures in DX10

### ISSUE THREAD

**Issue by shoober420** [doitsujin/dxvk#1580] opened 2020-04-20 01:46 UTC
### Software information
Bioshock (2007), high settings

### System information
- GPU: GTX 760
- Driver: 440.82
- Wine version: Proton 5.0-6
- DXVK version: v1.5.5-21-g3d52ab36a

### Log files
- d3d9.log (no esync and fsync): [Bioshock_d3d9no9.log](https://github.com/doitsujin/dxvk/files/4500783/Bioshock_d3d9no9.log)
- d3d9.log (with esync and fsync): [Bioshock_d3d9yes9.log](https://github.com/doitsujin/dxvk/files/4500784/Bioshock_d3d9yes9.log)
- d3d11.log (no esync and fsync): [Bioshock_d3d11no10.log](https://github.com/doitsujin/dxvk/files/4500786/Bioshock_d3d11no10.log)
- d3d11.log: (with esync and fsync): [Bioshock_d3d11yes10.log](https://github.com/doitsujin/dxvk/files/4500788/Bioshock_d3d11yes10.log)

- Proton DX9 (no esync and fsync): [steam-7670no9.log](https://github.com/doitsujin/dxvk/files/4500775/steam-7670no9.log)
- Proton DX9 (with esync and fsync): [steam-7670yes9.log](https://github.com/doitsujin/dxvk/files/4500776/steam-7670yes9.log)
- Proton DX10 (no esync and fsync): [steam-7670no10.log](https://github.com/doitsujin/dxvk/files/4500777/steam-7670no10.log)
- Proton DX10 (with esync and fsync): [steam-7670yes10.log](https://github.com/doitsujin/dxvk/files/4500778/steam-7670yes10.log)

The original Bioshock will crash at the loading screen after starting a new game or loading a save game in DX9 mode, no matter what FSync and ESync is set to. DX10 mode runs, but it still requires that FSync and ESync be disabled in Wine / Proton to fix low resolution textures. (PROTON_NO_ESYNC=1 and PROTON_NO_FSYNC=1).

https://github.com/ValveSoftware/Proton/issues/388

**Comment by doitsujin** [comment] 2020-04-20 07:26
Can you please test with `master` / 1.6.1? Reporting bugs with an old DXVK version is a bit annoying because these problems might have been fixed already.

**Comment by K0bin** [comment] 2020-04-20 13:07
The textures look fine but i can reproduce the crash.

**Comment by shoober420** [comment] 2020-04-20 15:08
I figured out how to install the latest DXVK versions into Proton, at least on Arch. Using the "dxvk-bin" package in the Arch AUR, I extracted the .dll files into the following directories.

32bit: /home/$USER/.local/share/Steam/steamapps/common/Proton 5.0/dist/lib/wine/dxvk

64bit: /home/$USER/.local/share/Steam/steamapps/common/Proton 5.0/dist/lib64/wine/dxvk

Anyway, here are the logs using DXVK v1.6.1 with the crash still present.

- Proton: [steam-7670.log](https://github.com/doitsujin/dxvk/files/4504351/steam-7670.log)
- d3d9.log: [Bioshock_d3d9.log](https://github.com/doitsujin/dxvk/files/4504356/Bioshock_d3d9.log)

**Comment by shoober420** [comment] 2020-04-20 15:28
@K0bin 
I'm almost for certain, Proton by default will use installed versions of DirectX if present.

Even so, if I use the "WINEDLLOVERRIDES=d3dx10_33=n" launch option, I still have low resolution textures unless I disable ESync and FSync.

What version of Wine are you using? I'm on Proton 5.0-6+DXVK 1.6.1

**Comment by shoober420** [comment] 2020-04-20 15:28
@K0bin
I'm almost for certain, Proton by default will use installed versions of DirectX if present.

Even so, if I use the "WINEDLLOVERRIDES=d3dx10_33=n" launch option, I still have low resolution textures unless I disable ESync and FSync.

What version of Wine are you using? I'm on Proton 5.0-6+DXVK 1.6.1

**Comment by K0bin** [comment] 2020-04-20 15:35
I'm not using Wine. I've tried it with DXVK on Windows.

**Comment by shoober420** [comment] 2020-04-20 15:40
The low resolution textures are a issue with Wine itself, as @doitsujin pointed out.

**Comment by K0bin** [comment] 2020-04-21 18:55
The D3D9 crash might be another case of #1318. Try running it with the evictManaged option.

**Comment by shoober420** [comment] 2020-04-21 19:06
Proton defaults to use “ PROTON_FORCE_LARGE_ADDRESS_AWARE=1”, so that can’t be it.

**Comment by K0bin** [comment] 2020-04-21 19:11
`PROTON_FORCE_LARGE_ADDRESS_AWARE=1` extends the address space of 32bit processes from 2GB to 3GB. DXVK can still easily exceed that.

It works fine for me with the config option.

**Comment by shoober420** [comment] 2020-04-21 19:16
I’m saying that Proton already enables that option by default, so it’s not that.

I should also mention that the game launches successfully in DX9 mode when using the “PROTON_USE_WINED3D=1” option. So this is a DXVK issue directly.

**Comment by K0bin** [comment] 2020-04-21 21:31
`PROTON_FORCE_LARGE_ADDRESS_AWARE=1` is not enough to fix the problem and Proton does not turn on `d3d9.evictManagedOnUnlock` by default

**Comment by shoober420** [comment] 2020-04-22 01:21
How do I enable ‘’’d3d9.evictManagedOnUnlock’’’ under Proton?

**Comment by shoober420** [comment] 2020-04-22 13:28
I enabled ```d3d9.evictManagedOnUnlock``` in my ```dxvk.conf``` file and put it in the directory with the Bioshock.exe file (```/home/$USER/.local/share/Steam/steamapps/common/Bioshock/Builds/Release```). I still crash at the loading screen after selecting a save file.

**Comment by Blisto91** [comment] 2022-06-03 08:52
If you are still around then try K0bin's new PR https://github.com/doitsujin/dxvk/pull/2663
Link to latest version as of this moment: https://github.com/doitsujin/dxvk/actions/runs/2430711234

**Comment by K0bin** [comment] 2022-07-29 12:25
The low resolution textures with D3D10 are not a DXVK bug and the D3D9 crash should be fixed now.

**Closed by K0bin** 2022-07-29 12:25 UTC
