### ISSUE TITLE
Uplay overlay does not work with DXVK

### ISSUE THREAD

**Issue by afettouhi** [doitsujin/dxvk#870] opened 2019-01-19 20:30 UTC
### Software information
Running Watch Dogs installed via Lutris with the UPlay profile from Lutris. With DXVK 0.95 the game now freezes at the Ubisoft logo. Switching to version 0.94 the game luanches correctly and can be played.

### System information
- GPU: Nvidia GPU 1080 GTX
- Driver: 415.27
- Wine version: 4.0-rc5
- DXVK version: 0.95 & 0.94

### Log files
[Watch_Dogs_dxgi.log](https://github.com/doitsujin/dxvk/files/2775933/Watch_Dogs_dxgi.log)
[Watch_Dogs_d3d11.log](https://github.com/doitsujin/dxvk/files/2775934/Watch_Dogs_d3d11.log)

**Comment by massatt212** [comment] 2019-01-19 20:48
And injustice 2 doesn't launch with 0.95 also via windows works.with 0.94

**Comment by afettouhi** [comment] 2019-01-19 21:56
How do I do that? Disabling the Uplay overlay.

**Comment by massatt212** [comment] 2019-01-20 14:50
all i get is low FPS MSAA is broken and stuttering no crashes ill try play it longer next time

**Comment by afettouhi** [comment] 2019-01-20 15:53
Seems to be the Uplay overlay that is causing the crash with DXVK 0.95 and Watch Dogs. The game launches without issues when the overlay is turned off with DXVK 0.95. But with 0.94 the game runs with the overlay turned on!

**Comment by doitsujin** [comment] 2019-01-20 18:50
I'm aware that there is a regression with the Uplay overlay, this was already discussed in #858.

**Comment by afettouhi** [comment] 2019-01-20 20:22
> I'm aware that there is a regression with the Uplay overlay, this was already discussed in #858.

I wasn't thinking of that when I submitted this bug.

**Comment by massatt212** [comment] 2019-01-21 04:54
Almost every game works on origin if u disable in-game overlay

**Comment by afettouhi** [comment] 2019-01-21 07:18
> Almost every game works on origin if u disable in-game overlay

Strange that is not my experience at all.

**Comment by jcdutton** [comment] 2019-02-02 16:40
Is there anything we can do, in order to help find out how to get the overlay to work?

**Comment by doitsujin** [comment] 2019-11-24 22:13
Turns out that this was actually a Uplay overlay bug all along - the overlay hooks the Vulkan DLL, but crashes somewhere while doing that. Apparently this got fixed by a recent client update.

**Closed by doitsujin** 2019-11-24 22:13 UTC
Labels: bug

**Comment by guillaumezin** [comment] 2020-04-07 18:57
Seems to crash again with last version (26/03/2020) of Uplay and DXVF 1.6

What log would you need?

[wine-watch_dogs-crash.log](https://github.com/doitsujin/dxvk/files/4446508/wine-watch_dogs-crash.log)
[upc_d3d9.log](https://github.com/doitsujin/dxvk/files/4446516/upc_d3d9.log)
[debug.log](https://github.com/doitsujin/dxvk/files/4446519/debug.log)
[UplayService_dxgi.log](https://github.com/doitsujin/dxvk/files/4446520/UplayService_dxgi.log)
