### ISSUE TITLE
Call of Duty: Modern Warfare Remastered crash on campaign mission "Aftermath"

### ISSUE THREAD

**Issue by kernle32dll** [doitsujin/dxvk#2735] opened 2022-07-20 13:12 UTC
I try to play [Call of Duty: Modern Warfare Remastered on Steam](https://store.steampowered.com/app/393080/Call_of_Duty_Modern_Warfare_Remastered/), using [GE-Proton7-26](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton7-26). As per the [ProtonDB listing](https://www.protondb.com/app/393080), my run command is `DXVK_ASYNC=1 %command%`. Altho testing revealed that removing the `DXVK_ASYNC` flag does not solve the issue.

So the game runs fine for the most part. However, the game instantly crashes (= black screen, when DXVK hud is enabled it freezes) when loading the campaign mission "Aftermath". If I load the previous mission, and play "into" the buggy mission, I _sometimes_ get into gameplay. But after taking some steps, the game crashes all the same.

Just FYI, I was able to run the game via Steam on an improvised Windows 10 VM on my machine, and the game booted up right away (altho with < 1 FPS, cause I suck at VMs).

### Software information

- [Call of Duty: Modern Warfare Remastered via Steam](https://store.steampowered.com/app/393080/Call_of_Duty_Modern_Warfare_Remastered/)
- [GE-Proton7-26](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton7-26)

### System information
- OS: Arch Linux
- GPU: NVIDIA GeForce RTX 3090
- Driver: 515.57.0
- Wine version: bleeding edge
- DXVK version: v1.10.2-async

### Apitrace file(s)
Couldn't get it to create one... will come back to this if required.

### Log files
- d3d11.log: https://pastebin.com/tASdR4w3
- dxgi.log: https://pastebin.com/MwJ1LBHQ

The gist of it is this, occuring right as the game crashes:

```
err:   DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err:   DxvkDevice: waitForIdle: Operation failed
```

Also, per `VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation PROTON_LOG=1` I was gather some additional error, which is thrown twice in between the `VK_ERROR_DEVICE_LOST` errors:

```
VUID-vkResetDescriptorPool-descriptorPool-00313(ERROR / SPEC): msgNum: -1611285309 - Validation Error: [ VUID-vkResetDescriptorPool-descriptorPool-00313 ] Object 0: handle = 0x14c4440000002637, type = VK_OBJECT_TYPE_DESCRIPTOR_POOL; | MessageID = 0x9ff5bcc3 | It is invalid to call vkResetDescriptorPool() with descriptor sets in use by a command buffer. The Vulkan spec states: All uses of descriptorPool (via any allocated descriptor sets) must have completed execution (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkResetDescriptorPool-descriptorPool-00313)
    Objects: 1
        [0] 0x14c4440000002637, type: 22, name: NULL
```

**Comment by kernle32dll** [comment] 2022-07-20 20:52
Damn.

Well, I am building a proton build with dxvk `master` right now. I will come back with results, but I don't have high hopes. I do recall that some GE build I previously tested _was_ based on dxvk `master`. No harm in checking tho.

As for debugging - I think I have an AMD R9 390X laying around here..... somewhere. I might whip up a system for debugging some time, but this will definitely take a while (don't have a spare motherboard at hand).

One note - I did try out Wine3D for comparison, and the mission did at least load right away ([as right away as 30min load time are without async](https://www.protondb.com/app/393080#IZNFIY3-2I)). But performance was < 1 FPS, so I didn't bother checking further if if crashes down the line.

**Comment by kernle32dll** [comment] 2022-07-21 07:53
No dice.

GE7-26 adjusted to dxvk master:
Did not build, I think _some_ patch applied wrongly... Not sure its even dxvk related. I will just wait for GE to cut a new release with dxvk patches rebased to master.

Proton Experimental adjusted to dxvk master:
Did build, but the same black screen while trying to load the mission in question. When trying to load the previous mission, game + Linux DE crashed after loading for about 30minutes (Long load time is expected without async support)

**Comment by gabriele2000** [comment] 2023-01-31 01:38
Uh, guys... you might check #3227 and #3073 since it's the same damn problem and any apitrace seems useless?
On Modern Warfare 1 Remastered the problem is gone after a year of DXVK commits and it's replaced by a super-cool terrain-disappearing bug, fixed by enabling pre-calculated spot-shadows and sun-shadows, which are taxing as hell thanks for the super-optimization used for this crappy games.

**Comment by gabriele2000** [comment] 2023-01-31 01:46
> This is a GPU hang, which we can't really debug especially if there are no validation errors and if it works on more debuggable drivers (read: RADV). The error you posted is _caused by_ the crash, rather than the cause _of_ the crash.
> 
> You can try if it works with the current `master` branch.

How could I obtain the cause of the crash?
Keep in mind that in the first Modern Warfare now the crash is replaced by that bug that you can see in 3073 and now the crash is in 3227, more recent game but eventually same engine/stuff... without DXVK you can observe the same behaviour, either it crashes or there are those glitches with disappearing stuff.

**Comment by Timothy95p** [comment] 2023-05-08 07:31
This game is really great and plays very well. I bought this game at a good price on [this](https://royalcdkeys.com/products/call-of-duty-modern-warfare-2-2022-cross-gen-edition-us-ps4-5-cd-key) site. I recommend it to anyone looking for a good price.

**Comment by Blisto91** [comment] 2023-05-08 11:55
No there is no fix out.

**Comment by rakshith-ravi** [comment] 2023-05-10 06:54
I'm unable to load the level at all, and am unable to move past this one. Anything you recommend I can try?

**Comment by Blisto91** [comment] 2023-05-10 09:42
If it's related to the blackout issue try to turn either `CACHE SUN SHADOW MAPS` **on**  or `shadows` **off**.
If that doesn't work then i don't you and you'll probably have to play without dxvk.

**Comment by rakshith-ravi** [comment] 2023-05-10 18:00
Oh hey that worked! Thanks for the suggestion @Blisto91. Much appreciated! I can finally move past that level now.

For others finding this - I turned off shadows completely and was able to load the level without any issues

**Comment by Blisto91** [comment] 2024-10-21 18:44
@kernle32dll @rakshith-ravi Are you able to give this a retry with dxvk master?

**Comment by kernle32dll** [comment] 2024-10-22 22:53
@Blisto91 Sure, I will test

**Comment by kernle32dll** [comment] 2024-10-24 00:10
Can confirm issue is gone. Made a custom ProtonGE build with f813549ced659358a018d657cab43e50f00ca2ab, and it works beautifully.

**Closed** 2024-10-24 09:38 UTC
Labels: nvidia proprietary
