### ISSUE TITLE
Assetto Corsa artifacting and GPU hangs

### ISSUE THREAD

**Issue by Lahvuun** [doitsujin/dxvk#648] opened 2018-09-18 19:09 UTC
Disabling reflections in Assetto Corsa causes image artifacts and general GPU instability.

### Software information
[Assetto Corsa](https://store.steampowered.com/app/244210/Assetto_Corsa/)

### System information
- GPU: AMD Radeon RX 560
- Driver: mesa-git-c9dbe52f848ae795ae9fdd7cbeca857db27dcc48
- Wine version: wine-staging-3.16
- DXVK version: dxvk-git-bf5476900ada0714a86737ddc96683721bffc605
- LLVM: llvm-git-fbb826fa5c2e828f0e27944ae92c60fe68208609

### Apitrace file(s)
https://drive.google.com/open?id=1yvh6uJg-p0IMrEo9bropR-KVCLIc_UEX

### Log files
- d3d11.log: [acs_d3d11.log](https://github.com/doitsujin/dxvk/files/2394187/acs_d3d11.log)
- dxgi.log: [acs_dxgi.log](https://github.com/doitsujin/dxvk/files/2394188/acs_dxgi.log)
- dmesg log of a GPU hang: [dmesg.log](https://github.com/doitsujin/dxvk/files/2394200/dmesg.log)

**Comment by doitsujin** [comment] 2018-09-18 19:15
In case of GPU hangs, please check #252.

When replaying the trace I pretty much instantly get a GPU hang, is that what happens in the game as well or is this an additional issue caused by apitrace?

**Comment by doitsujin** [comment] 2018-09-18 19:35
Do you have access to a Windows machine, and if so, can you record an apitrace there? Something's fishy there.

The GPU hang occurs because the game tries to create a texture with a size of 0x0, and DXVK doesn't return the appropriate error code. This is fixed with 837a3f5787c23e4b583ce6cdbca8fe1d8a4b5be6, and replaying the apitrace will now crash because the texture cannot be created.

**Comment by doitsujin** [comment] 2018-09-18 19:55
Update: I got a Windows trace from someone else, and it appears that the game creates a 2048x2048 texture where it creates a 0x0 texture in your trace. No idea why though.

Does the game now work correctly with latest `master` or are there still issues?

**Comment by doitsujin** [comment] 2018-09-19 10:07
> Are reflections disabled in that apitrace?

I asked and got another one with reflections disabled this time. The game does indeed try to create a 0x0 texture and keeps using it, which results in errors and silently dropped calls with native D3D11 but caused DXVK to crash.

Should be fixed in a95f292dcce681269654576d657b5dcb675540d7, please test if it works now.

**Comment by Lahvuun** [comment] 2018-09-19 10:27
https://github.com/doitsujin/dxvk/commit/a95f292dcce681269654576d657b5dcb675540d7 fails to build for me: https://pastebin.com/RYVG8Jgp

Am I doing something wrong?

**Comment by doitsujin** [comment] 2018-09-19 10:35
Sorry, my fault. Should be fixed now.

**Comment by Lahvuun** [comment] 2018-09-19 10:50
https://github.com/doitsujin/dxvk/commit/35238ec4d11cbf280209fab82ec2f85879e4c128 completely resolves the issue for me: no artifacting, no previous GPU issues.

**Comment by doitsujin** [comment] 2018-09-19 11:06
Thanks for the quick feedback.

**Closed by doitsujin** 2018-09-19 11:06 UTC
Labels: bug
