### ISSUE TITLE
Sonic Frontiers Major Rendering Issues on AMD 7900XTX

### ISSUE THREAD

**Issue by SolarNyan** [doitsujin/dxvk#3223] opened 2023-01-29 01:53 UTC
### Software information
Sonic Frontiers, official Valve Proton (Experimental, Next, and 7.5)and latest ProtonGE tested, OpenSUSE Tumbleweed with latest Mesa drivers.

### System information
- GPU: 7900XTX Red Devil
- Driver: Mesa 22.3.3-339.1x86_64
- Wine version: 8.0.1.1-x86_64
- DXVK version: 1.10.2-1.2-x86_64

### Apitrace file(s)
From what I read, Apitrace does not work with Frontiers.

### Log files
[SonicFrontiers_d3d11.log](https://github.com/doitsujin/dxvk/files/10528765/SonicFrontiers_d3d11.log)

Large amounts of land isn't rendered, leaving the map heavily borked, with collision still in-tact:

![20230128201251_1](https://user-images.githubusercontent.com/103155847/215299897-61147d69-9903-4df2-8ef9-7bc5085f0376.jpg)
![20230128201328_1](https://user-images.githubusercontent.com/103155847/215299898-ba042a3a-70ab-4812-91e1-8fba15c576a0.jpg)
![20230128201341_1](https://user-images.githubusercontent.com/103155847/215299899-6f1e9eb6-af5d-4996-b522-436c2e41ef68.jpg)

**Comment by doitsujin** [comment] 2023-01-29 02:06
Are we sure this isn't just a driver bug with the new cards?

I've tested this game quite a lot on both the Steam Deck and my desktop (6900XT) and have never seen anything like this at all.

**Comment by SolarNyan** [comment] 2023-01-29 02:42
> Are you sure this isn't just a driver bug with the new cards?
> 
> I've tested this game quite a lot on both the Steam Deck and my desktop (6900XT) and have never seen anything like this at all.
> 
> Also
> 
> > DXVK version: 1.10.2
> 
> ~Why are you using such an ancient version of DXVK? It's not really useful to report issues with something that's 6 months out of date...~ Actually the logs indicate that this must be on 2.1, so this info is kinda wrong.

That's the version of DXVK OpenSUSE ships in their repo when looking in YaST, it seems. That log was generated using the latest ProtonGE, which I think comes with latest DXVK by default and just uses that? I also thought it was super weird Tumbleweed was telling me that was my installed DXVK, and Tumbleweed is supposed to be rolling so I woulda thought they'd be shipping the latest...

There are decent odds that it's probably just a funky driver bug ATM. These cards are only like, a month old and even rolling distros are gonna have funky stuff for a good couple of months. FWIW, Frontiers is the only game I've had major issues like this running (so far), everything else has been running like a dream.

The only thing that caught my eye in the log here that I thought _might_ be of interest was this:

>info:  DXVK: Graphics pipeline libraries not supported
>info:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported
>err:   D3D11RasterizerState: Antialiased lines not supported

Granted, I have no idea if that's related to the issue or not.

**Comment by doitsujin** [comment] 2023-01-29 03:01
It's not. Again, game should [generally work](https://www.protondb.com/app/1237320) just fine, and I can't reproduce this problem at all.

**Comment by SolarNyan** [comment] 2023-01-29 03:14
It's probably a mesa driver issue, then. Thanks for taking the time to look at it, though, being able to rule out DXVK makes things pretty simple, as it probably means I'll just have to wait a couple of months for this to get patched out in mesa lol.

**Comment by Blisto91** [comment] 2023-02-03 23:23
I can reproduce this on my 7900xtx. You can work around it temporarily if you want by launching the game with `RADV_DEBUG=nodcc`
I will look into making a mesa issue.

**Comment by SolarNyan** [comment] 2023-02-04 00:30
> I can reproduce this on my 7900xtx. You can work around it temporarily if you want by launching the game with `RADV_DEBUG=nodcc` I will look into making a mesa issue.

Thank you for commenting on this! Knowing it isn't just my system doing this with the game is reassuring, oddly enough, lol.

I'll try using that work-around in the meantime, though. Hopefully it'll be patched out soon. :)

**Comment by Blisto91** [comment] 2023-02-08 19:21
Upstream MR will work around the issue https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21186

**Comment by Blisto91** [comment] 2023-02-14 09:03
MR has been merged into main

**Closed** 2023-02-14 09:07 UTC
Labels: amd radv, can't reproduce
