### ISSUE TITLE
EVE Online issues

### ISSUE THREAD

**Issue by sdack** [doitsujin/dxvk#402] opened 2018-05-28 18:46 UTC
#### Issues with known fixes
- For those who are experiencing hangs with EVE Online in combination with the Nvidia driver please try disabling **Allow Flipping** in the Nvidia settings panel under the _OpenGL Settings_. See also here: https://github.com/doitsujin/dxvk/issues/341
- The game's VSync settings of _Interval Two_ to _Four_ are known to produce 60fps instead of the expected 30fps, 20fps and 15fps. This issue has been fixed with https://github.com/doitsujin/dxvk/commit/e615fc19a91891828919e0029d73cec77553636a .
- Video capture may produce a static image when the game is rendered under DXVK (possibly a Vulkan/Nvidia issue). For it to work does one need to enable a composition pipeline in the Nvidia driver settings (see _X Server Display Configuration -> Advanced_).
- Problems in combination with the Linux launcher can be worked around by using the game's standard Windows Launcher under WINE.

#### Known Graphical Issues without fixes
- Flickering of the 1st person HUD.
- Flickering of the speed meter and the outer ring around the game's HUD.
- Flickering of the background logo during character creation.
https://www.dropbox.com/s/gecehtd0b0uz3no/vulkan.mkv
- Some background triangles don't render. https://github.com/doitsujin/dxvk/issues/402#issuecomment-394081891

#### Other Issues
- Game minimizes randomly. (Xfce4)
- Game becomes lowest window when in fullscreen mode. (Xfce4)
- Hanging clients after the Linux launcher exits. (KDE)
- High CPU usage of the Linux launcher. (KDE)

#### System Information
WINE 3.9, Nvidia 396.24.02 (GTX960), DXVK 0.53, Xfce4, Debian 10 "Buster"
WINE 3.9, Nvidia 396.24 (GTX1070), DXVK 0.53, KDE, Ubuntu 18.10 (dev branch), kernel 4.17rc7

[d3d11.log](https://github.com/doitsujin/dxvk/files/2045913/d3d11.log)
[dxgi.log](https://github.com/doitsujin/dxvk/files/2045914/dxgi.log)

@doitsujin I have no idea on how to create an apitrace at the moment. The .dll files provided by varis1 only produce crashes and the game itself is started by a launcher application, which cannot be worked around.

**Comment by varris1** [comment] 2018-05-28 19:06
I am not Doitsujin, but you can use this for easy tracing:
https://www.dropbox.com/sh/o769ius47wpu3pw/AABYFKQFFNsCsosXhl7_HReDa?dl=0
just put the correct dlls into the game folder and the apitrace will generate a <exename>.trace file.

If you fear for your account, you can create a throwaway one. Afaik nobody has been banned for using reshade yet, so I don't think apitrace will be a problem.

**Comment by sdack** [comment] 2018-05-28 19:33
@varris1 Thanks, I'll do this, but I first have to wait for CCP to respond to my requests. This is a matter of courtesy.

I've also now seen the patch for the VSync issues and have tested it. Works perfectly. Thank you!

**Comment by 3vi1** [comment] 2018-05-29 10:55
@sdack:  Which desktop are you using on your Debian setup?  Is it Gnome/Wayland?  I'm just curious because I'm using KDE/Xorg on the Ubuntu 18.10 dailies and I don't see the minimizing or bottom-most problem you've seen with the game window.

I do see the other issues you've reported (hud flicker, etc.).  I'm testing now with your suggestion to disable OpenGL flipping to see if it stops the random hangs.

**Comment by sdack** [comment] 2018-05-29 12:22
@3vi1 Says up there in the description. Can you spot it?

**Comment by 3vi1** [comment] 2018-05-29 12:35
Ah, Xfce4.  Must have skipped over it from "x burnout".  :)  That's weird, I would not have expected such odd behavior there.

**Comment by sdack** [comment] 2018-05-29 13:05
@3vi1 Don't worry about it. The game is playable with glitches and odd window behavior. This issues thread is here to collect all these. Other games have more pressing issues. So don't expect things to move fast here.

**Comment by 3vi1** [comment] 2018-05-30 02:13
Tested for several hours and found a couple of additional issues:  The launcher is suddenly eating a lot of CPU, and closing the launcher causes any game clients you have running to hang.  

I played two 1280x1080 windows on my external monitor for 2+ hours with no issues, but I eventually noticed that the launcher had started consuming a lot of CPU at some point.  So, I closed the launcher.  Within 10 seconds, both client windows froze.

I killed the hung clients, restarted the launcher, launched both clients again and waited a few minutes.  Everything was going fine, until I then I retested closing just the launcher window again.  Within a few seconds, both game client windows froze.

Killed/restarted everything again, and see the launcher eating a ton of CPU after only a few minutes of uptime:

`  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                              
14683 evil      20   0 2292080 1.139g 157808 R 150.0  3.6  15:10.31 exefile.exe                                                          
14768 evil      20   0 2288288 1.124g 154428 R 143.8  3.6  16:09.48 exefile.exe                                                          
13508 evil      20   0 4632060 1.560g 115088 R 137.5  5.0  10:01.95 evelauncher    `

**Comment by sdack** [comment] 2018-05-30 12:55
I've tried to capture the problem in a video. Turns out video capture doesn't work either. This is what it should look like (DX11 over OpenGL):
https://www.dropbox.com/s/ab0deov02nhfui3/orig.mkv
The capture of the game when render over Vulkan produces a static picture with only the mouse moving:
https://www.dropbox.com/s/mbtuonebxigyefg/vulkan.mkv
Here is a screenshot however of how the HUD in the center is getting damaged and starts to flicker:
https://www.dropbox.com/s/xhoi2sjuvdg6mxx/Screenshot_2018-05-30_13-31-41.png

All see if I can create another account and then run an API trace. CCP support only gave a "pick the bones out of this" type of response and it was likely just above their heads. Gone respect that, not doing it with my accounts, but will have to make one for it.

**Comment by sdack** [comment] 2018-05-30 13:54
@3vi1 I've seen the update, but I have no issues with the launcher, not with the CPU or with any hanging clients. Which launcher are you using?

**Comment by 3vi1** [comment] 2018-05-30 16:49
@sdack:  I'm using the native Linux launcher:  https://binaries.eveonline.com/evelauncher-1104891.tar.gz

**Comment by sdack** [comment] 2018-05-30 17:05
@3vi1 I thought so. Just remember it doesn't use WINE nor DXVK. Only the game client does. So any issues with the Linux launcher happen outside of WINE and DXVK.

On a different note, video capture now works. One needs to enable a composite pipeline in the Nvidia settings for ffmpeg to produce a proper video.

https://www.dropbox.com/s/gecehtd0b0uz3no/vulkan.mkv

**Comment by 3vi1** [comment] 2018-06-02 11:55
Additional bug:  Some background triangles don't render.  For instance, the image on the login screen when running in windowed mode consistently isn't drawing the bottom right triangle. ![as seen here](https://i.imgur.com/03aj7xj.png).

I can see the same effect in-game, also consistently but only on one of my accounts, in the background of the neocom panel.  The specific size of the panel/window may be a factor, as I see neither of these issues on other accounts running in different sized windows.

**Comment by sdack** [comment] 2018-06-02 14:45
@3vi1 I don't have this issue.

**Comment by 3vi1** [comment] 2018-06-07 13:50
> Also, have you tried using 296.24.02 yet?

I've updated to 396.24.02, and I still see the issue.  In fact, after resizing the windows a bit, I see it on both accounts.  What's more, I see it on both triangles of the background (entire background is black) now.  I don't see it on other accounts that I launch in fullscreen or large fixed-window sizes.

Also, I don't find using the windows launcher to be a suitable workaround to the native launcher issues.  I've been testing it since last weekend and the windows launcher a) has to be run WinXP mode due to Wine's perpetual IO completion ports issues and the way Qt5WebEngine behaves in Vista and later mode.  b) it FREQUENTLY crashes or hangs - taking all open game clients with it.  And, like the native launcher, it has none of these problems if you launch the clients in DX9 mode.

**Comment by 3vi1** [comment] 2018-06-15 12:41
I noticed something about the missing triangle on the start screen today.  That only seems to happen when I open the window on my 2560x1080 external screen.  If I open the same client on my 1920x1080 laptop screen, both triangles render fine.  Odd.  I'm not sure why the screen/aspect would even matter for a client starting in windowed mode.

**Comment by chrisharper** [comment] 2018-07-07 09:41
I can confirm resource usage(CPU+MEM) increase occurs when using the launcher and a game client is launched. I believe this is due to game client -> launcher communication with regards to logging .

If you check the launcher logs (~/.local/share/CCP/EVE/Launcher) you will note many of the following messages

`D3D11DeviceContainer::QueryInterface: Unknown interface query`

If however you set 

`DXVK_LOG_LEVEL=none`

this turns off the logging and resolves the increasing resource usage.

**Comment by chrisharper** [comment] 2018-07-08 13:01
Create a bash script that sets it and also runs the launcher (evelauncher/evelauncher.sh).

This will also allow you to set other config options in one location without making them global configs or getting removed on updates

**Comment by 3vi1** [comment] 2018-07-16 10:34
I can confirm chrisharper's log level solution fixes the biggest problems:  1)  It seems to stop the game from crashing if using the Windows launcher under wine and leaving it open with multiple clients running.  and 2) It stops the launcher from uploading tons of spam to CCP:  I noticed it was uploading 20kb/s+ the entire time the game was running if I left the launcher open before, whereas after setting the log variable it seems to have dropped of to practically nothing.

**Comment by ForlornWongraven** [comment] 2018-07-16 14:49
I can confirm this working well even with 0.54 (as I am stuck with Mesa > 18.0.5).

**Comment by 3vi1** [comment] 2018-09-23 20:06
As of the 394.54.05 Nvidia drivers (and most probably since the .02 driver), all the items referenced in the OP's "Known Graphical Issues without fixes" section appear to be resolved!  As long as you run the game with DXVK_LOG_LEVEL=none, the game appears to be working 100% here.

**Closed** 2019-02-28 14:34 UTC
Labels: bug, help wanted
