### ISSUE TITLE
After 2caa3c9 Tests D3D11 Going mad 

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#1438] opened 2020-02-11 14:07 UTC
Tk-Glitch BKGBUILD. Other Commits going to D3D9 allright

**Comment by Waddlen** [comment] 2020-02-11 15:44
Opening issues like this is almost certainly **not** helpful to the developers, nor was #1423 or #1337. Issues are for reporting bugs or regressions. If you are trying to report a bug, you did not provide enough information.

**Comment by doitsujin** [comment] 2020-02-11 16:01
The changes after 2caa3c9 do not affect D3D11 in any way.

Closing because this bug report contains no info.

**Closed by doitsujin** 2020-02-11 16:01 UTC
