### ISSUE TITLE
Farming Simulator 19 black screen with nvidia (optimus)

### ISSUE THREAD

**Issue by wioo** [doitsujin/dxvk#775] opened 2018-11-20 12:29 UTC
### Software information
Farming Simulator 19

### System information
- GPU: nvidia GTX 950M
- Driver: 410.73.0
- Wine version: 3.20
- DXVK version: 0.92

### Apitrace file(s)
https://drive.google.com/open?id=1s9nd7Ls5-t7BQo1Uj70i-aGX3HDTFNSd
(7z arhive)

### Log files
- d3d11.log: 
[FarmingSimulator2019Game_d3d11.log](https://github.com/doitsujin/dxvk/files/2599515/FarmingSimulator2019Game_d3d11.log)

- dxgi.log: 
[FarmingSimulator2019Game_dxgi.log](https://github.com/doitsujin/dxvk/files/2599518/FarmingSimulator2019Game_dxgi.log)

Screenshot
![fsscreen_2018_11_20_12_19_59](https://user-images.githubusercontent.com/8883640/48772240-0ff10900-ecc4-11e8-83ef-14bda59650ab.png)
![fsscreen_2018_11_20_12_21_38](https://user-images.githubusercontent.com/8883640/48772246-154e5380-ecc4-11e8-9e97-92cafdb70e70.png)

I am using arch linux. Tried with dxvk-bin and dxvk-git packages from aur. Tried wine versions 3.20, 3.19, 3.18, 3.20 staging, proton 3.7 and 3.16. It works with intel integrated graphics (HD 530).

Computer uses nvidia optimus. I am using nvidia-xrun to load nvidia drivers.

**Comment by doitsujin** [comment] 2018-11-20 12:41
Does this also happen when you replay the apitrace using `d3dretrace.exe`? On my system, the trace renders just fine.

**Comment by wioo** [comment] 2018-11-20 13:00
Yup, same black screen.

**Comment by Askannz** [comment] 2018-11-20 13:05
On my system the apitrace plays just fine, without a black screen.

![image](https://user-images.githubusercontent.com/9202863/48775417-ed80df00-ed07-11e8-927a-34011b1e3826.png)

Same software versions (Nvidia driver 410.73, wine staging 3.20, DXVK 0.92), on a GTX1060. It's also an Optimus machine, although I do not use nvidia-xrun.

**Comment by wioo** [comment] 2018-11-20 13:11
Interesting. How do you load your games then? Afaik I can't use primusrun with dxvk.

**Comment by Askannz** [comment] 2018-11-20 13:15
I use this method : https://wiki.archlinux.org/index.php/NVIDIA_Optimus#Using_nvidia plus a custom script that allows to revert back easily to the Intel configuration. I've released it publicly a few days ago, you can check it on my GitHub profile if you want.

**Comment by Askannz** [comment] 2018-11-20 14:10
So out of curiosity I ran the apitrace on my old laptop with a Kepler card (GT650M), and I was able to reproduce your issue.

![farming2](https://user-images.githubusercontent.com/9202863/48778818-21accd80-ed11-11e8-85ef-98a04a04143f.png)

**Comment by wioo** [comment] 2018-11-20 16:14
Tried with nvidia 410.66 and 410.78. Same problem.
Btw, it works in win10 if that helps in any way.

**Comment by doitsujin** [comment] 2018-11-22 08:50
Can reproduce this on my GTX 670, seems to be specific to older Nvidia architectures.

**Comment by wioo** [comment] 2018-11-22 14:21
> @pdaniell It looks like there's a driver bug related to clearing individual slices of a 3D texture. Here's what happens:
I think you ment pdaniell-nv.

**Comment by doitsujin** [comment] 2018-12-04 22:24
Should be fixed as of 6eae27bd2108ba0ab8f68cf0f558b4ad6acf8cce.

**Closed by doitsujin** 2018-12-04 22:24 UTC
Labels: nvidia
