### ISSUE TITLE
Lightning issue with Prey(2017).

### ISSUE THREAD

**Issue by eugenydn** [doitsujin/dxvk#308] opened 2018-04-19 20:12 UTC
I am having problems with Prey(2017). Lighting inside buildings does not work(just all black).
When I launch it with apitrace the game hangs in the main menu.
![1](https://user-images.githubusercontent.com/38526198/39015589-7c8b76aa-4426-11e8-90ef-23083dbda904.png)
![2](https://user-images.githubusercontent.com/38526198/39015597-84351514-4426-11e8-9c63-f111d5e23f2f.png)
![3](https://user-images.githubusercontent.com/38526198/39015603-88eb3b6a-4426-11e8-82b8-14c05df51cee.png)

### Software information
Game: Prey(2017)
Settings: tried all

### System information
- GPU: nvidia gtx 1050ti
- Driver: 390.48
- Wine version: wine-3.6 (Staging)
- DXVK version: aur/dxvk-git 20180413.8dfe708-1 (11, 5,46) [installed: 20180418.8eb7859-1]

### Log files
- d3d11.log:
[Prey_d3d11.log](https://github.com/doitsujin/dxvk/files/1929609/Prey_d3d11.log)
- dxgi.log:
[Prey_dxgi.log](https://github.com/doitsujin/dxvk/files/1929610/Prey_dxgi.log)

**Comment by Kerrung** [comment] 2018-04-19 20:19
@eugenydn  Try the newest Nvidia beta driver. I heard that it fixed this issue.

**Comment by doitsujin** [comment] 2018-04-19 20:29
I don't see any "failed to compile pipeline" issues in the log, but it might still be worth checking out.

I can try the demo at some point but in general, without an apitrace, issues like this are basically impossible to debug.

**Comment by eugenydn** [comment] 2018-04-19 20:50
Новый драйвер не помог, но мне удалось загрузить локацию с apitrace. Надеюсь это поможет.
https://drive.google.com/file/d/1CY5AF-gS8wn45DQ3skUfhl7zoQEK9wuM/view?usp=sharing

**Comment by eugenydn** [comment] 2018-04-19 22:15
I think this is related to GTAV "shadow issue" https://github.com/doitsujin/dxvk/issues/286

**Comment by Guy1524** [comment] 2018-04-20 02:56
The shadow issue is fixed with the new driver

**Comment by eugenydn** [comment] 2018-04-20 05:46
Its not related then.
![4](https://user-images.githubusercontent.com/38526198/39032698-55fcdf96-4477-11e8-94f9-c4c66fa6dcde.png)

**Comment by SveSop** [comment] 2018-04-20 08:39
The latest beta that fixes shadows should be 396.18.02 @eugenydn 
[https://developer.nvidia.com/vulkan-driver](https://developer.nvidia.com/vulkan-driver)

**Comment by eugenydn** [comment] 2018-04-20 09:45
Not helped(
![5](https://user-images.githubusercontent.com/38526198/39044407-bad1a07a-4498-11e8-9a07-13fab930dd69.png)

**Comment by doitsujin** [comment] 2018-04-20 10:06
> Can anyone explain me in basic words, why d3d->vulkan is faster then d3d->opengl?

Please **no off-topic discussions** in bug reports.

**Comment by SveSop** [comment] 2018-04-20 10:51
@eugenydn I wonder if there is anything to be found if i run some "cryengine" demo or something? See something called "The Office", but im unsure if this is a runnable demo, or some demo of a program to write graphics stuff with?

**Comment by sambow23** [comment] 2018-04-20 13:58
The lighting goes back to normal when you reach the lobby after the prologue.

**Comment by d3rrial** [comment] 2018-04-20 16:42
It should be related to Bloom, at least partially. Same issue exists in GTA V, and also only indoors.

**Comment by doitsujin** [comment] 2018-04-20 17:50
Just because the issue *looks* similar on the surface doesn't mean at all that they are related. Theorizing about that really only makes sense if you have actual data backing that up.

**Comment by d3rrial** [comment] 2018-04-20 18:14
My apologies.

**Comment by eugenydn** [comment] 2018-04-20 21:45
I tried some small games and demos from cryengine forum and unable to reproduce this issue.
Also i recorded some interesting video with this issue: https://youtu.be/pDaye_uh2rc
I can make an apitrace of the moment when someone switch off the lights in that room. Do you need it?

**Comment by Enverex** [comment] 2018-04-28 16:49
Is this likely to be the same issue as Wreckfest has? Looks fine except for areas in shadow which are almost jet-black.

![image](https://user-images.githubusercontent.com/958670/39398823-9a108eb8-4b0b-11e8-9583-e6fdfde27bcf.png)

**Comment by doitsujin** [comment] 2018-04-28 16:53
Different games, different engines, different issues. I'm aware of the Wreckfest problem though and I do have an apitrace to reproduce it.

**Comment by YuriNenakhov** [comment] 2018-05-07 07:10
Seems to be working fine now.
![screenshot_20180507_160705](https://user-images.githubusercontent.com/11544070/39689240-02b70e72-5211-11e8-9621-90067458e87c.png)

**Comment by doitsujin** [comment] 2018-05-07 11:43
Should indeed be working, this seems to have been the same issue that prevented Far Cry 5 from working.

**Closed by doitsujin** 2018-05-07 11:43 UTC
Labels: bug
