### ISSUE TITLE
Sekiro - disappearing objects, and invisible enemies

### ISSUE THREAD

**Issue by phush0** [doitsujin/dxvk#994] opened 2019-04-02 15:32 UTC
Game is starting, menus are perfect, but when you reach to your character, and he don't move object in distance disappear and after some time appear again, nonstop. It is not connected with camera movement. When Character starts to run, model disappear also. Enemies are invisible. Even when locked. Have tried same with original mesa of Ubuntu 18.04. Then with Oibaf PPA. Result is the same. Also tried with Proton 4.2, 3.16-8, 3.16-6 and 3.7 with default DXVK

### Software information
Sekiro - Shadows Die Twice

### System information
- GPU: VegaM (8706G)
- Driver: RADV 19.1 git Padoka PPA
- Wine version: proton 4.2
- DXVK version: 1.0.1

### Log files
[sekiro_d3d11.log](https://github.com/doitsujin/dxvk/files/3034682/sekiro_d3d11.log)
[sekiro_dxgi.log](https://github.com/doitsujin/dxvk/files/3034683/sekiro_dxgi.log)

**Comment by doitsujin** [comment] 2019-04-02 15:34
Can't reproduce, the game renders perfectly on my RX 480.

Also, you have this in your config file:
```
d3d11.relaxedBarriers = 1
```
This is **expected** to cause rendering issues in most games; please don't report issues with it enabled.

**Comment by phush0** [comment] 2019-04-02 15:42
Yes this was for test, it will not make any difference  in rendering. Errors are same with or without it

**Comment by doitsujin** [comment] 2019-04-02 15:47
The interesting bit in your log is this:
```
warn:  DxvkQueryPool: Failed to get query data for 124:4 with: VK_NOT_READY
```
Not sure why this fails. This is most likely what causes your rendering issues, but there's no obvious reason why retrieving query data would fail on your hardware.

**Comment by phush0** [comment] 2019-04-02 16:07
Shall I delete cache before test?

**Comment by phush0** [comment] 2019-04-02 17:40
[sekiro_d3d11.log](https://github.com/doitsujin/dxvk/files/3035234/sekiro_d3d11.log)
[sekiro_dxgi.log](https://github.com/doitsujin/dxvk/files/3035235/sekiro_dxgi.log)

This is with master version, nothing is flickering now, no problems with cache too.

**Comment by phush0** [comment] 2019-04-02 19:36
well this fixes Sekiro for me, but breaks everything else. Witcher 3 is on blue and yellow trinagels, Assasins Creed: Odyssey stay on black screen with dxvk info. And so on.

**Comment by bobberb** [comment] 2019-04-16 17:54
sorry to but in but if one install sekiro the legal way through steam is it possible to inject a different dxvk here?

**Comment by phush0** [comment] 2019-04-16 19:00
replace files in 
`~/.steam/steam/steamapps/common/Proton 4.2/dist/lib/wine/dxvk`
and
`~/.steam/steam/steamapps/common/Proton 4.2/dist/lib64/wine/dxvk`

**Comment by hakzsam** [comment] 2019-05-02 15:19
Are you still able to reproduce the rendering issue?

**Comment by phush0** [comment] 2019-05-02 16:27
With master branch Sekiro is OK, very playable, no flickering and no message about vulkan problems. Wine will crash on my machine will NULL pointer reference and it is crashing inside main exe nothing connected with graphics or so on. FPS are around 40 same as 1050ti on my other laptop (where game crashes also). Also I tried it on Vega 56 eGPU also around 40 FPS. With master I have problem with Unreal engine games like Hellblade. Intro starts ok and when start main part of game it is 2 FPS. GPU is 0% load. with 1.0.3 it is OK ~ 35 fps.

**Comment by doitsujin** [comment] 2019-05-02 17:00
That's interesting, Hellblade is actually one of those games that should benefit from `master` (and definitely not run at 2 fps).

**Comment by phush0** [comment] 2019-05-02 17:07
one core 100 %

**Comment by doitsujin** [comment] 2019-05-02 17:21
Probably waiting on an occlusion query then. Can't reproduce the problem on my RX 480 or on my Kaveri APU though, seems to be Raven-specific.

**Comment by phush0** [comment] 2019-05-02 17:27
And VegaM

**Comment by doitsujin** [comment] 2019-05-02 17:28
Ah right, you're on that weird thing that isn't Raven.

**Comment by doitsujin** [comment] 2019-05-02 17:29
Can you try AMDVLK?

**Comment by phush0** [comment] 2019-05-02 18:08
No support for this chip. Have tried with Padoka and Oibaf it is same so not connected with LLVM or so

**Comment by Oschowa** [comment] 2019-05-02 18:18
Have you actually tried? Just because it isn't explicitly mentioned in the README doesn't mean it won't work. You also don't need to install anything from the amdgpu-pro package.
Download the .deb form here: https://github.com/GPUOpen-Drivers/AMDVLK/releases
If you are on ubuntu you can install it as described in the installation instructions, just make sure to set
`VK_ICD_FILENAMES=/etc/vulkan/amd_icd64.json` to override driver selection.

**Comment by phush0** [comment] 2019-05-02 18:23
yes I have several times. it just trow error about host memory error and nothing else

**Comment by hakzsam** [comment] 2019-05-02 19:56
If I understand correctly, the initial problem is now fixed but you still have issues with occlusion queries?
And yes, AMDVLK doesn't seem to support VegaM.

**Comment by phush0** [comment] 2019-05-02 20:12
Correct

**Comment by phush0** [comment] 2019-05-05 11:42
Same problem like Hellblade in Assassins's Creed Odyssey. Game start and on page "Press Any Key" - display flicker to white and back "Loading additional contents" and stay there forever. GPU stop it's power. ALT+TAB is working no error messages, dmesg is clean, only music. With 1.0.3 it is working correct.

**Comment by hakzsam** [comment] 2019-06-11 14:47
@phush0 Does this series help https://patchwork.freedesktop.org/series/61903/ ?

**Comment by hakzsam** [comment] 2019-06-12 13:52
Occlusion queries should now be fixed with https://cgit.freedesktop.org/mesa/mesa/commit/?id=2ef9d2738c8905cb3a83baf14cc1d088786d57e3

Can you try please?

**Comment by phush0** [comment] 2019-06-12 14:18
Will try in several hours when I return from work and Oibaf compile new version.

**Comment by hakzsam** [comment] 2019-06-13 07:06
Thanks for confirming, this ticket can be closed then?

**Comment by phush0** [comment] 2019-06-13 07:39
Yes! Please close

**Closed** 2019-06-13 07:40 UTC
Labels: amd radv
