### ISSUE TITLE
[D3D9] Richard Burns Rally trees and objects disappear after about 2 minutes.

### ISSUE THREAD

**Issue by groybe** [doitsujin/dxvk#1983] opened 2021-03-20 10:53 UTC
Trees and other objects disappear after about 2 minutes. 

dgvoodoo2 by dege has fixed this in their closed source wrapper. From change log if this is of any help. 
"- Fixing a minor incompatibility for generated shader code (Richard Burns Rally)"

- GPU: GeForce GTX 750 Ti
- Driver: Nvidia 460.56
- Wine version: lutris-5.7.11
- DXVK version: v1.8.1

[Windows Apitrace
](https://www.mediafire.com/file/ceb7n7yogh2m1al/RichardBurnsRally_SSE.7z/file)
 d3d9.log
[RichardBurnsRally_SSE_d3d9.log](https://github.com/doitsujin/dxvk/files/6175333/RichardBurnsRally_SSE_d3d9.log)
![rbr_001](https://user-images.githubusercontent.com/8501882/111867104-0e37cd00-89c6-11eb-8af6-d2014f75a22d.jpg)

**Comment by xpander69** [comment] 2021-03-24 06:38
not sure if its even DXVK issue. still happens with regular wined3d also at least with the 5.xx versions of wine, havent tried with 6.x yet.
https://bugs.winehq.org/show_bug.cgi?id=11531

**Comment by groybe** [comment] 2021-03-24 08:16
I just tried 6. Keeps crashing and 10fps for me but eventually I got to go for long enough and it happen on wine3d too. If this was fixed in wine3d would it be fixed in dxvk too or are they diffrerent?

**Comment by xpander69** [comment] 2021-03-24 14:54
> I just tried 6. Keeps crashing and 10fps for me but eventually I got to go for long enough and it happen on wine3d too. If this was fixed in wine3d would it be fixed in dxvk too or are they diffrerent?

it depends if its caused by some GPU side of things (aka rendering) or some other crap. does it also happen in Windows with DXVK?

**Comment by groybe** [comment] 2021-03-25 01:10
Yeah happens in windows with DXVK.

**Comment by groybe** [comment] 2021-10-20 12:46
> not sure if its even DXVK issue. still happens with regular wined3d also at least with the 5.xx versions of wine, havent tried with 6.x yet. https://bugs.winehq.org/show_bug.cgi?id=11531

I see over at GamingOnLinux forums you had this working on an older version of d9vk? I tried all the versions up to around the time you posted that but still no joy. Perhaps the version of d3d9 or d3dcompiler I have is messing it up? I'm using lutris's versions. Although it should work on windows if that was the case I guess.

**Comment by DadSchoorse** [comment] 2021-11-12 12:52
Another case of #2195, INF/NAN in the VS.

**Comment by xpander69** [comment] 2021-11-13 08:40
Can confirm that this PR fixes the issue for RBR
https://github.com/doitsujin/dxvk/pull/2359

**Comment by groybe** [comment] 2021-11-15 09:42
Awesome! Thanks everyone.

I can compile the master branch and it runs but when i add the pull request it crashes before the game loads.
I suspect I'm doing something wrong either compiling or something with my system.
@xpander69 Could you possibly send me the compiled working binary? Thanks.

**Comment by groybe** [comment] 2021-11-15 12:14
> compiled master-branch with that PR applied: https://drive.google.com/file/d/1ygikbNBBq6RHE3sO93pfKmgam04Ekf7b/view?usp=sharing

No joy here still have the trees. Disappearing.
Why when I compile do i get v1.9.2-52? The one you sent says -43

**Comment by xpander69** [comment] 2021-11-15 12:19
I dont know..i built it the day i messaged here. So there might be some changes since then
are you launching the game from correct executable?

you can try dxvk.conf with d3d9.floatEmulation=true

as its only enabled for one executable of RBR

/* Richard Burns Rally                     */
    { R"(\\RichardBurnsRally_SSE_\.exe$)", {{
      { "d3d9.floatEmulation",              "Strict" },

**Comment by K0bin** [comment] 2021-11-15 12:26
> you can try dxvk.conf with d3d9.floatEmulation=true

You need d3d9.floatEmulation = strict and the matching git branch.

**Comment by groybe** [comment] 2021-11-15 12:54
d3d9.floatEmulation = strict fixed it.

I see in the code is says. { R"(\RichardBurnsRally_SSE_.exe$)", {{
Is it meant to be { R"(\RichardBurnsRally_SSE.exe$)", {{
Without the extra underscore?

**Comment by K0bin** [comment] 2021-11-15 13:17
>  Is it meant to be { R"(\RichardBurnsRally_SSE.exe$)", {{

Fixed. Thanks for the heads up.

**Comment by xpander69** [comment] 2021-11-15 14:51
yeah strict i meant, thanks for pointing out. Tested again just to be sure i wasn't seeing ghosts. Was lazy to hook up my wheel atm though, so i drove a bit with the keyboard and all is still fine (i have loads of mods though)
![ss_15112021_16 49 33](https://user-images.githubusercontent.com/1345116/141802398-b3486036-89d0-42fb-97a7-a22786411aaa.png)

**Comment by groybe** [comment] 2021-11-16 10:57
Awesome! I tried with Rallysimfans today all good. Thanks again.

**Comment by K0bin** [comment] 2021-12-05 17:43
Should be fixed by c13395db970d16a5631a7c0926e2c4529d2710c3

**Closed by K0bin** 2021-12-05 17:43 UTC
Labels: d3d9

**Comment by cognivore** [comment] 2022-02-09 23:07
Sorry for necroposting, but thank you everyone! You are the best!
