### ISSUE TITLE
Fallout 4 god rays not rendering properly

### ISSUE THREAD

**Issue by cyro666** [doitsujin/dxvk#823] opened 2018-12-21 20:38 UTC
### Software information
Fallout 4, steam version

### System information
- OS: Arch Linux
- GPU: R9 280
- Driver: amdgpu from kernel 4.19, mesa RADV 18.3.1
- Wine version: 4.0 - rc2 and Proton 3.16
- DXVK version: 0.94

### Log files
- d3d11.log: [Fallout4_d3d11.log](https://github.com/doitsujin/dxvk/files/2704115/Fallout4_d3d11.log)
- dxgi.log: [Fallout4_dxgi.log](https://github.com/doitsujin/dxvk/files/2704117/Fallout4_dxgi.log)

![screenshot_20181221_220800](https://user-images.githubusercontent.com/13151680/50361801-47720000-0565-11e9-91c6-0db6f62afa7b.png)

These rectangles are flickering randomly all over the place where there should've been god rays. The weird thing is Skyrim SE god rays work fine. I tried it on proton and my own compiled wine - same issue. On Windows the issue does not exist. This issue has been present ever since I've been using DXVK, so at least about 4 weeks now.

There is one more thing to be noted which might help or give a clue. The performance is subpar compared to Windows, about 20-30% worse, thus making it unplayable IMO (50 fps -> 35 fps). I wouldn't think that was weird if it wasn't for Skyrim SE which uses almost the same engine and gets the same performance on Linux as on Windows (if not better). I made sure both games are using the same settings (high). DOOM also gets very close to Windows performance so this should possibly rule out a problem with the RADV driver.

Turning off the god rays fixes the flickering and gives better performance, although still not satisfactory and on par with Windows.

If you can confirm this flickering is a valid issue, I'll try to give you an apitrace, once I figure out how one does that...

**Comment by doitsujin** [comment] 2018-12-21 21:11
I do have Fallout 4, will take a look at it next year.

> The performance is subpar compared to Windows, about 20-30% worse

This is not a bug or an issue, it's the expected performance loss.

**Comment by cyro666** [comment] 2018-12-22 16:14
> This is not a bug or an issue, it's the expected performance loss, especially if you're CPU limited.

That's why I'm so surprised... The GPU gets pegged to 100%, but all the CPU cores are around 40% on average, rarely 60%. But I guess it is just what it is.

**Comment by fls2018** [comment] 2018-12-26 14:41
I'm pretty sure unless you use Ultra godrays you get "block" effects & pixelation: https://youtu.be/k_MsRmN-XBQ

**Comment by doitsujin** [comment] 2019-01-07 18:31
Can reproduce, will investigate.

**Comment by doitsujin** [comment] 2019-01-07 21:40
Looks like a radv bug that also affects World of Warcraft (#343).

**Comment by doitsujin** [comment] 2019-01-09 22:54
Fixed in mesa by [this](https://gitlab.freedesktop.org/mesa/mesa/commit/ee8488ea3b99ad0632e5eac6defcef0264d8782c) commit.

**Closed by doitsujin** 2019-01-09 22:54 UTC
Labels: amd radv, bug

**Comment by mikhaelcool7** [comment] 2022-10-10 15:54
Godray flickering returns

**Comment by Blisto91** [comment] 2022-10-10 15:59
@mikhaelcool7 please make a new issue and fill out the template
