### ISSUE TITLE
Nine Sols rectangle graphic defect on AMD RDNA3 graphics systems(Linux & Windows)

### ISSUE THREAD

**Issue by brlin-tw** [doitsujin/dxvk#4092] opened 2024-06-27 09:50 UTC
### Software information

Game: [Nine Sols](https://store.steampowered.com/app/1809540/Nine_Sols/) v202406261615.64af447d.0-steam-app-packing/win-production
Graphic settings: Reproduced on 720p, 1080p, and others, with all the combinations of graphic details settings.
System: Framework Laptop 13(AMD 7040 series)@Linux

### System information

- GPU: Radeon 780M Graphics
- Driver: Mesa 24.0.5-1ubuntu1
- Wine version: Proton Experimental (Build ID: 14769515)
- DXVK version: 2.3.1-88-ga276e13 according to DXVK_HUD's output

### Apitrace file(s)

<https://drive.google.com/file/d/1W7krl7B_QVsnhYDxhbFDODi6B4rj8ZiO/view?usp=sharing>

### Log files

[steam-1809540.log.gz](https://github.com/user-attachments/files/16011544/steam-1809540.log.gz)

### Additional info

Corresponding Mesa issue: [\[RADV\] - Nine Sols(1809540) - Flickering random black rectangle graphic defects appear around the protagonist's sprite on AMD graphics systems. (#11404) · Issues · Mesa / mesa · GitLab](https://gitlab.freedesktop.org/mesa/mesa/-/issues/11404)

Some people reproduced this issue without using DXVK on:

* ROG Ally@Windows
* Radeon RX 7600@Windows.

So it's probably an even low-level problem.

**Comment by brlin-tw** [comment] 2024-06-27 09:57
Refer to the following clip for the symptoms(disregard the trailing noise frames) , it is usually seen around the protagonist's character sprite:

[Screencast_from_2024-06-08_22-04-57.webm](https://github.com/doitsujin/dxvk/assets/13408130/21bf0f79-d83b-4686-bc51-480321e4c8cf)

**Comment by Blisto91** [comment] 2024-06-27 11:26
Are you able to provide a save game for a section that shows the issue

**Comment by brlin-tw** [comment] 2024-06-27 12:27
@Blisto91 

> Are you able to provide a save game for a section that shows the issue

[This save file](https://drive.google.com/file/d/1kyqK4857JiI9w1Hi0SSC5CJq0GTmRv_E/view) can provide access to reproduce this issue, refer [Solution 3: Apply the Save Files We Provide | Save File Restore · 九日 支援 / Nine Sols Support](https://coda.io/@redcandlegames/nine-sols-support/save-file-restore-3#_luWNI) for the instructions.)

**Comment by brlin-tw** [comment] 2024-06-27 12:31
Reproduce instruction:

1. Load the save file, the game should now be in the Shengwu Hall map.
1. Move the protagonist to a location that has a light, even background (e.g. the entrance at the left of the root node(bonfire))
1. Observe the protagonist's sprite closely

I've filed a report to Mesa as well: [\[RADV\] - Nine Sols(1809540) - Flickering random black rectangle graphic defects appear around protagonist's sprite on AMD graphics systems. (#11404) · Issues · Mesa / mesa · GitLab](https://gitlab.freedesktop.org/mesa/mesa/-/issues/11404#description)

**Comment by Blisto91** [comment] 2024-06-27 13:03
I have not been able to reproduce it on my rdna2 iGPU (or Nvidia RTX 4080) even when using the same mesa and dxvk version. Have this only been observed on rdna3 GPUs?

**Comment by brlin-tw** [comment] 2024-06-27 13:30
@Blisto91 

> Have this only been observed on rdna3 GPUs?

As far as I can tell, yes.

> If this reproduces on Windows even without dxvk then i would say it is a likely game bug

This issue isn't reproducible on NVIDIA and other graphic hardware, though.  I'd rather doubt it is a bug in the graphics driver/shader compiler etc.  I've already filed the issue to the game developers before the release of the game.

Thanks for the info, feel free to close this issue if you believe this is out of scope.

**Comment by Blisto91** [comment] 2024-06-27 14:10
I will take another look when i switch back to my 7900 xtx

**Comment by brlin-tw** [comment] 2024-07-31 09:53
This bug is still reproducible in the current build of the game(b7ca1880).

**Comment by mbriar** [comment] 2024-07-31 09:57
Does `RADV_DEBUG=nodcc` help (on linux)?

**Comment by brlin-tw** [comment] 2024-07-31 10:17
> Does `RADV_DEBUG=nodcc` help (on linux)?

Yes!  The problem is no longer reproduced after specifying that environment variable in the Steam launch options.

**Comment by ewfwefewfw** [comment] 2024-08-01 06:35
@brlin-tw 
Could you share the save file again? [This save file](https://drive.google.com/file/d/1kyqK4857JiI9w1Hi0SSC5CJq0GTmRv_E/view) seems expired.

**Comment by brlin-tw** [comment] 2024-08-01 06:49
> @brlin-tw Could you share the save file again? [This save file](https://drive.google.com/file/d/1kyqK4857JiI9w1Hi0SSC5CJq0GTmRv_E/view) seems expired.

The developers seemed to have replaced the save file, please use this one instead:

<https://drive.google.com/file/d/1CO_7yxEvQGd4OkYHaJ6V6bZe6Mft2mVu/view?usp=drive_link>

It is the After Factory Boss Fight save file in the [[Save File Restore · 九日 支援 / Nine Sols Support](https://coda.io/@redcandlegames/nine-sols-support/save-file-restore-3)](https://coda.io/@redcandlegames/nine-sols-support/save-file-restore-3) support page.

**Comment by brlin-tw** [comment] 2024-08-02 06:07
The game devs have debugged the issue and made the following discoveries:

> I've tested the parameters one by one and found that the defect only appears when we set the Unity lightmask rendertexture (format) to a single R channel to reduce memory usage.  When I set it back to the default value the defect no longer appears.

> When the (render texture) format is set to channel R and (the texture) is thrown into postprocessing the problem resurfaces.

> Select the following format will trigger the issue: `R8_UNORM`
>
> ![image](https://github.com/user-attachments/assets/81685c4a-a781-4f60-97d8-3075973b860c)
>
> When I select the `R8G8B8A8_UNORM` below it the problem is no longer reproduced.

## References

* [Unity - Scripting API: RenderTextureFormat](https://docs.unity3d.com/ScriptReference/RenderTextureFormat.html)

**Comment by brlin-tw** [comment] 2024-08-02 06:23
The game devs have debugged the issue and made the following discoveries:

> I've tested the parameters one by one and found that the defect only appears when we set the Unity lightmask rendertexture (format) to a single R channel to reduce memory usage.  When I set it back to the default value the defect no longer appears.

> When the (render texture) format is set to channel R and (the texture) is thrown into postprocessing the problem resurfaces.

> Select the following format will trigger the issue: `R8_UNORM`
>
> ![image](https://github.com/user-attachments/assets/61513d9d-94d6-4e04-82b4-c28f3a639458)
>
> When I select the `R8G8B8A8_UNORM` below it the problem is no longer reproduced.

## References

* [Unity - Scripting API: RenderTextureFormat](https://docs.unity3d.com/ScriptReference/RenderTextureFormat.html)

**Comment by brlin-tw** [comment] 2024-08-08 04:22
It seems that [the Unity `SystemInfo.SupportsRenderTextureFormat` method call](https://docs.unity3d.com/ScriptReference/SystemInfo.SupportsRenderTextureFormat.html) returns `true` for the `R8_UNORM` render texture format on RDNA3 systems(e.g. ROG Alloy), so it's not that the graphical driver doesn't support such format.

**Comment by doitsujin** [comment] 2024-08-08 12:18
Closing here since there's a corresponding Mesa issue already and everything is strongly suggesting a hardware/driver quirk.

**Closed by doitsujin** 2024-08-08 12:18 UTC
Labels: d3d11
