### ISSUE TITLE
Spellforce 3 crashes at startup

### ISSUE THREAD

**Issue by dreamhunt** [doitsujin/dxvk#299] opened 2018-04-18 10:39 UTC
Spellforce 3 crashes at startup. The game doesn't run. At the start there is black screen for 2-3 seconds and the game crash with option to send a bug to developers with Ok button which redirects to developer bugs site. I try it with Wine-staging 3.5 and DXVK 0.42.

### Software information
Spellforce 3. I tried with installing DX9, DX11, nothing helps.

### System information
    GPU: Intel 3770
    Driver: 390.48, Nvidia GTX 1080Ti
    Wine version: 3.5 Staging/ 3.5 vanilla
    DXVK version: 0.42

### Apitrace file(s)
https://pastebin.com/kx79YEPS

### Log files
- d3d11.log:
https://pastebin.com/Ce8ab0sG
- dxgi.log: 
https://pastebin.com/9rrwTsKw

### Wine log
https://pastebin.com/Y9xQdD8y

**Comment by doitsujin** [comment] 2018-04-18 10:39
Duplicate of #274.

**Closed by doitsujin** 2018-04-18 10:39 UTC
Labels: duplicate
