### ISSUE TITLE
Shadow rendering bug in Hitman

### ISSUE THREAD

**Issue by aufkrawall** [doitsujin/dxvk#517] opened 2018-07-24 17:29 UTC
There is visual corruption in the sea water with DXVK on Sapienza map (you can untick all other episodes in the Steam DLC options before downloading):
https://abload.de/img/screenshot_20180724_1a6ek0.png

### Software information
Steam version of Hitman (2016) 1.14.2
maximum quality, 1440p

### System information
- GPU: GTX 1070 Ti
- Driver: 396.45
- Wine version: wine-staging 3.13
- DXVK version: 0.63_5_g656cb2e

### Apitrace file(s)
- Somehow apitrace doesn't save anything, despite of recording a lot on the console. Can try again, but need further guidance. I did

  wine apitrace.exe trace -a dxgi "/work/.wine/drive_c/Program Files (x86)/Steam/Steam.exe -applaunch 236870"

### Log files
- d3d11.log: https://pastebin.com/E7V10NJW

- dxgi.log: https://pastebin.com/3F3i27QC

**Comment by doitsujin** [comment] 2018-07-24 17:47
Can you explain what the corruption looks like? It's not obvious from your screenshot.

By the way I did test this game in the past and it was rendering just fine, might be worth testing older DXVK versions (0.50 or something like that).

**Comment by aufkrawall** [comment] 2018-07-24 18:34
The ocean should have a uniform color, that stripe with a darker blue is undesired (or the bigger brighter part, but I suppose the other way round).

**Comment by doitsujin** [comment] 2018-07-24 21:51
While I managed to reproduce the bug and record an apitrace myself, it is currently impossible for me to debug it because Renderdoc instantly crashes for some reason.

**Comment by aufkrawall** [comment] 2018-07-24 22:42
Thanks for looking into it so quickly. 👍

**Comment by doitsujin** [comment] 2018-08-02 11:16
Small update, I managed to get renderdoc to work, but it looks like the shadow map that's causing the problem is only ever rendered to once, which makes it pretty much impossible to debug this problem.

**Comment by aufkrawall** [comment] 2018-08-02 11:47
Ok. I will retest in a few months and keep you updated if something changed for the better or worse.

**Comment by doitsujin** [comment] 2018-08-03 13:23
Should be fixed in latest `master`, World of Warships had an issue with clamp-to-border samplers and this apparently was the same bug.

**Closed by doitsujin** 2018-08-03 13:23 UTC
Labels: bug, cantfix

**Comment by aufkrawall** [comment] 2018-08-03 21:24
Confirmed, all fine now.

Just in case anyone wonders: The shadow of Agent 47's head is missing at the starting location of the Bangkok mission. This is an issue of the game itself and thus also happens with native DX11 on Windows.
