### ISSUE TITLE
Dreamfall Chapters Special Edition - Invisible characters

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#740] opened 2018-10-28 14:04 UTC
### Software information
Dreamfall Chapters Special Edition

![screenshot_20181028_155133](https://user-images.githubusercontent.com/29783425/47616739-8d609980-dac9-11e8-9aa2-48f38770ba26.png)

All characters are invisible. There are 2 characters in this picture, one is sleeping (you can only see her pony tail and nothing else), and the main character which is invisible as well, and in the cutscene before this scene, there were many invisible characters as well.

![screenshot_20181028_154708](https://user-images.githubusercontent.com/29783425/47616864-d6fdb400-daca-11e8-9064-6d671e786019.png)

### System information
- GPU: AMD HD 8750M
- Driver: Mesa 18.2.3
- Wine version: TKG-3.19
- DXVK version: 0.90

### Apitrace file(s)
- The game crashs without using DXVK.

### Log files
[Dreamfall Chapters_d3d11.log](https://github.com/doitsujin/dxvk/files/2522812/Dreamfall.Chapters_d3d11.log)
[Dreamfall Chapters_dxgi.log](https://github.com/doitsujin/dxvk/files/2522814/Dreamfall.Chapters_dxgi.log)

**Comment by doitsujin** [comment] 2018-10-28 14:09
Can't debug without an apitrace.

**Comment by ahmed-elsayed2017** [comment] 2018-10-28 14:11
Can I do it in Windows instead?

**Comment by doitsujin** [comment] 2018-10-28 14:13
Yes.

Since this game is based on Unity, my first guess would be missing Stream Output (see #695), but your logs don't show anything related - but that might be because you didn't go ingame when generating those logs.

**Comment by ahmed-elsayed2017** [comment] 2018-10-28 16:59
[Dreamfall Chapters.2.zip](https://github.com/doitsujin/dxvk/files/2522982/Dreamfall.Chapters.2.zip)

**Comment by doitsujin** [comment] 2018-10-28 17:32
The file is empty.

**Comment by Jrugia** [comment] 2018-10-28 20:38
I'm noticing a pattern here in OP's reports: https://github.com/doitsujin/dxvk/issues/695#issuecomment-432659510

I think the issue is Stream Output, but maybe related to his GPU model? 

@ahmed-elsayed2017 

Can you confirm if your drivers have been built Stream Output support?

**Comment by doitsujin** [comment] 2018-10-28 20:48
They haven't, I can tell that from the logs. But if the game required this feature, messages would pop up in the logs.

*Unless* when generating the log files, it didn't get to the point where it would compile geometry shaders with stream output.

**Comment by ahmed-elsayed2017** [comment] 2018-10-28 21:37
Actually, the game doesn't support DX11 at first, but it got an update and it changed from DX9 to DX11. I will delete the old log files and create new log files.

I don't know why Apitrace failed to create an appropriate file, may be it needs admin privileges.

My card doesn't work well with Steam Output support and I am waiting for the next release at the end of this month.

**Comment by ahmed-elsayed2017** [comment] 2018-10-28 21:45
I deleted the old log files and started the game again to create a new log files.

[Dreamfall Chapters_d3d11.log](https://github.com/doitsujin/dxvk/files/2523253/Dreamfall.Chapters_d3d11.log)
[Dreamfall Chapters_dxgi.log](https://github.com/doitsujin/dxvk/files/2523254/Dreamfall.Chapters_dxgi.log)

**Comment by ahmed-elsayed2017** [comment] 2018-10-28 21:50
At the end of the log file, it says : 

> Transform feedback not supoorted by device

so I think that you were right from the beginning.

**Comment by doitsujin** [comment] 2018-10-28 22:14
Closing then, you know what to do.

**Closed by doitsujin** 2018-10-28 22:14 UTC

**Comment by ahmed-elsayed2017** [comment] 2018-10-30 05:28
A new Mesa 18.3 landed yesterday. Now, everything is working well in this game.

![screenshot_20181030_072238](https://user-images.githubusercontent.com/29783425/47697806-5ac3b780-dc15-11e8-8446-31bacc64f2b1.png)
