### ISSUE TITLE
Borderlands 3 - Fullscreen issue

### ISSUE THREAD

**Issue by juampiursic** [doitsujin/dxvk#1541] opened 2020-03-31 16:57 UTC
The issue I'm having is that I can't get the game in fullscreen mode. Game runs on borderless window and windowed but it won't go fullscreen, it gets at 1600x900 rectangle with black borders all around. Want to try fullscreen because borderless window gives me 20% less FPS than windowed. I have to run the game windowed to get some good FPS.

**Software information**
Borderlands 3
Epic Games Store
Set to high preset on settings

**System information**
- GPU: NVIDIA GTX 970
- Driver: 440.64
- Wine version: Lutris 5.4
- DXVK version: 1.6

**Comment by doitsujin** [comment] 2020-03-31 21:18
Apitrace? Log files?

**Comment by doitsujin** [comment] 2020-04-03 00:23
Closing. No logs -> can't do anything, and other users cannot reproduce the problem.

**Closed by doitsujin** 2020-04-03 00:23 UTC
