### ISSUE TITLE
World of Tanks - "Improved" graphics not working, unfinished/unloaded textures in the game

### ISSUE THREAD

**Issue by rado84-github** [doitsujin/dxvk#2909] opened 2022-09-12 21:30 UTC
### Software information
World of Tanks

### System information
- GPU: GTX 1660 Ti
- Driver: 515.57
- Wine version: 7.17
- DXVK version: 1.10.3

### Apitrace file(s)
Trying to use apitrace didn't work, if anyone else can do it, it would be great.

### Log files
The game/wine didn't create any logs.

I've downloaded the HD client but when in game, the "Improved" graphics which is supposed to use the HD textures is disabled, thus it can't be used. IDK if the unfinished (unloaded?) textures are the result of the standard graphics or of DXVK, so I'm uploading both of the screenshots.

I have played the game at maximum graphics (Improved) on Windows, so the reason for the not working improved graphics is NOT my hardware.

![Picture_created_12-09-2022_23-58-51](https://user-images.githubusercontent.com/41172201/189761822-29b527e7-956c-43f0-9b12-be11eb4e2f10.png)
![Picture_created_12-09-2022_23-59-49](https://user-images.githubusercontent.com/41172201/189761825-9ef92df2-3b77-4e24-b089-76a44d5dae5f.png)

**Comment by doitsujin** [comment] 2022-09-12 21:35
I know for a fact that this has worked on my system in the past.

Can you please post DXVK logs?

**Comment by Blisto91** [comment] 2022-09-12 21:40
The logs should appear either next to the exe or in the games root folder. If they don't it's either because you've set `DXVK_LOG_LEVEL=none` or the game isn't using dxvk.

You can launch with `DXVK_HUD=1` to verify it is using dxvk

**Comment by rado84-github** [comment] 2022-09-12 23:21
I think I have set dxvk log level to none for another game but it was a long time ago and I can't be sure.
Which of these levels should I set dxvk to: DXVK_LOG_LEVEL=error|warn|info|debug ?

**Comment by doitsujin** [comment] 2022-09-12 23:31
`DXVK_LOG_LEVEL=info` is good enough.

**Comment by rado84-github** [comment] 2022-09-13 01:18
These are the only logs that contain something, the rest were just empty files.
[DXVK_logs.zip](https://github.com/doitsujin/dxvk/files/9552737/DXVK_logs.zip)

**Comment by doitsujin** [comment] 2022-09-13 02:05
looks like the wine log of the actually relevant application gets eaten by the wargaming game center garbage, so that doesn't contain anything interesting...

Guess I'm not getting around reinstalling the game, but not expecting it to be very useful given that it was working just here fine last time about a year ago.

**Comment by doitsujin** [comment] 2022-09-13 02:45
Yeah, still works fine here. This is with the Lutris thing for Wargaming Game Center, using current dxvk master (but tested with 1.10.3 as well, same result). Enabling the option works fine and textures also load fine.
![Bildschirmfoto](https://user-images.githubusercontent.com/25567304/189795964-de87d3f8-3e09-48ba-a81a-8e2df67e7a0a.png)

**Comment by Blisto91** [comment] 2022-09-13 05:45
I will see if i can reproduce on any of ny setups here later

**Comment by rado84-github** [comment] 2022-09-13 10:54
I found a way to run the game without the game center and I think this problem is a game bug which I'll have to report to WG. Until now every attempt to run the game without the game center by running /World_of_Tanks_EU/WorldOfTanks.exe has failed and the game says it needs to be run through the game center. But it turned out that this is the wrong exe. In order to run it the old fashioned way, one needs to run /World_of_Tanks_EU/win64/WorldOfTanks.exe. When ran with that exe, "Improved graphics" works just fine. I haven't tried to run the 32-bit exe but I suspect that this is the exe the game center has been set to run and that's why the improved graphics doesn't work.

**Comment by doitsujin** [comment] 2022-09-13 11:50
Weird, but makes sense if it's actually launching the 32-bit exe. Closing as not our bug.

**Closed by doitsujin** 2022-09-13 11:50 UTC
Labels: can't reproduce

**Comment by rado84-github** [comment] 2022-09-13 20:09
@doitsujin can you try your game on the map Fjords? IDK if it will work in a training battle, bu you could try. I just had a battle there and the frames were 25 the whole time. I reduced almost every setting to low or off but that didn't change anything.

**Comment by Blisto91** [comment] 2022-09-14 07:36
If you can then post a screenshot with a full hud when it happens. `DXVK_HUD=full`

**Comment by Blisto91** [comment] 2022-09-14 12:59
I have never tried to install dxvk from the aur but i'm pretty sure you still have to run the install script to install it into your wine prefix if you want to do it properly.
See comment here https://aur.archlinux.org/packages/dxvk-bin#comment-639617
Looks like they symlink the install script directly to the bin folder so you can call it from the terminal like a regular program.
The putting the dll's next to exe method is generally not the recommended way to do it on linux as the results can be iffy. Also some games want to load the files directly from wines windows system folder.
