### ISSUE TITLE
Warcraft III 2019 build (not Reforged)

### ISSUE THREAD

**Issue by ChazyTheBest** [doitsujin/dxvk#1253] opened 2019-11-24 18:42 UTC
The new 2019 **build** (not game) of Warcraft III **The Frozen Throne** freezes when you enter in the options window and click cancel, it also happens once you start a new game, when you click options and then cancel the screen turns black for a second and then comes back but frozen with the cursor clicking the button.

For example: Options -> Video -> Cancel, when the screen turns black but you don't hear the chains sound you know it crashed. It may not crash/freeze always, while testing I noticed once didn't happened, it also doesn't crash when you go to Options and just click Cancel.

Windowed mode (not fullscreen) works fine.

### Software information
Warcraft III (1.31.1.12164 x86_64) default and all high, 1920x1080x75 fullscreen and windowed fullscreen.

### System information
- GPU: RX 480 8GB
- Driver: amdgpu (free) 19.2.6
- Wine version: 4.20 (staging)
- DXVK version: 1.4.4 and 1.4.5 (both compiled and tested)

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log: https://gist.github.com/ChazyTheBest/9fb88c7fa00b9f64fe0512584764d6ab
- dxgi.log: https://gist.github.com/ChazyTheBest/11b95d8e0ba38b0375fe8f5ba7164fdb

This wasn't included in the log (console output):

```
003d:fixme:thread:SetThreadDescription (FFFFFFFFFFFFFFFE L"dxvk-shader"): stub
003e:fixme:thread:SetThreadDescription (FFFFFFFFFFFFFFFE L"dxvk-shader"): stub
003f:fixme:thread:SetThreadDescription (FFFFFFFFFFFFFFFE L"dxvk-writer"): stub
0040:fixme:thread:SetThreadDescription (FFFFFFFFFFFFFFFE L"dxvk-submit"): stub
warn:  DXG0041:fixme:thread:SetThreadDescription (FFFFFFFFFFFFFFFE L"dxvk-queue"): stub
I: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
0042:fixme:thread:SetThreadDescription (FFFFFFFFFFFFFFFE L"dxvk-cs"): stub
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1920x1080
info:    Image count:  4
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1920x1080
info:    Image count:  4
0046:fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0000000003ABFD28): stub
002b:fixme:secur32:schan_QueryContextAttributesA Unhandled attribute 0x23
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
002b:err:secur32:schan_free_handle Handle 0(0xa1a10) is not of type 0x1
002b:err:secur32:schan_free_handle Handle 1(0xa1a20) is not of type 0x1
002b:fixme:setupapi:SetupDiOpenDeviceInterfaceW 0000000001778A60 L"\\\\?\\DISPLAY#Default_Monitor#0000&0000#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}" 00000000 000000000022BFE0
002b:err:secur32:schan_free_handle Handle 2(0xa1a30) is not of type 0x1
002b:err:secur32:schan_free_handle Handle 3(0xa1a40) is not of type 0x1
002b:fixme:setupapi:SetupDiOpenDeviceInterfaceW 0000000001F818F0 L"\\\\?\\DISPLAY#Default_Monitor#0000&0000#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}" 00000000 000000000022BFE0
002b:fixme:secur32:schan_QueryContextAttributesA Unhandled attribute 0x23
```

**Comment by K0bin** [comment] 2019-11-24 19:37
**Apitrace file(s)**
* Put a link here

There's a reason why that's in the issue template. Please make an apitrace.

**Comment by doitsujin** [comment] 2019-11-24 20:37
Is this the same game (and problem) as #1252?

**Comment by Thaodan** [comment] 2019-11-24 20:40
yes its Warcraft 3 Reforged Warcaft 3 original used d3dx9

**Comment by doitsujin** [comment] 2019-11-24 20:51
Considering that you're not getting any DXGI errors and the game seems to crash **before** even creating a swap chain, there are likely issues on your setup in addition to the DXVK problem. Closing as duplicate of #1252 .

**Comment by ChazyTheBest** [comment] 2019-11-24 21:17
@Thaodan No, Warcraft 3 classic/original got an update to support x86_64 and dx11, you can check the latest build is: 1.31.1.12164 x86_64 Jun 5 2019.
@doitsujin This is not the new Reforged remake. I am talking about the 2002 game Warcraft 3.

Does no one have this game to check it out? I can provide a screenshot:

![Screenshot_20191124_221608](https://user-images.githubusercontent.com/654229/69501747-27cb2080-0f08-11ea-8ece-c39c79652c91.png)

**Comment by doitsujin** [comment] 2019-11-24 21:31
> I am talking about the 2002 game Warcraft 3.

Why does that game even support D3D11? Did they remove D3D9 support or is that still an option?

If so, I'd suggest using D3D9 instead. I can't debug this without an apitrace and I don't have the game.

**Comment by Thaodan** [comment] 2019-11-24 22:16
It should even have a opengl 
switch if I remeber corectly

**Comment by Oschowa** [comment] 2019-11-24 22:20
@ChazyTheBest So i downloaded the game with the battle.net app, but i can't figure out how to actually  launch the game. Running either `x86_64/Warcraft III.exe` or `Warcraft III Public Test Launcher.exe` just exit immediately, and it doesn't even show up in the battle.net app itself.

**Comment by ChazyTheBest** [comment] 2019-11-24 22:33
> Why does that game even support D3D11? Did they remove D3D9 support or is that still an option?

@doitsujin I don't know, I was about to read the patch notes: https://wow.gamepedia.com/Warcraft_III/Patch_1.31.0
Looks like D3D9 is still an option:

> Removed: -d3d (Replacement: -graphicsapi Direct3D9 [May be removed in the future])

> Or try D3D11 with wined3d and see if that works.

I tried but I get a black window with sound.

> It should even have a opengl switch if I remeber corectly

@Thaodan Yes, it's in the patch notes:

> Remvoed: -opengl (Replacement: -graphicsapi OpenGL [May be removed in the future])

> So i downloaded the game with the battle.net app, but i can't figure out how to actually launch the game. Running either x86_64/Warcraft III.exe or Warcraft III Public Test Launcher.exe just exit immediately, and it doesn't even show up in the battle.net app itself.

@Oschowa Hmm I didn't do anything special, just compile dxvk and install it in a new prefix. I always enable the 2 options from staging: enable VAAPI and EAX. And also run the 64 bits binary:

`runaswine /home/GAMES/Warcraft\ III/x86_64/Warcraft\ III.exe`

**Comment by nvaert1986** [comment] 2019-12-03 21:57
The Reforged Multiplayer Beta actually stopped working ~ 1,5 - 2 weeks ago after the last Night Elf patch (they were added as a playable race in the Beta). The -graphicsapi OpenGL did resolve the issue either The dxvk-1.4.6 release resolved the issue with the beta, by adding the required features and is now working perfectly again with the Reforged Beta. 

Thanks! It's appreciated :-)

**Comment by RevenantX** [comment] 2019-12-18 09:24
> 
> 
> @ChazyTheBest So i downloaded the game with the battle.net app, but i can't figure out how to actually launch the game. Running either `x86_64/Warcraft III.exe` or `Warcraft III Public Test Launcher.exe` just exit immediately, and it doesn't even show up in the battle.net app itself.

You cannot install old Warcraft III from battle.net app (from app - only Reforged). To buy and install old Warcraft III you need buy it from battle.net shop and download original installers for Reign of Chaos and Frozen Throne.

**Comment by avindra** [comment] 2020-11-26 03:55
Sharing finding from the other thread here: this game used DirectX 8 before the 1.31 patch:

https://github.com/doitsujin/dxvk/issues/1808#issuecomment-734039255


Also the game's OpenGL backend is as raggedy as it was since the early 2000s. I barely get 20FPS on a Threadripper + 1080Ti build with Warcraft's OpenGL renderer.

The DirectX backends don't have this issue, so it's best to try to get it working properly (via dxvk).

A telltale sign is no logs from DXVK during startup, and `DXVK_HUD=1` having no effect. That means you fell into the OpenGL renderer.

**Comment by Blisto91** [comment] 2022-08-30 11:30
@ChazyTheBest @avindra is this still an issue? If you are still around and able to test this.

**Comment by K0bin** [comment] 2022-10-06 18:46
Stale

**Closed by K0bin** 2022-10-06 18:46 UTC
Labels: dxgi

**Comment by Blisto91** [comment] 2022-10-06 18:48
Also wasn't able to reproduce with the same warcraft version and newest dxvk or 1.4.5
If any of you still have the issue then comment here again.
