### ISSUE TITLE
World of Tanks caterpillars in wrong position with High LOD

### ISSUE THREAD

**Issue by ernstp** [doitsujin/dxvk#884] opened 2019-01-24 21:03 UTC
When setting Object LOD to "High", the caterpillars of tanks show up high in the air infront and above the tank. This is visible even in the garage. Setting this to "medium" does not show the issue.

Tested with DXVK 0.94 and 0.95, RADV git master, Wine staging 4.0-rc7.

**Comment by doitsujin** [comment] 2019-01-24 21:17
Have you tried an older DXVK and/or driver version? This used to work fine at some point.

Don't have WoT installed right now, might take a while until I can test.

**Comment by magist3r** [comment] 2019-01-25 18:06
Cannot reproduce even on Ultra settings. Could be RADV bug.

DXVK 0.95, NVIDIA GTX 660 Ti, Driver 415.22.05, Wine-staging 4.0

**Comment by doitsujin** [comment] 2019-01-25 18:25
Tested on mesa-git with LLVM 7.0.1 and can't reproduce either. Might be an LLVM regression, but to test that I'd have to get a 32-bit build to work first.

**Comment by gulafaran** [comment] 2019-02-13 18:25
happends here aswell on
linux 4.20.8
OpenGL renderer string: Radeon RX Vega (VEGA10, DRM 3.27.0, 4.20.8-zen1-1-zen, LLVM 9.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.1.0-devel (git-017349997f)

and dxvk from git.

**Comment by doitsujin** [comment] 2019-02-13 18:33
Yes, this is an issue with latest LLVM and will happen to everyone, regardless of the DXVK version.

**Comment by gulafaran** [comment] 2019-02-14 08:45
ah ok, do you know if there is an upstream bugreport for it then? so the amdgpu/llvm devs get to know about it?

**Comment by magist3r** [comment] 2019-06-29 09:50
I see this issue with LLVM 8 and Mesa 19.1.0 stable too.

**Comment by hakzsam** [comment] 2019-10-14 10:08
This issue is fixed with LLVM 9.0.1 (as well as LLVM git).

**Closed** 2019-10-14 10:17 UTC
Labels: amd radv
