### ISSUE TITLE
Grand Theft Auto IV, missions won't load on DXVK 1.8 and onwards

### ISSUE THREAD

**Issue by AsaeBega** [doitsujin/dxvk#2268] opened 2021-08-31 11:56 UTC
I get infinite loads when starting a mission. This only occurs on 1.7.3+ versions. 1.7.3 is fine. I also noticed that the game's VRAM usage jumps down to 750 mb (the value when game starts).

Didn't manage to run apitrace, yet I tried.

### Software information
GTA IV 1.0.7.0

### System information
- GPU: GTX 780 Ti
- Driver: 471.11
- Windows 10 21H1
- DXVK version: 1.9.1, 1.9, 1.8.1, 1.8

### Log files

8268 11:24:49.208 Starting DxWrapper v1.0.6387.21
8268 11:24:49.209 To be filled by O.E.M. To be filled by O.E.M. To be filled by O.E.M. (Desktop)
8268 11:24:49.209 Intel X79 To be filled by O.E.M. (Desktop)
8268 11:24:49.209 NVIDIA GeForce GTX 780 Ti
8268 11:24:49.209 Windows 10 Enterprise 64-bit (10.0.19041)
8268 11:24:49.209 "GTAIV.exe" (PID:11084)
8268 11:24:49.210 Steam game detected!
8268 11:24:49.210 Disabling High DPI Scaling...
8268 11:24:49.210 Loaded library: user32.dll
8268 11:24:49.210 Loaded library: shcore.dll
8268 11:24:49.210 Loading 'ddraw.dll'...
8268 11:24:49.211 Hooking ddraw.dll APIs...
8268 11:24:49.211 Enabling DDrawCompat
8268 11:24:49.211 Process path: E:\Games\Grand Theft Auto IV\GTAIV.exe
8268 11:24:49.211 Loading DDrawCompat from E:\Games\Grand Theft Auto IV\dxwrapper.asi
8268 11:24:49.211 Loaded library: uxtheme.dll
8268 11:24:49.212 DDrawCompat v0.2.1 loaded successfully
8268 11:24:49.212 Enabling d3d9 wrapper
8268 11:24:49.212 Loading 'd3d9.dll'...
8268 11:24:49.212 Hooking d3d9.dll APIs...
8268 11:24:49.212 DxWrapper loaded!
8268 11:24:53.507 d9_Direct3DCreate9
8268 11:24:53.507 Redirecting 'Direct3DCreate9' ...
8268 11:24:53.552 Creating interface m_IDirect3D9Ex::m_IDirect3D9Ex(06EC0BC8)
8268 11:24:53.571 UpdatePresentParameter Setting WndProc: WND(000B07FA,grcWindow,{-8,-20,1928,1099})
8268 11:24:53.601 m_IDirect3D9Ex::CreateDevice Failed to enable AntiAliasing!
8268 11:24:53.601 UpdatePresentParameter Setting WndProc: WND(000B07FA,grcWindow,{-8,-20,1928,1099})
8268 11:24:53.605 UpdatePresentParameter Setting WndProc: WND(000B07FA,grcWindow,{-8,-20,1928,1099})
8268 11:24:53.818 Setting MultiSample 8 Quality 3
8268 11:24:53.818 Creating interface m_IDirect3DDevice9Ex::InitDirect3DDevice(06EF55D8)
8268 11:24:53.818 Creating interface m_IDirect3DSwapChain9::m_IDirect3DSwapChain9(06D08788)
8268 11:24:53.818 Creating interface m_IDirect3DVertexDeclaration9::m_IDirect3DVertexDeclaration9(06D08938)
8268 11:24:53.818 Creating interface m_IDirect3DVertexDeclaration9::m_IDirect3DVertexDeclaration9(06D08E60)
8268 11:24:53.819 Creating interface m_IDirect3DVertexShader9::m_IDirect3DVertexShader9(007272E0)
8268 11:24:53.819 Creating interface m_IDirect3DVertexShader9::m_IDirect3DVertexShader9(00727400)
8268 11:24:53.819 Creating interface m_IDirect3DVertexShader9::m_IDirect3DVertexShader9(007272C8)
8268 11:24:53.820 Creating interface m_IDirect3DPixelShader9::m_IDirect3DPixelShader9(0FA92E70)
8268 11:24:53.820 Creating interface m_IDirect3DPixelShader9::m_IDirect3DPixelShader9(0FA92CD8)
8268 11:24:53.820 Creating interface m_IDirect3DPixelShader9::m_IDirect3DPixelShader9(0FA92F48)
8268 11:24:56.015 Redirecting 'Direct3DCreate9' ...
8268 11:24:56.023 Creating interface m_IDirect3D9Ex::m_IDirect3D9Ex(22087CD0)
8268 11:24:56.108 m_IDirect3D9Ex::~m_IDirect3D9Ex(22087CD0) deleting interface!
8268 11:24:56.109 d9_Direct3DCreate9Ex
8268 11:24:56.109 Redirecting 'Direct3DCreate9Ex' ...
8268 11:24:56.116 Creating interface m_IDirect3D9Ex::m_IDirect3D9Ex(0FB07308)
8268 11:24:56.116 m_IDirect3D9Ex::~m_IDirect3D9Ex(0FB07308) deleting interface!
8268 11:24:56.117 Installing DirectDraw hooks
8268 11:24:56.165 Installing GDI hooks
8268 11:24:56.173 Installing registry hooks
8268 11:24:56.173 Finished installing hooks
8268 11:24:58.128 Redirecting 'Direct3DCreate9' ...
8268 11:24:58.219 m_IDirect3D9Ex::~m_IDirect3D9Ex(0FB06DE8) deleting interface!
8268 11:24:58.220 Redirecting 'Direct3DCreate9Ex' ...
8268 11:24:58.294 Creating interface m_IDirect3DVertexBuffer9::m_IDirect3DVertexBuffer9(220D15F0)
8268 11:24:58.294 Creating interface m_IDirect3DVertexBuffer9::m_IDirect3DVertexBuffer9(220D1668)
8268 11:24:58.296 Creating interface m_IDirect3DTexture9::m_IDirect3DTexture9(220D1698)
8268 11:24:58.296 Creating interface m_IDirect3DTexture9::m_IDirect3DTexture9(220D17D0)
8268 11:24:58.296 Creating interface m_IDirect3DTexture9::m_IDirect3DTexture9(220D1518)
8268 11:24:58.339 Creating interface m_IDirect3DSurface9::m_IDirect3DSurface9(0FAC1F10)
8268 11:24:58.778 Creating interface m_IDirect3DVertexBuffer9::m_IDirect3DVertexBuffer9(220D1560)
8268 11:24:59.244 Creating interface m_IDirect3DVertexDeclaration9::m_IDirect3DVertexDeclaration9(22760C70)
8268 11:24:59.766 Creating interface m_IDirect3DSurface9::m_IDirect3DSurface9(24DA9868)
8268 11:24:59.766 Creating interface m_IDirect3DSurface9::m_IDirect3DSurface9(24DA99F8)
8268 11:24:59.894 Creating interface m_IDirect3DIndexBuffer9::m_IDirect3DIndexBuffer9(2536DDE8)
8268 11:24:59.894 Creating interface m_IDirect3DIndexBuffer9::m_IDirect3DIndexBuffer9(2536DEC0)
8268 11:24:59.894 Creating interface m_IDirect3DIndexBuffer9::m_IDirect3DIndexBuffer9(2536DD40)
8268 11:26:22.608 Quiting DxWrapper
8268 11:26:22.608 Detaching DDrawCompat
8268 11:26:22.620 DDrawCompat detached successfully
8268 11:26:22.620 Unloading libraries...
8268 11:26:22.620 Reseting screen resolution
8268 11:26:22.957 Reseting font smoothing
8268 11:26:22.967 DxWrapper terminated!

**Comment by K0bin** [comment] 2021-08-31 12:11
> I get infinite loads when starting a mission

That's a known issue which happens if you alt tab at any point while playing the game. We have no idea how to fix it.

Also, thats not the DXVK log and you didnt add an apitrace either.

**Comment by K0bin** [comment] 2021-08-31 12:11
Duplicate of #2119

**Closed by K0bin** 2021-08-31 12:11 UTC

**Comment by AsaeBega** [comment] 2021-08-31 12:25
> Also, thats not the DXVK log and you didnt add an apitrace either.

oh, I messed up :D

Would be glad if it's any useful:

info:  Game: GTAIV.exe
info:  DXVK: v1.9.1
info:  Found built-in config:
info:  Effective configuration:
info:    d3d9.customVendorId = 1002
info:    dxgi.emulateUMA = True
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 780 Ti:
info:    Driver: 471.11.0
info:    Vulkan: 1.2.175
info:    Memory Heap[0]: 
info:      Size: 3029 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 6103 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 780 Ti:
info:    Driver: 471.11.0
info:    Vulkan: 1.2.175
info:    Memory Heap[0]: 
info:      Size: 3029 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 6103 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : NVIDIA GeForce GTX 780 Ti
info:    Driver version   : 471.11.0
info:  Enabled device extensions:
info:    VK_EXT_4444_formats
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 0
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 1
info:    formatA4B4G4R4                         : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 0
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:  DXVK: Read 543 valid state cache entries
info:  DXVK: Using 5 compiler threads
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1920x1061
info:    Image count:  2
info:    Exclusive FS: 0
info:  Setting display mode: 1920x1080@0
info:  Game: GTAIV.exe
info:  DXVK: v1.9.1
info:  Found built-in config:
info:  Effective configuration:
info:    d3d9.customVendorId = 1002
info:    dxgi.emulateUMA = True
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 780 Ti:
info:    Driver: 471.11.0
info:    Vulkan: 1.2.175
info:    Memory Heap[0]: 
info:      Size: 3029 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 6103 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 780 Ti:
info:    Driver: 471.11.0
info:    Vulkan: 1.2.175
info:    Memory Heap[0]: 
info:      Size: 3029 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 6103 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  Process set as DPI aware
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Setting display mode: 1920x1080@60
warn:  D3D9DeviceEx::QueryInterface: Unknown interface query
warn:  db6f6ddb-ac77-4e88-8253-819df9bbf140
warn:  D3D9DeviceEx::QueryInterface: Unknown interface query
warn:  9b7e4c0f-342c-4106-a19f-4f2704f689f0
warn:  ConvertFormat: Unknown format encountered: 1396921934
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1920x1080
info:    Image count:  3
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  160x28
info:    Image count:  3
info:    Exclusive FS: 0
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Setting display mode: 1920x1080@60
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1920x1080
info:    Image count:  3
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  160x28
info:    Image count:  3
info:    Exclusive FS: 0
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Setting display mode: 1920x1080@60
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1920x1080
info:    Image count:  3
info:    Exclusive FS: 0
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_ADAPTIVETESS_Z
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_ADAPTIVETESS_W

**Comment by K0bin** [comment] 2021-08-31 12:28
Not useful unfortunately.
