### ISSUE TITLE
[Windows 10] [AMD] [D3D11] Yakuza 6: Certain white surfaces become yellow when inside buildings.

### ISSUE THREAD

**Issue by VidarPT** [doitsujin/dxvk#1992] opened 2021-03-28 20:17 UTC
By surfaces I mean people's clothing and even the eyes. This only seems to happen when inside buildings or, in the case of these photos, in the sewers.

How it should be:
![Yakuza 6 Native](https://user-images.githubusercontent.com/7354861/112766628-76139680-900a-11eb-99e0-955666c031a1.png)

How it looks like under DXVK:
![Yakuza 6 DXVK](https://user-images.githubusercontent.com/7354861/112766641-83c91c00-900a-11eb-8a5e-cc14f51ea0da.png)

And the freaky eyes;
![2021 03 28-21 23_02](https://user-images.githubusercontent.com/7354861/112766931-fdadd500-900b-11eb-9c3a-2cd33306fe80.png)

Also notice how his red shirt under his jacket is a bit buggy too. The lighting isn't right.

### Software information
High preset with medium shadows and SMAA. Even though it's a "new" release, Yakuza 6 uses the first iteration of the Dragon Engine used in Kiwami 2 and Like a Dragon.

### System information
- GPU: RX580
- Driver: 21.3.1
- Wine version: N/A
- DXVK version: 1.8.1

### Apitrace file(s)
I tried running "apitrace.exe trace -a dxgi path_to_game\Yakuza6.exe" but no trace file was created. The game boot fine but I can't find any new file containing any traces.

### Log files
dxgi.log: [Yakuza6_dxgi.log](https://github.com/doitsujin/dxvk/files/6217971/Yakuza6_dxgi.log)
d3d11.log: [Yakuza6_d3d11.log](https://github.com/doitsujin/dxvk/files/6217972/Yakuza6_d3d11.log)

**Comment by doitsujin** [comment] 2021-03-28 21:31
Does this happen on any other drivers?

I *don't care* about AMD Windows driver issues at this point, there's always something broken there and it's just not worth my time.

**Comment by VidarPT** [comment] 2021-03-28 22:05
I could try setting up a Linux distro. Do you know of any distro that's "plug and play" in the sense that I can simply create a liveCD USB pen and boot the game with minimal configuration? I'll take a look.

**Comment by Joshua-Ashton** [comment] 2021-03-29 06:43
If you record an apitrace we can play it back.

You just drop the dlls in the wrapper folder next to the game like you did with dxvk.

**Comment by VidarPT** [comment] 2021-03-29 12:35
> 
> 
> If you record an apitrace we can play it back.
> 
> You just drop the dlls in the wrapper folder next to the game like you did with dxvk.

You want me to run apitrace together with DXVK, right? If I put the wrapper files it just boots in D3D11. If I overwrite the files with DXVK's dll, it doesn't generate any trace.
Here's the massive trace: https://mega.nz/file/lswFEaQb#8QwW5Wy4I5yrFTWmn4elotneGJ-GjDC5RjIvPdEMHXE
And a video demonstrating the issue (because why not): https://mega.nz/file/J9p2Cb4I#vlzAjshRN4nUxPDhS7ebu1TJsq5VDcrnbX8aQHXw8tI

**Comment by doitsujin** [comment] 2021-03-29 13:03
> You want me to run apitrace together with DXVK, right?

No, that's not necessary unless there's a problem with the game executing some broken code path.

Anyway, the trace replays fine on my 6900XT (even with the proprietary AMD driver), can't really reproduce the problem here.

![Bildschirmfoto-1](https://user-images.githubusercontent.com/25567304/112840580-c8eb5d80-909f-11eb-86c6-79c62dcf670b.png)

**Comment by VidarPT** [comment] 2021-03-29 13:11
> even with the proprietary AMD driver

You mean the propretary drivers under Linux? Then this is a Windows driver bug, huh? I wouldn't mind reporting this to AMD but I don't know how to explain the situation.

**Comment by LordJBeckman** [comment] 2021-03-31 12:57
Could try against the latest Windows drivers with 21.3.2 and possibly 21.2.3 since the first March driver had the latest changes for Vulkan merged in and might have been where some of this broke. :)

I usually combine it with the latest runtime/loader as well since AMD's driver included one is older but I doubt that's going to change anything for this bug here. Probably a Windows driver specific issue since it's a different team compared to Linux with it's own set of issues and what you'd also get on Windows in general.
(The performance and compatibility gains are nice but there are some issues that can happen and Windows is not directly supported.)

**Comment by VidarPT** [comment] 2021-04-01 20:52
> 
> 
> Could try against the latest Windows drivers with 21.3.2 and possibly 21.2.3
Just finished testing them and no change. Still the same bugs. Such is the life of an AMD owner.

**Closed** 2022-07-20 20:05 UTC
Labels: not our bug, windows, amd proprietary
