### ISSUE TITLE
[d3d8] Old EverQuest client (takproject.net) still needs dgVoodoo

### ISSUE THREAD

**Issue by kai4785** [doitsujin/dxvk#4263] opened 2024-09-15 01:26 UTC
My working system looks like this:
Ubuntu 24.04
nvidia GeForce RTX 2060 driver 535.183.01 (from Ubuntu)
libvulkan1-1.3.275.0-1build1 (from Ubuntu)
[lutris-GE-Proton8-26-x86_64](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton8-26)
winecfg set `native,builtin` for all dxvk libraries: `d3d10core.dll`, `d3d11.dll`, `d3d8.dll`, `d3d9.dll`, `dxgi.dll`
`d3d8.dll` from [dgVoodoo2_8](https://dege.freeweb.hu/dgVoodoo2/dgVoodoo2/) ([direct link](http://dege.freeweb.hu/dgVoodoo2/bin/dgVoodoo2_8.zip))
`d3d11.dll` and `dxgi.dll` from dxvk-2.4

This works for the [old EverQuest client for The Al'Kabor Project server](https://wiki.takp.info/index.php/Getting_Started_on_Linux_(v2)).

If I copy the remaining dxvk libraries into place (`d3d10core.dll`, `d3d8.dll`, `d3d9.dll`), the game crashes after character select (which coincides with calling into d3d8).

Ideally I want to switch away from dgVoodoo and go with just dxvk now that there's d3d8 support.

I have tried looking at the diff of the log between the working environment and the broken one with `export WINEDEBUG=+loaddll,+d3d`, but nothing jumps out to me. I do notice that dxvk's `d3d8.dll` causes `d3d9.dll` to load when it does not when using dgVoodoo's version. But anything that looks like an error when it fails seems to also be in the logs when it is playable. Those logs are ~22MiB. Should I upload those?

Here's logs with just `export WINEDEBUG=+loaddll`. In the zip, `good.log` is with `dgVoodoo`, `bad.log` is with all dxvk libraries.
[logs.zip](https://github.com/user-attachments/files/17004265/logs.zip)

**Comment by WinterSnowfall** [comment] 2024-09-15 09:56
You'll need both the d3d8 and d3d8 dlls from dxvk to use with d3d8 games, [as descried in the readme](https://github.com/doitsujin/dxvk?tab=readme-ov-file#dll-dependencies). If a d3d8 game doesn't also load dxvk's d3d9.dll, it will crash.

**Comment by kai4785** [comment] 2024-09-15 22:55
I'm sorry, somehow I managed to click the link in the fine print instead of clicking the big green "Create a new bug" button. Here is a better bug report.

### Software information
[Old EverQuest client for The Al'Kabor Project server](https://wiki.takp.info/index.php/Getting_Started_on_Linux_(v2)).
No setting changes required. I wrote those instructions, and I'm currently looking to clean them up. I'd like to eliminate dgVoodoo if possible.

### System information
- GPU: NVIDIA GeForce RTX 2060
- Driver: 535.183.01
- Wine version: [lutris-GE-Proton8-26-x86_64](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton8-26)
- DXVK version: 2.4

### Apitrace file(s)
[eqgame.tar.gz](https://github.com/user-attachments/files/17007623/eqgame.tar.gz)

### Log files
Log file with apitrace enabled, no `WINEDEBUG` set.
[wine-mer4785.log](https://github.com/user-attachments/files/17007632/wine-mer4785.log)

### More testing
Thanks for the links, and that confirms what I was wondering. So I went back and copied *just* `d3d8.dll` and `d3d9.dll`, since dgVoodoo clearly hops straight from d3d8->d3d11. Here is a log with dxvk-2.4 `d3d8.dll` and `d3d9.dll` libraries (not the wrappers) with `+loaddll` enabled. I confirmed that this log includes the `The D3D9 device is now operating in D3D8 compatibility mode.` log line.
[wine-mer4785.log](https://github.com/user-attachments/files/17007661/wine-mer4785.log)

Thank you for your time.

**Comment by WinterSnowfall** [comment] 2024-09-16 06:53
Thank you, this is way more relevant to us. Having a look over the trace though I can see nothing out of place. I notice it detects 3 adapters on your system and picks the Nvidia GPU, so if any of this sounds unexpected, do let me know. Otherwise, it's creating a device, enumerating modes, querying format support (all standard and expected stuff)... and then, doing nothing. There's no crash or exception on dxvk side in d3d8 or d3d9.

Could you also attach a d3d8 trace captured while using dgVoodoo please (basically your working setup)? I can then compare the two and see if anything is amiss, such as cases where we should be erroring out some calls and we're currently not perhaps.

**Comment by kai4785** [comment] 2024-09-16 13:54
I may need assistance setting up the wrappers.

From my working setup with the overrides, I backed up `d3d8.dll`, `d3d11.dll`, and `dxgi.dll` in `C:\windows\system32`.
```
../../wineprefix/eggroll-lutris-GE-Proton8-26-x86_64/drive_c/windows/system32/d3d11.dll.back
../../wineprefix/eggroll-lutris-GE-Proton8-26-x86_64/drive_c/windows/system32/d3d8.dll.back
../../wineprefix/eggroll-lutris-GE-Proton8-26-x86_64/drive_c/windows/system32/dxgi.dll.back
```
Then I copied dgVoodoo's `d3d8.dll` and dxvk's `d3d11.dll` and `dxgi.dll` in their place. In this configuration the game launches just fine.

When I copy the wrapper files for `d3d8.dll`, `d3d11.dll` and `dxgi.dll`, the game crashes immediately after server selection. This is the same place it crashes when I use dxvk-2.4's d3d8 and d3d9 libraries alone. It generated 2 trace files.
[eqgame.tar.gz](https://github.com/user-attachments/files/17014332/eqgame.tar.gz)

Removing the wrapper dlls restores the game's functionality.

**Comment by kai4785** [comment] 2024-09-16 14:15
Ok, once more with just d3d8.dll apitrace wrapper!
[eqgame.tar.gz](https://github.com/user-attachments/files/17014689/eqgame.tar.gz)

**Comment by WinterSnowfall** [comment] 2024-09-16 14:27
> Still crashes unfortunately.

Interesting. The latest trace indicates that the d3d8 device creation is successful, much like it was with dxvk, so this went a bit better let's say. It still doesn't capture anything beyond that point though, as in the game doesn't appear to make any d3d8 calls after creating the device, so while the crash may be indeed related to getting d3d8 dxvk/apitrace into the picture, it occurs outside of our code. Which makes it very difficult to debug, if at all possible.

The only notable difference I could see between the dxvk trace and the dgVoodoo trace was that dgVoodoo advertises D32 support and the game indeed picks that for the auto depth-stencil during device creation, but I doubt that's relevant, since D32 is widely unsupported anyway even on Windows.

**Comment by kai4785** [comment] 2024-09-16 14:42
Reaching for adjacent things that might be useful.
I am using dgVoodoo v2.8, which is unfortunately not available to download at the moment (404). I have a cached copy locally. The next oldest version available to download is v2.82.2 (which is fewer updates than it seems) and the latest version is 2.83.1. Both of those versions of dgVodoo crash around the same time as dxvk.

**Comment by kai4785** [comment] 2024-09-16 17:20
Ok, clean wineprefix
```
wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v d3d8 /d native /f >/dev/null 2>&1
mv ../../wineprefix/eggroll-lutris-GE-Proton8-26-x86_64/drive_c/windows/system32/d3d8.dll{,.back}
cp -a ../../cache/dgVoodoo2_8/MS/x86/D3D8.dll ../../wineprefix/eggroll-lutris-GE-Proton8-26-x86_64/drive_c/windows/system32/d3d8.dll
cp -a ../../cache/apitrace-12.0-win32/lib/wrappers/d3d8.dll .
```
Expected crash after server select.
[eqgame.tar.gz](https://github.com/user-attachments/files/17017064/eqgame.tar.gz)

**Comment by WinterSnowfall** [comment] 2024-09-16 18:39
Thank you for trying. The trace looks identical to the ones captured before.

**Comment by dungeon007** [comment] 2024-09-16 19:31
> Reaching for adjacent things that might be useful. I am using dgVoodoo v2.8, which is unfortunately not available to download at the moment (404). I have a cached copy locally. The next oldest version available to download is v2.82.2 (which is fewer updates than it seems) and the latest version is 2.83.1. Both of those versions of dgVodoo crash around the same time as dxvk.

 Author is removing old releases (dont want to support something more than a year old) but you can get them from web archive:
http://web.archive.org/web/20230520013904/http://dege.freeweb.hu/dgVoodoo2/bin/dgVoodoo2_8.zip
Latest known that works on linux, seems to be 81_3:
http://web.archive.org/web/20240110053101/https://dege.freeweb.hu/dgVoodoo2/bin/dgVoodoo2_81_3.zip
 AFAIK he dont support linux in general, so dont file him bugs there... to be honest, i even think he broke it on purpose since ver 82, so that linux users dont come back

**Comment by kai4785** [comment] 2024-09-16 21:55
I tried replicating all the tests above using the `wine-stable` version `9.0` from winehq. Everything seemed literally the same.
Any other thoughts I can try out? Do you want to see any specific traces from stock wine, rather than from lutris-GE?

**Comment by dungeon007** [comment] 2024-09-17 20:14
> Any other thoughts I can try out?

Created accont just to try out this and as i see DxWrapper v1.0.990.18 wrapper is working, basically this 
[d3d8.zip](https://github.com/user-attachments/files/17034424/d3d8.zip)

![working](https://github.com/user-attachments/assets/ab0ed345-edb7-4f34-94c3-8d986e393aab)

DXVK's d3d9.dll that runs this could be anything going from versions 1.5 to 2.2, since 2.3+ there is a perf issue with this app:

![perf-issue](https://github.com/user-attachments/assets/e92359bc-f6b4-4634-a060-83645af6e2f7)

Game interacts with DDRAW for launcher and then doing some weird stuff with a window, to avoid some of these maybe you could launch it with something like this:

**WINE_D3D_CONFIG="renderer=no3d" wine explorer /desktop=TS,1920x1080 eqgame.exe`**

**Comment by Blisto91** [comment] 2024-09-17 20:25
We have poked at bunch at this, but haven't been able to figure out why the game doesn't like dxvk d3d8.

**Comment by dungeon007** [comment] 2024-09-17 20:29
It dont like any d3d8 wrapper, other that dxwrapper one of particular version too. Even there it throws exveption in the log:

> UnhandledExceptionFilter: exception code=3221225477 flags=0 addr=100032C8
 UnhandledExceptionFilter: NOP opcode=ó len=2 

 memory heap corruption, but is somehow able to continue to run.

**Comment by kai4785** [comment] 2024-09-17 21:01
dxwrapper does work!
![image](https://github.com/user-attachments/assets/62ff3e61-84e4-4c00-b8e6-9be7539c9a31)
And there certainly are performance problems. With dgVoodo->d3d11, GPU sits at 5% utilization.

The fullscreen/windowed shenanigans may be due to the `eqw` code that got baked into the TAKP client. The client is old enough to be from the time where "Full Screen" was used as anti-cheat!

I'll try to get an api trace with dxwrapper instead of dgvoodoo and see how that goes.

**Comment by dungeon007** [comment] 2024-09-17 21:04
As i mention, make sure it is DXVK 2.2 or older, there is a perf problem on DXVK 2.3+.
That is another bug, for a bisecting volonteers. :dancers:

**Comment by WinterSnowfall** [comment] 2024-09-17 21:23
> And there certainly are performance problems. With dgVoodo->d3d11, GPU sits at 5% utilization.

Not saying there aren't performance issues (that frametime chart does indeed look stuttery), but the 100% GPU utilization is very likely because:

- you are on Nvidia
- you have V-Sync enabled

It's basically a known issue that will cause GPU utilization to show up as peaked, but I assure you it's nowhere near 100%.

**Comment by kai4785** [comment] 2024-09-18 01:02
Ok, here are 3 traces. Hopefully I didn't trim them down too far to be useful.
[eqgame-trim.tar.gz](https://github.com/user-attachments/files/17036857/eqgame-trim.tar.gz)
* `dxvk2.4/eqgame-trim.trace`
  * `d3d8.dll` from dxvk-2.4
  * `d3d9.dll` from dxvk-2.4
* `dxwrapper-dxvk2.2/eqgame-trim.trace`
  * `d3d8.dll` from the provided dxwrapper zip above
  * `d3d9.dll` from dxvk-2.2
* `dxwrapper-dxvk2.4/eqgame-trim.trace`
  * `d3d8.dll` from dxwrapper
  * `d3d9.dll` from dxvk-2.4

**Comment by kai4785** [comment] 2024-09-18 01:20
I also went through all three of the same scenarios above, and tried setting `WINE_D3D_CONFIG="renderer=no3d"` with no change in behavior. I tried adding `wine explorer /desktop=EQ,1920x1080` before `eqgame.exe`, and it crashes with dxvk-2.4, and renders just a black screen with dxwrapper. When I tried all 3 scenarios with both `WINE_D3D_CONFIG` and `/desktop`, it crashed 2.4 and black screened dxwrapper.

**Comment by dungeon007** [comment] 2024-09-18 03:52
You can ignore these small traces, apitrace dlls also cant bypass these memory memory heap corruption exceptions.

Tried on Windows 7. Put a ddraw from apitrace - exception, put a d3d8 again exception. Look at a dxwrapper log there:

> UnhandledExceptionFilter: exception code=3221225477 flags=0 addr=100032C8
UnhandledExceptionFilter: NOP opcode=ó len=2

You see that? That dxwrapper version simply is able to continue there, somehow ignoring such exception... and thats it.

**Comment by WinterSnowfall** [comment] 2024-09-18 09:56
As @dungeon007 has said, this seems to be more of a problem with something crashing inside game code (or game code causing a crash somewhere) rather than with what any wrappers/translation layers are doing. I don't think there's a reasonable approach for us to solve this, and would classify it as a game bug. I guess it's just one of those situations where problematic behavior manages to sneak through and work on Windows d3d.

**Comment by dungeon007** [comment] 2024-09-18 14:38
Bug could stay for a D3D9 perf regression, as is using Software Vertex Processing i am not surprised... 
I already know d3d8 SVPs could turn into bad perf in DXVK's d3d9. Here is the best trace i know to optimise d3d9 SVPs for https://drive.google.com/file/d/1V_JT0FAPUejBMTXPXzakSBJfoMETEAgd/view?usp=sharing
 Crazy SVPs produces huge traces 🤣
 Or check demos of these d3d8 games yourself:
 https://codeminion.com/games/phantasmat
 https://codeminion.com/games/brunhilda-and-the-dark-crystal

**Comment by K0bin** [comment] 2024-09-18 15:26
@dungeon007 I don't really understand your last comment, could you please clarify what you meant?

Is there a performance problem with DXVK in that game?

**Comment by kai4785** [comment] 2024-09-18 15:55
![image](https://github.com/user-attachments/assets/3ae9551c-1a2b-4b34-ac0d-58db599c1f67)
I can confirm that d3d8 works just fine if I cut out the `eqw` code. As for an explanation, this client is so old that it doesn't support running in windowed mode. As far as I know, `eqw` was written a long time ago (I can't find a source for it's origin) and was written to provide windowing capability before it was officially added to the client later. I'm now certain it's `eqw`'s fault that I'm crashing.
![image](https://github.com/user-attachments/assets/8d1ceb61-afbb-4b44-9cab-bd7fd902f96a)
However, `d3d8` is performing poorly. CPU is at 100% when it's usually closer to 40%. I don't know much, but it sounds like maybe it's rendering things in software that could be done on hardware? I wouldn't begin to know how to track that down though.

**Comment by dungeon007** [comment] 2024-09-18 15:57
@Kobin I already clarified that for you elsewhere 🤣 
1. Trace is already maded
2. Link for the games is already given
3.  So, now i am just posting pictures:

Gallium NINE - very well optimized SVPs
![NINE1](https://github.com/user-attachments/assets/bb6b5f76-27dd-44ea-8f81-82e0f2d2e4ca) 
![NINE2](https://github.com/user-attachments/assets/a1001d7d-defc-4ca2-984d-3d2251e1fc75) 
![NINE3](https://github.com/user-attachments/assets/49b496cd-76ca-4bdd-8e47-fd80f0440406)

DXVK's D3D9 - very NOT well optimized SVP (since forever)

![DXVK1](https://github.com/user-attachments/assets/4a7ae40c-7527-4c00-afa7-dc3d6e33195b) 
![DXVK2](https://github.com/user-attachments/assets/1c329532-af9c-4397-acc4-9c26fa4012ec) 
![DXVK3](https://github.com/user-attachments/assets/b4b0e6e0-607f-4410-be57-9d9003d7862d)

**Comment by WinterSnowfall** [comment] 2024-09-18 15:58
> However, `d3d8` is performing poorly. CPU is at 100% when it's usually closer to 40%. I don't know much, but it sounds like maybe it's rendering things in software that could be done on hardware? I wouldn't begin to know how to track that down though.

Obligatory "does setting `d3d9.cachedDynamicBuffers = True` help?" question :).

**Comment by Blisto91** [comment] 2024-09-18 15:59
@kai4785 What `eqw` code?

**Comment by kai4785** [comment] 2024-09-18 16:10
Re: EQW @Blisto91 
On [the getting started page](https://wiki.takp.info/index.php/Getting_Started_on_Windows), there's a link to download the unmodified `eqgame.exe` file with a companion `eqw.exe` program (the purple link)
![image](https://github.com/user-attachments/assets/7c8f401b-715d-484e-921d-5fc32241154f)
I don't really have anymore information, and will go looking for it. However, this allows me to run `eqgame.exe` with out `eqw` in the way, and *that* launches for me just fine. If I launch `eqw.exe` directly from this environment, it crashes like my original post.
Re: `d3d9.cachedDynamicBuffers = True`
Unfortunately not.
```
$ grep cachedDynamicBuffers ../logs/lutris-GE-Proton8-26-x86_64/wine.log
info:    d3d9.cachedDynamicBuffers = True
info:    d3d9.cachedDynamicBuffers = True
```

**Comment by kai4785** [comment] 2024-09-18 18:39
Ok, I think we officially make this ticket a performance issue, like @dungeon007 suggests. I'm increasingly confident that the `eqw` program that we so heavily rely on is the source of all my problems, while simultaneously being indispensable by forcing the game into a window. I will take my adventure to find a replacement "Run it in a window" exercise somewhere else (like maybe [dxwnd](https://sourceforge.net/p/dxwnd/home/Home/)).

Since I have a new entry point to work with with out eqw, I have discovered that the game runs great with out of the box settings in lutris-GE-Proton8-26-x86_64; with out any help from dxwrapper, dxvk, or dgVoodoo. (I do get some flickering on the login server, where @dungeon007 says it's using DDRAW, but it's usable.)

So, let's reset a little bit and say:

This old EverQuest Client runs great on lutris-GE-Proton8-26-x86_64, and has performance issues when trying to use dxvk's d3d8.

**Comment by Blisto91** [comment] 2024-09-18 18:49
I dunno. I think it is fine to keep this about the original issue since it works fine on native Windows.
It has also gotten quite messy so i would personally prefer if the performance problem got it's own separate issue

**Comment by K0bin** [comment] 2024-09-18 22:21
@dungeon007 Try #4274

**Comment by dungeon007** [comment] 2024-09-18 22:57
@Kobin
 That perform OK:
 
![2024-09-19_00:51:56_1728x1080](https://github.com/user-attachments/assets/5efdc0a1-2655-4fcc-9ba9-567a2fa9460c) 
![2024-09-19_00:52:06_1728x1080](https://github.com/user-attachments/assets/c2db3c2d-28bd-428b-bc60-676681d51046) 
![2024-09-19_00:52:13_1728x1080](https://github.com/user-attachments/assets/b5d03628-2dba-4fe7-bc87-5b2011e88499)

 Maybe it could be pushed up a bit more for the last... anyway, even this is good.

**Comment by kai4785** [comment] 2024-09-19 00:42
> I dunno. I think it is fine to keep this about the original issue since it works fine on native Windows so ideally should with dxvk too. It has also gotten quite messy so i would personally prefer if the performance problem got its own separate issue

Well, if you're interested in trying to get `eqw` to work properly, I think we may be enlightened by the [dgVoodoo author's post](https://www.vogons.org/viewtopic.php?p=1164144#p1164144) a while back, when another player from this server asked him about a different bug.

> If I use a d3d8.dll that's emitted directly by the compiler then I can't even log in into the character selection screen because it crashes right after switching into d3d8 mode. This is because the game seems to hook D3D8 and does this by overwriting the virtual function table of the D3D8 COM object(s). TBH it's a very bad practice because the compiler puts vft's into a read-only memory section (that's why it crashes) and it's only by chance that it works with dgVoodoo releases (the executable packer makes those pages writable). Native D3D8 puts the vft into a dynamically allocated (writable) area that's why this hook method works with it.

This sound like exactly the problem I started with. His diagnosis is that `eqw` is scribbling in memory in order to hook d3d, and in some cases that memory is read-only. That's possibly what is happening to dxvk as well.

**Comment by dungeon007** [comment] 2024-09-19 01:50
BTW, @kai4785 which version you use there? These wikis lists versions liek TAKP PC V2.0 and 2.1c and 2.2 and... there is quite a lot text there to read, maybe there are more.... 
That is the first thing you had to say, as there could be some functional differences in these, but anyway .🤣

**Comment by kai4785** [comment] 2024-09-19 03:41
@dungeon007 
I'm using the `2.0` client which comes with the `freethemouse` version `eqgame_dll-v3.6.8.5-for-ftm`.

All versions contain the same game files and all versions contain the same `eqw.dll` library. They vary only in 2 ways:
* which version of `freethemouse`
* presence or absence of dgVoodoo

I have not tried using the `2.1` or `2.2` clients because they purported to resolve issues I didn't have, or were already solving (e.g. the addition of dgVoodoo).

For the purposes of this thread, I would suggest using the `2.0` client because really it boils down to figuring out if `eqw.dll` is doing something dxvk wants to support (overwriting the virtual function table?).

**Comment by kai4785** [comment] 2024-09-19 04:58
Had a friend divine what dege was saying about dgVoodoo crashing. Apparently if `d3d8.dll` is compressed, it will be decompressed into a writable location in memory.
```
kai@overmind:~/.takp/drive_e/TAKP$ sha256sum d3d*.dll
b6b9801a5eea87c061f974f9c182cbb601ee624e90b8ab84f8a842f808a1d661  d3d8.dll
b2c451064705afa824b6b24e71b7bfa5dccbce92c326665a30482908abd6ec5c  d3d9.dll
kai@overmind:~/.takp/drive_e/TAKP$ upx d3d8.dll
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.2       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 3rd 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1646606 ->    489486   29.73%    win32/pe     d3d8.dll                      

Packed 1 file.
kai@overmind:~/.takp/drive_e/TAKP$ sha256sum d3d*.dll
e32de843e9c795579bd27177f67ef4e4ab2cef0ba305fa69c27955fff19379d7  d3d8.dll
b2c451064705afa824b6b24e71b7bfa5dccbce92c326665a30482908abd6ec5c  d3d9.dll
```
Now `dxvk-2.4` gets past the crash originally reported in this bug. Very interesting!

**Comment by dungeon007** [comment] 2024-09-19 05:03
So if you are upxing it, it works? Thats iprobably means that game probably checks some flags, but it cant if upxed.

**Comment by WinterSnowfall** [comment] 2024-09-19 10:40
> Had a friend divine what dege was saying about dgVoodoo crashing. Apparently if `d3d8.dll` is compressed, it will be decompressed into a writable location in memory. I got it to work using [UPX](https://github.com/upx/upx) to compress `d3d8.dll`.

*Sigh*. Well, as I said before, a clear case of game code doing(/expecting) unreasonable things. We can mark the original issue as game(/loader)-specific bug, whereas the performance problems are in the process of being addressed by @K0bin.

> cos of redesign some potentional regressions on a HWVP path... that could be or might not 👯

K0bin's latest optimizations target SWVP only devices, so the likelihood of regressions outside of that is minimal. Of course it could regress other known SWVP-only games like The Sims 2, but those will be checked.

Overall I think it's looking good. Thanks to everyone on this thread for their contributions in figuring it all out. As soon as the performance optimizations get merged we can close this issue.

**Comment by dungeon007** [comment] 2024-09-19 17:50
I think that loading problem is all because dxwrapper particular version having less stalls, produces smoother scene tranistions in apps, also handling a window in a old way. etc...
 Meanwhile all else classic d3d8 wrappers (including DXVK's d3d8) arent this smooth. They all stall more here and there.
 So dont forget about mentioned **DxWrapper v1.0.990.18** wrapper, there are couple such good things in it to explore. If something is not smooth try that one.

**Comment by kai4785** [comment] 2024-09-19 20:55
@dungeon007  
I updated the wiki to enumerate a few more of the changes, but I think it comes down to the freethemouse code that emu devs created. Among other things, it adds a framerate limiter, and the different versions of the client have different default values for the framerate limiter. I have preferred using `DXVK_FRAME_RATE=60` on my machine. Sometimes 380 fps isn't worth the power consumption over 60fps when you have a 60hz monitor. : )

@WinterSnowfall
It makes sense that dxvk wouldn't want to be required to provide a work around for eqw poking holes in read-only memory, and it makes sense that old programs like `eqw` took advantage of the lack of these protections. I'd be interested to find a way to something like ask WINE to disable some of these modern security measures, especially if it could be done for a single dll. In lieu of something insane like that, I have a work around to compress the `d3d8.dll` file from DXVK that I'm happy to carry around for a while.

**Comment by kai4785** [comment] 2024-09-19 21:55
@dungeon007 I would be happy to test a build, but I'm not sure how to download builds from his branch ([this link](https://github.com/doitsujin/dxvk/suites/28601606220/artifacts/1954041703) gives me a 404), and I haven't setup a build environment yet. I may have time later, I'm eager to see if it works well for me.

**Comment by dungeon007** [comment] 2024-09-19 21:57
Ah, so just downlaod last artifact, this for example https://github.com/doitsujin/dxvk/actions/runs/10947178155/artifacts/1954906377

**Comment by kai4785** [comment] 2024-09-19 22:14
No upxing -- crash
with upxing -- same poor performance.
![image](https://github.com/user-attachments/assets/5aeb751b-5817-4dda-a2b7-c6301bfd8f06)
Even with this 8 FPS, CPU utilization is at ~40%.
When I look at a wall:
![image](https://github.com/user-attachments/assets/c09888e4-f588-4dc8-b1ad-55cd75d3de32)
CPU utilization jumps to ~80% with good framerate.

**Comment by Blisto91** [comment] 2024-09-19 22:18
The perf fix isn't merged so the master download linked  above doesn't contain it. You can download it from here https://github.com/doitsujin/dxvk/actions/runs/10944430419

**Comment by dungeon007** [comment] 2024-09-19 22:30
Yeah, it is possible that i posted a wrong link too. I was taking something else yesertday, while it was fresh.

**Comment by kai4785** [comment] 2024-09-20 03:44
Much better. Still have to `upx` it though.
![image](https://github.com/user-attachments/assets/aeb42066-0094-4599-a6e6-88be9bc44d3f)

However, it doesn't seem to respect `DXVK_FRAME_RATE=60`, so I get a smooth 100 FPS looking around in the bazaar (lots of character models and geometry) and 300 FPS looking at the wall. Is that a known issue for `d3d8`?

If I use the frame rate limiter hacked into the client, it burns about 20% cpu looking at the wall and 80% cpu walking around. 

Using the same build, but with dgVoodoo -> d3d11, `DXVK_FRAME_RATE=60` works properly, and the same experiment looking at the wall vs walking around, I get the same 20% cpu utilization looking at the wall and 60% utilization looking around.

I think it's more likely that dxvk's better at limiting framerate than the hacks in the client. I am optimistic that the next release of dxvk will be everything I need it to be! Thank you all so much!

**Comment by dungeon007** [comment] 2024-09-20 03:49
>However, it doesn't seem to respect DXVK_FRAME_RATE=60, so I get a smooth 100 FPS looking around in the bazaar (lots of character models and geometry) and 300 FPS looking at the wall. Is that a known issue for d3d8?

Perf issue there is related to D3D9 Software Vertex Processing, depends how much gonna be optimized :dancers:

**Comment by kai4785** [comment] 2024-09-21 05:02
While `DXVK_FRAME_RATE=60` does not work, `d3d9.maxFrameRate = 60` does work.

**Comment by Blisto91** [comment] 2024-09-21 06:20
How are you using the first one

**Comment by WinterSnowfall** [comment] 2024-09-21 07:34
> While `DXVK_FRAME_RATE=60` does not work, `d3d9.maxFrameRate = 60` does work.

What @Blisto91 is trying to say is that `DXVK_FRAME_RATE=60` is an env variable intended for command line use (or in .bashrc and the like), whereas `d3d9.maxFrameRate = 60` goes in dxvk.conf. Both work when used appropriately.

**Comment by kai4785** [comment] 2024-09-21 14:56
When using dgVoodoo d3d8-> dxvk d3d11+dxgi, both the environment variable `DXVK_FRAME_RATE=60` works as well as setting `dxgi.maxFrameRate = 60` in dxvk.

However, when using dxvk's d3d8->d3d9, setting the environment variable `DXVK_FRAME_RATE=60` does not limit frame rate, but setting `d3d9.maxFrameRate = 60` in dxvk.conf does work.

I'm suggesting that the environment variable is broken somehow when using d3d8+d3d9.

**Comment by WinterSnowfall** [comment] 2024-09-21 15:00
> I'm suggesting that the environment variable is broken somehow when using d3d8+d3d9.

Works just fine over here on dxvk master with d3d8 games, so I'm not sure why you're having issues with it.

**Comment by dungeon007** [comment] 2024-09-21 18:33
Stupid things could come when you are upxing something 🤣

**Comment by kai4785** [comment] 2024-09-22 03:21
@dungeon007 
I understand that using upx isn't a desirable solution. I only do it experiment with different ways to get this old game I like to play to work. I would be pleased if there was a way for dxvk to behave like Windows does, as you reported, and allow the `eqw` hack to hook d3d8 the way it does.
As far as stupid things happening, after a few hours of playing, the game operates just as well, and often better, than using dgVoodoo's d3d8 and dxvk's d3d11+dxgi. If there's an interest in changing dxvk's d3d8 to let `eqw` hack it's vtable in the way dege describes, I'd love to use it. If not, I'll probably continue to use upx on dxvk's d3d8 rather than mix and match with dgVoodoo.

I do really appreciate everyone's help on the multiple issues that came up in this thread. I realize just how edge case my problem is; an old 2002 video game with a third party hack to force the full-screen only game into windowed mode.

**Comment by dungeon007** [comment] 2024-09-22 04:30
>Thus far, adding explorer /desktop=EQ,1920x1080 has not worked
 WINE's virtual window is not any requirement, just recommendation to run inside of that, because of these fullscreen/windowed shenanigans of the game.
 I use Mesa drivers on AMD, while you are on nVidia, so of course YMMV there.

**Comment by dungeon007** [comment] 2024-09-22 21:54
Testing main of today, plus seems DxvkResourceAllocation and now we can talk about perfection :+1: 

![2024-09-22_23:47:36_1728x1080](https://github.com/user-attachments/assets/af267c86-5886-43d3-92dc-eeeeffe77673)

**Comment by kai4785** [comment] 2024-09-23 00:39
> I just dunno, how you can be supported if that become reason of some possible problems, so thats it 🤣

I totally understand. If I ever come back with an issue running this game, I will report it with out `upx`ing, and with instructions on how to replicate the problem *with out* using `eqw` at all.

I have a working development environment for `dxvk` and will try my hand at figuring out exactly what `eqw` is doing, and perhaps discover why it works for some `d3d8.dll` files (like Windows 7 and some dgVoodoo) but not others (like dxvk and other wrappers).

**Comment by WinterSnowfall** [comment] 2024-09-24 09:19
@kai4785 Performance should be fine with the game now on latest master. Please have a go and let us know if it behaves as expected. As for the upx-ing discussion, I would imagine that part (memory access shenanigans) is more in the realm of Wine and not something we (or other wrappers) should consider working around.

I think we can close this issue once you confirm it's good with latest master.

**Comment by kai4785** [comment] 2024-09-25 17:55
![image](https://github.com/user-attachments/assets/fa312c82-49a1-4c0d-b100-12126a63e448)
Ya, I think the latest master is running well.
If you have any pointers on where to go digging on the upx issue, I'd gladly take them. Thanks!

**Closed** 2024-09-25 18:51 UTC

**Comment by WinterSnowfall** [comment] 2024-09-25 19:02
> If you have any pointers on where to go digging on the upx issue, I'd gladly take them. Thanks!

Kind of hard to tell unless there's at least hints or code pertaining to what eqw might be doing. I suspect it *might* try to inject itself into d3d8, which would technically trigger a memory access violation. Upx-ing gets around that most likely because it unpacks the dll in a separate memory area (which is also writable?). I don't have anything beside these speculations, I'm afraid.

**Comment by dungeon007** [comment] 2024-09-25 23:39
>>If you have any pointers on where to go digging on the upx issue, I'd gladly take them. Thanks!
Just do not ever try to fixing things by upxing anything, that really is a wrong idea. :dancers: 
 
So, honestly i think that all wrappers are wrong into something there, including dgVoodoo2 that just hides an issue, because it is hackish upxed. You cant fix anything properly by hiding it, game will potentionaly forever crashing in places more or less..

Best pointer? Do not even try to play a game, no joke 
On Windows put a apitrace's ddraw.dll into the game folder and observe that OS throws a memory corruption window., even before a launcher.
 That is a good starting point. Now ,go around and change in game config files everything to a minimum, try to break logging, debuging, try to hexing up particular functions, etc... basically whatever you can, until you found out what exactly triggers/ making this memory corruption. As ideally, there shouldnt be any memory corruption there in the first place.

  As again **Game works on Windows 7 and native ddraw/d3d8.**

Similar thing happens in bug #4214, where all wrappers are getting something (else) wrong. DXVK's d3d8 leaks memory, dgVoodoo2 and WINED3D missrender in places, d3d8to9 seems to have broken PS1.1 shaders, etc... and so on and so forth, meanwhile there again **Game works and renders fine on Windows 7 and native d3d8.**   

 Techincally speaking these games do nothing wrong. There are really an ALL wrappers bug and in ALL OF THEM.

@Blisto91 I dont spam. I just trying to not hide anything. With that, story probably have to go a bit longer and then I cant help it 🤣

**Comment by dungeon007** [comment] 2024-09-26 11:12
On 2.4.1 release, our benchmark is saying that it is like 10% slower than what was i testing 4 days ago.

![2024-09-26_12:27:00_1728x1080](https://github.com/user-attachments/assets/d8d71eea-8adb-4611-89a9-0649d5d5384e)

Very good bench this is, it detects any move on a CPU side of things.  🤣 At best as a saw it was firing GPU 66% there and now about 60%, but i guess that is an improvment from compiler flags for these that prefers it more safe formed release build.
 Whatever, at least it dont drop crazy low like before, so alarm is not needed to be fired up, just slightly.

**Comment by K0bin** [comment] 2024-09-26 11:50
> On 2.4.1 release, our benchmark is saying that it is like 10% slower than what was i testing 4 days ago.

That must be margin of error then. The code hasn't changed since.

**Comment by kai4785** [comment] 2024-09-26 17:08
release 2.4.1 "works fo rme" (with upx). I'm not having much luck tracking down precisely what it's doing, but I strongly suspect that it's calling `Direct3DCreate8`, and then poking at the returned structure. I'm trying to catch it in the act and replicate it, but my windows debugging skills (especially with out debug symbols and source code) are insufficient.

**Comment by dungeon007** [comment] 2024-09-26 21:07
> > On 2.4.1 release, our benchmark is saying that it is like 10% slower than what was i testing 4 days ago.
> 
> That must be margin of error then. The code hasn't changed since.

Yeah, code didnt changed. But if compiling flags arent the same on Master and Release, then this diff could be explained easely. 

 @kai4785
"I have a working development environment for dxvk"
 Cool, so you can try playing with a compiler flags too. It is not imposible that something breaks if with too much optimizations enabled there.

**Comment by dungeon007** [comment] 2024-09-27 00:57
> > On 2.4.1 release, our benchmark is saying that it is like 10% slower than what was i testing 4 days ago.
> 
> That must be margin of error then. The code hasn't changed since.

 Of course code didnt changed, but other code get changed. So it immediately get affected by next commits. 

 ![2024-09-26_13:28:53_1728x1080](https://github.com/user-attachments/assets/ad0c5efc-ebab-45ba-ad1e-e29f8905eda1)

 ![2024-09-27_02:28:39_1728x1080](https://github.com/user-attachments/assets/d3f6bbb2-08a5-479d-9d38-ebcd46792d79)

 And then on release 60%.With such tendency of seems consisntently going down i cant guarantee SVP perf will remain fine for long. I guess we will get 20% less margin of error or probably even more very soon 🤣
