### ISSUE TITLE
Regression: Batman Arkham City GOTY fails with dxvk-1.4 with DirectX Features and Tesselation on

### ISSUE THREAD

**Issue by alasky17** [doitsujin/dxvk#1203] opened 2019-09-25 15:18 UTC
### Software information
Batman: Arkham City - GOTY (200260)
Note: to access the settings, must select "configure PC options" on launch instead of jumping straight into the game

Regression: When the configuration is set with DirectX11 Features and DirectX 11 Tessellation on, the game will fail shortly after launching, before getting into a game with an error dialogue "Rendering thread exception: Fatal error!....." (screenshot of full error attached). 
![arkam-city-error](https://user-images.githubusercontent.com/40211296/65614189-cd9bf680-df7c-11e9-901c-5f04957b9438.png)

This is a regression from dxvk-1.3.4.  I tested this with Proton 4.11-6 which includes dxvk-1.4 and got the failure.  When I dropped in dxvk-1.3.4 I did not get the error with the same settings and the game was playable.

### System information
- GPU:AMD Radeon RX 470
- Driver:amdgpu 
- Wine version: Proton 4.11-6 (based on wine 4.11)
- DXVK version: 1.4
Note: originally reported here with NVIDIA gpu: https://github.com/ValveSoftware/Proton/issues/309#issuecomment-534741580

### Apitrace file(s)
- The game failed to launch straight from the exe.  I tried both BatmanAC.exe and BmLauncher.exe but they failed before getting to the bug, so I don't have an apitrace to upload.

### Log files
- d3d11.log:
- dxgi.log:
[BatmanAC_dxgi.log](https://github.com/doitsujin/dxvk/files/3653156/BatmanAC_dxgi.log)
[BatmanAC_d3d11.log](https://github.com/doitsujin/dxvk/files/3653157/BatmanAC_d3d11.log)

**Comment by K0bin** [comment] 2019-09-25 18:03
Caused by b0f6655b92adbf24e53df865ea4481b02e3b9d73

**Comment by K0bin** [comment] 2019-09-25 18:59
Fixed by 53fe3423e232fe0da26e7d9f59802d091564cb92

**Closed** 2019-09-25 19:00 UTC
