### ISSUE TITLE
Red/yellow glow from fires in Assassin's Creed Odyssey

### ISSUE THREAD

**Issue by Mikaka27** [doitsujin/dxvk#1215] opened 2019-10-05 13:49 UTC
In Assassin's Creed Odyssey you can observe strange red/yellow glow from fires.
See screenshots from Linux and Windows (linux first, windows second):
![ACOdyssey Linux](https://user-images.githubusercontent.com/9214100/66255636-4faecb00-e786-11e9-9648-4355df2753c0.png)
![ACOdyssey Windows](https://user-images.githubusercontent.com/9214100/66255639-589f9c80-e786-11e9-8711-1f8686476a77.png)

You can see the glow is not present in Windows.

### Software information
Assassin's Creed Odyssey

### System information
- GPU: Nvidia Geforce GTX 1660 Ti
- Driver: 435.21
- Wine version: wine-4.0.2
- DXVK version: 1.4.2 (same thing on 1.4.1 as well)

### Apitrace file(s)
Game crashes without dxvk, so I tried to capture apitrace with DXVK installed, but only got this file:
[ACOdyssey-trace.txt](https://github.com/doitsujin/dxvk/files/3693293/ACOdyssey-trace.txt)

Used the following command:
wine ~/Pobrane/apitrace-8.0.20190414-win64/bin/apitrace.exe trace -a dxgi -o ACOdyssey-trace.txt ACOdyssey.exe
I'd appreciate any help in capturing the apitrace.

### Log files
- d3d11.log: [ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/3693294/ACOdyssey_d3d11.log)

- dxgi.log: [ACOdyssey_dxgi.log](https://github.com/doitsujin/dxvk/files/3693295/ACOdyssey_dxgi.log)

**Comment by doitsujin** [comment] 2019-10-05 14:05
Are you absolutely certain that you even tested the same settings on both systems?

Might also be worth checking out whether the same issue (if this is one at all) occurs on Windows with DXVK or on Nvidia's latest Beta driver. As far as I'm aware, this game renders correctly on DXVK on my AMD card.

**Comment by Mikaka27** [comment] 2019-10-05 16:59
Hi,
You're right this doesn't happen on Windows with dxvk.
On windows I see other artifacts (not relevant to this bug or maybe dxvk at all) in top right corner here:
![Zrzut ekranu (17)](https://user-images.githubusercontent.com/9214100/66258154-f5236800-e7a1-11e9-84fd-c97bb36059d0.png)

Do you mean I should try to install beta drivers on the linux or windows box?
Anyway my apologies for wasting your time if it's unrelated to dxvk.

**Comment by doitsujin** [comment] 2019-10-05 17:25
Linux.

I'll double-check this on my machine on monday, but it looks like a driver issue (perhaps Turing-specific, another user on an RTX 2080 confirmed your issue).

**Comment by Mikaka27** [comment] 2019-10-05 17:52
Hi,
Unfortunately it seems no beta drivers are available for this, I only see 430.09 which is older than what I have now.
![Zrzut ekranu z 2019-10-05 19-49-05](https://user-images.githubusercontent.com/9214100/66258782-919d3880-e7a9-11e9-9361-4101b1d5b90f.png)

**Comment by K0bin** [comment] 2019-10-05 18:23
Nvidia has a separate beta branch for the Vulkan driver. You can find those here:
https://developer.nvidia.com/vulkan-driver

**Comment by Mikaka27** [comment] 2019-11-07 18:47
Hi, just an update issue still happens with nvidia driver 440.26 installed from graphics-drivers ppa.

Sorry about the window in the middle of screenshot, something is wrong with screen capture (I get some weird frame from main menu instead of gameplay) otherwise:
![Zrzut ekranu z 2019-11-07 19-43-34](https://user-images.githubusercontent.com/9214100/68417802-60909900-0197-11ea-843b-1b65b884a455.png)

**Comment by Vash63** [comment] 2019-11-15 18:25
I believe this was fixed in 435.27.07 - it fixed a number of issues for me in the game. Note that this version is _newer_ than the 440.xx releases, you must use this exact version to test right now.

**Comment by doitsujin** [comment] 2019-12-11 21:18
Should indeed be fixed as of the latest Vulkan beta driver, and should make its way into the stable branch eventually.

**Closed by doitsujin** 2019-12-11 21:18 UTC
Labels: nvidia
