### ISSUE TITLE
Total War : Shogun 2 istability when using d3d9.dll and d3d11.dll from DXVK

### ISSUE THREAD

**Issue by llde** [doitsujin/dxvk#2591] opened 2022-04-06 21:47 UTC
Total War : Shogun 2 load both d3d9.dll and d3d11.dll on start before the DX selector (skipped usin g DXVK DXGI)
This seems to cause some instability during gameplay, in battles and when transitioning between battles
The presence of DXVK DXGI seems to affect instability (seems more unstable with DXVK DXGI then without) 
If I put on builtin one of d3d9.dll or d3d11.dll wasn't able to experience crash (excpet a couple of unrelated and reproducible crashes)
EDIT: I'm failing to crash again with Wine DXGI and both other DXVK dll under DX11 renderer at least. Need to do more test with and without DXVK DXGI and the 2 other DLLs (can't test wine d3d dlls and dxvk dxgi however, at least for d3d11). I can replicate the crash using dxvk dxgi
### Software information
Total War : Shogun 2, High settings
### System information
-GPU: RX580 8G
-Driver: RADV 22.0.1
-Wine version: 7.5
-DXVK version: https://github.com/doitsujin/dxvk/commit/42c66c410e213f7504903744a5684a4e453f71f2

### Apitrace file(s)
- apitrace is extremly slow and this seems to prevent me to experience the unstability. If this is necessary I will try to make it but not in short time.
### Log files
[Shogun2_dxgi.log](https://github.com/doitsujin/dxvk/files/8432039/Shogun2_dxgi.log)
[Shogun2_d3d9.log](https://github.com/doitsujin/dxvk/files/8432036/Shogun2_d3d9.log)
[Shogun2_d3d11.log](https://github.com/doitsujin/dxvk/files/8432037/Shogun2_d3d11.log)

**Comment by doitsujin** [comment] 2022-04-06 23:56
https://github.com/doitsujin/dxvk/issues/1318

**Comment by Blisto91** [comment] 2022-04-07 06:27
@llde If it's a memory issue you could try to see if [this PR](https://github.com/doitsujin/dxvk/pull/2524) alleviates the issue.

You can grab a non release build of it [here](https://github.com/doitsujin/dxvk/actions/runs/2042082711)

**Comment by llde** [comment] 2022-04-07 07:52
I'm not sure if this an address space issue. Other games that were affected with this got explicit allocation error in wine or dxvk log. Nothing was present here.

**Comment by Blisto91** [comment] 2022-04-07 08:08
I can try to test here later when i have time, think i have the game if i remember correctly.

**Comment by doitsujin** [comment] 2022-04-07 10:49
> @llde If it's a memory issue you could try to see if [this PR](https://github.com/doitsujin/dxvk/pull/2524) alleviates the issue.

This would only have an effect for D3D9 though, D3D11 doesn't work that way.

**Comment by llde** [comment] 2022-04-07 12:09
There are other know instances of games that load both APIs at the start? I was thinking that maybe is that the issue, as by loading only one of the DXVK DLLs seems to works stable (at least in the tutorial)

**Comment by Blisto91** [comment] 2022-04-08 10:51
I tried playing a bit through proton in dx9 mode (the only one i can get working) and i did notice it can crash when exiting a battle. When i looked at the vram usage and system memory usage i didn't notice anything worrying on that front. Not completely sure what crashes it yet or if it's dxvk.
Gonna try some more later.

**Comment by patmann03** [comment] 2022-04-10 02:54
> See #1318. All "modern" 32-bit games have this issue with DXVK, and this isn't really something we can fix without bascally writing a dedicated 32-bit version that is optimized solely for reducing address space usage.



In proton in my log I get this after 10-20 minutes on Total War: Rome 2 which I believe uses the same game engine as Shogun 2.  Is this the memory issue you're referring to?

`4172.818:0254:02dc:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
4172.818:0254:02dc:trace:seh:dispatch_exception  eax=00000004 ebx=1ed59500 ecx=00100000 edx=11014fac esi=ffff8001 edi=00000000
4172.818:0254:02dc:trace:seh:dispatch_exception  ebp=00000000 esp=1073fc20 cs=0023 ss=002b ds=002b es=002b fs=0063 gs=006b flags=00010216
4172.818:0254:02dc:trace:seh:call_vectored_handlers calling handler at 62538170 code=c0000005 flags=0
4172.818:0254:02dc:trace:seh:call_vectored_handlers handler at 62538170 returned 0
4172.818:0254:02dc:trace:seh:call_stack_handlers calling handler at 7BC68240 code=c0000005 flags=0
wine: Unhandled page fault on write access to 00000008 at address F188D013 (thread 02dc), starting debugger...
4172.832:0254:02dc:trace:seh:start_debugger Starting debugger L"winedbg --auto 596 1568"`


Been desperately trying to get Rome 2 to work well on linux.  Interestingly I added the latest GE Proton GE release (which is using the latest git as of 6 days ago) on Attila and DXVK isn't crashing.. I used to have to run that game with wined3d.  Played for 2+ hours last night without a single crash was very happy.

**Comment by Blisto91** [comment] 2022-04-10 11:41
Testing it for shogun 2 now.
Proton log stuff from crash
```
10053.847:0130:0134:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0xffde0000-(nil), unix_prot 0.
10053.847:0130:0134:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0xffde0000-(nil), unix_prot 0.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
10053.858:0130:0134:trace:seh:raise (22)
10053.859:0130:0134:fixme:msvcrt:__clean_type_info_names_internal (031FAB88) stub
10053.871:0130:0134:fixme:msvcrt:__clean_type_info_names_internal (59339348) stub
10053.871:0130:0134:fixme:msvcrt:__clean_type_info_names_internal (5BA7F78C) stub
10053.871:0130:0134:fixme:msvcrt:__clean_type_info_names_internal (5BA41894) stub
10053.871:0130:0134:fixme:msvcrt:__clean_type_info_names_internal (5B6A3A60) stub
_RECORD>,class CA_STD::ALLOCATOR<struct CA::UniString const *>,struct MEMORY::CAAllocator>::record_index
WS_LOADING_SCREEN_IMP::pf_on_destroy()
Imposter budget: 437Mb
Imposter quality 5 (size 2048, step 0.10): 36Mb
WS_SPRITE_IMP::pf_on_create() create_vertex_buffer() called, size:432000
WS_SPRITE_IMP::pf_on_create CreateIndexBuffer() called, size:48000
Setting breakpad minidump AppID = 34330
```

**Comment by Blisto91** [comment] 2022-04-10 17:22
Okay managed to get d11 working. Had to install `d3dx11_42` and not `d3dx11_43` i think. Although i have both so not sure.
Anyway, the specific crash above doesn't happen in dx11 mode, only dx9.

**Comment by Blisto91** [comment] 2022-04-10 21:36
I can run Rome 2 dx11 mode without messing with anything extra so thats nice.

I am very suspect with how Rome 2 handles Vram while loading into a battle or the other way. Dunno if it shortly spikes or what since i can never actually obersve my whole system Vram reach it's limit.
I have a save game on the campaign where when i end my turn i will get attacked in a sea battle. I could pretty consistently reproduce a crash while loading into this battle (tho did manage a very few times). I then found that the game sets my graphics level to Ultra by default and when i lower it to low i can enter the battle. (It resets my graphics after the crash)
I then kept crashing when setting water detail to very high. But then at some point after having turned Unlimited video memory on and off i could not reproduce this anymore. I can even set the graphics once i am in the battle map to extreme and i am fine. Not sure why that happened.
But still when i load into this map i will crash if graphics are set to Very High or above, UNLESS i have set Unlimited video memory.
The strange thing is tho if i set Unlimited Vmem on and set graphics to extreme when i get into the battle my overall system Vram usage is still only 3GB out of 4.
And if i don't set Unlimited Vmem i can enter the battle when graphics are below Very high, and then i can still set them to extreme in the battle without issue.

This might be half off topic, but maybe Shogun 2 behaves in a similar way. Haven't played much in dx11 mode yet.

**Comment by Blisto91** [comment] 2022-04-11 09:13
I haven't experienced a dxqq crash yet in shogun 2, but VRAM is generally a lot lower than in Rome 2 if that was the issue above. But need to play some more.

For the dx9 crash would a apitrace in either WINED3D or windows be helpful along with the save game?

**Comment by patmann03** [comment] 2022-04-11 12:45
> I haven't experienced a dx11 crash yet in shogun 2, but VRAM is generally a lot lower than in Rome 2 if that was the issue above. But need to play some more.
> 
> For the dx9 crash would a apitrace in either WINED3D or windows be helpful along with the save game?

Seeing Rome 2 is a 32-bit game, would having unlimited vram or overriding it in the preferences file have any impact?  I have a 6900xt, game only shows 3gb.  Is this forced by DXVK as stated in the other issue? [#1318 ](https://github.com/doitsujin/dxvk/issues/1318)?  When I'd run the game in older version of DXVK I wouldn't get the 'ACCESS VIOLATION' it would just crash with seemingly no error code in the proton log.  This is the only game I have a windows install for at the moment.  I tried adding the DLLs for the API trace to the game folder but when I override them with winecfg WINED3D fails to launch the game in Steam.  Never had to do a trace before so perhaps it didn't work.  When I tried running the API trace with DXVK the game would load, but when it went to load a campaign it would grind to a halt with less than 1FPS and I could never really get into the campaign (no issues with the main loading screen or settings) So whatever I can do to help identify the issue I'm game so I can delete windows once and for all.

**Comment by patmann03** [comment] 2022-04-11 17:16
Ok thanks. This likely means it wouldn't have any positive impact on the
stability issues I have.

**Comment by Blisto91** [comment] 2022-04-11 17:30
@patmann03 I tried running going into the crashing battle in WINED3D with unlimited memory off and it crashed the same. I got into it when i set graphics to medium. So maybe that particular one isn't dxvk.

You should probably make a separate issue for Rome 2 so we don't pollute this one too much hehe. Even tho the engines are similar it's not necessarily the same issues. :)

**Comment by patmann03** [comment] 2022-04-11 18:42
> Edit: I tried to compile a dxvk version where the 32bit memory limit was raised to around 4GB and now i don't seems to crash in this battle anymore even if i set my graphics to Ultra or Extreme before loading.

Interesting, how can I do that?  I can do additional testing tonight once I figure out out to build dxvk for myself and install in my pfx (heh).  I'll also run a trace in windows and create a separate issue.  Thank you for helping was hoping these issues were related to the game engine.

**Comment by Blisto91** [comment] 2022-04-11 22:53
@patmann03 I have made a separate issue. Tho i am a bit confused what is going on with it.
On windows native i can load the battle fine on Extreme even with a 2GB card because it will lower the details, but on Linux dxvk it instead just crashes.

**Comment by Blisto91** [comment] 2023-03-13 09:11
@llde could i get you to retest this issue with latest master when you have time? 🙂 
https://github.com/doitsujin/dxvk/actions/runs/4397579062

**Comment by Blisto91** [comment] 2023-05-06 15:11
@llde Friendly ping :slightly_smiling_face:

**Comment by K0bin** [comment] 2023-12-31 01:21
I'll assume this was fixed by the state block memory change.

Feel free to reopen if the issue persists.

**Closed by K0bin** 2023-12-31 01:21 UTC
