### ISSUE TITLE
The DLLs should be smaller.

### ISSUE THREAD

**Issue by SirSAC** [doitsujin/dxvk#3431] opened 2023-05-18 20:03 UTC
Please change the "--buildtype release" with "--optimization s".
On the https://mesonbuild.com/Builtin-options.html#details-for-buildtype it says the "release" comes with "debug false" and "optimization 3" but on the https://mesonbuild.com/Commands.html#setup we can use "--optimization s" for maximum compiler optimizations because the "--debug" is false by default if is not defined, in other words, smaller DLLs which means when a game loads the files it will have a copy for each DLL into the memory (RAM) but for some users like me that cant have better PCs because some don't have a job or we have too much bills to pay, each MB of size counts.
Also, the performance is not affected in a negative way, my PC have 8 GB and my system with everything closed it eats 5 GB so 3 GB left for games, for me each MB counts.
Please just make the change it doesn't hurt anything.

I forgot to mention the changes could be made on "package-release.sh".

I really wait the DXVK 2.3 with this change too, i'm bored wasting my time with my fork.

**Comment by gabriele2000** [comment] 2023-05-18 20:09
The problem is that your system eats 5GB of RAM, plus if you use ZRAM you'll have three times the RAM, basically.
I'm curious how -2MB (spitting a random number here) will affect the amount of available RAM.

**Comment by mbriar** [comment] 2023-05-18 20:15
How much size does it actually save? It's clearly not going to even be 2MiB (which would be like an 80% reduction in size from the option alone). I struggle to imagine a scenario where this would ever help, even on PCs with low RAM. On the other hand, optimizing for size can reduce performance of the resulting binary because the compiler won't unroll loops as aggressively, amongst other stuff. Although neither is like to make any difference in practice for DXVK.

**Comment by gabriele2000** [comment] 2023-05-18 20:16
> Maybe is my problem because I'm poor and can't have a decent PC, but it will be very kind with care about my situation (being poor) by the developers to just making this innocent change

I too am poor and recently landed a job, like a few days ago, but that doesn't matter, since I asked how a few MB less are going to change the situation.
Plus, you're poor? Install Linux and run games there if you're concerned about RAM usage, 5/8GB ARE TOO MUCH and since you're using Windows, it's not something that DXVK should change, since you don't even need DXVK.

DXVK is for Linux only, the fact that is windows-compatible is a coincidence at best.

**Comment by Blisto91** [comment] 2023-05-18 20:17
> How much size does it actually save

About half a Megabyte per dll ish

**Comment by SirSAC** [comment] 2023-05-18 20:20
1. Linux for me is not usefull at this moment because easy anti cheat and g hub software
2. for d3d9 from 3.6 MB to 1 MB
3. for d3d11 from 4.1 MB to 1 MB 
4. for dxgi from 2.7 MB to 1 MB

**Comment by SirSAC** [comment] 2023-05-18 20:21
> > How much size does it actually save
> 
> About 500-700 Kilobyte per dll ish (checked for fun).

see is not a bad thing, DLLs in general should be smaller than EXE files

**Comment by gabriele2000** [comment] 2023-05-18 20:23
> 1. Linux for me is not usefull at this moment because easy anti cheat and g hub software

I completely understand that, however, Easy anti-cheat and BattlEye are supported if you install the runtimes from Steam.

>     2. for d3d9 from 3.6 MB to 1 MB
> 
>     3. for d3d11 from 4.1 MB to 1 MB
> 
>     4. for dxgi from 2.7 MB to 1 MB

That's 7.4MB less, it's so irrelevant that I can't fathom why you can't realize that opening a single notepad istance will consume more RAM.

**Comment by gabriele2000** [comment] 2023-05-18 20:24
> > > How much size does it actually save
> > 
> > 
> > About 500-700 Kilobyte per dll ish (checked for fun).
> 
> see is not a bad thing, DLLs in general should be smaller than EXE files

What games are we talking about?
Your "everyday game" has an .exe that is about 15MB and more.
A game using Unreal Engine 4 as game engine has the main .dll with a size of minimum 40MB.

**Comment by SirSAC** [comment] 2023-05-18 20:26
> > > > How much size does it actually save
> > > 
> > > 
> > > About 500-700 Kilobyte per dll ish (checked for fun).
> > 
> > 
> > see is not a bad thing, DLLs in general should be smaller than EXE files
> 
> What games are we talking about? Your "everyday game" has an .exe that is about 15MB and more. A game using Unreal Engine 4 as game engine has the main .dll with a size of minimum 40MB.

Crossout, Star Conflict, League of Legends, Paladins, Robocraft, TerraTech, War Thunder, NARUTO TO BORUTO SHINOBI STRIKER, etc.

**Comment by gabriele2000** [comment] 2023-05-18 20:26
> i need dxvk for 30-40 fps boost in all my games tested and i play

That alone tells me that they're DX9 games.

Again though: how -7.4MB are going to change your situation?

**Comment by SirSAC** [comment] 2023-05-18 20:27
for my pc 7 MB is alot
i stopped and disabled all the services on windows that is not necessary for gaming and browsing

**Comment by SirSAC** [comment] 2023-05-18 20:29
half dx11 half dx9

**Comment by SirSAC** [comment] 2023-05-18 20:33
> > 1. Linux for me is not usefull at this moment because easy anti cheat and g hub software
> 
> I completely understand that, however, Easy anti-cheat and BattlEye are supported if you install the runtimes from Steam.
> 
> > ```
> > 2. for d3d9 from 3.6 MB to 1 MB
> > 
> > 3. for d3d11 from 4.1 MB to 1 MB
> > 
> > 4. for dxgi from 2.7 MB to 1 MB
> > ```
> 
> That's 7.4MB less, it's irrelevant and I can't fathom why you can't realize that opening a single notepad istance will consume more RAM.

because in general the devs (any company devs) don't even try to optimise the files to make more compact which dont affect performance if is done by the compiler

**Comment by SirSAC** [comment] 2023-05-18 20:35
> > it triggers the pagefile usage and froze my HDD by 100% usage
> 
> You're using an HDD, that why it freezes everything: the pagefile is surely saturating your HDD load.
> 
> > actualy only Star Conflict is DX9
> 
> If you're telling me that you have 30FPS increase with DX11 games there's something seriously wrong here: DXVK on DX11 runs almost at windows speed and sometimes more, but a 30FPS increase is only manageable with DX9 games (DX9 is a mess and DXVK has a wonderful implementation, DX9 -> VULKAN is a blessing in this case).

the games i listed is using max 80% of my gpu and the cpu is max 60% but with DXVK is 100% gpu and 80% cpu

**Comment by SirSAC** [comment] 2023-05-18 20:38
> > How much size does it actually save
> 
> About 500-700 Kilobyte per dll ish (checked for fun on Linux)
> 
> Edit: But as mbriar said, the problem with optimizing for size like here is that there usually is a tradeoff in some perf scenarios. If there wasn't it would just be a default in a release build, tho i also don't know how it would be in practice for dxvk.

u can check with and without the change to see if is a bad impact of perf

**Comment by gabriele2000** [comment] 2023-05-18 20:39
> the games i listed is using max 80% of my gpu and the cpu is max 60% but with DXVK is 100% gpu and 80% cpu don't ask me how or why, bcs idk, i tried with fresh install of windows and same result

I was talking about FPS, not usage.

Plus DXVK uses more VRAM (Video RAM) and it's normal.
Don't confuse GPU and CPU load with "more performance" since it's not related.

**Comment by SirSAC** [comment] 2023-05-18 20:42
> > the games i listed is using max 80% of my gpu and the cpu is max 60% but with DXVK is 100% gpu and 80% cpu don't ask me how or why, bcs idk, i tried with fresh install of windows and same result
> 
> I was talking about FPS, not usage.
> 
> Plus DXVK uses more VRAM (Video RAM) and it's normal. Don't confuse GPU and CPU load with "more performance" since it's not related.

i said thes above to say how effiecent is and how good is in handling the comunication between cpu and gpu.
and yes the VRAM is quite bigger but still enough room for more, with DXVK it eats 1.5-1.6 GB VRAM, without eats 1 GB

**Comment by SirSAC** [comment] 2023-05-18 20:51
I have a fork of this repo, i did any kind of modifications about compiler options and some values about versions things and commands that updates the submodules and packages in linux but only good thing i found is this "--optimization s" that i saw no performance degradation and also sometimes didn't trigger my system to do some pagefile.sys.

Also i have RAM compresion thing in windows enabled but is not enough and im on win 11 bcs on win 10 i had 10-20 fps less, even with fresh install.

**Closed** 2023-05-18 21:02 UTC

**Comment by SirSAC** [comment] 2023-05-18 21:14
> We're obviously not gonna optimize for size (over performance) to save 10MB.
> 
> @SirSAC Please reduce the number of poorly considered suggestions. I get it, you mean well, but so far it's mostly been bullshit to put it bluntly.

@K0bin i was having too much patience with u while u answer every time and offend me somehow with ur respones, at lest i always feel that, im done using this project bcs i dont like to use programs from some kind of jerk dev.

**Comment by Redundanz** [comment] 2023-05-19 02:30
> ... im done using this project ...

thank god
