### ISSUE TITLE
Star Wars Battlefront (2015) (Detected AMD Radeon driver version UNKNOWN)

### ISSUE THREAD

**Issue by BuzzBumbleBee** [doitsujin/dxvk#1177] opened 2019-08-28 14:06 UTC
When attempting to launch this game I get an error prompt informaing that the radeon driver version was detected as "UNKNOWN" the game then refuses to start.

Full error text "Detected AMD Radeon driver version UNKNOWN"

![Error](https://user-images.githubusercontent.com/484334/63862897-3fe0e180-c9a5-11e9-81f6-5995edba3fb4.png)

I have attached all populated log files (most are empty at this point), I have attached an image for the error pop up.

I have tried having nvapi DLL's enabled & disabled with no luck, I have also tried with

`dxgi.nvapiHack = False` and `dxgi.nvapiHack = True`

Command I am using to launch origin (and the game after) is

`DXVK_LOG_LEVEL=debug DXVK_LOG_PATH=/home/user/dxvk_logs WINEESYNC=1 WINEDEBUG=ALL DXVK_CONFIG_FILE=/home/user/dxvk.conf WINEPREFIX=/home/user/Games/origin wine ~/Games/origin/drive_c/Program\ Files\ \(x86\)/Origin/Origin.exe`

### Software information
Star Wars Battlefront (2015) launched from origin

Wine Tricks Enabled : 
- nocrashdialog
- win7
- xact
- vcrun2017

### System information
- GPU: AMD VEGA 64
- Driver: Mesa 19.1.5 (LLVM 8.0.1) / Vulkan: 1.1.90
- Wine version: wine-4.14 (Staging)
- DXVK version: v1.3.2-2
- OS : Arch Linux
- Kernel : 5.2.10

### Log files
- d3d11.log: Empty
- dxgi.log: Attached

[starwarsbattlefront_dxgi.log](https://github.com/doitsujin/dxvk/files/3551262/starwarsbattlefront_dxgi.log)

**Comment by doitsujin** [comment] 2019-08-28 14:44
This is not a DXVK bug. The game might use some version of amdags in order to check the driver version, so your best bet might be to just spoof an Nvidia GPU (`dxgi.customVendorId = 10de`).

**Comment by ptkato** [comment] 2019-08-30 05:12
The same happens with Battlefront 2, I tried spoofing a Nvidia GPU, but it didn't work.

**Comment by lle211967** [comment] 2019-09-01 21:22
Hi,
make sure you store the dxvk.cfg inside your current wine prefix.

For example ~/.wine/drive_c/dxvk.cfg
(~) points to your home path.

make sure your Environment Parameter point to the correct wine prefix.
For example: DXVK_CONFIG_FILE=/home/userx/.wine/drive_c/dxvk.conf

Hope this will fix your probs.

**Comment by ptkato** [comment] 2019-09-01 22:23
Okay, after I added a device id, the game started.

    dxgi.customDeviceId = 1C81
    dxgi.customVendorId = 10DE

However it’s not in any state playable, I can get in a match just fine, but when it gets there it’s mayhem. It freezes for whole minutes, to unfreeze for 2 seconds and either freeze again or disconnect me to the menus.

I’m not sure if that happens due to shader caching, but I’ll keep trying to see if gets any better with time.

**Comment by ptkato** [comment] 2019-09-02 01:52
Just to be clear, I'm talking about Battlefront 2.

The game seems to play fine, but whenever I take heavy damage or die, it freezes for more than 10 minutes straight, and while at that the game window flickers with some crazy artefacts:

![image](https://user-images.githubusercontent.com/10677806/64085776-07296b00-cd0b-11e9-9829-df78602f8df4.png)

After that, the game unfreezes and become playable again.

**Comment by Joshua-Ashton** [comment] 2019-09-02 03:53
There is always the possibility of it using D3D9 to check that... The functionality is exposed there -- but not in D3D11/DXGI.

I have seen games call through to D3D9 just to check some extra adapter info...

> the game window flickers with some crazy artefacts

Looks like its outputting some gbuffer

**Comment by doitsujin** [comment] 2019-09-02 12:08
Frostbite Engine is known not to work very well when spoofing a different GPU vendor.

You could always try Intel instead of Nvidia and see if that fixes the issue, but if that doesn't run either then you're screwed. Debugging the game seems pretty much impossible.

**Comment by ptkato** [comment] 2019-09-02 18:03
Spoofing Intel didn't really work, the hang is still there. What is interesting is that it shows an outdated driver message, but unlike with AMD, I'm allowed to continue with this "outdated" version.

![image](https://user-images.githubusercontent.com/10677806/64127954-4a76ee80-cd8a-11e9-9c7b-bea91ee9cd27.png)

**Comment by doitsujin** [comment] 2019-09-02 18:06
Nah, great.

Well, can't do very much about it. If there's a **fast** way to reproduce the hang, please record an apitrace, if not - well, as mentioned, you're screwed.

**Comment by lle211967** [comment] 2019-09-02 18:26
Hi,
i play many frostbite engine based games. Battelfield 3,4,1,and Battlefront 2 without any problems. But i used a nvidia gpu. The only thing what was different after initial Start on all mentioned games was, for starting Battlefront 2 successfully i had to set dxgi to the wine version.

It was funny, after the first start i switched back to the version which came with dxvk and... Battlefront 2 start successfully?

Maybe this can point in the right direction? Hope you can soon enjoy Battlefront 2 with the outstanding dxvk.

btw: Thanks to the team of dxvk and special thanks to doitsujin. You and your work are amazing. Sorry, out of scope, i know but i have to write it. Thank you.

**Comment by ptkato** [comment] 2019-09-03 00:05
> If there's a **fast** way to reproduce the hang, please record an apitrace

Why fast? Wouldn't it work with the 10 minutes hang?

Notice that the only thing that hangs is the display, the game audio keep playing (mostly) and other audio sources keep playing just fine. I can also switch to a tty without any problems.

**Comment by doitsujin** [comment] 2019-09-03 00:54
> Why fast? Wouldn't it work with the 10 minutes hang?

Well, yes, if you're going to play the game at ~1 FPS for 10 minutes and have enough patience to upload a 50GB trace file ;)

**Comment by ptkato** [comment] 2019-09-03 01:03
I see. Could that be related to hardware power? I tested it on a RX 550, maybe I don't have enough vram?

**Comment by ptkato** [comment] 2019-09-29 23:21
I tried again with Wine Staging 4.16 and DXVK 1.4.1 and the 10 minutes hangs are gone.

**Comment by BuzzBumbleBee** [comment] 2019-09-30 16:08
Main issue above AMD driver detection is fixed now with 

`dxgi.customDeviceId = 1C81
dxgi.customVendorId = 10DE`

**Closed** 2019-09-30 16:07 UTC

**Comment by PAPPL** [comment] 2020-12-31 21:31
Feedback.
It really works! Thanks for the fix.

On first startup when using AMD GPU:
**Error: Detected AMD Radeon driver version UNKNOWN**

**SIMPLE FIX:** 
Create a _**dxvk.conf**_ file in _/home/USERNAME/.steam/steam/steamapps/common/STAR WARS Battlefront/_ and write  this into the file:
```
dxgi.customDeviceId = 1C81
dxgi.customVendorId = 10DE

```
Save and hit play. Works like in Windows.
No other startup options required.
I'm happy.

**Comment by Ahmed-E-86** [comment] 2021-08-14 18:30
This workaround does not work with `Star Wars Battlefront II Celebration Edition`, I get this error:

![Screenshot from 2021-08-14 20-07-39](https://user-images.githubusercontent.com/29783425/129456920-5eaf5ebc-a0c9-4742-bb6a-1a76e4e1d58c.png)

**Comment by Ahmed-E-86** [comment] 2021-08-14 18:41
These options work for me:

```
dxgi.customDeviceId = 10de
dxgi.customVendorId = 1c06
```
