### ISSUE TITLE
STAR WARS Jedi: Fallen Order - Broken Textures

### ISSUE THREAD

**Issue by LiamDawe** [doitsujin/dxvk#3350] opened 2023-04-13 17:43 UTC
On [Star Wars Jedi Fallen Order](https://store.steampowered.com/app/1172380/STAR_WARS_Jedi_Fallen_Order/) on Steam Deck, tested across both Stable and Preview (and on two different Steam Decks) with Proton Experimental, there seems to be a whole lot of broken textures. They look like big blocky pixel-art in 3D, it's weird.

I'm unclear as to this being an issue with DXVK / Proton or Mesa, so posting here first to get some eyes on it to help figure it out. Really easy to see on the wookie planet Kashyyyk.

Using the current Proton Experimental, since that's set by Valve and as far as I know it's the only current version with the fixes needed for the EA App.

Can try and get an apitrace if really needed, but can't find instructions on doing it for Steam Deck.

Proton Log File: 
https://uploads.golmedia.net/uploads/randoms/steam-1172380.tar.gz (too big for GitHub...)

Screenshots: 
![Ftmxno6WAAE66pH](https://user-images.githubusercontent.com/83223/231838655-c3e68da5-57f9-4915-8c26-ab714bb60aac.jpeg)
![download](https://user-images.githubusercontent.com/83223/231840607-2adfcac2-97a9-4cc0-9c3c-bd88c3fafc42.jpeg)

Save Files: 
[JediFallenOrder.tar.gz](https://github.com/doitsujin/dxvk/files/11224866/JediFallenOrder.tar.gz)
(save location: compatdata/1172380/pfx/drive_c/users/steamuser/Saved Games/Respawn/JediFallenOrder/)

I should note actually as well, it's not the only graphical problem. Anywhere that has fog seems to have it flicker in and out as you move or even standing still moving the camera. A few people on Twitter and Mastodon mentioned they saw it too, and people seem to think it's something to do with transparent textures?

**Comment by doitsujin** [comment] 2023-04-13 18:18
Does this happen with `RADV_DEBUG=llvm`? Not sure if mesa on deck actually supports that but given the macropixel patterns this very much looks like some shader nonsense in the driver.

**Comment by Revan-12** [comment] 2023-04-17 15:26
I am experiencing the same issue. Did you find a solution?

**Comment by Blisto91** [comment] 2023-04-17 16:51
Not yet. I need to do some more testing to find out what is to blame

**Comment by Revan-12** [comment] 2023-04-17 20:52
Thanks for the update! Doesn't seem to get better by adjusting the settings on the deck or in game.

**Comment by Blisto91** [comment] 2023-04-20 18:39
Appears to be a mesa bug as it doesn't happen with the amd pro drivers.

Upstream issue https://gitlab.freedesktop.org/mesa/mesa/-/issues/8883

**Comment by Blisto91** [comment] 2023-04-24 15:46
Ugh. Missed that part. Is that issue also present in the save game above?

**Comment by LiamDawe** [comment] 2023-04-24 17:20
It's a good little after the save I attached, I will have to check if my current save allows you to go back to reproduce.

**Comment by Blisto91** [comment] 2023-05-12 12:57
Finally got to test the fog issue. I have found this to be a game bug as i can also easily reproduce it in the same location on native Windows without dxvk.
It is far worse and noticeable on medium settings than on High and Ultra (but does also happen slightly there) which is why Steam Deck users might run into it more in general than regular PC setups.

**Comment by K0bin** [comment] 2023-05-14 23:21
I'm gonna close this then.

**Closed by K0bin** 2023-05-14 23:21 UTC
Labels: d3d11, amd radv
