### ISSUE TITLE
Some textures flickering in "The Saboteur" game (d3d9)

### ISSUE THREAD

**Issue by rox4d** [doitsujin/dxvk#1560] opened 2020-04-07 09:43 UTC
There are some textures flickering in definite locations (in general game are playable).

### Software information
Saboteur.exe (from GOG)

### System information
- GPU: ACO POLARIS11 (LLVM 10.0.0)
- Driver: AMD RADV (mesa build from git)
- Wine version:  wine-5.5 (Staging)
![Снимок экрана в 2020-04-07 12-30-28](https://user-images.githubusercontent.com/34712490/78653519-ea21cf80-78cb-11ea-9281-510966455fe1.png)

- DXVK version: v1.6-28-g3f4ffdf

### Apitrace file(s)
- Put a link here
https://drive.google.com/file/d/1EUDneqhTe60--Sojf_RmH5UR-DQS4bkj/view?usp=sharing
### Log files
- d3d9.log: 
[Saboteur_d3d9.log](https://github.com/doitsujin/dxvk/files/4443201/Saboteur_d3d9.log)

- d3d11.log:
- dxgi.log:

**Comment by WinterSnowfall** [comment] 2020-06-02 18:35
It looks good to me on DXVK v1.7, so you may want to recheck.

![The_Saboteur](https://user-images.githubusercontent.com/6306593/83556505-b4d6de00-a518-11ea-8203-99e5841bd4d0.jpg)

It could also be an issue with RADV.

**Comment by rox4d** [comment] 2020-06-03 04:50
Looks so, just retested with dxvk v1.7-40-g5558460 - no changes here.

**Comment by rox4d** [comment] 2020-06-03 06:24
WinterSnowfall - trace replaying fine for you? (it may be different with game, i suppose).

**Comment by WinterSnowfall** [comment] 2020-06-03 06:47
> WinterSnowfall - trace replaying fine for you? (it may be different with game, i suppose).

Yes, your trace also looks good on my GTX 1080. I see no flickering.

**Comment by CME42** [comment] 2020-06-03 10:13
It's a precision error that only happens on AMD, both radv and amdvlk, `d3d9.invariantPosition = True` doesn't help.

**Comment by Blisto91** [comment] 2022-03-31 19:56
Just a quick update that this is still present on mesa git. Looking into making a mesa issue.

**Comment by Blisto91** [comment] 2022-04-02 00:33
Comment from the mesa issue

"This isn't a RADV issue as far as I can tell. It's caused by DXVK's D24 emulation using D32. AMD doesn't support D24, nvidia does. If I force DXVK to always use D32 I can reproduce the issue on nvidia."

**Comment by K0bin** [comment] 2022-06-11 23:20
This is probably caused by the depth bias.

First it draws this with a depth bias:
![image](https://user-images.githubusercontent.com/1131720/173207936-7a5740f9-cfa3-4e5d-8fab-01d5379634c0.png)

This this mesh without one:
![image](https://user-images.githubusercontent.com/1131720/173207939-53104769-614d-4df9-9002-f8ad7cce56d2.png)

**Comment by K0bin** [comment] 2023-06-20 12:36
Fixed by #3501

**Closed by K0bin** 2023-06-20 12:36 UTC
Labels: d3d9

**Comment by ivan89el** [comment] 2025-06-18 04:34
The problem persists on Windows 11 AMD Adrenalin 25.6.1

**Comment by Blisto91** [comment] 2025-06-18 04:41
Amd doesn't implemt `VK_EXT_depth_bias_control` which is needed to fix the issue.
