### ISSUE TITLE
Flickering texture artifacts and 3D objects in Arma2 OA and old bohemia games.

### ISSUE THREAD

**Issue by mmrsz** [doitsujin/dxvk#2475] opened 2022-02-01 17:11 UTC
when I play arma 2 oa, arma 2 on **directx 9** (and similar bohemia old games).
I have flickering textures and artifacts.
Sometimes the 3D objects themselves flicker (they disappear).
When loading a large number of polygons in the frame (for example: I go to a big city), there are friezes.
None of the dxvk.conf settings helped!

### ****Screenshot**:**

https://ibb.co/XCsHwmR
https://ibb.co/1vvdTj9
https://ibb.co/grM782Q

GPU: NVIDIA GeForce GTX 970
Driver GPU: 471.68.0 (05.08.2021)
OC: Windows 10 x64 LTSC (has also been tested on Win7, Win 10 home)
DXVK ver: i tried different versions, screenshots and info from last version 1.9.4

### **All Log Files**:

**d3d9.log**: ArmA2OA_d3d9.log https://pastebin.com/DXmgNQk1
**dxgi.log**: ArmA2OA_dxgi.log https://pastebin.com/KY5RusrH
**d3d11.log** empty...

**Comment by K0bin** [comment] 2022-02-01 21:26
Duplicate of #2124?

Please add an apitrace.

**Comment by mmrsz** [comment] 2022-02-01 22:07
https://drive.google.com/file/d/1AYhcjAjN7YS8f0fTp156gySTwXUhv8ZA/view?usp=sharing
file ArmA2OA.trace.zip.

No, I didn't duplicate the post.
But man has the same problem
And this is valid for 2022

**Comment by K0bin** [comment] 2022-02-01 22:13
I didn't mean you copied his exact issue. I meant that this is another issue for the same problem.

I'm closing this, as it's already tracked by the other issue.

**Closed by K0bin** 2022-02-01 22:13 UTC

**Comment by DeltaPony** [comment] 2022-02-01 22:20
@K0bin hello i am poster of original thread, should i copy apitrace from here to my ticked or should i close my ticket? this problem needs to be fixed and it would be great if it will be done sooner

**Comment by K0bin** [comment] 2022-02-01 22:22
Keep your ticket open, we'll use that when we (eventually) look into this. You can copy the apitrace link over if you like but the second issue is linked in the first one, so either way it's not hard to find.

**Comment by DeltaPony** [comment] 2022-02-01 22:23
> Keep your ticket open, we'll use that when we (eventually) look into this. You can copy the apitrace link over if you like but the second issue is linked in the first one, so either way it's not hard to find.

Okay, thank you, hope you will get this issue fixed

**Comment by mmrsz** [comment] 2022-02-01 22:27
yes, that would be great.
Let's talk in that topic.
what logs are needed and so on, I will try to show everything.
Hope this is solvable!
