### ISSUE TITLE
Skyrim SE rendering Issues

### ISSUE THREAD

**Issue by Glog78** [doitsujin/dxvk#189] opened 2018-03-20 23:37 UTC
Armors and environment flickering grey. See attached picture.
![skyrim_bug](https://user-images.githubusercontent.com/7598856/37687233-06663336-2c9b-11e8-90bf-84ab6b25c128.png)
Since i saw a youtube video with an amd card running it with no issues it might be an nvidia only issue or a regression

### System information
- GPU: GTX970
- Driver: 390.42
- Wine version: wine-staging-git
- DXVK version: 6550e8d623cafd9390c897cdc91adfbef13d31f5

### Apitrace file(s)
Sadly i wasn't able to get apitrace files because of the way the processes seem to stop apitrace before the game really loads up (SkyrimLauncher + bug while installing libraries)

### Log files with DXVK_LOG_LEVEL=debug
[SkyrimSE_d3d11.log](https://github.com/doitsujin/dxvk/files/1831588/SkyrimSE_d3d11.log)
[SkyrimSE_dxgi.log](https://github.com/doitsujin/dxvk/files/1831590/SkyrimSE_dxgi.log)

Additional Note when running the Game with DXVK_LOG_LEVEL=trace and DXVK_DEBUG_LAYERS=1 it basically hangs at the menu screen when usually the smoke starts to come in. Music is still playing but even after several minutes no change.
### Log files with DXVK_LOG_LEVEL=trace and DXVK_DEBUG_LAYERS=1
[SkyrimSE_d3d11.log](https://github.com/doitsujin/dxvk/files/1831594/SkyrimSE_d3d11.log)
[SkyrimSE_dxgi.log](https://github.com/doitsujin/dxvk/files/1831595/SkyrimSE_dxgi.log)

**Comment by Dealer** [comment] 2018-03-21 09:45
I can confirm this bug. I asked on Discord a few days ago if someone else has this bug (or plays Skyrim:SE with nvidia at all) but no one answered.
I also had an apitrace but it was useless for some reason (playing back the apitrace with DXVK had no artifacts). But if a apitrace is needed i can provide one.

**Comment by MEXAHOTABOP** [comment] 2018-03-21 19:42
@pingubot https://discordapp.com/invite/EMc4Kak

**Comment by Glog78** [comment] 2018-04-01 16:09
As of a2f05467c7d3789a42471170242f76d75e7cd02f still flickering.

**Comment by doitsujin** [comment] 2018-04-08 10:29
I can't reproduce this on radv, this seems to be Nvidia-specific.

**Comment by doitsujin** [comment] 2018-04-10 12:53
Update: It *does* happen on RADV as well, although only sporadically on a very small number of objects, so it's not going to be easy to debug. I'll see what I can do.

**Comment by Glog78** [comment] 2018-04-15 20:27
@doitsujin ok it seems to work the same as ati on new nvidia shader compiler but performance wise it's not playable on new shader compiler (3.5 fps vs 60 fps on same settings).

**Comment by doitsujin** [comment] 2018-04-15 20:29
Performance is something they need to fix, it's clearly a regression. You might want to report that to #267 .

**Comment by doitsujin** [comment] 2018-04-20 21:38
Please test commit 50f1cf007d4b91ebd70cb9d7e7825b1a44d5c67d. That seems to have fixed it for me on RADV.

**Comment by Glog78** [comment] 2018-04-20 21:57
50f1cf007d4b91ebd70cb9d7e7825b1a44d5c67d fixed it for me too :grin:

**Comment by varris1** [comment] 2018-04-20 22:04
Same here on NVIDIA.

**Comment by doitsujin** [comment] 2018-04-20 22:09
Great, in that case I'll close the issue.

**Closed by doitsujin** 2018-04-20 22:09 UTC
Labels: bug
