### ISSUE TITLE
World of Warcraft: Battle for Azeroth Black Screen

### ISSUE THREAD

**Issue by Mushoz** [doitsujin/dxvk#562] opened 2018-08-15 08:54 UTC
I used to play World of Warcraft on the prepatch just fine through DXVK. However, since the launch of Battle for Azeroth I am facing a black screen. When I open WoW via Battle.net I am greeted with the login screen as expected, and immediately shows the "connecting" message as it automatically logs in. So far so good. When the character selection screen is supposed to open afterwards, instead of seeing anything, the screen is entirely black.

The World of Warcraft mouse is visible (The little hand), the GPU is rendering something (I can hear the fan spin up, so there seems to be GPU load) and I can actually login just fine, by clicking the spot where the "enter world" button is supposed to be and listening to the sound for feedback I clicked the actual button. I am then able to walk around (I can hear footsteps from my character, and can cast spells), however the black screen remains.

This issue does not happen when I play through Wine's DLLs, albeit with heavy graphical artifacting, see: https://bugs.winehq.org/show_bug.cgi?id=45478

Interestingly, I asked around and most people are able to play just fine with many different drivers/vendors/kernels/DXVK versions/wine versions combinations. But one guy (raist356) apparently has the same issue on his nVidia box: https://www.reddit.com/r/wine_gaming/comments/97825d/dxvk_world_of_warcraft_battle_for_azeroth/

I have tried a completely fresh wine prefix with fresh World of Warcraft installation, and the issue remains.

### Software information
World of Warcraft: Battle for Azeroth
Graphics settings set to the preset of "7".

### System information
- GPU: Vega 64
- Driver: Mesa 18.1.5 + 6.0.1 LLVM
- Wine version: 3.13.1 staging
- DXVK version: 0.65
- Kernel: 4.17.14

### Log files
- d3d11.log:

```
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
```

- dxgi.log: 

```
info:  Game: Wow.exe
info:  DXVK: v0.65
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA10 (LLVM 6.0.1):
info:    Driver: 18.1.5
info:    Vulkan: 1.1.70
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 8176 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
warn:  DXGI: CheckInterfaceSupport: No D3D10 support
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DXGI: CheckInterfaceSupport: No D3D10 support
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  Game: Wow.exe
info:  DXVK: v0.65
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA10 (LLVM 6.0.1):
info:    Driver: 18.1.5
info:    Vulkan: 1.1.70
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 8176 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
warn:  DXGI: CheckInterfaceSupport: No D3D10 support
info:  Game: Wow.exe
info:  DXVK: v0.65
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA10 (LLVM 6.0.1):
info:    Driver: 18.1.5
info:    Vulkan: 1.1.70
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 8176 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
warn:  DXGI: CheckInterfaceSupport: No D3D10 support
info:  Game: Wow.exe
info:  DXVK: v0.65
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA10 (LLVM 6.0.1):
info:    Driver: 18.1.5
info:    Vulkan: 1.1.70
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 8176 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
warn:  DXGI: CheckInterfaceSupport: No D3D10 support
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  2048x1152
info:  Game: Wow.exe
info:  DXVK: v0.65
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA10 (LLVM 6.0.1):
info:    Driver: 18.1.5
info:    Vulkan: 1.1.70
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 8176 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
```

**Comment by Mushoz** [comment] 2018-08-15 09:35
This is really bizarre. I can repeatedly click the "play" button in battle.net to open multiple instances of the wow.exe process. Without fail, the first 4 will always show a black screen, while the 5th will render correctly. I can then login and play.

However, killing any of the other 4 wow.exe screens that show nothing but black, will instantly turn the working wow.exe black as well. Opening up yet another 5th wow.exe process will then render correctly, but the wow.exe process that's in-game will remain black.

I'm really stumped now.

**Comment by Thaodan** [comment] 2018-08-15 16:28
Which wine version do you used ?
I have the issue too on a 3.13 ish staging build and a dxvk build some day's a from git.

Starting wow outside of the launcher works fine.

Am 15. August 2018 14:21:34 MESZ schrieb Jaap Buurman <notifications@github.com>:

**Comment by Mushoz** [comment] 2018-08-15 17:02
Reopening the issue, since it doesn't seem to be an isolated issue with my setup. As for your question, I am using Wine-staging 3.13.1.

**Comment by Mushoz** [comment] 2018-08-15 17:27
I guess you're right. Although it is weird that without dxvk it was working fine. Also, a new wineprefix did not fix it for me. I had to reinstall the wine package as well for some reason. I'm leaving the decision whether to open/close this issue up to you.

**Comment by Thaodan** [comment] 2018-08-15 20:41
@doitsujin  thats the thing. I have a clean prefix and the occurs.
my system:
Name                     : mingw-w64-dxvk-git
Version                  : 20180812.294bdf5-2
Name                     : mingw-w64-gcc
Version                  : 8.2.0-1

**Comment by doitsujin** [comment] 2018-08-15 20:49
@Thaodan which version of wine are you using and with what patches?

I don't have the game so I can't reproduce the issue, none of the logs so far have been helpful, and it seems to work for most people, so there must be **something** specific to your setup that makes it not work.

**Comment by Thaodan** [comment] 2018-08-15 20:55
that one: https://github.com/Thaodan/thaopkgs/blob/master/wine-staging-git/PKGBUILD
Its wine-staging + pba patches.

log:
https://paste.kde.org/phqcreown

wow start script:
https://paste.kde.org/psp8gqosd

**Comment by doitsujin** [comment] 2018-08-15 20:58
By the way, does the DXVK HUD show up?

**Comment by IngeniousDox** [comment] 2018-08-15 21:50
Can you try turning PBA off with PBA_DISABLE=1?

I know it shouldn't affect eachother, but I have seen wierd interactions before.

**Comment by Kerrung** [comment] 2018-08-16 04:41
>I don't have the game so I can't reproduce the issue
@doitsujin World of Warcraft is a free-to-play game (but with subscription as option), so you can try it for free.

**Comment by daniel-medina** [comment] 2018-08-16 10:51
I have the same issue. However as mentionned by @Thaodan , launching the game outside the launcher ( Wow.exe ) makes it run perfectly. It's a nice workaround while the issue still exists.

**Comment by doitsujin** [comment] 2018-08-16 11:00
Can someone please answer my question as to whether the DXVK HUD shows up in the game?

@Kerrung I tried, but I simply cannot get the setup to work even when using the Lutris installer.

**Comment by Kerrung** [comment] 2018-08-16 12:02
@doitsujin I just reinstalled the Battle.Net client from scratch. It's installed for me and WoW works fine with DXVK without any black screens, etc.
Thank you.

[You should download this.](https://www.battle.net/download/getInstallerForGame?os=win&locale=ruRU&version=LIVE&gameProgram=BATTLENET_APP)
Unfortunately, now because of yesterday's release of a new game content patch, the game servers are heavily overloaded so the installation can last a very long time.

**Comment by doitsujin** [comment] 2018-08-16 13:05
> You should download this.

Well, that's **exactly** the app that just doesn't work on my end, but this is not the right place to discuss my issue.

**Comment by kudlatyamroth** [comment] 2018-08-16 14:36
I have same issue.
When launch from battle.net app there is completly black screen, only cursor shows.
exported DXVK_HUD=1, and nothing changed when launching from battle.net, hud does not show

but when launching from  Wow.exe with DXVK_HUD=1 everything works fine, and hud shows 

i don't know how to disable dxvk for launcher so i can't tell you if this would work

**Comment by doitsujin** [comment] 2018-08-16 14:45
@kudlatyamroth Thanks. Can you test if creating a [dxvk.conf](https://github.com/doitsujin/dxvk/wiki/Configuration#example-configuration) next to the game exe with the following contents works:
```
dxgi.deferSurfaceCreation = True
```

**Comment by varris1** [comment] 2018-08-16 15:03
Can you try to disable streaming in the battle net app, then start WoW as usual?

**Comment by kudlatyamroth** [comment] 2018-08-16 15:06
dxgi.deferSurfaceCreation = True
nothing changed

and disabling streaming works fine :)

**Comment by Mushoz** [comment] 2018-08-17 10:09
For the people using Wine(-staging) 3.13 or older, could you try using Wine-staging 3.13.1? Apparently it contains a few Battle.net related fixes.

**Comment by FireBurn** [comment] 2018-08-17 13:35
I have this issue with Wine-staging 3.13.1 without pba, launching WoW.exe on its own works fine. I've not tested it with 0.70 yet

**Comment by SveSop** [comment] 2018-08-17 13:44
I am using staging-3.13.1, and have (after BfA) issues with the Battle.net client. 

Whenever there are patches, or other changes/updates, it usually just hangs with "checking for update" or other errors, amongst sometimes just a blank screen with no "PLAY" button or any menus.

Clearing out `c:\users\Public\Application Data\Battle.net` folder downloads a new "Agent.exe", and it usually works after that.

I also run wow.exe directly with only a 64-bit wine client, and this seems to block Agent.exe (as it is a 32-bit app i guess), and wow plays very well. Have had issues with launching wow from the PLAY button in the past, so i rather just do it with a script to avoid that battle.net client other than for patching :)

PS. nVidia GTX 970 w/396.24.10 driver.

**Comment by kudlatyamroth** [comment] 2018-08-17 14:27
If you have black screen after clicking play button in launcher, go to launcher options and [disable streaming](https://image.ibb.co/cnTMiK/battlenet.jpg)

for me, after disabling streaming i can click play and everything works, no more black screen :)

**Comment by 7oxicshadow** [comment] 2018-08-17 22:57
I am unsure if this is related but I just tried to get crysis working with DX10 support on steam. When I first tried I had just a black screen and a mouse cursor but I could hear all of the game sounds in the same way as the OP.

I turns out that even though I had run the old script to remove the overrides before running the winetricks command I ended up with duplicate overrides specified for the DLL's.

I removed all of the duplicates so I just had the following:

*d3d10 (native)
*d3d10_1 (native)
*d3d10core (native)
*d3d11 (native)
*d3dcompiler_43 (native, builtin)
*dxgi (native)

After fixing that the game worked as expected and all graphics rendered properly

**Comment by FireBurn** [comment] 2018-08-17 23:09
Disabling steaming worked for me

**Comment by Palats** [comment] 2018-08-18 19:28
I have same symptom - when I launch Wow from Battle.net launcher, it gets a black screen [though it seems to be running fine, just nothing visible] - sometimes a few images are visible before blacking out, sometimes not. If I run Wow.exe directly, it usually works.

However, if I change the Battle.net setting "When I launch a game" to "Exit Battle.net completely" instead of "Keep the Battle.net window open", then it works fine - I can launch it from the launcher, and the display works. This is consistently reproducible.

I.e., it looks like the Battle.net runtime is vaguely interfering.

I've attached copies of d3d11.log and dxgi.log for both cases ("bad" being when I obtain a black screen, "good" when the display works). I don't know anything about dxvk logging, the only fishy thing I can see is that in the bad case, D3D11CoreCreateDevice happens twice, instance of once when it works:

> info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
> info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0

[wow-logs.tar.gz](https://github.com/doitsujin/dxvk/files/2299818/wow-logs.tar.gz)

**Comment by Maia-Everett** [comment] 2018-08-20 17:13
Had the same problem: WoW ran fine with DXVK if launched via Wow.exe, but not if launched via the Battle.net app. Disabling streaming in Battle.net app settings fixed the problem.

**Comment by Maltahl** [comment] 2018-08-30 17:17
Had same problem after a battle.net problem.

But this turned out to be related to Steaming options inside Battle.net app

@doitsujin Since you never got your answer about if the HUD appeared.
It does appear but the makes a blackscreen instantly, if you go windowed it will freeze the picture but the cursor will still animated.

**Comment by doitsujin** [comment] 2018-09-12 15:06
Closing, since this is apparently fixed by disabling the Streaming option in Battle.net. Not ideal, but ¯\_(ツ)_/¯

**Closed by doitsujin** 2018-09-12 15:06 UTC
Labels: bug
