### ISSUE TITLE
[D3D9] F.E.A.R.:  see-through player body

### ISSUE THREAD

**Issue by DaRkL3AD3R** [doitsujin/dxvk#1461] opened 2020-02-18 05:52 UTC
The player character's body model is ghostly transparent.

### Software information
F.E.A.R. max settings. FSAA = off, Soft Shadows = off.

### System information
- GPU: GTX 1080 Ti
- Driver: 442.19 
- DXVK version: v1.5.4-38-g4cf3ef5

### Apitrace file(s)
https://www.mediafire.com/file/dvf2lgnr5lopr57/FEAR.zip/file

### Log files
- d3d9.log: https://www.mediafire.com/file/539dmsneqkwn0wk/FEAR_d3d9.log/file

**Comment by Joshua-Ashton** [comment] 2020-02-18 06:11
Please upload the apitrace somewhere else -- I can't connect to that site.

**Comment by DaRkL3AD3R** [comment] 2020-02-18 06:19
https://drive.google.com/file/d/1rdir-Y3uUI-R1FPDxHAcYZ4YdE9ogtIJ/view?usp=sharing

**Comment by Joshua-Ashton** [comment] 2020-02-18 06:26
Looks like an NV only bug, I will look into it tomorrow. (I think it might be SWVP causing it because we currently have issues with that on NV due to uniform buffer range stuff)

AMD:
![image](https://user-images.githubusercontent.com/21316711/74709598-78a49980-5217-11ea-819c-51f366839bff.png)

Nvidia:
![image](https://user-images.githubusercontent.com/21316711/74709569-6296d900-5217-11ea-9e9d-770724b53bfa.png)

**Comment by NerosTie** [comment] 2020-02-18 14:05
On my side, when I start a new game I have an error message saying "Disconnect from server"

![Screenshot_20200218_150329](https://user-images.githubusercontent.com/4572452/74743050-0a37f980-5260-11ea-9e58-64eb7d805b00.png)

It doesn't happen witch wined3d.

@DaRkL3AD3R It wasn't an issue for you?

**Comment by xpander69** [comment] 2020-02-25 09:13
yeah, confirming on nvidia 440.58.02
![ss_25022020_11 12 08](https://user-images.githubusercontent.com/1345116/75232356-be390780-57bf-11ea-8fb9-f233bb736f27.png)

**Comment by NerosTie** [comment] 2020-07-08 15:49
The last time the textures were not transparent was with version 1067.

The issue comes from this commit: https://git.froggi.es/doitsujin/dxvk/-/commit/b738c4220b7f2ea71cf2f1f61521a08606ee7022

**Comment by Joshua-Ashton** [comment] 2020-07-08 16:42
I am aware it is depth bias scaling, sorry I should have updated the issue with that info.

**Comment by WinterSnowfall** [comment] 2020-07-08 18:30
> The last time the textures were not transparent was with version 1067.

Sorry for derailing this a bit, but since I can't check the trace myself at the moment, I have to ask: are the textures also transparent with wined3d, or only with dxvk?

I'm asking because I've seem something similar in D&D Dragonshard, only on Nvidia, but with both wined3d and dxvk. I thought it was a driver bug (since it looks fine on Intel at least), but I'd report it if it's something potentially fixable in dxvk.

**Comment by NerosTie** [comment] 2020-07-08 18:33
Only with dxvk (>1067), everything is fine with wined3d.

**Comment by DaRkL3AD3R** [comment] 2021-04-07 05:01
Is there any update to this depth bias issue? As an Nvidia user this one is a bit frustrating because DXVK actually resolves Nvidia driver bugs with the game (visible here on Nvidia and goes away when you start capturing through NVENC hence the camera capture: https://www.youtube.com/watch?v=d-sJef5M2J8 ).

**Comment by DaRkL3AD3R** [comment] 2021-06-18 00:02
Was going to open a new issue for FEAR about water shader effects being broken.

D3D9: https://i.imgur.com/xpvXU6e.png
DXVK: https://i.imgur.com/2JKDIQD.png

But then I remembered I was running an older version of DXVK to prevent this ghostly transparent bug I reported ages ago, so I updated the version FEAR was using and nice to see the water is rendering fine now: https://i.imgur.com/9bjIrhe.png

Unfortunately transparency problem is still present :( is there any hope for this one? Or are Nvidia users screwed?

**Comment by warriormaster12** [comment] 2021-08-01 06:34
It would be nice to get this fixed since soon Lutris will remove Wine3D support.

**Comment by warriormaster12** [comment] 2021-08-01 08:44
Nvm about the Wine3D part but still, any chance of getting this working in DXVK?

**Comment by vide0hanz** [comment] 2022-03-14 23:54
Confirming issue is still present.

- GPU: Nvidia RTX 2080 Super
- Driver version: 510.54-1
- OS: Arch Linux 5.16.14-arch1-1

Additionally, setting `PROTON_USE_WINED3D=1` now results in funky looking shadows and dark areas (probably this just happens to be more perceptible in these environments). Can provide screenshots if desired. Basically the colors look as if they are rendered in 16bit despite 32bit being set in-game.

**Comment by Blisto91** [comment] 2022-07-04 15:52
While i was testing something else in this game i tried to check out this issue a bit more.
I have found this to be a regression in dxvk 1.5.1. A more specific bisect will be done later

**Comment by mascherone108** [comment] 2022-07-12 18:38
Same issue also happens in Condemned: Criminal Origins. Using `PROTON_USE_WINED3D=1 %command%` fixes it.

**Comment by rakantoh** [comment] 2022-08-20 21:49
ok, known issue, some progress or workaround?

**Comment by Blisto91** [comment] 2022-08-20 21:52
For workaround you'll have to use wined3d or dxvk 1.5

**Comment by rakantoh** [comment] 2022-08-20 23:19
> For workaround you'll have to use wined3d (if on Linux) or dxvk 1.5

dxvk 1.5 is too old, and fear was affected by the megaissue #1318 out of space, but i will try again with 1.5

**Comment by K0bin** [comment] 2022-11-09 13:47
I'd still prefer to leave this open until we have a proper solution instead of a workaround.

**Comment by K0bin** [comment] 2023-06-20 12:36
Fixed by #3501

**Closed by K0bin** 2023-06-20 12:36 UTC
Labels: nvidia
