### ISSUE TITLE
Missing textures in Far Cry 5

### ISSUE THREAD

**Issue by AccountOneOff** [doitsujin/dxvk#344] opened 2018-05-05 08:00 UTC
Some of the ground textures are missing and show up as black. Water is bugged as well.

### Software information
Far Cry 5
High preset

### System information
- GPU: GTX 960
- Driver: 396.24
- Wine version: 3.5 Staging
- DXVK version: 94b7466

### Apitrace file(s)
- https://drive.google.com/open?id=1lpBOhGHfI8Su6NWnID1IWX8J1CNMXlTG

### Log files
- [FarCry5_d3d11.log](https://github.com/doitsujin/dxvk/files/1976422/FarCry5_d3d11.log)
- [FarCry5_dxgi.log](https://github.com/doitsujin/dxvk/files/1976423/FarCry5_dxgi.log)

**Comment by doitsujin** [comment] 2018-05-05 13:57
Missing terrain should be fixed as of 5a639797d24db85aaf3da9ab2d98ac5848687736.

**Comment by AccountOneOff** [comment] 2018-05-06 23:06
Ground textures now work. Not exactly sure how to describe this problem but it's been present for a while now. Objects get distorted getting near them and go back to normal a second later. Recored a trace of the problem:

### System information

- GPU: GTX 960
- Driver: 396.24
- Wine version: 3.7 Staging
- DXVK version:  757be61

### Apitrace:
https://drive.google.com/open?id=1H7bpOTGNijex4hMKCERgKe_UebYjtHYm

### Logs:
- [FarCry5_d3d11.log](https://github.com/doitsujin/dxvk/files/1978133/FarCry5_d3d11.log)
- [FarCry5_dxgi.log](https://github.com/doitsujin/dxvk/files/1978134/FarCry5_dxgi.log)

I'll try to get a trace of the water sometime soon.

**Comment by doitsujin** [comment] 2018-05-07 13:56
@AccountOneOff I cannot make out what the issue is because the trace is just as broken as the old one.

**Comment by AccountOneOff** [comment] 2018-05-07 19:56
Placing this here in case you didn't see it on Discord. Here's the issue shown in the second trace when zooming into the tree. https://www.youtube.com/watch?v=NIyoJNjFzFA

**Comment by AccountOneOff** [comment] 2018-05-07 22:04
Here's lighting issue I mentioned on Discord: https://www.youtube.com/watch?v=OZWjekCsIhc

DXVK version: cd92d0b

https://drive.google.com/open?id=1dZuI7hUsbJjg74CpvYF4aQ-A-h6JjAFE

Lighting issue isn't present when I replay the trace but maybe it's different on AMD?

**Comment by jarrard** [comment] 2018-05-08 02:59
Can't seem to find any DXVK info on howto obtain version information on a built DXVK. Is there a obvious trick I'm missing? or should I just take note at the walloftext on build time?

**Comment by saboya** [comment] 2018-05-08 03:31
@jarrard It's the commit version you are building.

**Comment by AccountOneOff** [comment] 2018-05-11 00:37
Muzzle flash, explosions, and fire don't render. I also traced some lighting and shadow issues that might be related to the water issue.

DXVK version: c7d2957

https://drive.google.com/open?id=1bNIovT4AL3gahV9p4ENozZzYBRC9vUxH

**Comment by mozo78** [comment] 2018-05-20 12:47
With latest DXVK builds graphics are messed severely. All is in red.

**Comment by AccountOneOff** [comment] 2018-05-20 21:58
@mozo78 did you use the nightlies by chance? Those create problems with Far Cry 5. Can you please test with my build? 

[dxvk-master.zip](https://github.com/doitsujin/dxvk/files/2020747/dxvk-master.zip)

**Comment by mozo78** [comment] 2018-05-21 08:42
Yes with your build there isn't any graphical problems :) I always use latest builds.

**Comment by AccountOneOff** [comment] 2018-05-21 21:07
I compiled it myself.

**Comment by mozo78** [comment] 2018-05-21 22:57
Understood thank you :)

**Comment by AccountOneOff** [comment] 2018-05-25 19:55
Explosions, muzzle flash, fire, and particles now render. The only problem present now is the LOD issue mention in https://github.com/doitsujin/dxvk/issues/344#issuecomment-387183881

**Comment by AccountOneOff** [comment] 2018-05-26 18:53
Rendering issues now fixed with the [dxbc-correct-derivs](https://github.com/doitsujin/dxvk/tree/dxbc-correct-derivs) branch.

**Comment by doitsujin** [comment] 2018-05-26 20:56
Should work on `master` as well now.

**Closed by doitsujin** 2018-05-26 20:56 UTC
Labels: bug

**Comment by mozo78** [comment] 2018-05-26 21:03
Great news, thank you \m/

**Comment by mozo78** [comment] 2018-11-08 15:38
@doitsujin, version 0.91 again introduces svere graphics issues and heavy flickering with this game. I tried 0.90 and 0.91 where the problem exists. With 0.81 there aren't any problems with the graphics. I tried the latest Nvidia drivers and the beta 396.54.09 also to no avail. I can record a clip if you wish.

![1](https://user-images.githubusercontent.com/38666396/48208708-13a79600-e37c-11e8-956b-0911778a5057.png)
![2](https://user-images.githubusercontent.com/38666396/48208914-8d3f8400-e37c-11e8-91ab-dabcfb83be62.png)
d3d11.log:
https://pastebin.com/im97UAUb
dxgi.log:
https://pastebin.com/78X2wkZ6

**Comment by doitsujin** [comment] 2018-11-08 16:18
@mozo78 I'm aware of that, and I won't fix it. Some users have reported that using an older GCC version to build DXVK fixes the issue.

**Comment by mozo78** [comment] 2018-11-08 16:41
No problem I can play it with older DXVK version but what is the reason you don't want to fix it?

**Comment by doitsujin** [comment] 2018-11-08 16:58
Two reasons:
- It is still impossible to run legal versions of this game on wine.
- I have absolutely no clue what the hell is going on.

**Comment by pchome** [comment] 2018-11-08 17:04
@doitsujin 
> I'm aware of that, and I won't fix it. Some users have reported that building DXVK with an older GCC version fixes the issue.

Good candidate for "Known issues" wiki page. Issue description and current status will inform people that you aware.

I'm wondering is this a regression in GCC or an flag, and is this issue affects both MinGW and winelib builds.

**Comment by mozo78** [comment] 2018-11-08 17:07
> Two reasons:
> 
>     * It is still impossible to run legal versions of this game on wine.
> 
>     * I have absolutely no clue what the hell is going on. This is probably the same issue that caused Far Cry 5 to be all red in the past, it only happened when building DXVK with some specific tool chains. In other words, I **cannot** fix it.

I see. Thank you :)
