### ISSUE TITLE
Gothic 3 artifacts on some particles

### ISSUE THREAD

**Issue by VortexAcherontic** [doitsujin/dxvk#1856] opened 2020-12-14 22:52 UTC
Hello you wonderful people,

I witnessed some visual artifacts at some particles in some DirectX 9 games in this case Gothic 3 Enhanced Edition with Community Patch 1.75 as you can see in the screenshots.

In Dead Space 2 I also sometimes spotted some of these artifacts but wasn't able to reproduce it for this ticket they just looked exactly the same and appeared on the flashlight particle effect when aiming an standing close to some surfaces.

Those artifacts are pretty minor and not a big deal after all so no hurry. :)

WineD3D:
![Screenshot_20201214_232153](https://user-images.githubusercontent.com/11244092/102144949-b2a9f080-3e66-11eb-93f3-cc9bdb5c0ee0.png)

DXVK:
![Screenshot_20201214_232352](https://user-images.githubusercontent.com/11244092/102144998-c8b7b100-3e66-11eb-8aec-11a068005ce5.png)

### Software information
Gothic 3 - Max Settings

### System information
- GPU: GTX 1080
- Driver: 455.46.02
- Wine version: 5.21-2 (Lutris build)
- DXVK version: 1.7.3

### Apitrace file(s)
https://drive.google.com/file/d/1HfjcrcaDT9EGuoRSt83rlNQ7fZI4cCg6/view?usp=sharing

### Log files
- d3d9.log: https://pastebin.com/LRTWw51U
- dxgi.log: (Empty)

**Comment by Joshua-Ashton** [comment] 2020-12-15 14:14
Thanks for the report!

**Comment by K0bin** [comment] 2020-12-15 22:10
Can you upload a save where you're standing at that spot?

**Comment by VortexAcherontic** [comment] 2020-12-15 23:20
Of course here you go:

https://drive.google.com/file/d/1LyGowCEe9USqW_dPPv4vbnhh8yLKErZn/view?usp=sharing

The file also contains my UserOptions.ini in case it matter and some Shader.Cache which seems to be done by the game itself in case it matters as well.

**Comment by TomadeTT** [comment] 2020-12-17 13:02
i can reproduce the visual artifacts.

**Comment by K0bin** [comment] 2020-12-21 14:55
The game is rendering to and reading from the same texture. That's technically illegal in Vulkan and our workaround apparently doesnt do the trick.

**Comment by DaRkL3AD3R** [comment] 2021-03-13 04:21
This is interesting because this issue wasn't present in older versions of Nvidia drivers, like for me on Windows drivers 460+ are the culprit (which coincidentally came out early December 2020 which is when OP started noticing this issue.)

I have a video of the issue happening in Dead Space 2 along with screenshots to confirm it is the same exact issue.

Video: https://www.youtube.com/watch?v=aKgHviJi8bs

Screenshot: https://i.imgur.com/QH1qLyG.png

**Comment by K0bin** [comment] 2021-03-13 13:09
Can you make an apitrace of that Dead Space 2 issue? Maybe that's easier to debug. (and I'll probably be a bit more motivated as Dead Space 2 is one of my favorites)

**Comment by DaRkL3AD3R** [comment] 2021-03-13 17:52
I hope this captured it clearly. It's hard to tell when rendering in native D3D9 and the issue isn't visible. But it should do it: https://drive.google.com/file/d/1aiP_jdQDmY_49ZTRYuMFjBWzwf5w03Ze/view?usp=sharing

**Comment by DaRkL3AD3R** [comment] 2021-03-20 04:52
I updated to the most recent dev build and this problem is resolved for me. No more coronas appearing through the walls, no more blocky rendering artifacts over stacked transparency effects.

**Comment by K0bin** [comment] 2021-04-24 11:11
The Dead Space 2 issue is fixed by b9360bacc27c30f413e154f4448cb812195d58c5

**Comment by Blisto91** [comment] 2022-04-03 15:50
I think this might have been fixed in newer Nvidia drivers? I can atleast not reproduce this at the same location with the 470 driver (earliest i can install without going crazy). This is on a 960 with 1.7.3 and gothic 3 with community patch and highest graphics settings.

**Comment by K0bin** [comment] 2022-04-03 15:54
Gonna close this. If it works, great, if it doesn't that comes down to a known issue. It's a feedback loop (with blending).

**Closed by K0bin** 2022-04-03 15:54 UTC
Labels: d3d9
