### ISSUE TITLE
Please FIX Operation Flashpoint Red River

### ISSUE THREAD

**Issue by baazthefalcon** [doitsujin/dxvk#3849] opened 2024-02-13 19:47 UTC
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Operation Flashpoint Red River, settings doesn't matter, with dxvk UI is bugged and even somehow i get into the game textures are not loaded, game is not passing thru dxvk dll ...please fix it will apreciate it.

### System information
- GPU: RTX 2060 Super
- Driver: Latest
- Wine version: 
- DXVK version: Any

**Comment by Blisto91** [comment] 2024-02-13 20:01
Duplicate of https://github.com/doitsujin/dxvk/issues/2184

**Comment by baazthefalcon** [comment] 2024-02-14 07:39
> Duplicate of #2184

should i close this one ?

**Comment by Blisto91** [comment] 2024-02-14 10:10
Yes. It's better to keep it tracked in one issue so not to spread out information too much.

**Closed** 2024-02-14 11:06 UTC
