### ISSUE TITLE
Grand Theft Auto IV Crash

### ISSUE THREAD

**Issue by Laksh2007** [doitsujin/dxvk#3162] opened 2023-01-01 19:45 UTC
Whenever I start my game I'm greeted with a black screen with the game closing shortly after. The installation was pretty simple all I copied was d3d9.dll from x32 folder. Some users reported stuttering issues so to fix the stuttering issues I created a config file by the name of dxvk.conf. It contains these two lines. How do I fix this? The real reason I didn't use v2.0 is because it gives me the D3D Fatal Error.

I've tried changing my settings, deleting some mods but it doesn't work.
I've included the things that are in GTAIV_d3d9.

dxgi.maxFrameLatency = 1
d3d9.maxFrameLatency = 1

### Software information
Grand Theft Auto IV downgraded to Patch 8 (1.0.8.0).
Settings used: 1366x768 [60Hz] Medium Preset with sliders set at 25.

### System information
- GPU: Intel® UHD 620
- Driver: 108.661.0
- DXVK version: info:  v1.10.3

### Log files
- d3d9.log: info:  Game: GTAIV.exe
info:  DXVK: v1.10.3
info:  Found config file: dxvk.conf
info:  Found built-in config:
info:    dxgi.emulateUMA = True
info:    d3d9.customVendorId = 1002
info:  Effective configuration:
info:    d3d9.customVendorId = 1002
info:    dxgi.emulateUMA = True
info:    d3d9.maxFrameLatency = 1
info:    dxgi.maxFrameLatency = 1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
warn:  D3D9: VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT -> VK_FORMAT_B4G4R4A4_UNORM_PACK16
info:  Intel(R) UHD Graphics:
info:    Driver: 108.661.0
info:    Vulkan: 1.2.151
info:    Memory Heap[0]: 
info:      Size: 3091 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 3091 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x7
info:      Memory Type[2]: Property Flags = 0xf
info:      Memory Type[3]: Property Flags = 0x1
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : Intel(R) UHD Graphics
info:    Driver version   : 108.661.0
info:  Enabled device extensions:
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_external_memory_win32
info:    VK_KHR_external_semaphore_win32
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:    VK_KHR_timeline_semaphore
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 0
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 0
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 0
info:    formatA4B4G4R4                         : 0
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 0
info:    customBorderColorWithoutFormat         : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 0
info:    robustImageAccess2                     : 0
info:    nullDescriptor                         : 0
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_buffer_device_address
info:    bufferDeviceAddress                    : 0
info:  VK_KHR_timeline_semaphore
info:    timelineSemaphore                      : 0
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 0
warn:  DXVK: No state cache file found
warn:  DXVK: Creating new state cache file
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1920x1061
info:    Image count:  3
info:    Exclusive FS: 0
info:  Setting display mode: 1920x1080@0
info:  Game: GTAIV.exe
info:  DXVK: v1.10.3
info:  Found config file: dxvk.conf
info:  Found built-in config:
info:    dxgi.emulateUMA = True
info:    d3d9.customVendorId = 1002
info:  Effective configuration:
info:    d3d9.customVendorId = 1002
info:    dxgi.emulateUMA = True
info:    d3d9.maxFrameLatency = 1
info:    dxgi.maxFrameLatency = 1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
warn:  D3D9: VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT -> VK_FORMAT_B4G4R4A4_UNORM_PACK16
info:  Intel(R) UHD Graphics:
info:    Driver: 108.661.0
info:    Vulkan: 1.2.151
info:    Memory Heap[0]: 
info:      Size: 3091 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 3091 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x7
info:      Memory Type[2]: Property Flags = 0xf
info:      Memory Type[3]: Property Flags = 0x1
info:  Process set as DPI aware
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1280
info:      - Height:             720
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Setting display mode: 1280x720@40
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1280x720
info:    Image count:  3
info:    Exclusive FS: 0

**Comment by Blisto91** [comment] 2023-01-01 21:04
I don't think anyone here can point to anything specific that you can do to fix it. The game have always had some semi weird issues together with dxvk, especially on Windows. And even more especially, dxvk in general have worked pretty badly on older Intel GPUs afaik.
The general advice is to make sure your drivers are up to date. The 1.10.3 version of dxvk is not really supported anymore besides some maybe very minor backports for the 1.10.x branch.

A quick skim of your log doesn't reveal anything obvious besides some weird resolution and refresh rate values. Which dxvk also sometimes behave a bit weirdly with, especially on Windows.
```
info: Buffer size: 1920x1061
```
```
1280x720@40
```

**Comment by Laksh2007** [comment] 2023-01-01 21:07
Ok, I'll do that.

**Comment by Laksh2007** [comment] 2023-01-01 21:10
Updated log file:

info:  Game: PlayGTAIV.exe
info:  DXVK: v1.10.3
info:  Found config file: dxvk.conf
info:  Effective configuration:
info:    d3d9.maxFrameLatency = 1
info:    dxgi.maxFrameLatency = 1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
warn:  D3D9: VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT -> VK_FORMAT_B4G4R4A4_UNORM_PACK16
info:  Intel(R) UHD Graphics:
info:    Driver: 108.661.0
info:    Vulkan: 1.2.151
info:    Memory Heap[0]: 
info:      Size: 3091 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 3091 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x7
info:      Memory Type[2]: Property Flags = 0xf
info:      Memory Type[3]: Property Flags = 0x1
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : Intel(R) UHD Graphics
info:    Driver version   : 108.661.0
info:  Enabled device extensions:
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_external_memory_win32
info:    VK_KHR_external_semaphore_win32
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:    VK_KHR_timeline_semaphore
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 0
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 0
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 0
info:    formatA4B4G4R4                         : 0
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 0
info:    customBorderColorWithoutFormat         : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 0
info:    robustImageAccess2                     : 0
info:    nullDescriptor                         : 0
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_buffer_device_address
info:    bufferDeviceAddress                    : 0
info:  VK_KHR_timeline_semaphore
info:    timelineSemaphore                      : 0
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 0
info:  DXVK: Read 0 valid state cache entries
info:  D3D9DeviceEx: Using extended constant set for software vertex processing.
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              0
info:      - Height:             0
info:      - Format:             D3D9Format::Unknown
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           true
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  800x300
info:    Image count:  2
info:    Exclusive FS: 0

**Comment by Laksh2007** [comment] 2023-01-01 21:12
Sorry please ignore those as I accidentally clicked on Close this issue.

**Comment by Laksh2007** [comment] 2023-01-01 21:29
This game has to be the only one where it's refusing to start. Others start up but don't get past the menus.

**Comment by Blisto91** [comment] 2023-01-01 21:33
As said GTA IV has always been a bit of a special case. It's probably the single game that has had the most amount of issues on this GitHub 🙂

**Comment by Laksh2007** [comment] 2023-01-01 22:33
Well any tips I could try? This game is a pain in the ass to get working properly. My friend didn't have any issues even though he has an Intel HD 520 whilst I have an intel UHD 620 and RTX 2080 Ti.

**Comment by Blisto91** [comment] 2023-01-01 22:40
Don't have much advise besides drivers, trying older versions of dxvk or if you mean you have two GPUs in the same system then make sure it picks the right one using the environmental variable https://github.com/doitsujin/dxvk#device-filter

**Comment by Laksh2007** [comment] 2023-01-01 22:46
They're both different systems. Plus I tried v1.9.4 that did the same thing.

**Comment by Laksh2007** [comment] 2023-01-02 21:41
Hmmm, old versions didn't work. What else should I do?

**Comment by Blisto91** [comment] 2023-01-03 06:06
Update your driver https://www.intel.com/content/www/us/en/support/products/126789/graphics/intel-uhd-graphics-family/intel-uhd-graphics-620.html 
Also make sure Windows is up to date.

**Comment by K0bin** [comment] 2023-01-13 01:38
Probably a duplicate of #3110

**Closed by K0bin** 2023-01-13 01:38 UTC
Labels: d3d9

**Comment by Zawad-2007** [comment] 2024-06-25 18:26
Watch this video. It helped me to fix lagging in gta 4. https://youtu.be/WfsIpXI_BFk?si=lYIkU40aeqSQEa2t

**Comment by MrKoddy** [comment] 2026-03-17 03:03
dxvk 2.7.1 version make the game crashed during the Lure mission for GTA IV. I deleted the file and game didn't crash anymore. I was able to reinstall the driver after that mission and it works

**Comment by K0bin** [comment] 2026-03-17 12:33
@MrKoddy Please make an apitrace of that mission.

**Comment by Blisto91** [comment] 2026-03-17 14:26
Ideally in a new issue with filled out issue template
