### ISSUE TITLE
World of Warcraft logs and trace

### ISSUE THREAD

**Issue by Thaodan** [doitsujin/dxvk#35] opened 2018-01-26 20:02 UTC
Game just starts and exists and says it cant start 3D accerlation.
Needs dx3d10 support I think.

### Software information
World of Warctaft 7.3.5

### System information
- GPU: NVIDIA Geforce 1080Ti
- Driver: 387.34
- Wine version:  wine-staging 2.21
- DXVK version: latest git(20180125.d3fe362-1)

### Apitrace file(s)
- https://www.dropbox.com/s/wsvpfvidl0u92cm/Wow-64.trace?dl=0

### Log files
- 
- d3d11.log: empty
- dxgi.log: https://gist.github.com/Thaodan/89dd828f5262b108c49516c805bf6f1e

**Comment by gverm** [comment] 2018-01-26 20:33
Looks like a dupe of #14

**Comment by Thaodan** [comment] 2018-01-26 20:52
Oh sorry good that someone tried before, I couldn't get apitrace work with wine.

**Comment by SveSop** [comment] 2018-01-27 17:16
Good luck getting World of Warcraft to work with DXVK :) 

I have a minor theory that wow is not a "clean" dx11 app as it is now, but they do seem to have a plan with cleaning up some stuff as DX9 support is going to be dropped. Perhaps then things will start to kick off? DX10 support in wine is not really that good, as it is a lot of stuff that is not implemented. They (wine) kinda skipped working that much on DX10 i think and more or less went from DX9 -> DX11. 

Not that many DX10 tests around either, but Unigine Tropics has DX9/10/11, and DX9 works, and DX11 works.. DX10 just segfaults with loads of crap. So i guess the DX10 implementations is somewhat lacking. 

In a distant dream, i would love to see some performance in WoW again, but not really sure when. Atleast unless you use a AMD card perhaps? Cant really get much more than "cube" to work with nVidia binary blob :)

**Comment by Thaodan** [comment] 2018-01-27 17:24
The thing is how much of directx 10 is really used.
I mean even when using directx 9 the game tests for directx 10/11 support so maybe they don't really use it.
Imagine what happens if you just fake support it.

Yes the performance in wow is worse this is why I looked on this.
The directx "11" is the only left in the next add-on.

Am 27. Januar 2018 18:16:27 MEZ schrieb SveSop <notifications@github.com>:
>Good luck getting World of Warcraft to work with DXVK :) 
>
>I have a minor theory that wow is not a "clean" dx11 app as it is now,
>but they do seem to have a plan with cleaning up some stuff as DX9
>support is going to be dropped. Perhaps then things will start to kick
>off? DX10 support in wine is not really that good, as it is a lot of
>stuff that is not implemented. They (wine) kinda skipped working that
>much on DX10 i think and more or less went from DX9 -> DX11. 
>
>Not that many DX10 tests around either, but Unigine Tropics has
>DX9/10/11, and DX9 works, and DX11 works.. DX10 just segfaults with
>loads of crap. So i guess the DX10 implementations is somewhat lacking.
>
>
>In a distant dream, i would love to see some performance in WoW again,
>but not really sure when. Atleast unless you use a AMD card perhaps?
>Cant really get much more than "cube" to work with nVidia binary blob
>:)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/doitsujin/dxvk/issues/35#issuecomment-360999225

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by doitsujin** [comment] 2018-01-27 17:58
Closing this as this is indeed a duplicate of #14, but feel free to post any new information there.

**Closed by doitsujin** 2018-01-27 17:58 UTC
Labels: duplicate
